force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee Information</label>
    <nameField>
        <label>English Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Information</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/ReportTo__c.field-meta.xml
<CustomField>
    <fullName>ReportTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Report to</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Information</relationshipLabel>
    <relationshipName>Employee_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This position report to</inlineHelpText>
    <label>Report to</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PositionTreeController.cls
public with sharing class PositionTreeController {

    @AuraEnabled
    public static List<Employee__c> getPositionById(String id){
        List<Employee__c> rsList = new List<Employee__c>();
        String tmpId = id;
        Employee__c rs;
        while(tmpId != null){
            rs = [SELECT Id, Name, ReportTo__c, Position__r.Name FROM Employee__c WHERE Id = :tmpId];
            rsList.add(rs);
            tmpId = rs.ReportTo__c;
        }
        return rsList;
    }

    @AuraEnabled
    public static List<Employee__c> getAllPosition(String id){
        List<Employee__c> rsList = new List<Employee__c>();
        List<Employee__c> listRs;
        List<String> ids = new List<String>();
        ids.add(id);
        while(ids.size() > 0){
            try{
                listRs = [SELECT Id, Name, ReportTo__c, Position__r.Name FROM Employee__c WHERE ReportTo__c IN :ids];
            } catch(Exception e){
                listRs = new List<Employee__c>();
            }
            ids = new List<String>();
            for(Employee__c item : listRs){
                ids.add(item.Id);
                rsList.add(item);
            }
        }

        return rsList;
    }
}