force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity.</label>
    <nameField>
        <displayFormat>OP-{0000}</displayFormat>
        <label>Opporturnity</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipName>Opporturnities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>QT-{00000}</displayFormat>
        <label>Quote ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <label>Remarks</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote_route__c/Quote_route__c.object-meta.xml
<CustomObject>
    <label>Quote Route</label>
    <nameField>
        <displayFormat>QR-{00000}</displayFormat>
        <label>Quote route ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_route__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote ID</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipName>Quote_route</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote_route__c/fields/Quote_Route__c.field-meta.xml
<CustomField>
    <fullName>Quote_Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipName>Quote_route</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_route__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipName>Quote_route</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quoteline__c/Quoteline__c.object-meta.xml
<CustomObject>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000}</displayFormat>
        <label>Quoteline ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quoteline__c/fields/ChargeQuantity__c.field-meta.xml
<CustomField>
    <fullName>ChargeQuantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Charge Quantity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quoteline__c/fields/CurrencySelling__c.field-meta.xml
<CustomField>
    <fullName>CurrencySelling__c</fullName>
    <label>Currency-Selling</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VND</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>KHR</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>KRW</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quoteline__c/fields/PrintingSection__c.field-meta.xml
<CustomField>
    <fullName>PrintingSection__c</fullName>
    <label>Printing Section</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1st Section</fullName>
                <default>true</default>
                <label>1st Section</label>
            </value>
            <value>
                <fullName>2nd Section</fullName>
            </value>
            <value>
                <fullName>3rd Section</fullName>
            </value>
            <value>
                <fullName>4th Section</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quoteline__c/fields/Quote_route__c.field-meta.xml
<CustomField>
    <fullName>Quote_route__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Quote route</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Quote_route__c.Quote__c</field>
            <operation>equals</operation>
            <valueField>$Source.QuoteID__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Quote_route__c</referenceTo>
    <relationshipLabel>Quote lines</relationshipLabel>
    <relationshipName>Quote_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quoteline__c/fields/QuoteID__c.field-meta.xml
<CustomField>
    <fullName>QuoteID__c</fullName>
    <label>Quote ID</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote lines</relationshipLabel>
    <relationshipName>Quote_lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quoteline__c/fields/ReferencePrice__c.field-meta.xml
<CustomField>
    <fullName>ReferencePrice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference Price</label>
    <referenceTo>ReferencePrice__c</referenceTo>
    <relationshipLabel>Quote lines</relationshipLabel>
    <relationshipName>Quote_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quoteline__c/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <label>Remarks</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quoteline__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Quote lines</relationshipLabel>
    <relationshipName>Quote_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quoteline__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Section</label>
    <referenceTo>Section__c</referenceTo>
    <relationshipLabel>Quote lines</relationshipLabel>
    <relationshipName>Quote_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quoteline__c/fields/SellingListPriceActual__c.field-meta.xml
<CustomField>
    <fullName>SellingListPriceActual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Selling List Price (Actual)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quoteline__c/fields/TaxRateSelling__c.field-meta.xml
<CustomField>
    <fullName>TaxRateSelling__c</fullName>
    <label>Tax Rate-Selling(%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ReferencePrice__c/ReferencePrice__c.object-meta.xml
<CustomObject>
    <label>Reference Price</label>
    <nameField>
        <displayFormat>RP-{00000}</displayFormat>
        <label>Reference Price ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Price</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ReferencePrice__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Reference Price</relationshipLabel>
    <relationshipName>Reference_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Section__c/Section__c.object-meta.xml
<CustomObject>
    <label>Section</label>
    <nameField>
        <label>Section  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Section__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote ID</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Section</relationshipLabel>
    <relationshipName>Section</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MassEditQuoteLineController.cls
public without sharing class MassEditQuoteLineController{
    @AuraEnabled
    public static void saveQuoteLineList(List<Quoteline__c> quoteLineList, Id quoteId){
        System.debug('12345:' + quoteLineList);
        for (Quoteline__c quoLine : quoteLineList){
            quoLine.QuoteID__c = quoteId;
        }
        try{
            Insert quoteLineList;
        } catch (DmlException e){
            throw e;
        }
    }

    @AuraEnabled
    public static List<Quoteline__c> getAllQuoteLine(String QuoteId){
        List<AggregateResult> lstQuoteRoute = [SELECT Route__r.Route__c
                                               FROM Quote_route__c
                                               WHERE Quote__c = :QuoteId
                                               GROUP BY Route__r.Route__c];
        Set<String> Ids = new Set<String>();
        for (AggregateResult agg : lstQuoteRoute){
            Ids.add((String) agg.get('Route__c'));
        }
        List<Quoteline__c> lstQuoteLine = Security.stripInaccessible(AccessType.READABLE, [Select Name, Id, ReferencePrice__c, PrintingSection__c, ChargeQuantity__c, CurrencySelling__c, TaxRateSelling__c, SellingListPriceActual__c, Remarks__c, Section__c
                                                                                           From Quoteline__c
                                                                                           WHERE QuoteID__c = :QuoteId AND ReferencePrice__r.Route__c IN:Ids
                                                                                           ORDER BY NAME]).getRecords();
        return lstQuoteLine;
    }

    @AuraEnabled
    public static Boolean deleteQuoteLine(List<String> lstQuoteLineId){
        try{
            Set<String> Ids = new Set<String>();
            for (Integer i = 0; i < lstQuoteLineId.size(); i++){
                Ids.add((String) lstQuoteLineId[i]);
            }
            List<Quoteline__c> quoteLines = [Select Id
                                             FROM Quoteline__c
                                             WHERE Id IN:Ids];
            if (quoteLines.size() == 0)
                return false;
            delete quoteLines;
            return true;
        } catch (Exception e){
            throw e;
        }
    }

    @AuraEnabled
    public static void updateQuoteLine(List<String> lstIdQuoteLine, List<Quoteline__c> lstQuoteLine){
        upsert lstQuoteLine;
    }

    @AuraEnabled
    public static List<Quoteline__c> getInfoQuoteLine(String QuoteLineId){
        return [Select Id, Name, ReferencePrice__c, PrintingSection__c, ChargeQuantity__c, CurrencySelling__c, TaxRateSelling__c, SellingListPriceActual__c, Remarks__c, Section__c
                FROM Quoteline__c
                where Id = :QuoteLineId];
    }

    @AuraEnabled
    public static List<contact> getContacts(){
        return [SELECT Id, name, phone
                FROM contact
                ORDER BY createdDate ASC];
    }

    @AuraEnabled
    public static List<Quote_route__c> getRoute(String QuoteId){
        return [SELECT Route__r.Route__c
                FROM Quote_route__c
                WHERE Quote__c = :QuoteId];
    }

}