force-app/main/default/objects/Application_Assessment__c/Application_Assessment__c.object-meta.xml
<CustomObject>
    <label>Application Assessment.</label>
    <nameField>
        <displayFormat>AAS-{000000}</displayFormat>
        <label>Application Assessment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Assessment.</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Assessment__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Action</label>
    <referenceTo>ApplicationToDoList__c</referenceTo>
    <relationshipLabel>Application Assessment.</relationshipLabel>
    <relationshipName>Application_Assessment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Assessment__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Applicationn__c</referenceTo>
    <relationshipLabel>Application Assessment.</relationshipLabel>
    <relationshipName>Application_Assessment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Application_Assessment__c/fields/AssessorUser__c.field-meta.xml
<CustomField>
    <fullName>AssessorUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessor (User)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Application_Assessment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Assessment__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_Assessment__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Application_Stage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicationn__c/Applicationn__c.object-meta.xml
<CustomObject>
    <label>Application.</label>
    <nameField>
        <displayFormat>AL-{000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application.</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicationn__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CV Unqualified</fullName>
            </value>
            <value>
                <fullName>CV Qualified</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Interview 1 Qualified</fullName>
            </value>
            <value>
                <fullName>Interview 2 Qualified</fullName>
            </value>
            <value>
                <fullName>Considering</fullName>
            </value>
            <value>
                <fullName>BOD Approved</fullName>
            </value>
            <value>
                <fullName>Sent Offer Letter</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Interview Failed</fullName>
                <isActive>false</isActive>
                <label>Interview Failed</label>
            </value>
            <value>
                <fullName>Interview Passed</fullName>
                <isActive>false</isActive>
                <label>Interview Passed</label>
            </value>
            <value>
                <fullName>Rejected by Candidate</fullName>
                <isActive>false</isActive>
                <label>Rejected by Candidate</label>
            </value>
            <value>
                <fullName>Submit to BOD</fullName>
                <isActive>false</isActive>
                <label>Submit to BOD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApplicationToDoList__c/ApplicationToDoList__c.object-meta.xml
<CustomObject>
    <label>Application To Do List</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Application Process</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application To Do List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationToDoList__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProcessTemplate</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApplicationToDoList__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Applicationn__c</referenceTo>
    <relationshipName>Application_Process</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApplicationToDoList__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApplicationToDoList__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/globalValueSets/Application_Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CV Qualified</fullName>
    </customValue>
    <customValue>
        <fullName>Manager Approving</fullName>
    </customValue>
    <customValue>
        <fullName>Inviting</fullName>
    </customValue>
    <customValue>
        <fullName>Interviewing</fullName>
    </customValue>
    <customValue>
        <fullName>Considering</fullName>
    </customValue>
    <customValue>
        <fullName>BOD Approving</fullName>
    </customValue>
    <customValue>
        <fullName>Sending Offer Letter</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <masterLabel>Application Stage</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ProcessTemplate.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Check candidate CV</fullName>
    </customValue>
    <customValue>
        <fullName>Manager Approving</fullName>
    </customValue>
    <customValue>
        <fullName>Schedule the interview</fullName>
    </customValue>
    <customValue>
        <fullName>Email candidate on upcoming interview</fullName>
    </customValue>
    <customValue>
        <fullName>Interview</fullName>
    </customValue>
    <customValue>
        <fullName>HR Manager Approving</fullName>
    </customValue>
    <customValue>
        <fullName>Department Manager Approving</fullName>
    </customValue>
    <customValue>
        <fullName>BOD Approving</fullName>
    </customValue>
    <customValue>
        <fullName>Send offer letter</fullName>
    </customValue>
    <customValue>
        <fullName>Finalize the onboard date and prepare the document</fullName>
    </customValue>
    <customValue>
        <fullName>Welcome candidate onboard</fullName>
    </customValue>
    <description>Recruitment Process &amp; Employee Process</description>
    <masterLabel>Process Template</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CustomApplicationStage.cls
public with sharing class CustomApplicationStage {
    @AuraEnabled
    public static List<String> getPickListValuesIntoList(){
        List<String> pickListValuesList= new List<String>();
        Schema.DescribeFieldResult fieldResult = Applicationn__c.Stage__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesList.add(pickListVal.getLabel());
        }     
        return pickListValuesList;
    }
    @AuraEnabled
    public static string getCurrentStage(String id){
        try {
            Applicationn__c rs = [SELECT Stage__c FROM Applicationn__c WHERE Id = :id];
            return rs.Stage__c;
        } catch (Exception e) {
            return null;
        }
    }
    @AuraEnabled
    public static string markCurrentStage(String id, String curStage){
        try {
            Applicationn__c rs = [SELECT Stage__c FROM Applicationn__c WHERE Id = :id];
            rs.Stage__c = curStage;
            update rs;
            return 'SUCCESS';
        } catch (Exception e) {
            return null;
        }
    }
    @AuraEnabled
    public static List<Application_Assessment__c> getApplicationAssessmentList(String applicationId, String curStage){
        try {
            List<Application_Assessment__c> rsList = [SELECT Name, AssessorUser__r.Name, Result__c FROM Application_Assessment__c WHERE Application__c = :applicationId AND Stage__c = :curStage LIMIT 3];
            return rsList;
        } catch (Exception e) {
            return new List<Application_Assessment__c>();
        }
    }
    @AuraEnabled
    public static List<ApplicationToDoList__c> getApplicationToDoList(String applicationId, String actionF){
        try {
            List<ApplicationToDoList__c> rsList = [SELECT Name, Time__c, Status__c FROM ApplicationToDoList__c WHERE Application__c = :applicationId AND Action__c = :actionF LIMIT 3];
            return rsList;
        } catch (Exception e) {
            return new List<ApplicationToDoList__c>();
        }
    }
}