force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This position report to</inlineHelpText>
    <label>Report to</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RecruitmentPlan__c/RecruitmentPlan__c.object-meta.xml
<CustomObject>
    <label>Recruitment Plan</label>
    <nameField>
        <label>Recruitment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recruitment Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RecruitmentPlanLine__c/RecruitmentPlanLine__c.object-meta.xml
<CustomObject>
    <label>Recruitment Plan Line</label>
    <nameField>
        <label>Recruitment Plan Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recruitment Plan Line</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RecruitmentPlanLine__c/fields/Change__c.field-meta.xml
<CustomField>
    <fullName>Change__c</fullName>
    <label>Change</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Arised</fullName>
            </value>
            <value>
                <fullName>Mixed</fullName>
            </value>
            <value>
                <fullName>No change</fullName>
            </value>
            <value>
                <fullName>Position</fullName>
            </value>
            <value>
                <fullName>Quantity</fullName>
            </value>
            <value>
                <fullName>Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RecruitmentPlanLine__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Recruitment_Plan_Line</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RecruitmentPlanLine__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <defaultValue>CASE(MONTH(today()),
1, &quot;January&quot;,
2, &quot;February&quot;,
3, &quot;March&quot;, 
4, &quot;April&quot;, 
5, &quot;May&quot;, 
6, &quot;June&quot;,
7, &quot;July&quot;,
8, &quot;August&quot;,
9, &quot;September&quot;,
10, &quot;October&quot;,
11, &quot;November&quot;,
12, &quot;December&quot;,
&quot;None&quot;)</defaultValue>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>January</fullName>
                <default>true</default>
                <label>January</label>
            </value>
            <value>
                <fullName>February</fullName>
            </value>
            <value>
                <fullName>March</fullName>
            </value>
            <value>
                <fullName>April</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>August</fullName>
            </value>
            <value>
                <fullName>September</fullName>
            </value>
            <value>
                <fullName>October</fullName>
            </value>
            <value>
                <fullName>November</fullName>
            </value>
            <value>
                <fullName>December</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RecruitmentPlanLine__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Recruitment Plan Line</relationshipLabel>
    <relationshipName>Recruitment_Plan_Line</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RecruitmentPlanLine__c/fields/Quarter_of_Year__c.field-meta.xml
<CustomField>
    <fullName>Quarter_of_Year__c</fullName>
    <formula>CEILING( MONTH (  ClosingDate__c  ) / 3 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quarter of Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RecruitmentPlanLine__c/fields/RecruitmentPlan__c.field-meta.xml
<CustomField>
    <fullName>RecruitmentPlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recruitment Plan</label>
    <referenceTo>RecruitmentPlan__c</referenceTo>
    <relationshipLabel>Recruitment Plan Line</relationshipLabel>
    <relationshipName>Recruitment_Plan_Line</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RecruitmentPlanLine__c/fields/Week_of_year__c.field-meta.xml
<CustomField>
    <fullName>Week_of_year__c</fullName>
    <formula>IF( 
  CEILING( (  ClosingDate__c - DATE( YEAR( ClosingDate__c), 1, 1) + 1) / 7) &gt; 52,
  52,
  CEILING( ( ClosingDate__c- DATE( YEAR( ClosingDate__c), 1, 1) + 1) / 7)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Week of year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <label>Manager</label>
    <relationshipName>User</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/classes/RecruitmentPlanCalendarController.cls
public with sharing class RecruitmentPlanCalendarController {

    @AuraEnabled
    public static RecruitmentPlan__c getCurRPL(String id){
        RecruitmentPlan__c rs;
        try {
            rs = [SELECT StartDate__c FROM RecruitmentPlan__c WHERE Id = :id];
            return rs;
        } catch (Exception e) {
            return new RecruitmentPlan__c();
        }
    }
    
    @AuraEnabled
    public static List<RecruitmentPlanLine__c> getAllRPLLineByWeek(String rplId){
        List<RecruitmentPlanLine__c> rs = null;
        try {
            rs = [SELECT 
            Id,
            Name,
            Month__c,
            Quarter_of_Year__c,
            Week_of_year__c,
            ClosingDate__c,
            Position__r.Id,
            Position__r.Name,
            Quantity__c,
            ReasonsForRecruitment__c,
            Manager__r.Id,
            Manager__r.Name,
            Change__c
            FROM RecruitmentPlanLine__c
            WHERE RecruitmentPlan__c = :rplId AND Week_of_year__c != NULL
            ORDER BY Week_of_year__c];
            return rs;
        } catch (Exception e) {
            return new List<RecruitmentPlanLine__c>();
        }
    }
    @AuraEnabled
    public static List<RecruitmentPlanLine__c> getAllRPLLineByMonth(String rplId, String month){
        List<RecruitmentPlanLine__c> rs = null;
        String monthName;
        Integer monthNum = Integer.valueOf(month);
        switch on monthNum {
            when 1 {		// when block 1
                monthName = 'January';
            }	
            when 2 {		// when block 2
                monthName = 'February';
            }
            when 3 {		// when block 3
                monthName = 'March';
            }
            when 4 {		// when block 1
                monthName = 'April';
            }	
            when 5 {		// when block 2
                monthName = 'May';
            }
            when 6 {		// when block 3
                monthName = 'June';
            }
            when 7 {		// when block 1
                monthName = 'July';
            }	
            when 8 {		// when block 2
                monthName = 'August';
            }
            when 9 {		// when block 3
                monthName = 'September';
            }
            when 10 {		// when block 1
                monthName = 'October';
            }	
            when 11 {		// when block 2
                monthName = 'November';
            }
            when 12 {		// when block 3
                monthName = 'December';
            }
            when else {		  // default block, optional
                monthName = '';
            }
        }
        try {
            System.debug('month: '+monthName);
            rs = [SELECT 
            Id,
            Name,
            Month__c,
            Quarter_of_Year__c,
            Week_of_year__c,
            ClosingDate__c,
            Position__r.Id,
            Position__r.Name,
            Quantity__c,
            ReasonsForRecruitment__c,
            Manager__r.Id,
            Manager__r.Name,
            Change__c
            FROM RecruitmentPlanLine__c
            WHERE RecruitmentPlan__c = :rplId AND Week_of_year__c != NULL AND Month__c != NULL AND Month__c = :monthName
            ORDER BY Week_of_year__c];
            System.debug('RS LENGTH: ');
            System.debug(rs.size());
            System.debug(rs);
            return rs;
        } catch (Exception e) {
            return new List<RecruitmentPlanLine__c>();
        }
    }
    @AuraEnabled
    public static List<RecruitmentPlanLine__c> getAllRPLLineByQuarter(String rplId, String quarter){
        List<RecruitmentPlanLine__c> rs = null;
        Decimal quarterNum = Decimal.valueOf(quarter);
        try {
            rs = [SELECT 
            Id,
            Name,
            Month__c,
            Quarter_of_Year__c,
            Week_of_year__c,
            ClosingDate__c,
            Position__r.Id,
            Position__r.Name,
            Quantity__c,
            ReasonsForRecruitment__c,
            Manager__r.Id,
            Manager__r.Name,
            Change__c
            FROM RecruitmentPlanLine__c
            WHERE RecruitmentPlan__c = :rplId AND Week_of_year__c != NULL AND Quarter_of_Year__c != NULL AND Quarter_of_Year__c = :quarterNum
            ORDER BY Week_of_year__c];
            return rs;
        } catch (Exception e) {
            return new List<RecruitmentPlanLine__c>();
        }
    }
    @AuraEnabled
    public static List<RecruitmentPlanLine__c> getMoreRecord(String rplId, String weekNum, String colNum){
        List<RecruitmentPlanLine__c> rs = null;
        Integer colNumVal = Integer.valueOf(colNum);
        Decimal weekNumVal = Decimal.valueOf(weekNum);
        try {
            rs = [SELECT 
            Id,
            Name,
            Month__c,
            Quarter_of_Year__c,
            Week_of_year__c,
            ClosingDate__c,
            Position__r.Id,
            Position__r.Name,
            Quantity__c,
            ReasonsForRecruitment__c,
            Manager__r.Id,
            Manager__r.Name,
            Change__c
            FROM RecruitmentPlanLine__c
            WHERE RecruitmentPlan__c = :rplId AND Week_of_year__c != NULL AND Week_of_year__c = :weekNumVal
            ORDER BY Week_of_year__c
            LIMIT 5 OFFSET :colNumVal];
            return rs;
        } catch (Exception e) {
            return new List<RecruitmentPlanLine__c>();
        }
    }
}