force-app/main/default/objects/AdvancedShipment__c/AdvancedShipment__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>AS-{00000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AdvancedShipment__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch (not used)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ho Chi Minh</fullName>
            </value>
            <value>
                <fullName>Ha Noi</fullName>
            </value>
            <value>
                <fullName>Hai Phong</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/Master_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Master_Record_Type__c</fullName>
    <label>Master Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ocean Export</fullName>
            </value>
            <value>
                <fullName>Ocean Import</fullName>
            </value>
            <value>
                <fullName>Air Export</fullName>
                <isActive>false</isActive>
                <label>Air Export</label>
            </value>
            <value>
                <fullName>Air Import</fullName>
                <isActive>false</isActive>
                <label>Air Import</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/MPOL__c.field-meta.xml
<CustomField>
    <fullName>MPOL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.L(A.O.D)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>AdvancedShipment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/Shipment_Type__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Type__c</fullName>
    <label>Shipment Type (not use)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consol</fullName>
            </value>
            <value>
                <fullName>FCL</fullName>
            </value>
            <value>
                <fullName>LCL</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PortCode__c/PortCode__c.object-meta.xml
<CustomObject>
    <label>Port Code</label>
    <nameField>
        <label>Port Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Port Code</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PortCode__c/fields/PortCode__c.field-meta.xml
<CustomField>
    <fullName>PortCode__c</fullName>
    <label>Port Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PrintAdvancedShipmentManifestCtlTest.cls
@isTest
public class PrintAdvancedShipmentManifestCtlTest {
	@isTest
    public static void Test1(){
       
        
         PortCode__c pc2= new PortCode__c(Name= 'VP of Services',Active__c = true);
        insert pc2;
        Id rcID= Schema.SObjectType.AdvancedShipment__c.getRecordTypeInfosByName().get('Consol').getRecordTypeId();
        AdvancedShipment__c av= new AdvancedShipment__c(
       		RecordTypeId=rcID,
            Branch__c= 'Ho Chi Minh',
            Shipment_Type__c='Consol',
            Master_Record_Type__c='Ocean Export',
            MPOL__c=pc2.Id
          
        );
        insert av;
        Test.startTest();
        PageReference pageRef = Page.page_PrintAdvancedShipmentManifest;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('Id', String.valueOf(av.Id));
        ApexPages.StandardController stdController = new ApexPages.StandardController(av);
        PrintAdvancedShipmentManifestController form = new PrintAdvancedShipmentManifestController();
        System.assertEquals(true, true);
        Test.stopTest();
    }
}