force-app/main/default/objects/AdvancedShipment__c/AdvancedShipment__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>AS-{00000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AdvancedShipment__c/fields/Agent2nd__c.field-meta.xml
<CustomField>
    <fullName>Agent2nd__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent (2nd)</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Advanced_Shipment6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch (not used)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ho Chi Minh</fullName>
            </value>
            <value>
                <fullName>Ha Noi</fullName>
            </value>
            <value>
                <fullName>Hai Phong</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/CargoType__c.field-meta.xml
<CustomField>
    <fullName>CargoType__c</fullName>
    <label>Cargo Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CY/CY</fullName>
            </value>
            <value>
                <fullName>CFS/CFS</fullName>
            </value>
            <value>
                <fullName>CY/CFS</fullName>
            </value>
            <value>
                <fullName>CFS/CY</fullName>
            </value>
            <value>
                <fullName>LCL/LCL</fullName>
            </value>
            <value>
                <fullName>FCL/FCL</fullName>
            </value>
            <value>
                <fullName>FI/CL</fullName>
            </value>
            <value>
                <fullName>CY/FO</fullName>
            </value>
            <value>
                <fullName>FI/FO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/Container_Qnty_1__c.field-meta.xml
<CustomField>
    <fullName>Container_Qnty_1__c</fullName>
    <label>Container Qnty-1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/Container_Qnty_2__c.field-meta.xml
<CustomField>
    <fullName>Container_Qnty_2__c</fullName>
    <label>Container Qnty-2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/Container_Qnty_3__c.field-meta.xml
<CustomField>
    <fullName>Container_Qnty_3__c</fullName>
    <label>Container Qnty-3</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/Container_Type_1__c.field-meta.xml
<CustomField>
    <fullName>Container_Type_1__c</fullName>
    <label>Container Type-1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20&apos;DC</fullName>
            </value>
            <value>
                <fullName>20&apos;HC</fullName>
            </value>
            <value>
                <fullName>40&apos;DC</fullName>
            </value>
            <value>
                <fullName>45&apos;DC</fullName>
            </value>
            <value>
                <fullName>40&apos;HC</fullName>
            </value>
            <value>
                <fullName>45&apos;HC</fullName>
            </value>
            <value>
                <fullName>20&apos;RF</fullName>
            </value>
            <value>
                <fullName>40&apos;RF</fullName>
            </value>
            <value>
                <fullName>45&apos;RF</fullName>
            </value>
            <value>
                <fullName>20&apos;OT</fullName>
            </value>
            <value>
                <fullName>40&apos;OT</fullName>
            </value>
            <value>
                <fullName>45&apos;OT</fullName>
            </value>
            <value>
                <fullName>20&apos;FR</fullName>
            </value>
            <value>
                <fullName>40&apos;FR</fullName>
            </value>
            <value>
                <fullName>Bulk</fullName>
            </value>
            <value>
                <fullName>ISO</fullName>
            </value>
            <value>
                <fullName>20&apos;IMO</fullName>
            </value>
            <value>
                <fullName>40&apos;IMO</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>CBM</fullName>
            </value>
            <value>
                <fullName>RTON</fullName>
            </value>
            <value>
                <fullName>-1000KGS</fullName>
            </value>
            <value>
                <fullName>+1000KGS</fullName>
            </value>
            <value>
                <fullName>+2000KGS</fullName>
            </value>
            <value>
                <fullName>+3000KGS</fullName>
            </value>
            <value>
                <fullName>+4000KGS</fullName>
            </value>
            <value>
                <fullName>+5000KGS</fullName>
            </value>
            <value>
                <fullName>+6000KGS</fullName>
            </value>
            <value>
                <fullName>+7000KGS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/Container_Type_2__c.field-meta.xml
<CustomField>
    <fullName>Container_Type_2__c</fullName>
    <label>Container Type-2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20&apos;DC</fullName>
            </value>
            <value>
                <fullName>20&apos;HC</fullName>
            </value>
            <value>
                <fullName>40&apos;DC</fullName>
            </value>
            <value>
                <fullName>45&apos;DC</fullName>
            </value>
            <value>
                <fullName>40&apos;HC</fullName>
            </value>
            <value>
                <fullName>45&apos;HC</fullName>
            </value>
            <value>
                <fullName>20&apos;RF</fullName>
            </value>
            <value>
                <fullName>40&apos;RF</fullName>
            </value>
            <value>
                <fullName>45&apos;RF</fullName>
            </value>
            <value>
                <fullName>20&apos;OT</fullName>
            </value>
            <value>
                <fullName>40&apos;OT</fullName>
            </value>
            <value>
                <fullName>45&apos;OT</fullName>
            </value>
            <value>
                <fullName>20&apos;FR</fullName>
            </value>
            <value>
                <fullName>40&apos;FR</fullName>
            </value>
            <value>
                <fullName>Bulk</fullName>
            </value>
            <value>
                <fullName>ISO</fullName>
            </value>
            <value>
                <fullName>20&apos;IMO</fullName>
            </value>
            <value>
                <fullName>40&apos;IMO</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>CBM</fullName>
            </value>
            <value>
                <fullName>RTON</fullName>
            </value>
            <value>
                <fullName>-1000KGS</fullName>
            </value>
            <value>
                <fullName>+1000KGS</fullName>
            </value>
            <value>
                <fullName>+2000KGS</fullName>
            </value>
            <value>
                <fullName>+3000KGS</fullName>
            </value>
            <value>
                <fullName>+4000KGS</fullName>
            </value>
            <value>
                <fullName>+5000KGS</fullName>
            </value>
            <value>
                <fullName>+6000KGS</fullName>
            </value>
            <value>
                <fullName>+7000KGS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/FileNo__c.field-meta.xml
<CustomField>
    <fullName>FileNo__c</fullName>
    <label>File No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>Gross Weight</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/JobRequestID__c.field-meta.xml
<CustomField>
    <fullName>JobRequestID__c</fullName>
    <label>Job Request ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/MAgent__c.field-meta.xml
<CustomField>
    <fullName>MAgent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>M-Agent</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Advanced_Shipment2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/MBLorMAWBNumber__c.field-meta.xml
<CustomField>
    <fullName>MBLorMAWBNumber__c</fullName>
    <label>M B/L or M AWB Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/MeasurementCBM__c.field-meta.xml
<CustomField>
    <fullName>MeasurementCBM__c</fullName>
    <label>Measurement(CBM)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/MPOD__c.field-meta.xml
<CustomField>
    <fullName>MPOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.D(A.O.A)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>Advanced_Shipment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/MPOL__c.field-meta.xml
<CustomField>
    <fullName>MPOL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.L(A.O.D)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>AdvancedShipment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/Shipment_Type__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Type__c</fullName>
    <label>Shipment Type (not use)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consol</fullName>
            </value>
            <value>
                <fullName>FCL</fullName>
            </value>
            <value>
                <fullName>LCL</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/VesselFlight__c.field-meta.xml
<CustomField>
    <fullName>VesselFlight__c</fullName>
    <label>Vessel/Flight</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/Voyage__c.field-meta.xml
<CustomField>
    <fullName>Voyage__c</fullName>
    <label>Voyage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AdvancedShipmentClass.cls
//public class AdvancedShipmentClass {
public without sharing class AdvancedShipmentClass {
    private static Set<String> setFieldSO = new Set<String>();
    static{
        setFieldSO.add('JobRequestID__c');
        setFieldSO.add('FileNo__c');
        // setFieldSO.add('GrossWeight__c');
        // // setFieldSO.add('Measurement__c');
        setFieldSO.add('MAgent__r.Name');
        setFieldSO.add('Agent2nd__r.Name');
        setFieldSO.add('MPOD__r.Name');
        setFieldSO.add('MPOL__r.Name');
        // setFieldSO.add('POD_Formul__c');
        // setFieldSO.add('POLformula__c');
        setFieldSO.add('VesselFlight__c');
        setFieldSO.add('Voyage__c');
        setFieldSO.add('MBLorMAWBNumber__c');
        // setFieldSO.add('MBLNumber__c');
        setFieldSO.add('Name');
        setFieldSO.add('Branch__c');
        setFieldSO.add('CargoType__c');
        setFieldSO.add('GrossWeight__c');
        setFieldSO.add('MeasurementCBM__c');
        setFieldSO.add('Shipment_Type__c');
        setFieldSO.add('RecordType.Name');

        setFieldSO.add('Container_Qnty_1__c');
        setFieldSO.add('Container_Qnty_2__c');
        setFieldSO.add('Container_Qnty_3__c');
        setFieldSO.add('Container_Type_1__c');
        setFieldSO.add('Container_Type_2__c');
        setFieldSO.add('Container_Type_3__c');
    }
	public static void isBeforeInsert(List<AdvancedShipment__c> lstAdShipNew){
        System.debug('12345');
        Set<Date> setAccountedDate = new Set<Date>();
        for (AdvancedShipment__c adShip : lstAdShipNew){
            if (adShip.isClone()){
                adShip.CheckClone__c = true;
            }
            
            // Accouted Date
            if (adShip.AccountedDate__c == null) {
                if (adShip.TypeofTrade__c == 'IMPORT') {
                    adShip.AccountedDate__c = adShip.ETA__c;
                } else if (adShip.TypeofTrade__c == 'EXPORT') {
                    adShip.AccountedDate__c = adShip.ETD__c;
                } else {
                    adShip.AccountedDate__c = Date.today();
                }
            }
            setAccountedDate.add(adShip.AccountedDate__c);
        }
        // File No
        System.debug('1234567');
        if (setAccountedDate.size() > 0) {
            String selectStr = 'SELECT MAX(NumberMonth__c),CALENDAR_MONTH(AccountedDate__c), CALENDAR_YEAR(AccountedDate__c) FROM AdvancedShipment__c ';
            String whereStr = 'WHERE ';
            String groupByStr = ' GROUP BY CALENDAR_MONTH(AccountedDate__c), CALENDAR_YEAR(AccountedDate__c) ';
            for (Date accDate : setAccountedDate) {
                whereStr += ' (CALENDAR_MONTH(AccountedDate__c) = '+ accDate.month() + ' AND CALENDAR_YEAR(AccountedDate__c) = '+ accDate.year() + ') AND';
            }
            whereStr = whereStr.removeEnd(' AND');
            List<AggregateResult> lstItem = new List<AggregateResult>();
            system.debug(selectStr + whereStr + groupByStr);
            try {
                system.debug(selectStr + whereStr + groupByStr);
                lstItem = Database.query(selectStr + whereStr + groupByStr);
            } catch (QueryException e) {
                
            }
            
            Map<String, Integer> mapCount = new Map<String, Integer>();
            for (AggregateResult item : lstItem) {
                String key = String.valueOf((Integer)item.get('expr1')) +'-' + String.valueOf((Integer)item.get('expr2'));
                Integer count = (Decimal) item.get('expr0') != null ? Integer.valueOf((Decimal) item.get('expr0')) : 0;
                mapCount.put(key,count);
            }
            for (AdvancedShipment__c adShip : lstAdShipNew) {
                if (adShip.FileNo__c == null) {
                    String key = String.valueOf(adShip.AccountedDate__c.month()) + '-' + String.valueOf(adShip.AccountedDate__c.year());
                    Integer count = 0;
                    if (mapCount.containsKey(key)) {
                        count = mapCount.get(key);
                    }
                    String typeOfTrade = '';
                    if (adShip.TypeofTrade__c == 'IMPORT') {
                        typeOfTrade = 'IM';
                    } else if (adShip.TypeofTrade__c == 'EXPORT') {
                        typeOfTrade = 'EX';
                    } else if (adShip.TypeofTrade__c == 'DOMESTIC') {
                        typeOfTrade = 'DO';
                    } else if (adShip.TypeofTrade__c == 'ENTREPOT') {
                        typeOfTrade = 'EN';
                    } else if (adShip.TypeofTrade__c == 'THIRD COUNTRY') {
                        typeOfTrade = 'TC';
                    }
                    String shipmentTerm = '';
                    if (adShip.ShipmentTerm__c == 'FCL') {
                        shipmentTerm = 'F';
                    } else if (adShip.ShipmentTerm__c == 'LCL') {
                        shipmentTerm = 'L';
                    } else if (adShip.ShipmentTerm__c == 'CONSOL') {
                        shipmentTerm = 'C';
                    } else if (adShip.ShipmentTerm__c == 'CHARTER') {
                        shipmentTerm = 'R';
                    }
                    String transWay = '';
                    if (adShip.TransportationWay__c == 'SEA') {
                        transWay = 'SEA';
                    } else if (adShip.TransportationWay__c == 'AIR') {
                        transWay = 'AIR';
                    } else if (adShip.TransportationWay__c == 'TRUCKING') {
                        transWay = 'TRU';
                    } else if (adShip.TransportationWay__c == 'RAIL') {
                        transWay = 'RAI';
                    } else if (adShip.TransportationWay__c == 'INLAND WATERWAY') {
                        transWay = 'INW';
                    }
                    count++;
                    String jobId = typeOfTrade + '-' + shipmentTerm + transWay + String.valueOf(adShip.AccountedDate__c.year()).subString(3,4) + String.valueOf(adShip.AccountedDate__c.month()).leftPad(2,'0') + String.valueOf(count).leftPad(3,'0');
                    adShip.FileNo__c = jobId;
                    adShip.NumberMonth__c = count;
                    mapCount.put(key,count);
                }
            }
         }
    }
    
    public static void isBeforeUpdate(List<AdvancedShipment__c> lstAdShipNew){
        System.debug('lstAdShipNew'+ lstAdShipNew);
        Set<Date> setAccountedDate = new Set<Date>();
        for (AdvancedShipment__c adShip : lstAdShipNew){
            // Accouted Date
            if (adShip.AccountedDate__c == null) {
                if (adShip.TypeofTrade__c == 'IMPORT') {
                    adShip.AccountedDate__c = adShip.ETA__c;
                } else if (adShip.TypeofTrade__c == 'EXPORT') {
                    adShip.AccountedDate__c = adShip.ETD__c;
                } else {
                    adShip.AccountedDate__c = Date.valueOf(adShip.CreatedDate);
                }
            }
            setAccountedDate.add(adShip.AccountedDate__c);
        }
        // File No
        if (setAccountedDate.size() > 0) {
            String selectStr = 'SELECT MAX(NumberMonth__c),CALENDAR_MONTH(AccountedDate__c), CALENDAR_YEAR(AccountedDate__c) FROM AdvancedShipment__c ';
            String whereStr = 'WHERE ';
            String groupByStr = ' GROUP BY CALENDAR_MONTH(AccountedDate__c), CALENDAR_YEAR(AccountedDate__c) ';
            for (Date accDate : setAccountedDate) {
                whereStr += ' (CALENDAR_MONTH(AccountedDate__c) = '+ accDate.month() + ' AND CALENDAR_YEAR(AccountedDate__c) = '+ accDate.year() + ') AND';
            }
            whereStr = whereStr.removeEnd(' AND');
            List<AggregateResult> lstItem = new List<AggregateResult>();
            system.debug(selectStr + whereStr + groupByStr);
            try {
                system.debug(selectStr + whereStr + groupByStr);
                lstItem = Database.query(selectStr + whereStr + groupByStr);
            } catch (QueryException e) {
                
            }
            
            Map<String, Integer> mapCount = new Map<String, Integer>();
            for (AggregateResult item : lstItem) {
                String key = String.valueOf((Integer)item.get('expr1')) +'-' + String.valueOf((Integer)item.get('expr2'));
                Integer count = (Decimal) item.get('expr0') != null ? Integer.valueOf((Decimal) item.get('expr0')) : 0;
                mapCount.put(key,count);
            }
            for (AdvancedShipment__c adShip : lstAdShipNew) {
                if (adShip.FileNo__c == null) {
                    String key = String.valueOf(adShip.AccountedDate__c.month()) + '-' + String.valueOf(adShip.AccountedDate__c.year());
                    Integer count = 0;
                    if (mapCount.containsKey(key)) {
                        count = mapCount.get(key);
                    }
                    String typeOfTrade = '';
                    if (adShip.TypeofTrade__c == 'IMPORT') {
                        typeOfTrade = 'IM';
                    } else if (adShip.TypeofTrade__c == 'EXPORT') {
                        typeOfTrade = 'EX';
                    } else if (adShip.TypeofTrade__c == 'DOMESTIC') {
                        typeOfTrade = 'DO';
                    } else if (adShip.TypeofTrade__c == 'ENTREPOT') {
                        typeOfTrade = 'EN';
                    } else if (adShip.TypeofTrade__c == 'THIRD COUNTRY') {
                        typeOfTrade = 'TC';
                    }
                    String shipmentTerm = '';
                    if (adShip.ShipmentTerm__c == 'FCL') {
                        shipmentTerm = 'F';
                    } else if (adShip.ShipmentTerm__c == 'LCL') {
                        shipmentTerm = 'L';
                    } else if (adShip.ShipmentTerm__c == 'CONSOL') {
                        shipmentTerm = 'C';
                    } else if (adShip.ShipmentTerm__c == 'CHARTER') {
                        shipmentTerm = 'R';
                    }
                    String transWay = '';
                    if (adShip.TransportationWay__c == 'SEA') {
                        transWay = 'SEA';
                    } else if (adShip.TransportationWay__c == 'AIR') {
                        transWay = 'AIR';
                    } else if (adShip.TransportationWay__c == 'TRUCKING') {
                        transWay = 'TRU';
                    } else if (adShip.TransportationWay__c == 'RAIL') {
                        transWay = 'RAI';
                    } else if (adShip.TransportationWay__c == 'INLAND WATERWAY') {
                        transWay = 'INW';
                    }
                    count++;
                    String jobId = typeOfTrade + '-' + shipmentTerm + transWay + String.valueOf(adShip.AccountedDate__c.year()).subString(3,4) + String.valueOf(adShip.AccountedDate__c.month()).leftPad(2,'0') + String.valueOf(count).leftPad(3,'0');
                    adShip.FileNo__c = jobId;
                    adShip.NumberMonth__c = count;
                    mapCount.put(key,count);
                    System.debug('jobID:' + adShip.FileNo__c);
                }
            }
         }
    }
    // @future (callout= true)
    // public static void generateAttachmentFile(String TargetObjectId){
    //     System.debug('loggg :');
    //     // String TargetObjectId = '';
    //     // for (AdvancedShipment__c adShip : lstAdShipNew){
    //     //     TargetObjectId = adShip.Id;

    //     // }
    //     // System.debug('TargetObjectId :'+TargetObjectId);
        
    //     PageReference pdf_file =Page.page_ProfitStatementForRequestV2;
    //     pdf_file.getParameters().put('Id', TargetObjectId);

    //     System.debug('shipmentID :'+TargetObjectId);
        
    //     AdvancedShipment__c item = new AdvancedShipment__c();
    //     String strSelect = 'SELECT ' + String.join(new List<String>(setFieldSO), ',');
    //     String strFrom = ' FROM AdvancedShipment__c ';
    //     String strWhere = 'WHERE Id = \'' + TargetObjectId + '\'' ;
    //     String strOrderBy = ' ORDER BY Name LIMIT 1';
    //     String data = strSelect + strFrom + strWhere + strOrderBy;
    //     item = Database.query(data);
    //     String namefile =item.Name +'_ProfitStatementRequest_' ;

       
    //     String attachName = namefile ;
    //     String attachNameSearch = attachName + '%';
    //     // get exist file Name
    //     List<Attachment> attachments = [SELECT Id, Name, ParentId 
    //                                     FROM Attachment 
    //                                     WHERE ParentId =: TargetObjectId 
    //                                     AND Name LIKE : attachNameSearch 
    //                                     ORDER BY CreatedDate DESC LIMIT 1];
                                        
    //     if(attachments.isEmpty()){
    //         attachName += '1.1';
    //     }else{
    //         String attachNameExist = attachments[0].Name;
    //         attachNameExist = attachNameExist.substringAfter(attachName);
    //         attachNameExist = attachNameExist.substringBefore('.pdf');
    //         Decimal versionNumber = Decimal.valueOf(attachNameExist);
    //         versionNumber += 0.1;
    //         attachName += String.valueOf(versionNumber);
    //     }
    //     // if(requiredAttachmentCreation != false){
    //         Attachment attach = new Attachment();
    //         Blob body;
    //         attach.Name = attachName + '.pdf'; 
    //         attach.IsPrivate = false;
    //         attach.ParentId = TargetObjectId;
    //         if(!Test.isRunningTest()){
    //         body = pdf_file.getContentAsPDF();
    //         System.debug('debuggg Thong :'+body);
    //         attach.Body = body;
    //         FlsService.doInsert(attach);
    //     }
    //     // }
        
        
    // }
}