force-app/main/default/objects/AdvancedShipment__c/AdvancedShipment__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>AS-{00000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AdvancedShipment__c/fields/CargoQuantity__c.field-meta.xml
<CustomField>
    <fullName>CargoQuantity__c</fullName>
    <label>Cargo Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/CheckClone__c.field-meta.xml
<CustomField>
    <fullName>CheckClone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Check Clone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/FileNo__c.field-meta.xml
<CustomField>
    <fullName>FileNo__c</fullName>
    <label>File No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/JobRequestID__c.field-meta.xml
<CustomField>
    <fullName>JobRequestID__c</fullName>
    <label>Job Request ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/Shipment_Type__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Type__c</fullName>
    <label>Shipment Type (not use)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consol</fullName>
            </value>
            <value>
                <fullName>FCL</fullName>
            </value>
            <value>
                <fullName>LCL</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/CntrinTrans__c.object-meta.xml
<CustomObject>
    <label>CNTR in Trans</label>
    <nameField>
        <displayFormat>CNTR-{00000}</displayFormat>
        <label>CNTR in Trans</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CNTR in Trans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CntrinTrans__c/fields/AdvancedShipment__c.field-meta.xml
<CustomField>
    <fullName>AdvancedShipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advanced Shipment</label>
    <referenceTo>AdvancedShipment__c</referenceTo>
    <relationshipLabel>CNTR in Trans</relationshipLabel>
    <relationshipName>CNTRinTrans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/Cargo_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Cargo_Quantity__c</fullName>
    <label>Cargo Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/CargoUnit__c.field-meta.xml
<CustomField>
    <fullName>CargoUnit__c</fullName>
    <label>Cargo Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargoUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/Container_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Container_Quantity__c</fullName>
    <formula>1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Container Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/Container_Type__c.field-meta.xml
<CustomField>
    <fullName>Container_Type__c</fullName>
    <label>Container Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20&apos;DC</fullName>
            </value>
            <value>
                <fullName>20&apos;HC</fullName>
            </value>
            <value>
                <fullName>40&apos;DC</fullName>
            </value>
            <value>
                <fullName>45&apos;DC</fullName>
            </value>
            <value>
                <fullName>40&apos;HC</fullName>
            </value>
            <value>
                <fullName>45&apos;HC</fullName>
            </value>
            <value>
                <fullName>20&apos;RF</fullName>
            </value>
            <value>
                <fullName>40&apos;RF</fullName>
            </value>
            <value>
                <fullName>45&apos;RF</fullName>
            </value>
            <value>
                <fullName>20&apos;OT</fullName>
            </value>
            <value>
                <fullName>40&apos;OT</fullName>
            </value>
            <value>
                <fullName>45&apos;OT</fullName>
            </value>
            <value>
                <fullName>20&apos;FR</fullName>
            </value>
            <value>
                <fullName>40&apos;FR</fullName>
            </value>
            <value>
                <fullName>Bulk</fullName>
            </value>
            <value>
                <fullName>ISO</fullName>
            </value>
            <value>
                <fullName>20&apos;IMO</fullName>
            </value>
            <value>
                <fullName>40&apos;IMO</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>20&apos;DC-Flexi</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>CBM</fullName>
            </value>
            <value>
                <fullName>RTON</fullName>
            </value>
            <value>
                <fullName>2*20&apos;DC</fullName>
                <isActive>false</isActive>
                <label>2*20&apos;DC</label>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/F_TMS_S_O__c.field-meta.xml
<CustomField>
    <fullName>F_TMS_S_O__c</fullName>
    <label>F/TMS S/O</label>
    <referenceTo>FTMSSO__c</referenceTo>
    <relationshipLabel>CNTR in Trans</relationshipLabel>
    <relationshipName>CNTR_in_Trans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/Gross_Weight_Kg__c.field-meta.xml
<CustomField>
    <fullName>Gross_Weight_Kg__c</fullName>
    <label>Gross Weight(Kg)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/Measurement_CBM__c.field-meta.xml
<CustomField>
    <fullName>Measurement_CBM__c</fullName>
    <label>Measurement(CBM)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/FTMSSO__c.object-meta.xml
<CustomObject>
    <label>Shipment.</label>
    <nameField>
        <displayFormat>FSO-{000000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments.</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSSO__c/fields/AccountedDate__c.field-meta.xml
<CustomField>
    <fullName>AccountedDate__c</fullName>
    <label>Accounted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoQuantity__c.field-meta.xml
<CustomField>
    <fullName>CargoQuantity__c</fullName>
    <label>Cargo Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoUnit__c.field-meta.xml
<CustomField>
    <fullName>CargoUnit__c</fullName>
    <label>Cargo Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargoUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CheckClone__c.field-meta.xml
<CustomField>
    <fullName>CheckClone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Check Clone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ConsolidationID__c.field-meta.xml
<CustomField>
    <fullName>ConsolidationID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consolidation ID</label>
    <referenceTo>AdvancedShipment__c</referenceTo>
    <relationshipName>F_TMS_S_O</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HAWBNumber__c.field-meta.xml
<CustomField>
    <fullName>HAWBNumber__c</fullName>
    <label>H AWB Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HBLNumber__c.field-meta.xml
<CustomField>
    <fullName>HBLNumber__c</fullName>
    <label>H B/L Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/JobRequestID__c.field-meta.xml
<CustomField>
    <fullName>JobRequestID__c</fullName>
    <label>File No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number FTSSO IN Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ParentFTMSSO__c.field-meta.xml
<CustomField>
    <fullName>ParentFTMSSO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent F/TMS S/O</label>
    <referenceTo>FTMSSO__c</referenceTo>
    <relationshipName>F_TMS_S_O</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PlaceofReceipt__c.field-meta.xml
<CustomField>
    <fullName>PlaceofReceipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place of Receipt</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PODAOA__c.field-meta.xml
<CustomField>
    <fullName>PODAOA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.D(A.O.A)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/POLAOD__c.field-meta.xml
<CustomField>
    <fullName>POLAOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.L(A.O.D)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Shipment_Type__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Type__c</fullName>
    <label>Shipment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consol</fullName>
            </value>
            <value>
                <fullName>FCL</fullName>
            </value>
            <value>
                <fullName>LCL</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
                <isActive>false</isActive>
                <label>Logistics</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/TransportationWay__c.field-meta.xml
<CustomField>
    <fullName>TransportationWay__c</fullName>
    <label>Transportation Way</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>TypeofTrade__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Transportation_Way</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/TypeofTrade__c.field-meta.xml
<CustomField>
    <fullName>TypeofTrade__c</fullName>
    <label>Type of Trade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_of_Trade</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PortCode__c/PortCode__c.object-meta.xml
<CustomObject>
    <label>Port Code</label>
    <nameField>
        <label>Port Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Port Code</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PortCode__c/fields/PortCode__c.field-meta.xml
<CustomField>
    <fullName>PortCode__c</fullName>
    <label>Port Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortCode__c/fields/Standard_Port_Code__c.field-meta.xml
<CustomField>
    <fullName>Standard_Port_Code__c</fullName>
    <label>Standard Port Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/CargoUnit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B/PLT</fullName>
    </customValue>
    <customValue>
        <fullName>BAG</fullName>
    </customValue>
    <customValue>
        <fullName>BAL</fullName>
    </customValue>
    <customValue>
        <fullName>BALE</fullName>
    </customValue>
    <customValue>
        <fullName>BALE, COMPRESSED</fullName>
    </customValue>
    <customValue>
        <fullName>Bale,non-compressed</fullName>
        <label>BALE, NON-COMPRESSED</label>
    </customValue>
    <customValue>
        <fullName>Bar</fullName>
        <label>BAR</label>
    </customValue>
    <customValue>
        <fullName>BARE</fullName>
    </customValue>
    <customValue>
        <fullName>BARREL</fullName>
    </customValue>
    <customValue>
        <fullName>BILL</fullName>
    </customValue>
    <customValue>
        <fullName>BIN</fullName>
    </customValue>
    <customValue>
        <fullName>BOX</fullName>
    </customValue>
    <customValue>
        <fullName>BOX CARTON</fullName>
    </customValue>
    <customValue>
        <fullName>BOXE</fullName>
    </customValue>
    <customValue>
        <fullName>BOXPAL</fullName>
    </customValue>
    <customValue>
        <fullName>BUCKET</fullName>
    </customValue>
    <customValue>
        <fullName>BULK</fullName>
    </customValue>
    <customValue>
        <fullName>BUNDLE</fullName>
    </customValue>
    <customValue>
        <fullName>CAGE</fullName>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
    </customValue>
    <customValue>
        <fullName>Can,cylindrical</fullName>
        <label>CAN, CYLINDRICAL</label>
    </customValue>
    <customValue>
        <fullName>Can,rectangular</fullName>
        <label>CAN, RECTANGULAR</label>
    </customValue>
    <customValue>
        <fullName>CARBOY, NON-PROTECTED</fullName>
    </customValue>
    <customValue>
        <fullName>Carboy,protected</fullName>
        <label>CARBOY, PROTECTED</label>
    </customValue>
    <customValue>
        <fullName>CARDBOARD</fullName>
    </customValue>
    <customValue>
        <fullName>CARDBOXE</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON BOX</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON BOXE</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON PALLET</fullName>
    </customValue>
    <masterLabel>Cargo Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Transportation_Way.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SEA</fullName>
        <default>true</default>
        <label>SEA</label>
    </customValue>
    <customValue>
        <fullName>AIR</fullName>
    </customValue>
    <customValue>
        <fullName>TRUCKING</fullName>
    </customValue>
    <customValue>
        <fullName>RAIL</fullName>
    </customValue>
    <customValue>
        <fullName>INLAND WATERWAY</fullName>
    </customValue>
    <customValue>
        <fullName>MULTIMODAL</fullName>
    </customValue>
    <masterLabel>Transportation Way</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Type_of_Trade.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DOMESTIC</fullName>
    </customValue>
    <customValue>
        <fullName>IMPORT</fullName>
    </customValue>
    <customValue>
        <fullName>EXPORT</fullName>
    </customValue>
    <customValue>
        <fullName>ENTREPOT</fullName>
    </customValue>
    <customValue>
        <fullName>THIRD COUNTRY</fullName>
    </customValue>
    <masterLabel>Type of Trade</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FTMSSOClass.cls
//public class FTMSSOClass {
public without sharing class FTMSSOClass {
    private static Map<String, Id> mapRecordTypes = retrieveRecordTypeIdsByNames();
    private static Integer year = Date.today().year();
    private static Integer month = Date.today().month();
    private static String polPordCode = '';
    private static String podPordCode = '';
    private static String lastNumerOfYearStr = String.valueof(year).right(1);
    private static String monthStr = String.valueof(month).leftPad(2, '0');
    private static Datetime firstDayOfMonth = Datetime.newInstanceGmt(year, month, 1);
    private static Datetime firstDayOfNextMonth = firstDayOfMonth.addMonths(1);
    public static void isBeforeInsert(List<FTMSSO__c> lstSONew){
        System.debug('ThongDebug :'+lstSONew.size());
        Integer numberFTSSO = 0;
        List<AggregateResult> lstNumber = getMaxFTMSSOInMonth(firstDayOfMonth, firstDayOfNextMonth);
        if(lstNumber[0].get('expr0') != null) {
            numberFTSSO = Integer.valueOf(lstNumber[0].get('expr0'));
        }
       
        List<String> portCodeLst = new List<String>();
        for (FTMSSO__c ship : lstSONew){
            if (ship.TypeofTrade__c == 'Export') {
                if (ship.TransportationWay__c == 'SEA' || ship.TransportationWay__c == 'AIR') {
                    if(ship.POLAOD__c != null) {
                        portCodeLst.add(ship.POLAOD__c);
                    }
                    if(ship.PODAOA__c != null) {
                        portCodeLst.add(ship.PODAOA__c);
                    }
                }
            }
        }
        Map<ID, PortCode__c> mapPortCode = new Map<ID, PortCode__c>();
        if(!portCodeLst.isEmpty()) {
            mapPortCode = getPortCode(portCodeLst);
        }
        // accouted date and file no
        List<String> lstIdAdShip = new List<String>();
        for (FTMSSO__c ship : lstSONew) {
            lstIdAdShip.add(ship.ConsolidationID__c);
        }
        List<AdvancedShipment__c> lstAdShip = [SELECT Id, Name, AccountedDate__c, FileNo__c FROM AdvancedShipment__c WHERE Id IN: lstIdAdShip];
        Map<String, AdvancedShipment__c> mapIdAdShip = new Map<String, AdvancedShipment__c>();
        for (AdvancedShipment__c item : lstAdShip){
            mapIdAdShip.put(item.Id, item);
        }
        for (FTMSSO__c ship : lstSONew){
            if (ship.AccountedDate__c == null || ship.isClone()) {
            	ship.AccountedDate__c = mapIdAdShip.get(ship.ConsolidationID__c).AccountedDate__c;
            }
            if (ship.JobRequestID__c == null || ship.isClone()) {
            	ship.JobRequestID__c = mapIdAdShip.get(ship.ConsolidationID__c).FileNo__c;
            }
            if (ship.isClone()){
                ship.CheckClone__c = true;
            }

            if (ship.TypeofTrade__c == 'Export') {
                String numberFTSSOStr = String.valueOf(numberFTSSO + 1);
                if (ship.TransportationWay__c == 'SEA') {
                    if(ship.POLAOD__c != null) {
                        polPordCode = mapPortCode.get(ship.POLAOD__c).Standard_Port_Code__c.right(3);
                    }
                    if(ship.PODAOA__c != null) {
                        podPordCode =  mapPortCode.get(ship.PODAOA__c).Standard_Port_Code__c.right(3);
                    }
                    ship.HBLNumber__c = polPordCode + podPordCode + lastNumerOfYearStr + monthStr + numberFTSSOStr.leftPad(3,'0');
                    ship.HBLNumber__c = checkMaxLength(ship.HBLNumber__c);
                }

                if (ship.TransportationWay__c == 'AIR') {
                    if(ship.PODAOA__c != null) {
                        podPordCode =  mapPortCode.get(ship.PODAOA__c).Standard_Port_Code__c.right(3);
                    }
                    ship.HAWBNumber__c = 'TCL' + lastNumerOfYearStr + monthStr + numberFTSSOStr.leftPad(3,'0') + podPordCode;
                    ship.HAWBNumber__c = checkMaxLength(ship.HAWBNumber__c);
                }
                numberFTSSO++;
                ship.Number__c = numberFTSSO;
                System.debug('ThongcheckNumber :'+ship.Number__c);
            }
        }
    }
    public static void isBeforeUpdate(List<FTMSSO__c> lstSONew, Map<Id,FTMSSO__c> mapSOOld){
        System.debug('ThongDebug2 :'+lstSONew.size());
        Integer numberFTSSO = 0;
        System.debug('firstDayOfMonth :'+firstDayOfMonth);
        System.debug('firstDayOfNextMonth :'+firstDayOfNextMonth);
        List<AggregateResult> lstNumber = getMaxFTMSSOInMonth(firstDayOfMonth, firstDayOfNextMonth);
        System.debug('ThongDebuglstNumber :'+lstNumber.size());
        if(lstNumber[0].get('expr0') != null) {
            numberFTSSO = Integer.valueOf(lstNumber[0].get('expr0'));
        }
       
        //Map<ID, PortCode__c> mapPortCode = getPortCode();
        List<String> portCodeLst = new List<String>();
        for (FTMSSO__c ship : lstSONew){
            if (ship.TypeofTrade__c == 'Export') {
                if (ship.TransportationWay__c == 'SEA' || ship.TransportationWay__c == 'AIR') {
                    if(ship.POLAOD__c != null) {
                        portCodeLst.add(ship.POLAOD__c);
                    }
                    if(ship.PODAOA__c != null) {
                        portCodeLst.add(ship.PODAOA__c);
                    }
                }
            }
        }

        Map<ID, PortCode__c> mapPortCode = new Map<ID, PortCode__c>();
        if(!portCodeLst.isEmpty()) {
            mapPortCode = getPortCode(portCodeLst);
        }
        Map<String, Id> mapRecordTypes = retrieveRecordTypeIdsByNames();
        // accouted date and file no
        List<String> lstIdAdShip = new List<String>();
        for (FTMSSO__c ship : lstSONew) {
            lstIdAdShip.add(ship.ConsolidationID__c);
        }
        System.debug('lstIdAdShip :'+lstIdAdShip);
        List<AdvancedShipment__c> lstAdShip = [SELECT Id, Name, AccountedDate__c, FileNo__c FROM AdvancedShipment__c WHERE Id IN: lstIdAdShip];
        System.debug('lstAdShip :'+lstAdShip.size());
        Map<String, AdvancedShipment__c> mapIdAdShip = new Map<String, AdvancedShipment__c>();
        for (AdvancedShipment__c item : lstAdShip){
            mapIdAdShip.put(item.Id, item);
        }
        for (FTMSSO__c ship : lstSONew){
            if (ship.AccountedDate__c == null) {
            	ship.AccountedDate__c = mapIdAdShip.get(ship.ConsolidationID__c).AccountedDate__c;
            }
            if (ship.JobRequestID__c == null) {
            	ship.JobRequestID__c = mapIdAdShip.get(ship.ConsolidationID__c).FileNo__c;
            }
            if ((ship.Shipment_Type__c != mapSOOld.get(ship.Id).Shipment_Type__c) || (ship.Shipment_Type__c != 'FCL' && (ship.CargoQuantity__c != mapSOOld.get(ship.Id).CargoQuantity__c || ship.CargoUnit__c != mapSOOld.get(ship.Id).CargoUnit__c))) {
                Map<String,String> mapSOReadContainer = new Map<String,String>();
                Map<String,Decimal> mapContTypeandQuantity = new Map<String,Decimal>();
                List<CntrinTrans__c> lstCNTR = [SELECT Id, Name, F_TMS_S_O__c, F_TMS_S_O__r.Shipment_Type__c, Container_Number__c, Container_Type__c, Seal_Number__c, Container_Quantity__c, Cargo_Quantity__c, Gross_Weight_Kg__c, Measurement_CBM__c, Cargo_Unit__c FROM CntrinTrans__c WHERE F_TMS_S_O__c =: ship.Id];
                for (CntrinTrans__c cont : lstCNTR) {
                    if (!mapContTypeandQuantity.containsKey(cont.Container_Type__c)) {
                        Decimal contQuantity = cont.Container_Quantity__c != null? cont.Container_Quantity__c : 0;
                        mapContTypeandQuantity.put(cont.Container_Type__c,contQuantity);
                    } else {
                        Decimal contQuantity = cont.Container_Quantity__c != null? cont.Container_Quantity__c : 0;
                        Decimal contQuan = mapContTypeandQuantity.get(cont.Container_Type__c) + contQuantity;
                        mapContTypeandQuantity.put(cont.Container_Type__c, contQuan);
                    }
                }
                String readCont = '';
                Integer count = 0;
                for (String key : mapContTypeandQuantity.keySet()) {
                    Decimal contQuantity = mapContTypeandQuantity.get(key);
                    if (count ==0) {
                        if (contQuantity > 0 && contQuantity <10) {
                            readCont += ReadNumberToWords.convert(contQuantity.setScale(2, System.RoundingMode.HALF_UP)) + ' ('+'0'  + contQuantity + ')X' + key;
                        } else {
                            readCont += ReadNumberToWords.convert(contQuantity.setScale(2, System.RoundingMode.HALF_UP)) + ' (' + contQuantity + ')X' + key;
                        }
                    } else {
                        if (contQuantity > 0 && contQuantity <10) {
                            readCont += ' AND ' +  ReadNumberToWords.convert(contQuantity.setScale(2, System.RoundingMode.HALF_UP)) + ' ('+'0'  + contQuantity + ')X' + key;
                        } else {
                            readCont += ' AND ' +  ReadNumberToWords.convert(contQuantity.setScale(2, System.RoundingMode.HALF_UP)) + ' (' + contQuantity + ')X' + key;
                        }
                    }
                    count++;
                }
                // for (CntrinTrans__c cont : lstCNTR) {
                //     Decimal contQuantity = cont.Container_Quantity__c != null? cont.Container_Quantity__c : 0;
                //     if (!mapSOReadContainer.containsKey(cont.F_TMS_S_O__c)) {
                //         String readCont = '';
                //         if (contQuantity > 0 && contQuantity <10) {
                //             readCont = ReadNumberToWords.convert(contQuantity.setScale(2, System.RoundingMode.HALF_UP)) + ' ('+'0'  + contQuantity + ')X' + cont.Container_Type__c;
                //         } else {
                //             readCont = ReadNumberToWords.convert(contQuantity.setScale(2, System.RoundingMode.HALF_UP)) + ' (' + contQuantity + ')X' + cont.Container_Type__c;
                //         }
                //         mapSOReadContainer.put(cont.F_TMS_S_O__c,readCont);
                //     } else {
                //         String readCont = mapSOReadContainer.get(cont.F_TMS_S_O__c);
                //         if (contQuantity > 0 && contQuantity <10) {
                //             readCont += ' AND ' + ReadNumberToWords.convert(contQuantity.setScale(2, System.RoundingMode.HALF_UP)) + ' ('+'0'  + contQuantity + ')X' + cont.Container_Type__c;
                //         } else {
                //             readCont += ' AND ' + ReadNumberToWords.convert(contQuantity.setScale(2, System.RoundingMode.HALF_UP)) + ' (' + contQuantity + ')X' + cont.Container_Type__c;
                //         }
                //         mapSOReadContainer.put(cont.F_TMS_S_O__c,readCont);
                //     }
                // }

                if (ship.Shipment_Type__c == 'FCL') {
                    ship.ReadContainers__c = readCont + ' CONTAINER(S)'; 
                    ship.ReadCargoes__c = readCont + ' CONTAINER(S) ONLY';
                } else {
                    Decimal shipQuantity = ship.CargoQuantity__c != null? ship.CargoQuantity__c : 0;
                    ship.ReadContainers__c = 'A PART OF ' + readCont + ' CONTAINER(S)';
                    ship.ReadCargoes__c = ReadNumberToWords.convert(shipQuantity.setScale(2, System.RoundingMode.HALF_UP)) + ' (' + shipQuantity + ') ' + ship.CargoUnit__c + '(S) ONLY';
                }
            }
            // Change HBL When ETD is updated
            if (ship.ETD__c != mapSOOld.get(ship.Id).ETD__c) {
                if (ship.TypeofTrade__c == 'Export') {
                    String numberFTSSOStr = String.valueOf(numberFTSSO + 1);
                    if (ship.TransportationWay__c == 'SEA') {
                        if(ship.POLAOD__c != null) {
                            polPordCode = mapPortCode.get(ship.POLAOD__c).Standard_Port_Code__c.right(3);
                        }
                        if(ship.PODAOA__c != null) {
                            podPordCode =  mapPortCode.get(ship.PODAOA__c).Standard_Port_Code__c.right(3);
                        }
                        ship.HBLNumber__c = polPordCode + podPordCode + lastNumerOfYearStr + monthStr + numberFTSSOStr.leftPad(3,'0');
                        ship.HBLNumber__c = checkMaxLength(ship.HBLNumber__c);
                    }
    
                    if (ship.TransportationWay__c == 'AIR') {
                        if(ship.PODAOA__c != null) {
                            podPordCode =  mapPortCode.get(ship.PODAOA__c).Standard_Port_Code__c.right(3);
                        }
                        ship.HAWBNumber__c = 'TCL' + lastNumerOfYearStr + monthStr + numberFTSSOStr.leftPad(3,'0') + podPordCode;
                        ship.HAWBNumber__c = checkMaxLength(ship.HAWBNumber__c);
                    }
                    numberFTSSO++;
                    ship.Number__c = numberFTSSO;
                }
            }
        }
    }
    
    private static Map<String, Id> retrieveRecordTypeIdsByNames() {
        String objectName = 'FTMSSO__c';
        Map<String, Id> mapRecordTypes = new Map<String, Id>();
        List<RecordType> recordTypes = [
                SELECT DeveloperName, Id
                FROM RecordType
                WHERE SObjectType = :objectName AND IsActive = True
        ];
        for (RecordType rt : recordTypes) {
            mapRecordTypes.put(rt.DeveloperName, rt.Id);
        }
        return mapRecordTypes;
    }
    private static List<AggregateResult> getMaxFTMSSOInMonth(Datetime firstDayOfMonth, Datetime firstDayOfNextMonth) {
        List<AggregateResult> lstNumber = new List<AggregateResult>();
        lstNumber = [SELECT MAX(Number__c) FROM FTMSSO__c WHERE Createddate >= :firstDayOfMonth AND Createddate < :firstDayOfNextMonth];
        System.debug('lstNumber :'+lstNumber.size());
        return lstNumber;
    }

    private static Map<ID, PortCode__c> getPortCode(List<String> portCodeLst) {
        Map<ID, PortCode__c> mapPortCode = new Map<ID, PortCode__c>([SELECT Id, Standard_Port_Code__c FROM PortCode__c WHERE Id In :portCodeLst]);
        System.debug('mapPortCode' + mapPortCode);
        return mapPortCode;
    }
    private static String checkMaxLength(String tmpStr) {
        if(tmpStr.length() > 12) {
           tmpStr = tmpStr.left(12);
        }
        return tmpStr;
    }
}