force-app/main/default/objects/AdvancedShipment__c/AdvancedShipment__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>AS-{00000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AdvancedShipment__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch (not used)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ho Chi Minh</fullName>
            </value>
            <value>
                <fullName>Ha Noi</fullName>
            </value>
            <value>
                <fullName>Hai Phong</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/CargoQuantity__c.field-meta.xml
<CustomField>
    <fullName>CargoQuantity__c</fullName>
    <label>Cargo Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/ETD__c.field-meta.xml
<CustomField>
    <fullName>ETD__c</fullName>
    <label>ETD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/FileNo__c.field-meta.xml
<CustomField>
    <fullName>FileNo__c</fullName>
    <label>File No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>Gross Weight</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/MAgent__c.field-meta.xml
<CustomField>
    <fullName>MAgent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>M-Agent</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Advanced_Shipment2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/MBLorMAWBNumber__c.field-meta.xml
<CustomField>
    <fullName>MBLorMAWBNumber__c</fullName>
    <label>M B/L or M AWB Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/MPOD__c.field-meta.xml
<CustomField>
    <fullName>MPOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.D(A.O.A)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>Advanced_Shipment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/MPOL__c.field-meta.xml
<CustomField>
    <fullName>MPOL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.L(A.O.D)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>AdvancedShipment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/PlaceofDelivery__c.field-meta.xml
<CustomField>
    <fullName>PlaceofDelivery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place of Delivery</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>Advanced_Shipment2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/VesselFlight__c.field-meta.xml
<CustomField>
    <fullName>VesselFlight__c</fullName>
    <label>Vessel/Flight</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/Voyage__c.field-meta.xml
<CustomField>
    <fullName>Voyage__c</fullName>
    <label>Voyage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/CompanyInformation__c.object-meta.xml
<CustomObject>
    <label>Company Information</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CompanyInformation__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch (not used)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ha Noi</fullName>
            </value>
            <value>
                <fullName>Hai Phong</fullName>
            </value>
            <value>
                <fullName>Ho Chi Minh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConsolCNTR__c/ConsolCNTR__c.object-meta.xml
<CustomObject>
    <label>Job Container</label>
    <nameField>
        <displayFormat>CSC-{00000}</displayFormat>
        <label>Job Container ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Containers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ConsolCNTR__c/fields/AdvancedShipment__c.field-meta.xml
<CustomField>
    <fullName>AdvancedShipment__c</fullName>
    <label>Advanced Shipment</label>
    <referenceTo>AdvancedShipment__c</referenceTo>
    <relationshipName>Consol_CNTR</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ConsolCNTR__c/fields/Container_Number__c.field-meta.xml
<CustomField>
    <fullName>Container_Number__c</fullName>
    <label>Container Number</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConsolCNTR__c/fields/Container_Type__c.field-meta.xml
<CustomField>
    <fullName>Container_Type__c</fullName>
    <label>Container Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20&apos;DC</fullName>
            </value>
            <value>
                <fullName>20&apos;HC</fullName>
            </value>
            <value>
                <fullName>40&apos;DC</fullName>
            </value>
            <value>
                <fullName>45&apos;DC</fullName>
            </value>
            <value>
                <fullName>40&apos;HC</fullName>
            </value>
            <value>
                <fullName>45&apos;HC</fullName>
            </value>
            <value>
                <fullName>20&apos;RF</fullName>
            </value>
            <value>
                <fullName>40&apos;RF</fullName>
            </value>
            <value>
                <fullName>45&apos;RF</fullName>
            </value>
            <value>
                <fullName>20&apos;OT</fullName>
            </value>
            <value>
                <fullName>40&apos;OT</fullName>
            </value>
            <value>
                <fullName>45&apos;OT</fullName>
            </value>
            <value>
                <fullName>20&apos;FR</fullName>
            </value>
            <value>
                <fullName>40&apos;FR</fullName>
            </value>
            <value>
                <fullName>Bulk</fullName>
            </value>
            <value>
                <fullName>ISO</fullName>
            </value>
            <value>
                <fullName>20&apos;IMO</fullName>
            </value>
            <value>
                <fullName>40&apos;IMO</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>20&apos;DC-Flexi</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>CBM</fullName>
            </value>
            <value>
                <fullName>RTON</fullName>
            </value>
            <value>
                <fullName>2*20&apos;DC</fullName>
                <isActive>false</isActive>
                <label>2*20&apos;DC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConsolCNTR__c/fields/ETA__c.field-meta.xml
<CustomField>
    <fullName>ETA__c</fullName>
    <formula>AdvancedShipment__r.ETA__c</formula>
    <label>ETA</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/FTMSSO__c.object-meta.xml
<CustomObject>
    <label>Shipment.</label>
    <nameField>
        <displayFormat>FSO-{000000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments.</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSSO__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch (not used)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ha Noi</fullName>
                <default>true</default>
                <label>Ha Noi</label>
            </value>
            <value>
                <fullName>Hai Phong</fullName>
            </value>
            <value>
                <fullName>Ho Chi Minh</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoQuantity__c.field-meta.xml
<CustomField>
    <fullName>CargoQuantity__c</fullName>
    <label>Cargo Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoUnit__c.field-meta.xml
<CustomField>
    <fullName>CargoUnit__c</fullName>
    <label>Cargo Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargoUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ConsigneeDetailInformation_text__c.field-meta.xml
<CustomField>
    <fullName>ConsigneeDetailInformation_text__c</fullName>
    <label>Consignee&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>Gross Weight</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HBLNumber__c.field-meta.xml
<CustomField>
    <fullName>HBLNumber__c</fullName>
    <label>H B/L Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HouseFreightCollectPrepaid__c.field-meta.xml
<CustomField>
    <fullName>HouseFreightCollectPrepaid__c</fullName>
    <label>House Freight Collect/Prepaid</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collected</fullName>
            </value>
            <value>
                <fullName>Prepaid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HouseNotifyDetailInformation_text__c.field-meta.xml
<CustomField>
    <fullName>HouseNotifyDetailInformation_text__c</fullName>
    <label>House Notify&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MarksNumbersAttachment__c.field-meta.xml
<CustomField>
    <fullName>MarksNumbersAttachment__c</fullName>
    <label>Marks &amp; Numbers Attachment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MeasurementTotalCBM__c.field-meta.xml
<CustomField>
    <fullName>MeasurementTotalCBM__c</fullName>
    <label>Measurement (Total CBM)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PlaceofDelivery__c.field-meta.xml
<CustomField>
    <fullName>PlaceofDelivery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place of Delivery</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/VesselFlight__c.field-meta.xml
<CustomField>
    <fullName>VesselFlight__c</fullName>
    <label>Vessel/Flight</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Voyage__c.field-meta.xml
<CustomField>
    <fullName>Voyage__c</fullName>
    <label>Voyage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/CargoUnit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B/PLT</fullName>
    </customValue>
    <customValue>
        <fullName>BAG</fullName>
    </customValue>
    <customValue>
        <fullName>BAL</fullName>
    </customValue>
    <customValue>
        <fullName>BALE</fullName>
    </customValue>
    <customValue>
        <fullName>BALE, COMPRESSED</fullName>
    </customValue>
    <customValue>
        <fullName>Bale,non-compressed</fullName>
        <label>BALE, NON-COMPRESSED</label>
    </customValue>
    <customValue>
        <fullName>Bar</fullName>
        <label>BAR</label>
    </customValue>
    <customValue>
        <fullName>BARE</fullName>
    </customValue>
    <customValue>
        <fullName>BARREL</fullName>
    </customValue>
    <customValue>
        <fullName>BILL</fullName>
    </customValue>
    <customValue>
        <fullName>BIN</fullName>
    </customValue>
    <customValue>
        <fullName>BOX</fullName>
    </customValue>
    <customValue>
        <fullName>BOX CARTON</fullName>
    </customValue>
    <customValue>
        <fullName>BOXE</fullName>
    </customValue>
    <customValue>
        <fullName>BOXPAL</fullName>
    </customValue>
    <customValue>
        <fullName>BUCKET</fullName>
    </customValue>
    <customValue>
        <fullName>BULK</fullName>
    </customValue>
    <customValue>
        <fullName>BUNDLE</fullName>
    </customValue>
    <customValue>
        <fullName>CAGE</fullName>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
    </customValue>
    <customValue>
        <fullName>Can,cylindrical</fullName>
        <label>CAN, CYLINDRICAL</label>
    </customValue>
    <customValue>
        <fullName>Can,rectangular</fullName>
        <label>CAN, RECTANGULAR</label>
    </customValue>
    <customValue>
        <fullName>CARBOY, NON-PROTECTED</fullName>
    </customValue>
    <customValue>
        <fullName>Carboy,protected</fullName>
        <label>CARBOY, PROTECTED</label>
    </customValue>
    <customValue>
        <fullName>CARDBOARD</fullName>
    </customValue>
    <customValue>
        <fullName>CARDBOXE</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON BOX</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON BOXE</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON PALLET</fullName>
    </customValue>
    <masterLabel>Cargo Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PrintAdvancedShipmentManifestController.cls
public with sharing class PrintAdvancedShipmentManifestController {
    public AdvancedShipment__c advancedShipment {get; set;}
    public List<FTMSSO__c> lstShipment {get; set;}
    public List<ConsolCNTR__c> lstConsolCont {get; set;}
    public CompanyInformation__c ComInf {get; set;}
    public Date today {get; set;}
    public String userName {get; set;}
    public Integer totalShip {get; set;}
    public Decimal totalPackage {get; set;}
    public Decimal totalGrossWeight {get; set;}
    public Decimal totalMeasurement {get; set;}
    // public List<String> lstType {get; set;}
    public String type {get; set;}
    private String advancedShipId {get; set;}


    private static Set<String> fieldsAdvancedShipQuery = new Set<String>();
    static {
        fieldsAdvancedShipQuery.add('Id');
        fieldsAdvancedShipQuery.add('Name');
        fieldsAdvancedShipQuery.add('VesselFlight__c');
        fieldsAdvancedShipQuery.add('Voyage__c');
        fieldsAdvancedShipQuery.add('FileNo__c');
        fieldsAdvancedShipQuery.add('MPOL__r.Name');
        fieldsAdvancedShipQuery.add('MPOD__r.Name');
        fieldsAdvancedShipQuery.add('ETD__c');
        fieldsAdvancedShipQuery.add('ETA__c');
        fieldsAdvancedShipQuery.add('MBLorMAWBNumber__c');
        fieldsAdvancedShipQuery.add('Branch__c');
        fieldsAdvancedShipQuery.add('MAgent__r.Name');
    }

    private static Set<String> fieldConsolCont = new Set<String>();
    static {
        fieldConsolCont.add('Id');
        fieldConsolCont.add('Name');
        fieldConsolCont.add('AdvancedShipment__c');
        fieldConsolCont.add('Container_Number__c');
        fieldConsolCont.add('Seal_Number__c');
        fieldConsolCont.add('Container_Type__c');
    }

    private static Set<String> fieldsShipQuery = new Set<String>();
    static {
        fieldsShipQuery.add('Id');
        fieldsShipQuery.add('Name');
        fieldsShipQuery.add('PlaceofDelivery__r.Name');
        fieldsShipQuery.add('HBLNumber__c');
        fieldsShipQuery.add('ConsigneeDetailInformation_text__c');
        fieldsShipQuery.add('HouseNotifyDetailInformation_text__c');
        fieldsShipQuery.add('MarksNumbersAttachment__c'); 
        fieldsShipQuery.add('CargoQuantity__c');
        fieldsShipQuery.add('CargoUnit__c');
        fieldsShipQuery.add('DescriptionofGoods__c');
        fieldsShipQuery.add('GrossWeight__c');
        fieldsShipQuery.add('MeasurementTotalCBM__c');
        fieldsShipQuery.add('HouseFreightCollectPrepaid__c');
        fieldsShipQuery.add('HBLType__c');
        fieldsShipQuery.add('ConsolidationID__c');
    }


    private static Set<String> fieldsComInQuery = new Set<String>();
    static {
        fieldsComInQuery.add('Id');
        fieldsComInQuery.add('Name');
        fieldsComInQuery.add('Address__c');
        fieldsComInQuery.add('Tel__c');
        fieldsComInQuery.add('Fax__c');
        fieldsComInQuery.add('Taxcode__c');
        fieldsComInQuery.add('Email__c');
        fieldsComInQuery.add('Website__c');
        fieldsComInQuery.add('Branch__c');
        fieldsComInQuery.add('CompanyLogo__c');
    }

    public PrintAdvancedShipmentManifestController() {
        advancedShipId = ApexPages.currentPage().getParameters().get('Id');
        advancedShipment = getAdvancedShipment(advancedShipId);
        lstConsolCont = getListConsolContainer(advancedShipId);
        lstShipment = getListShipment(advancedShipId);
        ComInf = getComIn(advancedShipment.Branch__c);
        today = Date.today();
        userName = UserInfo.getName();
        totalShip = 0;
        totalPackage = 0;
        totalGrossWeight = 0;
        totalMeasurement = 0;
        totalShip = lstShipment.size();
        type = '';
        Set<String> lstType = new Set<String>();
        for (FTMSSO__c so : lstShipment){
            totalPackage += so.CargoQuantity__c != null?so.CargoQuantity__c:0;
            totalGrossWeight += so.GrossWeight__c != null?so.GrossWeight__c:0;
            totalMeasurement += so.MeasurementTotalCBM__c != null?so.MeasurementTotalCBM__c:0;
            if (so.CargoUnit__c != null){
                type = so.CargoUnit__c;
                lstType.add(so.CargoUnit__c);
            }
        }
        if(lstType.size()>1){
            type = 'PKGS';
        }
    }

    private AdvancedShipment__c getAdvancedShipment(String advancedShipId){
        String strSelect = String.join(new List<String>(fieldsAdvancedShipQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM AdvancedShipment__c'
                    + ' WHERE Id = \'' + String.escapeSingleQuotes(advancedShipId) + '\'';
        System.debug('queryAdvancedShip: '+strQuery);
        AdvancedShipment__c advancedShip;
        try{
            advancedShip = Database.query(strQuery);
        } catch(QueryException e){
            advancedShip = new AdvancedShipment__c();
        }
        return advancedShip;
    }
    
    private List<ConsolCNTR__c> getListConsolContainer(String advancedShipId){
        String strSelect = String.join(new List<String>(fieldConsolCont), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM ConsolCNTR__c'
                    + ' WHERE AdvancedShipment__c = \'' + String.escapeSingleQuotes(advancedShipId) + '\'';
        System.debug('queryShip: '+strQuery);
        List<ConsolCNTR__c> lstConsolCont;
        try{
            lstConsolCont = Database.query(strQuery);
        } catch(QueryException e){
            lstConsolCont = new  List<ConsolCNTR__c>();
        }
        return lstConsolCont;
    }

    private List<FTMSSO__c> getListShipment(String advancedShipId){
        String strSelect = String.join(new List<String>(fieldsShipQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM FTMSSO__c'
                    + ' WHERE ConsolidationID__c = \'' + String.escapeSingleQuotes(advancedShipId) + '\'';
        System.debug('queryShip: '+strQuery);
        List<FTMSSO__c> lstShip;
        try{
            lstShip = Database.query(strQuery);
        } catch(QueryException e){
            lstShip = new  List<FTMSSO__c>();
        }
        return lstShip;
    }

    private CompanyInformation__c getComIn(String branch){
        String strSelect = String.join(new List<String>(fieldsComInQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM CompanyInformation__c'
                    + ' WHERE Branch__c = \'' + String.escapeSingleQuotes(branch) + '\'';
        strQuery += ' ORDER BY Name ASC Limit 1';        
        CompanyInformation__c ComIn;
        try{
            ComIn = Database.query(strQuery);
        } catch(QueryException e){
            ComIn = new CompanyInformation__c();
        }
        return ComIn;
    }
}