force-app/main/default/objects/AdvancedShipment__c/AdvancedShipment__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>AS-{00000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AdvancedShipment__c/fields/TotalBuyingInclTaxFCY__c.field-meta.xml
<CustomField>
    <fullName>TotalBuyingInclTaxFCY__c</fullName>
    <label>Total Buying Incl Tax (USD)</label>
    <summarizedField>ConsolBill__c.TotalBuyingInclTaxFCY__c</summarizedField>
    <summaryFilterItems>
        <field>ConsolBill__c.Allocated__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>ConsolBill__c.Billing_status__c</field>
        <operation>equals</operation>
        <value>Approved</value>
    </summaryFilterItems>
    <summaryForeignKey>ConsolBill__c.ConsolidationShipmentName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/TotalBuyingInclTaxLocal__c.field-meta.xml
<CustomField>
    <fullName>TotalBuyingInclTaxLocal__c</fullName>
    <label>Total Buying Incl Tax (VND)</label>
    <summarizedField>ConsolBill__c.TotalBuyingInclTaxLocal__c</summarizedField>
    <summaryFilterItems>
        <field>ConsolBill__c.Allocated__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>ConsolBill__c.Billing_status__c</field>
        <operation>equals</operation>
        <value>Approved</value>
    </summaryFilterItems>
    <summaryForeignKey>ConsolBill__c.ConsolidationShipmentName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/TotalSellingInclTaxFCY__c.field-meta.xml
<CustomField>
    <fullName>TotalSellingInclTaxFCY__c</fullName>
    <label>Total Selling Incl Tax (USD)</label>
    <summarizedField>ConsolBill__c.Total_Selling_Incl_Tax_FCY__c</summarizedField>
    <summaryFilterItems>
        <field>ConsolBill__c.Allocated__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>ConsolBill__c.Billing_status__c</field>
        <operation>equals</operation>
        <value>Approved</value>
    </summaryFilterItems>
    <summaryForeignKey>ConsolBill__c.ConsolidationShipmentName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AdvancedShipment__c/fields/TotalSellingInclTaxLocal__c.field-meta.xml
<CustomField>
    <fullName>TotalSellingInclTaxLocal__c</fullName>
    <label>Total Selling Incl Tax (VND)</label>
    <summarizedField>ConsolBill__c.Total_Selling_Incl_Tax_Local__c</summarizedField>
    <summaryFilterItems>
        <field>ConsolBill__c.Allocated__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>ConsolBill__c.Billing_status__c</field>
        <operation>equals</operation>
        <value>Approved</value>
    </summaryFilterItems>
    <summaryForeignKey>ConsolBill__c.ConsolidationShipmentName__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Ref No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/AdvancedShipment__c.field-meta.xml
<CustomField>
    <fullName>AdvancedShipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advanced Shipment</label>
    <referenceTo>AdvancedShipment__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Billto__c.field-meta.xml
<CustomField>
    <fullName>Billto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill to</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/DocumentsDetails__c.field-meta.xml
<CustomField>
    <fullName>DocumentsDetails__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Documents Details</label>
    <referenceTo>Documentsdetails__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Official</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/TotalBuyingInclTaxFCY__c.field-meta.xml
<CustomField>
    <fullName>TotalBuyingInclTaxFCY__c</fullName>
    <label>Total Buying Incl Tax (USD)</label>
    <summarizedField>Documentsdetails__c.TotalBuyingInclTaxFCY__c</summarizedField>
    <summaryForeignKey>Documentsdetails__c.Document__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/TotalBuyingInclTaxLocal__c.field-meta.xml
<CustomField>
    <fullName>TotalBuyingInclTaxLocal__c</fullName>
    <label>Total Buying Incl Tax (VND)</label>
    <summarizedField>Documentsdetails__c.TotalBuyingInclTaxLocal__c</summarizedField>
    <summaryForeignKey>Documentsdetails__c.Document__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/TotalSellingInclTaxFCY__c.field-meta.xml
<CustomField>
    <fullName>TotalSellingInclTaxFCY__c</fullName>
    <label>Total Selling Incl Tax (USD)</label>
    <summarizedField>Documentsdetails__c.Total_Selling_Incl_Tax_FCY__c</summarizedField>
    <summaryForeignKey>Documentsdetails__c.Document__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/TotalSellingInclTaxLocal__c.field-meta.xml
<CustomField>
    <fullName>TotalSellingInclTaxLocal__c</fullName>
    <label>Total Selling Incl Tax (VND)</label>
    <summarizedField>Documentsdetails__c.Total_Selling_Incl_Tax_Local__c</summarizedField>
    <summaryForeignKey>Documentsdetails__c.Document__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/Documentsdetails__c.object-meta.xml
<CustomObject>
    <label>Documents details</label>
    <nameField>
        <displayFormat>DD-{0000000}</displayFormat>
        <label>Documents details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Documentsdetails__c/fields/AdvancedShipment__c.field-meta.xml
<CustomField>
    <fullName>AdvancedShipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advanced Shipment</label>
    <referenceTo>AdvancedShipment__c</referenceTo>
    <relationshipLabel>Documents details</relationshipLabel>
    <relationshipName>Documents_details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/Billto__c.field-meta.xml
<CustomField>
    <fullName>Billto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill to</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents details</relationshipLabel>
    <relationshipName>Documents_details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/ChargeUnit__c.field-meta.xml
<CustomField>
    <fullName>ChargeUnit__c</fullName>
    <formula>text( ConsolBill__r.ChargeUnit__c )</formula>
    <label>Charge Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/CurrencyBuying__c.field-meta.xml
<CustomField>
    <fullName>CurrencyBuying__c</fullName>
    <formula>text( ConsolBill__r.CurrencyBuying__c )</formula>
    <label>Currency Buying</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/CurrencySelling__c.field-meta.xml
<CustomField>
    <fullName>CurrencySelling__c</fullName>
    <formula>text( ConsolBill__r.CurrencySelling__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Selling</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <referenceTo>Document__c</referenceTo>
    <relationshipLabel>Documents details</relationshipLabel>
    <relationshipName>Documents_details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/PricingNamePrinted__c.field-meta.xml
<CustomField>
    <fullName>PricingNamePrinted__c</fullName>
    <label>Pricing Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <formula>ConsolBill__r.Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/TaxRatioBuying__c.field-meta.xml
<CustomField>
    <fullName>TaxRatioBuying__c</fullName>
    <formula>ConsolBill__r.TaxRatioBuying__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tax Ratio-Buying</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/TaxRatioSelling__c.field-meta.xml
<CustomField>
    <fullName>TaxRatioSelling__c</fullName>
    <formula>ConsolBill__r.TaxRatioSelling__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tax Ratio-Selling</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/Total_Selling_Incl_Tax_FCY__c.field-meta.xml
<CustomField>
    <fullName>Total_Selling_Incl_Tax_FCY__c</fullName>
    <label>Total Selling Incl Tax (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/Total_Selling_Incl_Tax_Local__c.field-meta.xml
<CustomField>
    <fullName>Total_Selling_Incl_Tax_Local__c</fullName>
    <label>Total Selling Incl Tax (VND)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/TotalBuyingInclTaxFCY__c.field-meta.xml
<CustomField>
    <fullName>TotalBuyingInclTaxFCY__c</fullName>
    <label>Total Buying Incl Tax (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/TotalBuyingInclTaxLocal__c.field-meta.xml
<CustomField>
    <fullName>TotalBuyingInclTaxLocal__c</fullName>
    <label>Total Buying Incl Tax (VND)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/UnitPriceofBuyingFCY__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceofBuyingFCY__c</fullName>
    <formula>ConsolBill__r.UnitPriceofBuyingFCY__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Price of Buying (USD)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/UnitPriceofBuyingLocal__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceofBuyingLocal__c</fullName>
    <formula>ConsolBill__r.UnitPriceofBuyingLocal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Price of Buying (VND)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/UnitPriceofSellingFCY__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceofSellingFCY__c</fullName>
    <formula>ConsolBill__r.UnitPriceofSellingFCY__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Price of Selling (USD)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/UnitPriceofSellingLocal__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceofSellingLocal__c</fullName>
    <formula>ConsolBill__r.UnitPriceofSellingLocal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Price of Selling (VND)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CDI_TableController.cls
public with sharing class CDI_TableController {
    private static Set<String> docQr = new Set<String>();
    private static Set<String> docDtQr = new Set<String>();
    public List<docListWapper> listItem {get;set;}
    public String searchValue {get;set;}
    public Integer pagination {get;set;}
    public class DeleteResult {
        public Boolean isSuccess;
        public String message;
   
        public DeleteResult(Boolean isSuccess, String message) {
            this.isSuccess = isSuccess;
            this.message = message;
        }
    }
    public class docListWapper{
        public Document__c Doc;
        public List<Documentsdetails__c> DocDT;
        public docListWapper(){
            DocDT = new List<Documentsdetails__c>();
        }
    }
    static{
        docQr.add('Id');
        docQr.add('Name');
        docQr.add('Billto__r.Name');
        docQr.add('TotalSellingInclTaxLocal__c');
        docQr.add('TotalSellingInclTaxFCY__c');
        docQr.add('TotalBuyingInclTaxLocal__c');
        docQr.add('TotalBuyingInclTaxFCY__c');
        docQr.add('Status__c');
        


        



    }
    // public static CDI_TableController() {
    //     String ShipID = ApexPages.currentPage().getParameters().get('id');
    //     pagination=1;
    //     listItem = new List<docListWapper>();
    //     listItem=getListWapper(ShipID,pagination);
    //     r
    // }
    @AuraEnabled
    public static  Map<String, Object> getListWapper(String ShipID,Integer pagination,String searchValue,String recordType){
        Map<String, Object> result = new Map<String, Object>();
        List<Documentsdetails__c> lisdt= new List<Documentsdetails__c>();
        System.debug('devRecordTypeId-getListWapper:'+recordType);

        List<Document__c> lisdoc=getDoc(ShipID,pagination,searchValue,recordType);
       

        List<Id> unique = new List<Id>();
        for (Document__c lisdocItem : lisdoc) {
            if (lisdocItem.Id != null && !unique.contains(lisdocItem.Id)) {
                unique.add(lisdocItem.Id);
            }
        } 

        system.debug('Fu doc list:'+lisdoc);
        if(lisdoc.size()>0){
           lisdt = getDocDt(ShipID,unique);
            
        }
        List<Object> obj = new List<Object>();
   
        result.put('DocList', lisdoc);
        result.put('DocListDT', lisdt);
        result.put('total', obj);
        return result;
          
        
    }
    @AuraEnabled
    public static List<Document__c> getDoc(String ShipID,Integer pagination,String searchValue,String recordType){
        String strSelect = String.join(new List<String>(docQr), ',');
        System.debug('devRecordTypeId:'+recordType);

        Id devRecordTypeId = Schema.SObjectType.Document__c.getRecordTypeInfosByName().get(recordType).getRecordTypeId();

        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM Document__c'
                    + ' WHERE AdvancedShipment__c = \'' + ShipID + '\''
                    + ' AND RecordTypeId = \'' + devRecordTypeId + '\'';
                    
        if(searchValue != null && searchValue.length() >0){
            strQuery += ' AND Name LIKE \'%' + searchValue + '%\'';
        }
                    // strQuery  += 'LIMIT  ' + pagination*10;
                    List<Document__c>  ListDoc;
        try{
            ListDoc = Database.query(strQuery);
        } catch(QueryException e){
            ListDoc = new List<Document__c>();
        }
        return ListDoc;
    }
    @AuraEnabled
    public static List<Documentsdetails__c> getDocDt(String DocId, List<id> Lid){
        
        List<Documentsdetails__c> ListDoc;
        try{
            ListDoc = [    
                SELECT  Name,Id,Billto__r.Name,Document__c,
                Quantity__c,ChargeUnit__c,CurrencySelling__c,TaxRatioSelling__c,
                UnitPriceofSellingLocal__c,Total_Selling_Incl_Tax_Local__c,UnitPriceofSellingFCY__c,
                Total_Selling_Incl_Tax_FCY__c,CurrencyBuying__c,TaxRatioBuying__c,UnitPriceofBuyingLocal__c,
                TotalBuyingInclTaxLocal__c, UnitPriceofBuyingFCY__c,TotalBuyingInclTaxFCY__c,PricingNamePrinted__c
                FROM Documentsdetails__c    
                WHERE Document__c IN :Lid  ];
   
        } catch(QueryException e){
            ListDoc = new List<Documentsdetails__c>();
        }
        return ListDoc;
    }
    @AuraEnabled
    public static String deletePKD(List<Id> ListPKID) {
        List<Documentsdetails__c> packagesToDelete = new List<Documentsdetails__c>();
        
        // Query for Packages_detail__c records with IDs from ListPKID
        List<Documentsdetails__c> packages = [SELECT Id FROM Documentsdetails__c WHERE Id IN :ListPKID];
       

            packagesToDelete.addAll(packages);
            
        // Delete the records
        if (!packagesToDelete.isEmpty()) {
            try {
                delete packagesToDelete;
                System.debug('Deleted ' + packagesToDelete.size() + ' Documentsdetails__c records.');
                
                return  JSON.serialize(new DeleteResult(true, '')); 
            } catch (DmlException e) {
                System.debug('An error occurred while deleting Documentsdetails__c records: ' + e.getMessage());
                return  JSON.serialize(new DeleteResult(false, 'An error occurred while deleting Packages_detail__c records: ' + e.getMessage())); 
                
            }
        } else {
            System.debug('No Documentsdetails__c records found to delete.');
            return  JSON.serialize(new DeleteResult(false, '')); 
            
            
        }
   
    }
}