force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Agent</label>
</RecordType>

force-app/main/default/objects/FTMSBill__c/FTMSBill__c.object-meta.xml
<CustomObject>
    <label>F/TMS Bill</label>
    <nameField>
        <displayFormat>FTB-{000000}</displayFormat>
        <label>F/TMS Bill ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>F/TMS Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSBill__c/fields/FTMSSO__c.field-meta.xml
<CustomField>
    <fullName>FTMSSO__c</fullName>
    <label>F/TMS S/O</label>
    <referenceTo>FTMSSO__c</referenceTo>
    <relationshipLabel>F/TMS Bills</relationshipLabel>
    <relationshipName>F_TMS_Bills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/PaymentTo__c.field-meta.xml
<CustomField>
    <fullName>PaymentTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS Bills (Payment To)</relationshipLabel>
    <relationshipName>F_TMS_Bills1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/FTMSSO__c.object-meta.xml
<CustomObject>
    <label>Shipment.</label>
    <nameField>
        <displayFormat>FSO-{000000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments.</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/CreditNoteSelectionController.cls
public with sharing class CreditNoteSelectionController {
    public String shipmentID {get; set;}
    public String selectedCustomerId {get; set;}
    public String openUrl {get; set;}
    public String errorMessage {get; private set;}
    public Boolean requiredAttachmentCreation {get; set;}
    public CreditNoteSelectionController() {
        shipmentID = ApexPages.currentPage().getParameters().get('id');
        errorMessage = null;
    }
    public List<SelectOption> getCustomers() {
        List<FTMSBill__c> bills = [SELECT PaymentTo__c, PaymentTo__r.Name FROM FTMSBill__c WHERE FTMSSO__c =: shipmentId];
        List<SelectOption> options = new List<SelectOption>();
        Set<String> lstCus = new Set<String>();
        for (FTMSBill__c bill : bills){
            if (!lstCus.contains(bill.PaymentTo__c) && bill.PaymentTo__c != null){
                lstCus.add(bill.PaymentTo__c);
                options.add(new SelectOption(bill.PaymentTo__c, bill.PaymentTo__r.Name));
            }
        }
        return options;
    }
    public void generateReport() {
        errorMessage = null;
        if (StringUtils.isEmpty(selectedCustomerId)) {
            errorMessage = 'You have not selected any customer/partner or no customer/partner is applicable.';
        }  else {
            // openUrl = '/apex/page_PrintCreditNote?Id=' + shipmentID+ '&cusId=' + selectedCustomerId;
            // System.debug('hello' + openUrl);
            if (requiredAttachmentCreation) {
                String attachmentId = createAttachment(shipmentID,selectedCustomerId);
                openUrl = '/servlet/servlet.FileDownload?file=' + attachmentId;
            } else {
                openUrl = '/apex/page_PrintCreditNote?Id=' + shipmentID+ '&cusId=' + selectedCustomerId;

            }
        }  
            // if (requiredAttachmentCreation) {
            //     String attachmentId = createAttachment(shipmentID,selectedCustomerId);
            //     openUrl = '/servlet/servlet.FileDownload?file=' + attachmentId;
            // } else {
            //     openUrl = '/apex/page_PrintCreditNote?Id=' + shipmentID+ '&cusId=' + selectedCustomerId;

            // }
        
    }
    private String createAttachment(String shipid, String customerId) {
        if (PermissionValidationUtil.isCreatableAttachment()) {
            PageReference pageRef = new PageReference('/apex/page_PrintCreditNote');
            pageRef.getParameters().put('Id',shipid);
            pageRef.getParameters().put('customerValue',customerId);
            String attachName = 'Credit Notes' + ' v';
	        String attachNameSearch = attachName + '%';
	        // get exist file Name
	        List<Attachment> attachments = [SELECT Id, Name, ParentId 
	                                        FROM Attachment 
	                                        WHERE Name LIKE : attachNameSearch 
	                                        ORDER BY CreatedDate DESC LIMIT 1];
	        if(attachments.isEmpty()){
	            attachName += '1.1';
	        }else{
	            String attachNameExist = attachments[0].Name;
	            attachNameExist = attachNameExist.substringAfter(attachName);
	            attachNameExist = attachNameExist.substringBefore('.pdf');
	            Decimal versionNumber = Decimal.valueOf(attachNameExist);
	            versionNumber += 0.1;
	            attachName += String.valueOf(versionNumber);
	        }
	        Attachment attach = new Attachment();
	        Blob body;
	        attach.Name = attachName + '.pdf'; 
	        attach.IsPrivate = false;
            attach.ParentId = shipid;
	        if(!Test.isRunningTest()){
	            body = pageRef.getContentAsPDF();
	            attach.Body = body;
	            FlsService.doInsert(attach);
	        }
            return attach.Id;
        }
        return null;
    }
}