force-app/main/default/objects/Account/fields/AccountNameENG__c.field-meta.xml
<CustomField>
    <fullName>AccountNameENG__c</fullName>
    <label>Abbreviations Name (ENG)</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/CntrinTrans__c.object-meta.xml
<CustomObject>
    <label>CNTR in Trans</label>
    <nameField>
        <displayFormat>CNTR-{00000}</displayFormat>
        <label>CNTR in Trans</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CNTR in Trans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CntrinTrans__c/fields/Cargo_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Cargo_Quantity__c</fullName>
    <label>Cargo Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/CargoUnit__c.field-meta.xml
<CustomField>
    <fullName>CargoUnit__c</fullName>
    <label>Cargo Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargoUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/ContainerDetailedInformation__c.field-meta.xml
<CustomField>
    <fullName>ContainerDetailedInformation__c</fullName>
    <formula>Text(Container_Quantity__c)  &amp;  &quot;x&quot;  &amp;   Text(Container_Type__c)  &amp; &quot;/&quot;  &amp; Container_Number__c  &amp;  &quot;/&quot;  &amp;  Seal_Number__c</formula>
    <label>Container Detail Information</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/Description_of_Goods__c.field-meta.xml
<CustomField>
    <fullName>Description_of_Goods__c</fullName>
    <label>Description of Goods</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/ETA__c.field-meta.xml
<CustomField>
    <fullName>ETA__c</fullName>
    <formula>F_TMS_S_O__r.ETA__c</formula>
    <label>ETA</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/Gross_Weight_Kg__c.field-meta.xml
<CustomField>
    <fullName>Gross_Weight_Kg__c</fullName>
    <label>Gross Weight(Kg)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/HSCode__c.field-meta.xml
<CustomField>
    <fullName>HSCode__c</fullName>
    <label>HS Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/Measurement_CBM__c.field-meta.xml
<CustomField>
    <fullName>Measurement_CBM__c</fullName>
    <label>Measurement(CBM)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/PluralCargoUnit__c.field-meta.xml
<CustomField>
    <fullName>PluralCargoUnit__c</fullName>
    <formula>IF( Cargo_Quantity__c = 1, TEXT(CargoUnit__c) ,
IF(Text(CargoUnit__c)= &quot;&quot;, &quot;&quot;,
IF(Text(CargoUnit__c)= &quot;BALE, COMPRESSED&quot;, &quot;BALES, COMPRESSED&quot;,
IF(Text(CargoUnit__c)= &quot;CARBOY, NON-PROTECTED&quot;, &quot;CARBOYS, NON-PROTECTED&quot;,
IF(
OR(
RIGHT(TEXT(CargoUnit__c), 1) = &quot;S&quot;,
RIGHT(TEXT(CargoUnit__c), 1) = &quot;Z&quot;,
RIGHT(TEXT(CargoUnit__c), 1) = &quot;O&quot;,
RIGHT(TEXT(CargoUnit__c), 2) = &quot;SH&quot;,
RIGHT(TEXT(CargoUnit__c), 2) = &quot;CH&quot;,
RIGHT(TEXT(CargoUnit__c), 2) = &quot;SS&quot;,
RIGHT(TEXT(CargoUnit__c), 1) = &quot;X&quot;,
RIGHT(TEXT(CargoUnit__c), 2) = &quot;SS&quot;),
TEXT(CargoUnit__c) &amp; &quot;ES&quot;,
IF(
OR(
RIGHT(TEXT(CargoUnit__c), 2) = &quot;AY&quot;,
RIGHT(TEXT(CargoUnit__c), 2) = &quot;OY&quot;,
RIGHT(TEXT(CargoUnit__c), 2) = &quot;EY&quot;,
RIGHT(TEXT(CargoUnit__c), 2) = &quot;IY&quot;,
RIGHT(TEXT(CargoUnit__c), 2) = &quot;UY&quot;
),
TEXT(CargoUnit__c) &amp; &quot;S&quot;,
IF(
RIGHT(TEXT(CargoUnit__c), 1) = &quot;Y&quot;,
LEFT(TEXT(CargoUnit__c), LEN(TEXT(CargoUnit__c)) - 1) &amp; &quot;IES&quot;,
IF(
RIGHT(TEXT(CargoUnit__c), 2) = &quot;FE&quot;,
IF(
TEXT(CargoUnit__c) = &quot;wife&quot;,
&quot;wives&quot;,
IF(
TEXT(CargoUnit__c) = &quot;wolf&quot;,
&quot;wolves&quot;,
LEFT(TEXT(CargoUnit__c), LEN(TEXT(CargoUnit__c)) - 2) &amp; &quot;VES&quot;
)
),
TEXT(CargoUnit__c) &amp; &quot;S&quot;
)
)
)
))))
)</formula>
    <label>Plural Cargo Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/CompanyInformation__c.object-meta.xml
<CustomObject>
    <label>Company Information</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CompanyInformation__c/fields/Branch1__c.field-meta.xml
<CustomField>
    <fullName>Branch1__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Branch</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/fields/ShowAddressonHeader__c.field-meta.xml
<CustomField>
    <fullName>ShowAddressonHeader__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Address on Header</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/fields/Tel__c.field-meta.xml
<CustomField>
    <fullName>Tel__c</fullName>
    <label>Tel</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/FTMSSO__c.object-meta.xml
<CustomObject>
    <label>Shipment.</label>
    <nameField>
        <displayFormat>FSO-{000000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments.</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSSO__c/fields/Branch1__c.field-meta.xml
<CustomField>
    <fullName>Branch1__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Branch</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoClosingTime__c.field-meta.xml
<CustomField>
    <fullName>CargoClosingTime__c</fullName>
    <label>Cargo Closing Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoQuantity__c.field-meta.xml
<CustomField>
    <fullName>CargoQuantity__c</fullName>
    <label>Cargo Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoUnit__c.field-meta.xml
<CustomField>
    <fullName>CargoUnit__c</fullName>
    <label>Cargo Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargoUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commodity</label>
    <referenceTo>Commodity__c</referenceTo>
    <relationshipName>F_TMS_S_O</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Consignee__c.field-meta.xml
<CustomField>
    <fullName>Consignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consignee</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>F_TMS_S_O2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Date_of_issue__c.field-meta.xml
<CustomField>
    <fullName>Date_of_issue__c</fullName>
    <label>Date of issue</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>Gross Weight</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HouseBookingNo__c.field-meta.xml
<CustomField>
    <fullName>HouseBookingNo__c</fullName>
    <label>House Booking No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HSCode__c.field-meta.xml
<CustomField>
    <fullName>HSCode__c</fullName>
    <label>HS Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MasterBookingNo__c.field-meta.xml
<CustomField>
    <fullName>MasterBookingNo__c</fullName>
    <label>Master Booking No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MeasurementTotalCBM__c.field-meta.xml
<CustomField>
    <fullName>MeasurementTotalCBM__c</fullName>
    <label>Measurement (Total CBM)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MotherVesselFlight__c.field-meta.xml
<CustomField>
    <fullName>MotherVesselFlight__c</fullName>
    <label>Mother Vessel/Flight</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PlaceofDelivery__c.field-meta.xml
<CustomField>
    <fullName>PlaceofDelivery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place of Delivery</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PlaceofReceipt__c.field-meta.xml
<CustomField>
    <fullName>PlaceofReceipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place of Receipt</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PODAOAsDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>PODAOAsDetailInformation__c</fullName>
    <label>P.O.D(A.O.A)&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/POLAOD__c.field-meta.xml
<CustomField>
    <fullName>POLAOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.L(A.O.D)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/POLAODsDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>POLAODsDetailInformation__c</fullName>
    <label>P.O.L(A.O.D)&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PortofDischargeDetailPrint__c.field-meta.xml
<CustomField>
    <fullName>PortofDischargeDetailPrint__c</fullName>
    <formula>&quot;Port&quot;</formula>
    <label>Port of Discharge Detail-Print</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Shipper__c.field-meta.xml
<CustomField>
    <fullName>Shipper__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipper</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>F_TMS_S_O1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/StuffingContact__c.field-meta.xml
<CustomField>
    <fullName>StuffingContact__c</fullName>
    <label>Stuffing Contact</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/TransitPort__c.field-meta.xml
<CustomField>
    <fullName>TransitPort__c</fullName>
    <label>Transit Port</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/VesselFlight__c.field-meta.xml
<CustomField>
    <fullName>VesselFlight__c</fullName>
    <label>Vessel/Flight</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/VesselName__c.field-meta.xml
<CustomField>
    <fullName>VesselName__c</fullName>
    <label>Feeder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Voyage__c.field-meta.xml
<CustomField>
    <fullName>Voyage__c</fullName>
    <label>Voyage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortCode__c/PortCode__c.object-meta.xml
<CustomObject>
    <label>Port Code</label>
    <nameField>
        <label>Port Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Port Code</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PortCode__c/fields/City_Name__c.field-meta.xml
<CustomField>
    <fullName>City_Name__c</fullName>
    <label>City Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortCode__c/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <formula>Country__r.CountryCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Branch.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cambodia</fullName>
    </customValue>
    <customValue>
        <fullName>Hải Phòng</fullName>
    </customValue>
    <customValue>
        <fullName>Hồ Chí Minh</fullName>
        <default>true</default>
        <label>Hồ Chí Minh</label>
    </customValue>
    <customValue>
        <fullName>Đà Nẵng</fullName>
    </customValue>
    <customValue>
        <fullName>Taiwan</fullName>
    </customValue>
    <masterLabel>Branch</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/CargoUnit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B/PLT</fullName>
    </customValue>
    <customValue>
        <fullName>BAG</fullName>
    </customValue>
    <customValue>
        <fullName>BAL</fullName>
    </customValue>
    <customValue>
        <fullName>BALE</fullName>
    </customValue>
    <customValue>
        <fullName>BALE, COMPRESSED</fullName>
    </customValue>
    <customValue>
        <fullName>Bale,non-compressed</fullName>
        <label>BALE, NON-COMPRESSED</label>
    </customValue>
    <customValue>
        <fullName>Bar</fullName>
        <label>BAR</label>
    </customValue>
    <customValue>
        <fullName>BARE</fullName>
    </customValue>
    <customValue>
        <fullName>BARREL</fullName>
    </customValue>
    <customValue>
        <fullName>BILL</fullName>
    </customValue>
    <customValue>
        <fullName>BIN</fullName>
    </customValue>
    <customValue>
        <fullName>BOX</fullName>
    </customValue>
    <customValue>
        <fullName>BOX CARTON</fullName>
    </customValue>
    <customValue>
        <fullName>BOXE</fullName>
    </customValue>
    <customValue>
        <fullName>BOXPAL</fullName>
    </customValue>
    <customValue>
        <fullName>BUCKET</fullName>
    </customValue>
    <customValue>
        <fullName>BULK</fullName>
    </customValue>
    <customValue>
        <fullName>BUNDLE</fullName>
    </customValue>
    <customValue>
        <fullName>CAGE</fullName>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
    </customValue>
    <customValue>
        <fullName>Can,cylindrical</fullName>
        <label>CAN, CYLINDRICAL</label>
    </customValue>
    <customValue>
        <fullName>Can,rectangular</fullName>
        <label>CAN, RECTANGULAR</label>
    </customValue>
    <customValue>
        <fullName>CARBOY, NON-PROTECTED</fullName>
    </customValue>
    <customValue>
        <fullName>Carboy,protected</fullName>
        <label>CARBOY, PROTECTED</label>
    </customValue>
    <customValue>
        <fullName>CARDBOARD</fullName>
    </customValue>
    <customValue>
        <fullName>CARDBOXE</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON BOX</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON BOXE</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON PALLET</fullName>
    </customValue>
    <masterLabel>Cargo Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PrintBookingOrderFCL.cls
public with sharing class PrintBookingOrderFCL{
    public FTMSSO__c shipment {get;set;}
    public List <CompanyInformation__c> companyInfor {get; set;}
    public String shipId {get; set;}
    public Date today {get; set;}
    public Datetime myDatetime {get; set;}
    public String myDateString {get; set;}
    public String accountName {get; set;}
    public List <CntrinTrans__c> cntrinTrans {get; set;}
    
    private static Set<String> fieldsCNTRQuery = new Set<String>();
    static{
        fieldsCNTRQuery.add('ContainerDetailedInformation__c');
        fieldsCNTRQuery.add('CargoUnit__c');
        fieldsCNTRQuery.add('Cargo_Quantity__c');
        fieldsCNTRQuery.add('PluralCargoUnit__c');
        fieldsCNTRQuery.add('Description_of_Goods__c');
        fieldsCNTRQuery.add('Gross_Weight_Kg__c');
        fieldsCNTRQuery.add('HSCode__c');
        fieldsCNTRQuery.add('Measurement_CBM__c');
        
    }

    private static Set<String> fieldsComInfoQuery = new Set<String>();
    static{
        fieldsComInfoQuery.add('Name');
        fieldsComInfoQuery.add('Address__c');
        fieldsComInfoQuery.add('Branch1__c');
        fieldsComInfoQuery.add('Fax__c');
        fieldsComInfoQuery.add('Tel__c');
        fieldsComInfoQuery.add('Website__c');
        fieldsComInfoQuery.add('ShowAddressonHeader__c');
        
    }

    private static Set<String> fieldsFTMSQuery = new Set<String>();
    static{
        fieldsFTMSQuery.add('PlaceofReceipt__r.Name');
        fieldsFTMSQuery.add('Date_of_issue__c');
        fieldsFTMSQuery.add('PlaceofDelivery__r.Name');
        fieldsFTMSQuery.add('PlaceofDelivery__r.CountryCode__c');
        fieldsFTMSQuery.add('StuffingContact__c');
        fieldsFTMSQuery.add('HouseBookingNo__c');
        fieldsFTMSQuery.add('Shipper__r.AccountNameENG__c');
        fieldsFTMSQuery.add('Consignee__r.AccountNameENG__c');
        fieldsFTMSQuery.add('CargoClosingTime__c');
        fieldsFTMSQuery.add('VesselName__c');
        fieldsFTMSQuery.add('Voyage__c');
        fieldsFTMSQuery.add('ETD__c');
        fieldsFTMSQuery.add('ETA__c');
        fieldsFTMSQuery.add('PODAOAsDetailInformation__c');
        fieldsFTMSQuery.add('POLAODsDetailInformation__c');
        fieldsFTMSQuery.add('VesselFlight__c');
        fieldsFTMSQuery.add('CargoQuantity__c');
        fieldsFTMSQuery.add('CargoUnit__c');
        fieldsFTMSQuery.add('Commodity__c');
        fieldsFTMSQuery.add('GrossWeight__c');
        fieldsFTMSQuery.add('MeasurementTotalCBM__c');
        fieldsFTMSQuery.add('PlaceofDelivery__r.Name');
        fieldsFTMSQuery.add('HouseBookingNo__c');
        fieldsFTMSQuery.add('MasterBookingNo__c');
        fieldsFTMSQuery.add('MotherVesselFlight__c');
        fieldsFTMSQuery.add('TransitPort__c');
    }

    public PrintBookingOrderFCL(){
        companyInfor = new List<CompanyInformation__c>();
        companyInfor = getComInfor();

        shipId = ApexPages.currentPage().getParameters().get('Id');
        shipment = getShipment(shipId); 
        //cntrinTrans = getCntrinTrans(shipId);

        today = Date.today();
        myDateString = Datetime.now().format('dd MMM, yyyy h:mm:ssa');
        accountName = UserInfo.getName();
        
        // if(shipment.PortofDischargeDetailPrint__c!= null) shipment.PortofDischargeDetailPrint__c = shipment.PortofDischargeDetailPrint__c.toUppercase();
        // if (shipment.POLAOD__r.City_Name__c != null) shipment.POLAOD__r.City_Name__c = shipment.POLAOD__r.City_Name__c.toUppercase();
        // if (shipment.PODAOA__r.City_Name__c != null) shipment.PODAOA__r.City_Name__c = shipment.PODAOA__r.City_Name__c.toUppercase();
        // if (shipment.PODAOA__r.Name != null) shipment.PODAOA__r.Name = shipment.PODAOA__r.Name.toUppercase();
        // for(CntrinTrans__c cntr: cntrinTrans){
        //     if (cntr.Cargo_Quantity__c == null) cntr.Cargo_Quantity__c = -1;
        // }
        
    }

    private List<CompanyInformation__c> getComInfor (){
        List<CompanyInformation__c> infor = new List<CompanyInformation__c>();
        List<String> city_name = new List<String>{'Hồ Chí Minh','Hải Phòng'};

        String strSelect = String.join(new List<String>(fieldsComInfoQuery), ','); 

        for (String city: city_name){
            CompanyInformation__c comInfor = new CompanyInformation__c();
            String strQuery  =  'SELECT ' + strSelect 
            + ' FROM CompanyInformation__c'
            + ' WHERE ShowAddressonHeader__c = true AND Branch1__c = \'' + String.escapeSingleQuotes(city) + '\'';
            try{
                comInfor = Database.query(strQuery); 
                infor.add(comInfor);
            } catch(QueryException e){
                comInfor = new CompanyInformation__c();
            }
        }
        for(CompanyInformation__c com : infor){
            if(com.Name != null){
                com.Name = com.Name.replace('TIMES CARGO LOGISTIC CO.,LTD - ', '');
            }
        }
        return infor;
    }

    private FTMSSO__c getShipment(String shipId){
        FTMSSO__c shipment = new FTMSSO__c();
        String strSelect = String.join(new List<String>(fieldsFTMSQuery), ','); 
        String strQuery  =  'SELECT ' + strSelect 
                            + ' FROM FTMSSO__c'
                            + ' WHERE Id = \'' + String.escapeSingleQuotes(shipId) + '\'';
        try{
            shipment = Database.query(strQuery); 
        } catch(QueryException e){
            shipment = new FTMSSO__c();
        }
        return shipment;
    }

    private List<CntrinTrans__c> getCntrinTrans(String shipId){
        List<CntrinTrans__c> cntrinTrans = new List<CntrinTrans__c>();
        String strSelect = String.join(new List<String>(fieldsCNTRQuery), ','); 
        String strQuery  =  'SELECT ' + strSelect 
                            + ' FROM CntrinTrans__c'
                            + ' WHERE F_TMS_S_O__c = \'' + String.escapeSingleQuotes(shipId) + '\'';
        try{
            cntrinTrans = Database.query(strQuery); 
        } catch(QueryException e){
            cntrinTrans = new List<CntrinTrans__c>();
        }
        return cntrinTrans;
    }
}