force-app/main/default/objects/Account/fields/AccountNameENG__c.field-meta.xml
<CustomField>
    <fullName>AccountNameENG__c</fullName>
    <label>Abbreviations Name (ENG)</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/EnglishAddress__c.field-meta.xml
<CustomField>
    <fullName>EnglishAddress__c</fullName>
    <label>English Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/TaxCode__c.field-meta.xml
<CustomField>
    <fullName>TaxCode__c</fullName>
    <label>Tax Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/CntrinTrans__c.object-meta.xml
<CustomObject>
    <label>CNTR in Trans</label>
    <nameField>
        <displayFormat>CNTR-{00000}</displayFormat>
        <label>CNTR in Trans</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CNTR in Trans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CntrinTrans__c/fields/CargoUnit__c.field-meta.xml
<CustomField>
    <fullName>CargoUnit__c</fullName>
    <label>Cargo Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargoUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/Description_of_Goods__c.field-meta.xml
<CustomField>
    <fullName>Description_of_Goods__c</fullName>
    <label>Description of Goods</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/F_TMS_S_O__c.field-meta.xml
<CustomField>
    <fullName>F_TMS_S_O__c</fullName>
    <label>F/TMS S/O</label>
    <referenceTo>FTMSSO__c</referenceTo>
    <relationshipLabel>CNTR in Trans</relationshipLabel>
    <relationshipName>CNTR_in_Trans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/Gross_Weight_Kg__c.field-meta.xml
<CustomField>
    <fullName>Gross_Weight_Kg__c</fullName>
    <label>Gross Weight(Kg)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/HSCode__c.field-meta.xml
<CustomField>
    <fullName>HSCode__c</fullName>
    <label>HS Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/Measurement_CBM__c.field-meta.xml
<CustomField>
    <fullName>Measurement_CBM__c</fullName>
    <label>Measurement(CBM)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/FTMSSO__c.object-meta.xml
<CustomObject>
    <label>Shipment.</label>
    <nameField>
        <displayFormat>FSO-{000000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments.</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSSO__c/fields/CargoQuantity__c.field-meta.xml
<CustomField>
    <fullName>CargoQuantity__c</fullName>
    <label>Cargo Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoType__c.field-meta.xml
<CustomField>
    <fullName>CargoType__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargoType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoUnit__c.field-meta.xml
<CustomField>
    <fullName>CargoUnit__c</fullName>
    <label>Cargo Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargoUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Consignee__c.field-meta.xml
<CustomField>
    <fullName>Consignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consignee</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>F_TMS_S_O2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ConsigneeDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>ConsigneeDetailInformation__c</fullName>
    <label>Consignee’s Detail Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ConsigneeDetailInformation_text__c.field-meta.xml
<CustomField>
    <fullName>ConsigneeDetailInformation_text__c</fullName>
    <label>Consignee&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/DateofHouseBLIssued__c.field-meta.xml
<CustomField>
    <fullName>DateofHouseBLIssued__c</fullName>
    <label>Date of House B/L Issued</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/DateofMasterBLIssued__c.field-meta.xml
<CustomField>
    <fullName>DateofMasterBLIssued__c</fullName>
    <label>Date of Master B/L Issued</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/FinalDestination__c.field-meta.xml
<CustomField>
    <fullName>FinalDestination__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Final Destination</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/GoodsAttachment__c.field-meta.xml
<CustomField>
    <fullName>GoodsAttachment__c</fullName>
    <label>Goods Attachment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>Gross Weight</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HBLNumber__c.field-meta.xml
<CustomField>
    <fullName>HBLNumber__c</fullName>
    <label>H B/L Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HouseNotifyDetailInformation_text__c.field-meta.xml
<CustomField>
    <fullName>HouseNotifyDetailInformation_text__c</fullName>
    <label>House Notify&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HouseNotifyParty__c.field-meta.xml
<CustomField>
    <fullName>HouseNotifyParty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>House Notify Party</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>F_TMS_S_O3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HSCode__c.field-meta.xml
<CustomField>
    <fullName>HSCode__c</fullName>
    <label>HS Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/JobRequestID__c.field-meta.xml
<CustomField>
    <fullName>JobRequestID__c</fullName>
    <label>File No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MBLNumber__c.field-meta.xml
<CustomField>
    <fullName>MBLNumber__c</fullName>
    <label>M B/L Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PackageUnitCode__c.field-meta.xml
<CustomField>
    <fullName>PackageUnitCode__c</fullName>
    <label>Package Unit Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BK</fullName>
            </value>
            <value>
                <fullName>BL</fullName>
            </value>
            <value>
                <fullName>BN</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>BX</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CG</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CK</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CP</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>CS</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>CX</fullName>
            </value>
            <value>
                <fullName>CY</fullName>
            </value>
            <value>
                <fullName>DJ</fullName>
            </value>
            <value>
                <fullName>DP</fullName>
            </value>
            <value>
                <fullName>DR</fullName>
            </value>
            <value>
                <fullName>FB</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>FT</fullName>
            </value>
            <value>
                <fullName>HD</fullName>
            </value>
            <value>
                <fullName>HG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PlaceofDelivery__c.field-meta.xml
<CustomField>
    <fullName>PlaceofDelivery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place of Delivery</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PODAOA__c.field-meta.xml
<CustomField>
    <fullName>PODAOA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.D(A.O.A)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/POLAOD__c.field-meta.xml
<CustomField>
    <fullName>POLAOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.L(A.O.D)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/RemarkonManifest__c.field-meta.xml
<CustomField>
    <fullName>RemarkonManifest__c</fullName>
    <label>Remark on Manifest</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/RemarksforOfficialDocument__c.field-meta.xml
<CustomField>
    <fullName>RemarksforOfficialDocument__c</fullName>
    <label>Remarks for Official Document</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/SecondNotifyParty__c.field-meta.xml
<CustomField>
    <fullName>SecondNotifyParty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>2nd Notify Party</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>FTMSSO7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Shipper__c.field-meta.xml
<CustomField>
    <fullName>Shipper__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipper</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>F_TMS_S_O1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ShipperDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>ShipperDetailInformation__c</fullName>
    <label>Shipper’s Detail Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ShipperDetailInformation_text__c.field-meta.xml
<CustomField>
    <fullName>ShipperDetailInformation_text__c</fullName>
    <label>Shipper&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/TransitPortCode__c.field-meta.xml
<CustomField>
    <fullName>TransitPortCode__c</fullName>
    <label>Transit Port Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/X2ndNotifyPartyNew__c.field-meta.xml
<CustomField>
    <fullName>X2ndNotifyPartyNew__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>2nd Notify Party-New</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>FTMSSO8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PortCode__c/PortCode__c.object-meta.xml
<CustomObject>
    <label>Port Code</label>
    <nameField>
        <label>Port Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Port Code</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PortCode__c/fields/PortCode__c.field-meta.xml
<CustomField>
    <fullName>PortCode__c</fullName>
    <label>Port Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/CargoType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CFS/CFS</fullName>
    </customValue>
    <customValue>
        <fullName>CFS/CY</fullName>
    </customValue>
    <customValue>
        <fullName>CFS/DOOR</fullName>
    </customValue>
    <customValue>
        <fullName>CY/CFS</fullName>
    </customValue>
    <customValue>
        <fullName>CY/CY</fullName>
    </customValue>
    <customValue>
        <fullName>DOOR/DOOR</fullName>
    </customValue>
    <customValue>
        <fullName>FCL/FCL</fullName>
    </customValue>
    <customValue>
        <fullName>LCL/LCL</fullName>
    </customValue>
    <masterLabel>Cargo Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/CargoUnit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B/PLT</fullName>
    </customValue>
    <customValue>
        <fullName>BAG</fullName>
    </customValue>
    <customValue>
        <fullName>BAL</fullName>
    </customValue>
    <customValue>
        <fullName>BALE</fullName>
    </customValue>
    <customValue>
        <fullName>BALE, COMPRESSED</fullName>
    </customValue>
    <customValue>
        <fullName>Bale,non-compressed</fullName>
        <label>BALE, NON-COMPRESSED</label>
    </customValue>
    <customValue>
        <fullName>Bar</fullName>
        <label>BAR</label>
    </customValue>
    <customValue>
        <fullName>BARE</fullName>
    </customValue>
    <customValue>
        <fullName>BARREL</fullName>
    </customValue>
    <customValue>
        <fullName>BILL</fullName>
    </customValue>
    <customValue>
        <fullName>BIN</fullName>
    </customValue>
    <customValue>
        <fullName>BOX</fullName>
    </customValue>
    <customValue>
        <fullName>BOX CARTON</fullName>
    </customValue>
    <customValue>
        <fullName>BOXE</fullName>
    </customValue>
    <customValue>
        <fullName>BOXPAL</fullName>
    </customValue>
    <customValue>
        <fullName>BUCKET</fullName>
    </customValue>
    <customValue>
        <fullName>BULK</fullName>
    </customValue>
    <customValue>
        <fullName>BUNDLE</fullName>
    </customValue>
    <customValue>
        <fullName>CAGE</fullName>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
    </customValue>
    <customValue>
        <fullName>Can,cylindrical</fullName>
        <label>CAN, CYLINDRICAL</label>
    </customValue>
    <customValue>
        <fullName>Can,rectangular</fullName>
        <label>CAN, RECTANGULAR</label>
    </customValue>
    <customValue>
        <fullName>CARBOY, NON-PROTECTED</fullName>
    </customValue>
    <customValue>
        <fullName>Carboy,protected</fullName>
        <label>CARBOY, PROTECTED</label>
    </customValue>
    <customValue>
        <fullName>CARDBOARD</fullName>
    </customValue>
    <customValue>
        <fullName>CARDBOXE</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON BOX</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON BOXE</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON PALLET</fullName>
    </customValue>
    <masterLabel>Cargo Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ManifestController.cls
public with sharing class ManifestController {

    public FTMSSO__c objSearch {get; set;}
    public String message {get; set;}
    public Boolean displayReportTable {get; set;}
    public List<ResultWrapper> arrResult {get; set;}

    public String strQuery {get; set;}
    private static Set<String> setFields = new Set<String>();
    public String jobRequestId {get; set;}
    public String hbl {get; set;}

    static{
        setFields.add('Id');
        setFields.add('Shipper__r.TaxCode__c');
        setFields.add('Shipper__c');
        setFields.add('Shipper__r.AccountNameENG__c');
        setFields.add('Shipper__r.EnglishAddress__c');
        setFields.add('Consignee__r.TaxCode__c');
        setFields.add('Consignee__c');
        setFields.add('Consignee__r.AccountNameENG__c');
        setFields.add('Consignee__r.EnglishAddress__c');
        setFields.add('HouseNotifyParty__c');
        setFields.add('HouseNotifyParty__r.AccountNameENG__c');
        setFields.add('HouseNotifyParty__r.TaxCode__c');
        setFields.add('HouseNotifyParty__r.EnglishAddress__c');
        setFields.add('SecondNotifyParty__c');
        setFields.add('SecondNotifyParty__r.AccountNameENG__c');
        setFields.add('SecondNotifyParty__r.TaxCode__c');
        setFields.add('SecondNotifyParty__r.EnglishAddress__c');
        setFields.add('X2ndNotifyPartyNew__c');
        setFields.add('X2ndNotifyPartyNew__r.AccountNameENG__c');
        setFields.add('X2ndNotifyPartyNew__r.TaxCode__c');
        setFields.add('X2ndNotifyPartyNew__r.EnglishAddress__c');
        setFields.add('TransitPortCode__c');
        setFields.add('FinalDestination__c');
        setFields.add('FinalDestination__r.PortCode__c');
        setFields.add('POLAOD__c');
        setFields.add('POLAOD__r.PortCode__c');
        setFields.add('PODAOA__c');
        setFields.add('PODAOA__r.PortCode__c');
        setFields.add('PlaceofDelivery__c');
        setFields.add('PlaceofDelivery__r.Name');
        setFields.add('CargoType__c');
        setFields.add('HBLNumber__c');
        setFields.add('DateofHouseBLIssued__c');
        setFields.add('MBLNumber__c');
        setFields.add('DateofMasterBLIssued__c');
        setFields.add('ETD__c');
        setFields.add('CargoQuantity__c');
        setFields.add('CargoUnit__c');
        setFields.add('GrossWeight__c');
        setFields.add('RemarksforOfficialDocument__c');
        setFields.add('ShipperDetailInformation_Text__c');
        setFields.add('ConsigneeDetailInformation_Text__c');
        setFields.add('HouseNotifyDetailInformation_Text__c');
        setFields.add('PackageUnitCode__c');
        setFields.add('JobRequestID__c');
        setFields.add('RemarkonManifest__c');
        setFields.add('HSCode__c');
        setFields.add('DescriptionofGoods__c');
        setFields.add('GoodsAttachment__c');
    }

    public ManifestController(){
        arrResult = new List<ResultWrapper>();
        objSearch = new FTMSSO__c();
        message = '';
        strQuery = '';
        jobRequestId = 'JobID';
        hbl = 'HBL';
        displayReportTable = false;
        String reportType = ApexPages.currentPage().getParameters().get('reportType');
        if(reportType == 'excel'){
            displayReportTable = true;
            String ankenIds = ApexPages.currentPage().getParameters().get('ankenIds');
            Set<String> setShipId = new Set<String>();
            String prmID = '';
            String prmJobRequestID = '';
            String prmMasterBL = '';
            String prmHBL = '';
            if(!String.isBlank(ankenIds)){
                setShipId.addAll(ankenIds.split(','));
            }
            else{
                prmID = ApexPages.currentPage().getParameters().get('ID');
                prmJobRequestID = ApexPages.currentPage().getParameters().get('JobRequestID');
                prmMasterBL = ApexPages.currentPage().getParameters().get('MasterBL');
                prmHBL = ApexPages.currentPage().getParameters().get('HBL');
            }
            strQuery = stringQueryShipment(prmID, prmJobRequestID, prmMasterBL, prmHBL, setShipId);
            arrResult = getData(strQuery);
            if(arrResult.size() > 0){
                if(!String.isBlank(String.valueOf(arrResult.get(0).shipment.JobRequestID__c))){
                    jobRequestId = String.valueOf(arrResult.get(0).shipment.JobRequestID__c);
                }
                if(!String.isBlank(String.valueOf(arrResult.get(0).shipment.HBLNumber__c))){
                    hbl = String.valueOf(arrResult.get(0).shipment.HBLNumber__c);
                }
            }
        }
    }

    public void reset(){
        arrResult = new List<ResultWrapper>();
        objSearch = new FTMSSO__c();
        message = '';
        displayReportTable = false;
    }

    public void generateReport(){
        strQuery = stringQueryShipment(objSearch.Name, objSearch.JobRequestID__c, objSearch.MBLNumber__c, objSearch.HBLNumber__c, new Set<String>());
        arrResult = getData(strQuery);
        if(arrResult.size() == 0){
            message = 'No record.';
            displayReportTable = false;
        }
        else displayReportTable = true;
    }

    private List<ResultWrapper> getData(String strQuery){
        List<ResultWrapper> results = new List<ResultWrapper>();
        List<FTMSSO__c> shipments = new List<FTMSSO__c>();
        Set<String> setShipId = new Set<String>();
        shipments = Database.query(strQuery);
        for(FTMSSO__c ship : shipments){
            setShipId.add(ship.Id);
            ResultWrapper item = new ResultWrapper();
            item.shipmentId = String.valueOf(ship.Id);
            item.shipment = ship;
            if(ship.HouseNotifyParty__c == ship.Consignee__c){
                item.notifyPart1 = 'SAME AS CONSIGNEE';
            }
            else if(!String.isBlank(ship.HouseNotifyParty__c)){
                // item.notifyPart1 = ship.HouseNotifyParty__r.TaxCode__c +'#'+ship.HouseNotifyParty__r.AccountNameENG__c.replaceAll('\n', '<br/>')+'#'+ship.HouseNotifyParty__r.EnglishAddress__c;
                item.notifyPart1 = '';
            }

            if(ship.X2ndNotifyPartyNew__c == ship.Consignee__c){
                item.notifyPart2 = 'SAME AS CONSIGNEE';
            }
            else if(!String.isBlank(ship.X2ndNotifyPartyNew__r.AccountNameENG__c)){
                // item.notifyPart2 = ship.X2ndNotifyPartyNew__r.TaxCode__c +'#'+ship.X2ndNotifyPartyNew__r.EnglishCompanyName__c.replaceAll('\n', '<br/>')+'#'+ship.X2ndNotifyPartyNew__r.EnglishAddress__c;
                item.notifyPart2 = '';
            }

            // if(!String.isBlank(ship.ShipperDetailInformation__c)){
            //     item.shipment.ShipperDetailInformation__c = ship.ShipperDetailInformation__c.replaceAll('\n', '<br/>');
            // }
            
            // if(!String.isBlank(ship.ConsigneeDetailInformation__c)){
            //     item.shipment.ConsigneeDetailInformation__c = ship.ConsigneeDetailInformation__c.replaceAll('\n', '<br/>');
            // }

            if(!String.isBlank(ship.RemarksforOfficialDocument__c)){
                item.shipment.RemarksforOfficialDocument__c = ship.RemarksforOfficialDocument__c.replaceAll('\n', '<br/>');
            }
            if(!String.isBlank(ship.RemarkonManifest__c)){
                item.shipment.RemarkonManifest__c = ship.RemarkonManifest__c.replaceAll('\n', '<br/>');
            }
            if(!String.isBlank(ship.DescriptionofGoods__c)){
                if(!String.isBlank(ship.GoodsAttachment__c)){
                    item.shipment.DescriptionofGoods__c += '<br/>';
                }
                item.shipment.DescriptionofGoods__c = ship.DescriptionofGoods__c.replaceAll('\n', '<br/>');
            }
            if(!String.isBlank(ship.GoodsAttachment__c)){
                item.shipment.GoodsAttachment__c = ship.GoodsAttachment__c.replaceAll('\n', '<br/>');
            }
            
            results.add(item);
        }

        Map<String, List<CntrinTrans__c>> mapConInfo = getContainerInfo(setShipId);
        for(ResultWrapper item : results){
            if(mapConInfo.containsKey(item.shipmentId)){
                item.arrConInfo = mapConInfo.get(item.shipmentId);
            }
        }

        return results;
    }

    private Map<String, List<CntrinTrans__c>> getContainerInfo(Set<String> setShipId){
        Map<String, List<CntrinTrans__c>> mapConInfo = new Map<String, List<CntrinTrans__c>>();
        List<CntrinTrans__c> conInfos = new List<CntrinTrans__c>();
        conInfos = [ SELECT F_TMS_S_O__c, 
                            Description_of_Goods__c, 
                            Gross_Weight_Kg__c, 
                            Measurement_CBM__c, 
                            Container_Number__c, 
                            Seal_Number__c 
                    FROM CntrinTrans__c 
                    WHERE F_TMS_S_O__c IN :setShipId ];
        for(CntrinTrans__c con : conInfos){
            if(!mapConInfo.containsKey(con.F_TMS_S_O__c)){
                mapConInfo.put(con.F_TMS_S_O__c, new List<CntrinTrans__c>());
            }
            if(!String.isBlank(con.Description_of_Goods__c)){
                con.Description_of_Goods__c = con.Description_of_Goods__c.replaceAll('\n', '<br/>');
            } 
            mapConInfo.get(con.F_TMS_S_O__c).add(con);
        }
        return  mapConInfo;
    }

    private String stringQueryShipment(String prmID, String prmJobRequestID, String prmMasterBL, String prmHBL, Set<String> setIds){
        String strSelect = 'SELECT ' + String.join(new List<String>(setFields), ',');
        String strFrom = ' FROM FTMSSO__c ';
        String strWhere = '';
        String strOrderBy = ' ORDER BY Name';

        if(setIds.size() > 0){
            String condIds = '';
            for(String shipId : setIds){
                condIds += '\'' + shipId + '\',';
            }
            condIds = '(' + condIds.removeEnd(',') + ')';
            strWhere += 'AND Id IN ' + condIds;
        }

        if(!String.isBlank(prmID)){
            strWhere += returnWhereCondition('Name', String.escapeSingleQuotes(prmID));
        }

        if(!String.isBlank(prmJobRequestID)){
            strWhere += returnWhereCondition('JobRequestID__c', String.escapeSingleQuotes(prmJobRequestID));
        }

        if(!String.isBlank(prmMasterBL)){
            strWhere += returnWhereCondition('MBLNumber__c', String.escapeSingleQuotes(prmMasterBL));
        }

        if(!String.isBlank(prmHBL)){
            strWhere += returnWhereCondition('HBLNumber__c', String.escapeSingleQuotes(prmHBL));
        }

        if(!String.isBlank(strWhere)) {
            strWhere = strWhere.replaceFirst('AND', 'WHERE');
        }
        return strSelect + strFrom + strWhere + strOrderBy;
    }

    private String returnWhereCondition(String fieldSearch, String valueSearch){
        String whereStr = '';
        List<String> listValue = valueSearch.split(',');
        for(String item : listValue){
            whereStr += fieldSearch + ' LIKE \'%' + String.escapeSingleQuotes(item.trim()) + '%\' OR ';
        }
        if(!String.isBlank(whereStr)){
            whereStr = ' AND (' + whereStr.removeEnd('OR ') + ')';
        }
        return whereStr;
    }

    public class ResultWrapper{
        public String shipmentId {get; set;}
        public FTMSSO__c shipment {get; set;}
        public String notifyPart1 {get; set;}
        public String notifyPart2 {get; set;}
        public List<CntrinTrans__c> arrConInfo {get; set;}

        public ResultWrapper(){
            this.shipmentId = '';
            this.shipment = new FTMSSO__c();
            this.notifyPart1 = '';
            this.notifyPart2 = '';
            this.arrConInfo = new List<CntrinTrans__c>();
        }
    }

}