force-app/main/default/objects/Account/fields/AccountNameENG__c.field-meta.xml
<CustomField>
    <fullName>AccountNameENG__c</fullName>
    <label>Abbreviations Name (ENG)</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Connectbill__c/Connectbill__c.object-meta.xml
<CustomObject>
    <label>Connect Bill</label>
    <nameField>
        <displayFormat>BILLPR-{000000000}</displayFormat>
        <label>Connector ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Connect Bill</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Connectbill__c/fields/Billingid__c.field-meta.xml
<CustomField>
    <fullName>Billingid__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing ID</label>
    <referenceTo>ConsolBill__c</referenceTo>
    <relationshipLabel>Connect Bill</relationshipLabel>
    <relationshipName>Connect_Bill</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Connectbill__c/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>Connect Bill</relationshipLabel>
    <relationshipName>Connect_Bill</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Connectbill__c/fields/Payment_Request_Currency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request_Currency__c</fullName>
    <formula>text(Payment_Request__r.Payment_Currency__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Request Currency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Connectbill__c/fields/Request_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Request_Payment_Amount__c</fullName>
    <label>Request Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Connectbill__c/fields/Service_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Name__c</fullName>
    <formula>Billingid__r.PricingName__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Connectbill__c/fields/Total_Paid_USD__c.field-meta.xml
<CustomField>
    <fullName>Total_Paid_USD__c</fullName>
    <label>Total Paid USD</label>
    <summarizedField>Payment_Allocation__c.Amount_USD__c</summarizedField>
    <summaryForeignKey>Payment_Allocation__c.AllocatetoPR__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Connectbill__c/fields/Total_Paid_VND__c.field-meta.xml
<CustomField>
    <fullName>Total_Paid_VND__c</fullName>
    <label>Total Paid VND</label>
    <summarizedField>Payment_Allocation__c.Amountvnd__c</summarizedField>
    <summaryForeignKey>Payment_Allocation__c.AllocatetoPR__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Connectbill__c/fields/Unpaid_Balance__c.field-meta.xml
<CustomField>
    <fullName>Unpaid_Balance__c</fullName>
    <formula>if(Payment_Request_Currency__c =&quot;VND&quot;, Request_Payment_Amount__c - Total_Paid_VND__c , Request_Payment_Amount__c-Total_Paid_USD__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unpaid Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OperationPaymentRequest__c/OperationPaymentRequest__c.object-meta.xml
<CustomObject>
    <label>Operation Payment Request</label>
    <nameField>
        <displayFormat>OP - {000000}</displayFormat>
        <label>Operation Payment Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operation Payment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OperationPaymentRequest__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VND</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>KHR</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>KRW</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OperationPaymentRequest__c/fields/Payment_to__c.field-meta.xml
<CustomField>
    <fullName>Payment_to__c</fullName>
    <label>Payment to</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OperationPaymentRequest__c/fields/Paymentto__c.field-meta.xml
<CustomField>
    <fullName>Paymentto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment to</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Payment_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Allocation__c/Payment_Allocation__c.object-meta.xml
<CustomObject>
    <label>Payment Allocation</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Payment Allocation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Allocation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Allocation__c/fields/Allocate_to__c.field-meta.xml
<CustomField>
    <fullName>Allocate_to__c</fullName>
    <label>Allocate to</label>
    <referenceTo>ConsolBill__c</referenceTo>
    <relationshipLabel>Payment Allocation</relationshipLabel>
    <relationshipName>Payment_Allocation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Allocation__c/fields/AllocatetoPR__c.field-meta.xml
<CustomField>
    <fullName>AllocatetoPR__c</fullName>
    <label>Allocate to PR</label>
    <referenceTo>Connectbill__c</referenceTo>
    <relationshipLabel>Payment Allocation</relationshipLabel>
    <relationshipName>Payment_Allocation</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Allocation__c/fields/Amount_USD__c.field-meta.xml
<CustomField>
    <fullName>Amount_USD__c</fullName>
    <label>Amount USD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Allocation__c/fields/Amountvnd__c.field-meta.xml
<CustomField>
    <fullName>Amountvnd__c</fullName>
    <label>Amount VND</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Allocation__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <formula>Text(Payment_Voucher__r.Payment_Currency__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Allocation__c/fields/Payment_Voucher__c.field-meta.xml
<CustomField>
    <fullName>Payment_Voucher__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Voucher</label>
    <referenceTo>Payment_Voucher__c</referenceTo>
    <relationshipLabel>Payment Allocation</relationshipLabel>
    <relationshipName>Payment_Allocation</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/Payment_Request__c.object-meta.xml
<CustomObject>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PR{000000}</displayFormat>
        <label>Payment Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Request__c/fields/Payment_Currency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Currency__c</fullName>
    <label>Payment Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Payment_to__c.field-meta.xml
<CustomField>
    <fullName>Payment_to__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment to</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Request</relationshipLabel>
    <relationshipName>Payment_Request1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Total_Paid_USD__c.field-meta.xml
<CustomField>
    <fullName>Total_Paid_USD__c</fullName>
    <label>Total Paid USD</label>
    <summarizedField>Connectbill__c.Total_Paid_USD__c</summarizedField>
    <summaryForeignKey>Connectbill__c.Payment_Request__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Total_Paid_VND__c.field-meta.xml
<CustomField>
    <fullName>Total_Paid_VND__c</fullName>
    <label>Total Paid VND</label>
    <summarizedField>Connectbill__c.Total_Paid_VND__c</summarizedField>
    <summaryForeignKey>Connectbill__c.Payment_Request__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Payment_Voucher__c/Payment_Voucher__c.object-meta.xml
<CustomObject>
    <label>Payment Voucher</label>
    <nameField>
        <displayFormat>PV-{000000}</displayFormat>
        <label>Payment Voucher ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Voucher</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Voucher__c/fields/Allocated_Amount__c.field-meta.xml
<CustomField>
    <fullName>Allocated_Amount__c</fullName>
    <label>Allocated</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Voucher__c/fields/Payment_Currency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Currency__c</fullName>
    <label>Payment Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Voucher__c/fields/Payment_To__c.field-meta.xml
<CustomField>
    <fullName>Payment_To__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Voucher</relationshipLabel>
    <relationshipName>Payment_Voucher</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>VND</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>KHR</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <customValue>
        <fullName>KRW</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>Value1</fullName>
        <isActive>false</isActive>
        <label>Value1</label>
    </customValue>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AllocatePaymentController.cls
public without sharing class AllocatePaymentController {
    public List<Connectbill__c> ConnectBills {get;set;}
    public Payment_Voucher__c PaymentVoucher {get;set;} 

    private static Set<String> fieldsConnectBillQuery = new Set<String>();
    static{
        fieldsConnectBillQuery.add('Id');
        fieldsConnectBillQuery.add('Payment_Request_Currency__c');
        fieldsConnectBillQuery.add('Total_Paid_USD__c');
        fieldsConnectBillQuery.add('Total_Paid_VND__c');
        fieldsConnectBillQuery.add('Unpaid_Balance__c');
        fieldsConnectBillQuery.add('Request_Payment_Amount__c');
        fieldsConnectBillQuery.add('Service_Name__c');
        fieldsConnectBillQuery.add('Billingid__c');
        fieldsConnectBillQuery.add('Payment_Request__r.Name');
    }
    private static Set<String> fieldsPaymentVoucherQuery = new Set<String>();
    static{
        fieldsPaymentVoucherQuery.add('Id');
        fieldsPaymentVoucherQuery.add('Payment_Amount__c');
        fieldsPaymentVoucherQuery.add('Payment_To__r.Id');
        fieldsPaymentVoucherQuery.add('Payment_Currency__c');
        fieldsPaymentVoucherQuery.add('Payment_To__r.AccountNameENG__c');
        fieldsPaymentVoucherQuery.add('Allocated_Amount__c');
    }

    
    @AuraEnabled
    public static List<Connectbill__c> QueryConnectBill(String Payment_to, String Currency_Voucher){
        
        List<Connectbill__c>ConnectBills_temp = new List<Connectbill__c>();
        String strSelect  = String.join(new List<String>(fieldsConnectBillQuery),',');
        String strQuery   = 'SELECT ' + strSelect + ' FROM Connectbill__c WHERE  Unpaid_Balance__c > 0' + 
                                'AND Payment_Request_Currency__c = \'' + Currency_Voucher + '\'' + 'AND Payment_Request__r.Payment_to__r.Id = \'' + Payment_to + '\'';
        try {
            ConnectBills_temp = Database.query(strQuery);
        } catch (Exception e) {
            ConnectBills_temp = new List<Connectbill__c>();
            throw new AuraHandledException(e.getMessage());
        }
        return ConnectBills_temp;
    }

    @AuraEnabled
    public static Payment_Voucher__c QueryPaymentVoucher(String recordId)
    {
        Payment_Voucher__c PaymentVoucher_temp = new Payment_Voucher__c();
        String strSelect  = String.join(new List<String>(fieldsPaymentVoucherQuery),',');
        String strQuery    = 'SELECT ' + strSelect + ' FROM Payment_Voucher__c WHERE Id = \'' + recordId + '\'';
        try {
            PaymentVoucher_temp = Database.query(strQuery);
        } catch (Exception e) {
            PaymentVoucher_temp = new Payment_Voucher__c();
            throw new AuraHandledException(e.getMessage());
        }
        return PaymentVoucher_temp;
    }

    @AuraEnabled
    public static Integer InsertPaymentAllocation(String CurrencyPayment, List<String> AllocateTo, String PaymentVoucherId,
                                                                                    List<decimal> Amount, List<String> ConnectBill)
    {
        List<Payment_Allocation__c> lstPaymentAllocation = new List<Payment_Allocation__c>();
        for(Integer i = 0; i < AllocateTo.size(); i++)
        {
            Payment_Allocation__c PaymentAllocation = new Payment_Allocation__c();
            if(CurrencyPayment=='USD')
            {
                PaymentAllocation.Amount_USD__c = Amount[i];
                PaymentAllocation.Amountvnd__c = 0;
            }
            else
            {
                PaymentAllocation.Amountvnd__c = Amount[i];
                PaymentAllocation.Amount_USD__c = 0;
            }
            //PaymentAllocation.Currency__c = CurrencyPayment;
            PaymentAllocation.Allocate_to__c = AllocateTo[i];   
            PaymentAllocation.AllocatetoPR__c = ConnectBill[i];
            PaymentAllocation.Payment_Voucher__c = PaymentVoucherId;
            lstPaymentAllocation.add(PaymentAllocation);
        }
        insert lstPaymentAllocation;
        return lstPaymentAllocation.size();

    }

    @AuraEnabled
    public static void UpdatePaymentVoucher(decimal CurrentAllocation,String PaymentVoucherId)
    {
        Payment_Voucher__c lstPaymentVoucher = [SELECT Id,Allocated_Amount__c FROM Payment_Voucher__c WHERE Id =: PaymentVoucherId];
        if(lstPaymentVoucher.Allocated_Amount__c != null)
        {
            lstPaymentVoucher.Allocated_Amount__c += CurrentAllocation;
        }
        else{
            lstPaymentVoucher.Allocated_Amount__c = CurrentAllocation;
        }
        update lstPaymentVoucher;
    }

    
    public AllocatePaymentController() {
    }
}