force-app/main/default/objects/Account/fields/AccountNameENG__c.field-meta.xml
<CustomField>
    <fullName>AccountNameENG__c</fullName>
    <label>Abbreviations Name (ENG)</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/EnglishAddress__c.field-meta.xml
<CustomField>
    <fullName>EnglishAddress__c</fullName>
    <label>English Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/FTMSSO__c.object-meta.xml
<CustomObject>
    <label>Shipment.</label>
    <nameField>
        <displayFormat>FSO-{000000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments.</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSSO__c/fields/CargoType__c.field-meta.xml
<CustomField>
    <fullName>CargoType__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargoType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Consignee__c.field-meta.xml
<CustomField>
    <fullName>Consignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consignee</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>F_TMS_S_O2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ContainerNo__c.field-meta.xml
<CustomField>
    <fullName>ContainerNo__c</fullName>
    <label>Container No</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ContainerType1__c.field-meta.xml
<CustomField>
    <fullName>ContainerType1__c</fullName>
    <label>Container Type 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20&apos;DC</fullName>
            </value>
            <value>
                <fullName>40&apos;DC</fullName>
            </value>
            <value>
                <fullName>45&apos;DC</fullName>
            </value>
            <value>
                <fullName>40&apos;HC</fullName>
            </value>
            <value>
                <fullName>45&apos;HC</fullName>
            </value>
            <value>
                <fullName>20&apos;RF</fullName>
            </value>
            <value>
                <fullName>40&apos;RF</fullName>
            </value>
            <value>
                <fullName>45&apos;RF</fullName>
            </value>
            <value>
                <fullName>20&apos;OT</fullName>
            </value>
            <value>
                <fullName>40&apos;OT</fullName>
            </value>
            <value>
                <fullName>45&apos;OT</fullName>
            </value>
            <value>
                <fullName>20&apos;FR</fullName>
            </value>
            <value>
                <fullName>40&apos;FR</fullName>
            </value>
            <value>
                <fullName>Bulk</fullName>
            </value>
            <value>
                <fullName>ISO</fullName>
            </value>
            <value>
                <fullName>20&apos;IMO</fullName>
            </value>
            <value>
                <fullName>40&apos;IMO</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>20&apos;DC-Flexi</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>CBM</fullName>
            </value>
            <value>
                <fullName>RTON</fullName>
            </value>
            <value>
                <fullName>2*20&apos;DC</fullName>
                <isActive>false</isActive>
                <label>2*20&apos;DC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ContainerType2__c.field-meta.xml
<CustomField>
    <fullName>ContainerType2__c</fullName>
    <label>Container Type 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20&apos;DC</fullName>
            </value>
            <value>
                <fullName>40&apos;DC</fullName>
            </value>
            <value>
                <fullName>45&apos;DC</fullName>
            </value>
            <value>
                <fullName>40&apos;HC</fullName>
            </value>
            <value>
                <fullName>45&apos;HC</fullName>
            </value>
            <value>
                <fullName>20&apos;RF</fullName>
            </value>
            <value>
                <fullName>40&apos;RF</fullName>
            </value>
            <value>
                <fullName>45&apos;RF</fullName>
            </value>
            <value>
                <fullName>20&apos;OT</fullName>
            </value>
            <value>
                <fullName>40&apos;OT</fullName>
            </value>
            <value>
                <fullName>45&apos;OT</fullName>
            </value>
            <value>
                <fullName>20&apos;FR</fullName>
            </value>
            <value>
                <fullName>40&apos;FR</fullName>
            </value>
            <value>
                <fullName>Bulk</fullName>
            </value>
            <value>
                <fullName>ISO</fullName>
            </value>
            <value>
                <fullName>20&apos;IMO</fullName>
            </value>
            <value>
                <fullName>40&apos;IMO</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>20&apos;DC-Flexi</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>CBM</fullName>
            </value>
            <value>
                <fullName>RTON</fullName>
            </value>
            <value>
                <fullName>2*20&apos;DC</fullName>
                <isActive>false</isActive>
                <label>2*20&apos;DC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>Gross Weight</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HBLIssueStatus__c.field-meta.xml
<CustomField>
    <fullName>HBLIssueStatus__c</fullName>
    <label>H B/L Issue Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Original H B/L Issued</fullName>
            </value>
            <value>
                <fullName>Waybill Issued</fullName>
            </value>
            <value>
                <fullName>H B/L Surrendered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HBLNumber__c.field-meta.xml
<CustomField>
    <fullName>HBLNumber__c</fullName>
    <label>H B/L Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HBLType__c.field-meta.xml
<CustomField>
    <fullName>HBLType__c</fullName>
    <label>House bill Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ORIGINAL</fullName>
            </value>
            <value>
                <fullName>SURRENDERED</fullName>
            </value>
            <value>
                <fullName>TELEX</fullName>
                <isActive>false</isActive>
                <label>TELEX</label>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/JobRequestID__c.field-meta.xml
<CustomField>
    <fullName>JobRequestID__c</fullName>
    <label>File No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MBLNumber__c.field-meta.xml
<CustomField>
    <fullName>MBLNumber__c</fullName>
    <label>M B/L Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/NumberofContainersPackages__c.field-meta.xml
<CustomField>
    <fullName>NumberofContainersPackages__c</fullName>
    <label>Number of Containers/Packages</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PlaceofDelivery__c.field-meta.xml
<CustomField>
    <fullName>PlaceofDelivery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place of Delivery</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/POLAOD__c.field-meta.xml
<CustomField>
    <fullName>POLAOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.L(A.O.D)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/SealNo__c.field-meta.xml
<CustomField>
    <fullName>SealNo__c</fullName>
    <label>Seal No</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Shipper__c.field-meta.xml
<CustomField>
    <fullName>Shipper__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipper</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>F_TMS_S_O1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ShipperDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>ShipperDetailInformation__c</fullName>
    <label>Shipper’s Detail Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/VesselFlight__c.field-meta.xml
<CustomField>
    <fullName>VesselFlight__c</fullName>
    <label>Vessel/Flight</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Voyage__c.field-meta.xml
<CustomField>
    <fullName>Voyage__c</fullName>
    <label>Voyage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortCode__c/PortCode__c.object-meta.xml
<CustomObject>
    <label>Port Code</label>
    <nameField>
        <label>Port Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Port Code</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PortCode__c/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <label>Country Name (not used)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Åland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas (the)</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia (Plurinational State of)</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/CargoType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CFS/CFS</fullName>
    </customValue>
    <customValue>
        <fullName>CFS/CY</fullName>
    </customValue>
    <customValue>
        <fullName>CFS/DOOR</fullName>
    </customValue>
    <customValue>
        <fullName>CY/CFS</fullName>
    </customValue>
    <customValue>
        <fullName>CY/CY</fullName>
    </customValue>
    <customValue>
        <fullName>DOOR/DOOR</fullName>
    </customValue>
    <customValue>
        <fullName>FCL/FCL</fullName>
    </customValue>
    <customValue>
        <fullName>LCL/LCL</fullName>
    </customValue>
    <masterLabel>Cargo Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PrintDOController.cls
public with sharing class PrintDOController {
    public FTMSSO__c shipment {get; set;}
    public CompanyInformation__c ComInf {get; set;}
    public Date today {get; set;}

    public String shipId {get; set;}
    public String recordType {get;set;}
    public String titlePdf {get;set;}
    public Boolean requiredAttachment {get;set;}

    private static Set<String> fieldsShipQuery = new Set<String>();
    static {
        fieldsShipQuery.add('Id');
        fieldsShipQuery.add('Name');
        // fieldsShipQuery.add('ShipperDetailInformation__c');
        fieldsShipQuery.add('Shipper__r.Name');
        fieldsShipQuery.add('VesselFlight__c');
        fieldsShipQuery.add('Voyage__c');
        fieldsShipQuery.add('POLAOD__r.Name');
        fieldsShipQuery.add('POLAOD__r.Country_Name__c');
        fieldsShipQuery.add('ETA__c');
        fieldsShipQuery.add('CargoType__c');
        fieldsShipQuery.add('NumberofContainersPackages__c');
        fieldsShipQuery.add('GrossWeight__c');
        fieldsShipQuery.add('HBLNumber__c');
        fieldsShipQuery.add('MBLNumber__c');
        fieldsShipQuery.add('HBLIssueStatus__c');
        fieldsShipQuery.add('PlaceofDelivery__r.Name');
        fieldsShipQuery.add('HBLType__c');
        fieldsShipQuery.add('Consignee__r.AccountNameENG__c');
        fieldsShipQuery.add('Consignee__r.Name');
        fieldsShipQuery.add('Consignee__r.EnglishAddress__c');
        fieldsShipQuery.add('JobRequestID__c');
        fieldsShipQuery.add('Owner.Name');
        fieldsShipQuery.add('Owner.Email');
        fieldsShipQuery.add('ContainerNo__c');
        fieldsShipQuery.add('SealNo__c');
        fieldsShipQuery.add('ContainerType1__c');
        fieldsShipQuery.add('ContainerType2__c');
        fieldsShipQuery.add('CargoQuantity__c');
        fieldsShipQuery.add('Measurement__c');
        fieldsShipQuery.add('DescriptionofGoods__c');
        fieldsShipQuery.add('Branch__c');
        fieldsShipQuery.add('CargoUnit__c');
        fieldsShipQuery.add('Warehouse__c');
        fieldsShipQuery.add('ContainerNo__c');
        fieldsShipQuery.add('RecordTypeId');
        fieldsShipQuery.add('HAWBNumber__c');
        fieldsShipQuery.add('Terminal__r.PortCode__c');
        fieldsShipQuery.add('ContainerDetailonBL__c');
        fieldsShipQuery.add('MeasurementTotalCBM__c');
        fieldsShipQuery.add('PlaceofDeliveryDetailInformation__c');
		fieldsShipQuery.add('POLAODsDetailInformation__c');
		fieldsShipQuery.add('Shipment_Type__c');
        fieldsShipQuery.add('ConsigneeDetailInformation_text__c');
    }


    private static Set<String> fieldsComInQuery = new Set<String>();
    static {
        fieldsComInQuery.add('Id');
        fieldsComInQuery.add('Name');
        fieldsComInQuery.add('Address__c');
        fieldsComInQuery.add('Tel__c');
        fieldsComInQuery.add('Fax__c');
        fieldsComInQuery.add('Taxcode__c');
        fieldsComInQuery.add('Email__c');
        fieldsComInQuery.add('Website__c');
        fieldsComInQuery.add('Branch__c');
        fieldsComInQuery.add('CompanyLogo__c');
    }

    public PrintDOController() {
        shipId = ApexPages.currentPage().getParameters().get('Id');
        System.debug('1234:' + shipId);
        shipment = getShipment(shipId);
        if( shipment.PlaceofDeliveryDetailInformation__c != null){

            shipment.PlaceofDeliveryDetailInformation__c=shipment.PlaceofDeliveryDetailInformation__c.toUppercase();
        }
        if(shipment.POLAOD__r.Name != null) shipment.POLAOD__r.Name= shipment.POLAOD__r.Name.toUppercase();
        if(shipment.POLAOD__r.Country_Name__c != null) shipment.POLAOD__r.Country_Name__c= shipment.POLAOD__r.Country_Name__c.toUppercase();

        System.debug('1234:'+shipment);
        
        String RecordTypeId = shipment.RecordTypeId;
        System.debug('1234:' + RecordTypeId);
        RecordType = [SELECT Id,Name from RecordType WHERE Id =:recordTypeId].Name;
        if(recordType == 'Ocean Export' || recordType == 'Ocean Import'){
            titlePdf = 'DO - ' + shipment.HBLNumber__c;
        }else if(recordType == 'Air Export' || recordType == 'Air Import'){
            titlePdf = 'DO - ' + shipment.HAWBNumber__c;
        }
        Apexpages.currentPage().getHeaders().put('content-disposition', 'inline; filename=\"'+titlePdf+'.pdf'+'\"');
        
        ComInf = getComIn(shipment.Branch__c);
        today = Date.today();

    }

    public PageReference closePopupDialog() {
        PageReference page = new PageReference('/'+shipId);
        page.setRedirect(true);
        return page;
      }

    private FTMSSO__c getShipment(String shipId){
        String strSelect = String.join(new List<String>(fieldsShipQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM FTMSSO__c'
                    + ' WHERE Id = \'' + String.escapeSingleQuotes(shipId) + '\'';
        System.debug('queryShip: '+strQuery);
        FTMSSO__c ship;
        try{
            ship = Database.query(strQuery);
        } catch(QueryException e){
            ship = new FTMSSO__c();
        }
        return ship;
    }

    private CompanyInformation__c getComIn(String branch){
        String strSelect = String.join(new List<String>(fieldsComInQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM CompanyInformation__c'
                    + ' WHERE Branch__c = \'' + String.escapeSingleQuotes(branch) + '\'';
        strQuery += ' ORDER BY Name ASC Limit 1';        
        CompanyInformation__c ComIn;
        try{
            ComIn = Database.query(strQuery);
        } catch(QueryException e){
            ComIn = new CompanyInformation__c();
        }
        return ComIn;
    }
}