force-app/main/default/objects/Account/fields/Company_Address__c.field-meta.xml
<CustomField>
    <fullName>Company_Address__c</fullName>
    <label>Company Address (ENG)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/TaxCode__c.field-meta.xml
<CustomField>
    <fullName>TaxCode__c</fullName>
    <label>Tax Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/case__c/case__c.object-meta.xml
<CustomObject>
    <label>CASE</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/case__c/fields/Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner__c</fullName>
    <formula>AccountId__r.Owner.FirstName +  AccountId__r.Owner.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Owner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/case__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/case__c/fields/Company_Address__c.field-meta.xml
<CustomField>
    <fullName>Company_Address__c</fullName>
    <label>Company Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/case__c/fields/Credit_limit__c.field-meta.xml
<CustomField>
    <fullName>Credit_limit__c</fullName>
    <formula>AccountId__r.CreditLimit__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Credit limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/case__c/fields/Payment_Methods__c.field-meta.xml
<CustomField>
    <fullName>Payment_Methods__c</fullName>
    <label>Payment Methods</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/case__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <formula>AccountId__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/case__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <formula>TEXT( AccountId__r.Owner.Role__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Role</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/case__c/fields/Sales_Owner__c.field-meta.xml
<CustomField>
    <fullName>Sales_Owner__c</fullName>
    <label>Sales Owner</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/case__c/fields/Sales_Request__c.field-meta.xml
<CustomField>
    <fullName>Sales_Request__c</fullName>
    <label>Sales Request</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/case__c/fields/Sales_Request_s_Phone__c.field-meta.xml
<CustomField>
    <fullName>Sales_Request_s_Phone__c</fullName>
    <formula>Owner:User.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Request&apos;s Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/case__c/fields/Sales_Request_s_Role__c.field-meta.xml
<CustomField>
    <fullName>Sales_Request_s_Role__c</fullName>
    <formula>TEXT( Owner:User.Role__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Request&apos;s Role</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/case__c/fields/Sales_Request_s_Title__c.field-meta.xml
<CustomField>
    <fullName>Sales_Request_s_Title__c</fullName>
    <formula>Owner:User.Title</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Request&apos;s Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/case__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CONTAINER FEE</fullName>
            </value>
            <value>
                <fullName>CUSTOMS</fullName>
            </value>
            <value>
                <fullName>EXPRESS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/case__c/fields/Service_Type_Original__c.field-meta.xml
<CustomField>
    <fullName>Service_Type_Original__c</fullName>
    <formula>text(Service_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Type(Original)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/case__c/fields/Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Tax_Code__c</fullName>
    <formula>AccountId__r.TaxCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tax Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/case__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <formula>AccountId__r.Owner.Title</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/CompanyInformation__c.object-meta.xml
<CustomObject>
    <label>Company Information</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CompanyInformation__c/fields/Branch1__c.field-meta.xml
<CustomField>
    <fullName>Branch1__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Branch</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/fields/CompanyLogo__c.field-meta.xml
<CustomField>
    <fullName>CompanyLogo__c</fullName>
    <label>Company Logo</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <defaultValue>&apos;TIMES CARGO LOGISTIC CO.,LTD&apos;</defaultValue>
    <label>Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/fields/TaxCode__c.field-meta.xml
<CustomField>
    <fullName>TaxCode__c</fullName>
    <label>Tax Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/fields/Tel__c.field-meta.xml
<CustomField>
    <fullName>Tel__c</fullName>
    <label>Tel</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/User/fields/Branch1__c.field-meta.xml
<CustomField>
    <fullName>Branch1__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Branch</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Branch.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cambodia</fullName>
    </customValue>
    <customValue>
        <fullName>Hải Phòng</fullName>
    </customValue>
    <customValue>
        <fullName>Hồ Chí Minh</fullName>
        <default>true</default>
        <label>Hồ Chí Minh</label>
    </customValue>
    <customValue>
        <fullName>Đà Nẵng</fullName>
    </customValue>
    <customValue>
        <fullName>Taiwan</fullName>
    </customValue>
    <masterLabel>Branch</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TT_HT_NoiBoController.cls
public with sharing class TT_HT_NoiBoController {
        private static Set<String> SoQuery = new Set<String>();
        private static Set<String> CNTRQuery = new Set<String>();
        public CompanyInformation__c Company {get;set;}
        public String formattedDateTime { get; set; }
        public Attachment myfile  {get;set;}
        public case__c So {get;set;}
        public User user {get;set;}
        public Account ac {get;set;}
        public Blob body { get; set; }
        public String name { get; set; }
        public String OderID { get; set; }
        
        static{
            SoQuery.add('Account_Owner__c');
            SoQuery.add('Title__c');
            SoQuery.add('Role__c');
            SoQuery.add('Phone__c');
            SoQuery.add('Sales_Request_s_Title__c');
            SoQuery.add('Sales_Request_s_Role__c');
            SoQuery.add('Sales_Request_s_Phone__c');
            // SoQuery.add('OwnerId.LastName');
            // SoQuery.add('OwnerId.FirstName');
            SoQuery.add('OwnerId');
            SoQuery.add('AccountId__c');

            SoQuery.add('AccountId__r.Name');
            SoQuery.add('Tax_Code__c');
            SoQuery.add('Company_Address__c');
            SoQuery.add('Service_type_original__c');
            SoQuery.add('Service_Type__c');
            SoQuery.add('Credit_limit__c');
            SoQuery.add('Payment_Methods__c');
            SoQuery.add('Sales_Owner__c');
            SoQuery.add('Sales_Request__c');
        


            
        }
       

        public TT_HT_NoiBoController() {
           
           OderID = ApexPages.currentPage().getParameters().get('id');
           
            So = getSo(OderID);
        

            Company= [SELECT Name,Name__c,
            Id,CompanyLogo__c,
            TaxCode__c,Tel__c,Website__c
            ,Email__c ,Address__c,Fax__c
            FROM CompanyInformation__c  WHERE Branch1__c = 'Hồ Chí Minh' limit 1];


            if(So.OwnerId  != null){
    
                user = [SELECT FirstName, LastName, Email
                        FROM User  WHERE Id =: So.OwnerId ];
            }else user =  new User();

            if(So.AccountId__c  != null){
    
                ac = [SELECT Name
                        FROM Account  WHERE Id =: So.AccountId__c ];
            }else ac =  new Account();
            
        }
        
        private case__c getSo(String scheduleID){
            String strSelect = String.join(new List<String>(SoQuery), ',');
            String strQuery = 'SELECT ' + strSelect 
                        + ' FROM case__c'
                        + ' WHERE Id = \'' + scheduleID + '\'';
                        case__c donhang;
            try{
                donhang = Database.query(strQuery);
            } catch(QueryException e){
                donhang = new case__c();
            }
            return donhang;
        }

        
        

       
        public void  Savedoc()
        {
            String OderID = ApexPages.currentPage().getParameters().get('id');
            Attachment attach = new Attachment();
                 attach.Name = name; 
                attach.IsPrivate = false;
                attach.ParentId = OderID;
                if(!Test.isRunningTest()){
                attach.Body = body;
                try{
                    
                    FlsService.doInsert(attach);
                }catch(Exception ex){
                    System.debug(ex.getMessage());
                }
                // if(body!=null && name != null){

                    
                // }
              }   
        }
       
    }