force-app/main/default/objects/Account/fields/EnglishAddress__c.field-meta.xml
<CustomField>
    <fullName>EnglishAddress__c</fullName>
    <label>English Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/TaxCode__c.field-meta.xml
<CustomField>
    <fullName>TaxCode__c</fullName>
    <label>Tax Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/CompanyInformation__c.object-meta.xml
<CustomObject>
    <label>Company Information</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CompanyInformation__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch (not used)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ha Noi</fullName>
            </value>
            <value>
                <fullName>Hai Phong</fullName>
            </value>
            <value>
                <fullName>Ho Chi Minh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/fields/CompanyLogo__c.field-meta.xml
<CustomField>
    <fullName>CompanyLogo__c</fullName>
    <label>Company Logo</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/fields/TaxCode__c.field-meta.xml
<CustomField>
    <fullName>TaxCode__c</fullName>
    <label>Tax Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/fields/Tel__c.field-meta.xml
<CustomField>
    <fullName>Tel__c</fullName>
    <label>Tel</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/FTMSSO__c.object-meta.xml
<CustomObject>
    <label>Shipment.</label>
    <nameField>
        <displayFormat>FSO-{000000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments.</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSSO__c/fields/AirWarehouse__c.field-meta.xml
<CustomField>
    <fullName>AirWarehouse__c</fullName>
    <label>Air Warehouse</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Kho ALSC: CÔNG TY CỔ PHẦN NHÀ GA HÀNG HÓA (ALSC)</fullName>
            </value>
            <value>
                <fullName>Kho ACSV: CÔNG TY CỔ PHẦN DỊCH VỤ HÀNG HÓA HÀNG KHÔNG VIỆT NAM (ACSV)</fullName>
            </value>
            <value>
                <fullName>Kho NCTS: CÔNG TY CỔ PHẦN DỊCH VỤ HÀNG HÓA NỘI BÀI (NCTS)</fullName>
            </value>
            <value>
                <fullName>Kho SCSC: CÔNG TY CỔ PHẦN HÀNG HÓA SÀI GÒN (SCSC)</fullName>
            </value>
            <value>
                <fullName>Kho TSC: CÔNG TY CỔ PHẦN DỊCH VỤ HÀNG HÓA TÂN SƠN NHẤT (TCS)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch (not used)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ha Noi</fullName>
                <default>true</default>
                <label>Ha Noi</label>
            </value>
            <value>
                <fullName>Hai Phong</fullName>
            </value>
            <value>
                <fullName>Ho Chi Minh</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoQuantity__c.field-meta.xml
<CustomField>
    <fullName>CargoQuantity__c</fullName>
    <label>Cargo Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Consignee__c.field-meta.xml
<CustomField>
    <fullName>Consignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consignee</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>F_TMS_S_O2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/FlightNumber__c.field-meta.xml
<CustomField>
    <fullName>FlightNumber__c</fullName>
    <label>Flight Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>Gross Weight</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HAWBNumber__c.field-meta.xml
<CustomField>
    <fullName>HAWBNumber__c</fullName>
    <label>H AWB Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/JobRequestID__c.field-meta.xml
<CustomField>
    <fullName>JobRequestID__c</fullName>
    <label>File No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MAWBNumber__c.field-meta.xml
<CustomField>
    <fullName>MAWBNumber__c</fullName>
    <label>MAWB Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PlaceofDeliveryDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>PlaceofDeliveryDetailInformation__c</fullName>
    <label>Place of Delivery&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Terminal__c.field-meta.xml
<CustomField>
    <fullName>Terminal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Terminal</label>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/VesselFlight__c.field-meta.xml
<CustomField>
    <fullName>VesselFlight__c</fullName>
    <label>Vessel/Flight</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortCode__c/PortCode__c.object-meta.xml
<CustomObject>
    <label>Port Code</label>
    <nameField>
        <label>Port Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Port Code</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/FormAirController.cls
public with sharing class FormAirController {
    public FTMSSO__c shipment {get; set;}

    public CompanyInformation__c ComInf {get; set;}

    private String shipId {get; set;}

    public Date PrintDate {get; set;}

    public String ComName {get;set;}

    private static Set<String> fieldsShipQuery = new Set<String>();

    static{ 
        fieldsShipQuery.add('Terminal__r.Name');
        fieldsShipQuery.add('JobRequestID__c');
        fieldsShipQuery.add('Consignee__r.Name');
        fieldsShipQuery.add('Consignee__r.EnglishAddress__c');
        fieldsShipQuery.add('MAWBNumber__c');
        fieldsShipQuery.add('HAWBNumber__c');
        fieldsShipQuery.add('FlightNumber__c');
        fieldsShipQuery.add('CargoQuantity__c');
        fieldsShipQuery.add('GrossWeight__c');
        fieldsShipQuery.add('DescriptionofGoods__c');
        fieldsShipQuery.add('Branch__c');
        fieldsShipQuery.add('ETA__c');
        fieldsShipQuery.add('VesselFlight__c');
        fieldsShipQuery.add('PlaceofDeliveryDetailInformation__c');
        fieldsShipQuery.add('AirWarehouse__c');
    }
    private static Set<String> fieldsComInQuery = new Set<String>();
    static {
        fieldsComInQuery.add('Id');
        fieldsComInQuery.add('Name');
        fieldsComInQuery.add('Address__c');
        fieldsComInQuery.add('Tel__c');
        fieldsComInQuery.add('Fax__c');
        fieldsComInQuery.add('Taxcode__c');
        fieldsComInQuery.add('CompanyLogo__c');
        fieldsComInQuery.add('Email__c');
        fieldsComInQuery.add('Website__c');
    }
    public FormAirController() {
        shipId = ApexPages.currentPage().getParameters().get('id');
        System.debug('shipId :'+shipId);
        shipment = getShipment(shipId);
        System.debug('shipment :'+shipment);
        String city = shipment.Branch__c;
        System.debug('city :'+city);
        ComInf = getComIn(city);
        PrintDate = Date.today();
        // ComName = '';
        if(shipment.AirWarehouse__c != null){
            ComName = shipment.AirWarehouse__c.subStringAfter(':');
            System.debug('1122: ' + ComName);
        }
    }
    private FTMSSO__c getShipment(String shipId){
        String strSelect = String.join(new List<String>(fieldsShipQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM FTMSSO__c'
                    + ' WHERE Id = \'' + String.escapeSingleQuotes(shipId) + '\'';
        FTMSSO__c ship;
        try{
            ship = Database.query(strQuery);
        } catch(QueryException e){
            ship = new FTMSSO__c();
        }
        return ship;
    }
    private CompanyInformation__c getComIn(String branch){
        String strSelect = String.join(new List<String>(fieldsComInQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM CompanyInformation__c'
                    + ' WHERE Branch__c = \'' + String.escapeSingleQuotes(branch) + '\'';
        strQuery += ' ORDER BY Name ASC Limit 1';        
        CompanyInformation__c ComIn;
        try{
            ComIn = Database.query(strQuery);
            System.debug('ComIn :'+ComIn);
        } catch(QueryException e){
            ComIn = new CompanyInformation__c();
        }
        return ComIn;
    }
}