force-app/main/default/objects/Account/fields/Salesman__c.field-meta.xml
<CustomField>
    <fullName>Salesman__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesman</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/CompanyInformation__c.object-meta.xml
<CustomObject>
    <label>Company Information</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CompanyInformation__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch (not used)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ha Noi</fullName>
            </value>
            <value>
                <fullName>Hai Phong</fullName>
            </value>
            <value>
                <fullName>Ho Chi Minh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/fields/Tel__c.field-meta.xml
<CustomField>
    <fullName>Tel__c</fullName>
    <label>Tel</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/FTMSBill__c.object-meta.xml
<CustomObject>
    <label>F/TMS Bill</label>
    <nameField>
        <displayFormat>FTB-{000000}</displayFormat>
        <label>F/TMS Bill ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>F/TMS Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSBill__c/fields/AmountTaxSellingFCY__c.field-meta.xml
<CustomField>
    <fullName>AmountTaxSellingFCY__c</fullName>
    <formula>if ( TaxIncluded__c = FALSE, ChargeQuantity__c *  UnitPriceFCY__c *  TaxRateSelling__c , (ChargeQuantity__c * UnitPriceFCY__c * TaxRateSelling__c )/ (1+TaxRateSelling__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Tax Selling (FCY)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/AmountTaxSellingLocal__c.field-meta.xml
<CustomField>
    <fullName>AmountTaxSellingLocal__c</fullName>
    <formula>if ( TaxIncluded__c = FALSE, ChargeQuantity__c *  UnitPriceofSellingLocal__c *  TaxRateSelling__c , (ChargeQuantity__c * UnitPriceofSellingLocal__c * TaxRateSelling__c )/ (1+TaxRateSelling__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Tax Selling (Local)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/BillNameatPrintENG__c.field-meta.xml
<CustomField>
    <fullName>BillNameatPrintENG__c</fullName>
    <label>Bill Name at Print(ENG)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/ChargeQuantity__c.field-meta.xml
<CustomField>
    <fullName>ChargeQuantity__c</fullName>
    <label>Charge Quantity</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/ExchangeRateSelling__c.field-meta.xml
<CustomField>
    <fullName>ExchangeRateSelling__c</fullName>
    <label>Exchange Rate - Selling</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/FTMSSO__c.field-meta.xml
<CustomField>
    <fullName>FTMSSO__c</fullName>
    <label>F/TMS S/O</label>
    <referenceTo>FTMSSO__c</referenceTo>
    <relationshipLabel>F/TMS Bills</relationshipLabel>
    <relationshipName>F_TMS_Bills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/InvoiceTo__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS Bills</relationshipLabel>
    <relationshipName>F_TMS_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/TaxRateSelling__c.field-meta.xml
<CustomField>
    <fullName>TaxRateSelling__c</fullName>
    <label>Tax Rate-Selling(%)</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/TotalAmountofSellingFCY__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountofSellingFCY__c</fullName>
    <formula>IF(TaxIncluded__c= FALSE, ChargeQuantity__c *  UnitPriceFCY__c, ChargeQuantity__c *  UnitPriceFCY__c - AmountTaxSellingFCY__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount of Selling (FCY)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/TotalAmountofSellingLocal__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountofSellingLocal__c</fullName>
    <formula>IF(TaxIncluded__c= FALSE, ChargeQuantity__c *  UnitPriceofSellingLocal__c, ChargeQuantity__c *  UnitPriceofSellingLocal__c - AmountTaxSellingLocal__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount of Selling (Local)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/TotalSellingInclTaxFCY__c.field-meta.xml
<CustomField>
    <fullName>TotalSellingInclTaxFCY__c</fullName>
    <formula>AmountTaxSellingFCY__c +  TotalAmountofSellingFCY__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Selling Incl Tax (FCY)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/TotalSellingInclTaxLocal__c.field-meta.xml
<CustomField>
    <fullName>TotalSellingInclTaxLocal__c</fullName>
    <formula>AmountTaxSellingLocal__c +  TotalAmountofSellingLocal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Selling Incl Tax (Local)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/UnitPriceFCY__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceFCY__c</fullName>
    <label>Unit Price of Selling (FCY)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/UnitPriceofSellingLocal__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceofSellingLocal__c</fullName>
    <label>Unit Price of Selling(Local)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/FTMSSO__c.object-meta.xml
<CustomObject>
    <label>Shipment.</label>
    <nameField>
        <displayFormat>FSO-{000000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments.</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSSO__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch (not used)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ha Noi</fullName>
                <default>true</default>
                <label>Ha Noi</label>
            </value>
            <value>
                <fullName>Hai Phong</fullName>
            </value>
            <value>
                <fullName>Ho Chi Minh</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Date_of_issue__c.field-meta.xml
<CustomField>
    <fullName>Date_of_issue__c</fullName>
    <label>Date of issue</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HBLNumber__c.field-meta.xml
<CustomField>
    <fullName>HBLNumber__c</fullName>
    <label>H B/L Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Salesman__c.field-meta.xml
<CustomField>
    <fullName>Salesman__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesman</label>
    <referenceTo>User</referenceTo>
    <relationshipName>F_TMS_S_O1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/TotalAmountofSellingLocal__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountofSellingLocal__c</fullName>
    <label>Total Amount of Selling (Local)</label>
    <summarizedField>FTMSBill__c.TotalAmountofSellingLocal__c</summarizedField>
    <summaryForeignKey>FTMSBill__c.FTMSSO__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/TotalSellingInclTaxFCY__c.field-meta.xml
<CustomField>
    <fullName>TotalSellingInclTaxFCY__c</fullName>
    <label>Total Selling Incl Tax (USD)</label>
    <summarizedField>FTMSBill__c.TotalSellingInclTaxFCY__c</summarizedField>
    <summaryFilterItems>
        <field>FTMSBill__c.CurrencySelling__c</field>
        <operation>equals</operation>
        <value>USD</value>
    </summaryFilterItems>
    <summaryForeignKey>FTMSBill__c.FTMSSO__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/TotalSellingInclTaxLocal__c.field-meta.xml
<CustomField>
    <fullName>TotalSellingInclTaxLocal__c</fullName>
    <label>Total Selling Incl Tax (Local)</label>
    <summarizedField>FTMSBill__c.TotalSellingInclTaxLocal__c</summarizedField>
    <summaryForeignKey>FTMSBill__c.FTMSSO__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/User/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch (not used)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ha Noi</fullName>
            </value>
            <value>
                <fullName>Hai Phong</fullName>
            </value>
            <value>
                <fullName>Ho Chi Minh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DebitNoteController.cls
public with sharing class DebitNoteController {
    public FTMSSO__c shipment {get; set;}

    public List<FTMSBill__c> lstBill {get; set;}
    
    public FTMSBill__c bill {get; set;}

    public Contact contact {get; set;}

    public CompanyInformation__c Company {get; set;}

    public String selectedCustomerId {get; set;}

    public String customerValue {get; set;}

    private String shipId {get; set;}

    public String branchCompany {get; set;}

    public Decimal AmountSellingFCY {get; set;}
    
    public Decimal AmountSellinglocal {get; set;}

    public Decimal AmountSellingInclFCY {get; set;}

    public Decimal AmountSellingInclLocal {get; set;}

    public Decimal AmountTaxSellingFCY {get; set;}

    public Decimal AmountTaxSellingLocal {get; set;}

    public String readTotalAmountVND {get; set;}

    private static Set<String> fieldsShipQuery = new Set<String>();

    static{
        fieldsShipQuery.add('Salesman__r.Name');
        fieldsShipQuery.add('Date_of_issue__c');
        fieldsShipQuery.add('ETD__c');
        fieldsShipQuery.add('HBLNumber__c');
        fieldsShipQuery.add('Branch__c');
    }
    private static Set<String> fieldsBillQuery = new Set<String>();
    static{
        fieldsBillQuery.add('BillNameatPrintENG__c');
        fieldsBillQuery.add('ChargeQuantity__c	');
        fieldsBillQuery.add('UnitPriceFCY__c');
        fieldsBillQuery.add('UnitPriceofSellingLocal__c');
        fieldsBillQuery.add('TotalAmountofSellingFCY__c');
        fieldsBillQuery.add('TotalAmountofSellingLocal__c');
        fieldsBillQuery.add('TaxRateSelling__c');
        fieldsBillQuery.add('TotalSellingInclTaxFCY__c');
        fieldsBillQuery.add('TotalSellingInclTaxLocal__c');
        fieldsBillQuery.add('ExchangeRateSelling__c');
        fieldsBillQuery.add('AmountTaxSellingFCY__c');
        fieldsBillQuery.add('AmountTaxSellingLocal__c');
        fieldsBillQuery.add('InvoiceTo__r.Name');
    }
    private static Set<String> fieldsCompanyQuery = new Set<String>();
    static{
        fieldsCompanyQuery.add('Name');
        fieldsCompanyQuery.add('Address__c');
        fieldsCompanyQuery.add('Tel__c');
        fieldsCompanyQuery.add('Fax__c');
    }
    public DebitNoteController() {
        shipId = ApexPages.currentPage().getParameters().get('Id');
        customerValue = ApexPages.currentPage().getParameters().get('customerValue');
        AmountSellingFCY = 0;
        AmountSellinglocal = 0;
        AmountSellingInclFCY = 0;
        AmountSellingInclLocal = 0;
        AmountTaxSellingFCY = 0;
        AmountTaxSellingLocal = 0;
        readTotalAmountVND = '';
        branchCompany = '';
        System.debug('customerValue123 :'+customerValue);
        shipment = getShipment(shipId);
        lstBill = getListBill(shipId,customerValue);
        bill = getBill(shipId,customerValue);
        contact = getContact(customerValue);
        branchCompany = shipment.Branch__c;
        Company = getListCompany(branchCompany);
        System.debug('lstCompany :'+Company);
        
        System.debug('lstBill :'+lstBill);

        for(FTMSBill__c bill : lstBill){
            AmountSellingFCY += bill.TotalAmountofSellingFCY__c;
            AmountSellinglocal += bill.TotalAmountofSellingLocal__c;
            AmountSellingInclFCY += bill.TotalSellingInclTaxFCY__c;
            AmountSellingInclLocal += bill.TotalSellingInclTaxLocal__c;
            AmountTaxSellingFCY += bill.AmountTaxSellingFCY__c;
            AmountTaxSellingLocal += bill.AmountTaxSellingLocal__c;
        }

        readTotalAmountVND = EnglishNumberToWords.convert(AmountSellingInclLocal.setScale(2));

    }
    private FTMSSO__c getShipment(String shipId){
        String strSelect = String.join(new List<String>(fieldsShipQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM FTMSSO__c'
                    + ' WHERE Id = \'' + String.escapeSingleQuotes(shipId) + '\'';
        FTMSSO__c ship;
        try{
            ship = Database.query(strQuery);
        } catch(QueryException e){
            ship = new FTMSSO__c();
        }
        return ship;
    }

    private List<FTMSBill__c> getListBill(String shipId, String cusId){
        String strSelect = String.join(new List<String>(fieldsBillQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM FTMSBill__c'
                    + ' WHERE FTMSSO__c = \'' + String.escapeSingleQuotes(shipId) + '\' AND InvoiceTo__c = \''+ String.escapeSingleQuotes(cusId) + '\'';
        strQuery += ' ORDER BY Name ASC';
        List<FTMSBill__c> lstBill;
        try{
            lstBill = Database.query(strQuery);
        } catch(QueryException e){
            lstBill = new List<FTMSBill__c>();
        }
        return lstBill;
    }

    private FTMSBill__c getBill(String shipId, String cusId){
        String strSelect = String.join(new List<String>(fieldsBillQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM FTMSBill__c'
                    + ' WHERE FTMSSO__c = \'' + String.escapeSingleQuotes(shipId) + '\' AND InvoiceTo__c = \''+ String.escapeSingleQuotes(cusId) + '\'';
        strQuery += ' ORDER BY Name LIMIT 1';
        FTMSBill__c Bill;
        try{
            Bill = Database.query(strQuery);
        } catch(QueryException e){
            Bill = new FTMSBill__c();
        }
        return Bill;
    }

    private Contact getContact(String customerValue){
        // String strSelect = String.join(new List<String>(fieldsBillQuery), ',');
        String strQuery = 'SELECT Name'
                    + ' FROM Contact'
                    + ' WHERE AccountId = \'' + String.escapeSingleQuotes(customerValue) + '\'';
        strQuery += ' ORDER BY Name LIMIT 1';
        Contact cont;
        try{
            cont = Database.query(strQuery);
        } catch(QueryException e){
            cont = new Contact();
        }
        return cont;
    }

    private CompanyInformation__c getListCompany(String branchCompany){
        String strSelect = String.join(new List<String>(fieldsCompanyQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM CompanyInformation__c'
                    + ' WHERE Branch__c = \'' + String.escapeSingleQuotes(branchCompany) + '\'';
        strQuery += ' ORDER BY Name LIMIT 1';
        CompanyInformation__c lstCompany;
        try{
            lstCompany = Database.query(strQuery);
        } catch(QueryException e){
            lstCompany = new CompanyInformation__c();
        }
        return lstCompany;
    }
}