force-app/main/default/objects/Account/fields/Salesman__c.field-meta.xml
<CustomField>
    <fullName>Salesman__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesman</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/CntrinTrans__c.object-meta.xml
<CustomObject>
    <label>CNTR in Trans</label>
    <nameField>
        <displayFormat>CNTR-{00000}</displayFormat>
        <label>CNTR in Trans</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CNTR in Trans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CntrinTrans__c/fields/CargoUnit__c.field-meta.xml
<CustomField>
    <fullName>CargoUnit__c</fullName>
    <label>Cargo Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargoUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/ETA__c.field-meta.xml
<CustomField>
    <fullName>ETA__c</fullName>
    <formula>F_TMS_S_O__r.ETA__c</formula>
    <label>ETA</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/Salesman__c.field-meta.xml
<CustomField>
    <fullName>Salesman__c</fullName>
    <formula>HYPERLINK( &quot;/&quot; &amp; CASESAFEID(F_TMS_S_O__r.Salesman__r.Id)
,F_TMS_S_O__r.Salesman__r.FirstName&amp;&quot; &quot;&amp;F_TMS_S_O__r.Salesman__r.LastName
, &quot;_self&quot; )</formula>
    <label>Salesman</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/CompanyInformation__c.object-meta.xml
<CustomObject>
    <label>Company Information</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CompanyInformation__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch (not used)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ha Noi</fullName>
            </value>
            <value>
                <fullName>Hai Phong</fullName>
            </value>
            <value>
                <fullName>Ho Chi Minh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/FTMSSO__c.object-meta.xml
<CustomObject>
    <label>Shipment.</label>
    <nameField>
        <displayFormat>FSO-{000000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments.</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSSO__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch (not used)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ha Noi</fullName>
                <default>true</default>
                <label>Ha Noi</label>
            </value>
            <value>
                <fullName>Hai Phong</fullName>
            </value>
            <value>
                <fullName>Ho Chi Minh</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoClosingTime__c.field-meta.xml
<CustomField>
    <fullName>CargoClosingTime__c</fullName>
    <label>Cargo Closing Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoQuantity__c.field-meta.xml
<CustomField>
    <fullName>CargoQuantity__c</fullName>
    <label>Cargo Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoUnit__c.field-meta.xml
<CustomField>
    <fullName>CargoUnit__c</fullName>
    <label>Cargo Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargoUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CollectAt__c.field-meta.xml
<CustomField>
    <fullName>CollectAt__c</fullName>
    <label>Collect At</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Date_of_issue__c.field-meta.xml
<CustomField>
    <fullName>Date_of_issue__c</fullName>
    <label>Date of issue</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/FinalDestinationDetail__c.field-meta.xml
<CustomField>
    <fullName>FinalDestinationDetail__c</fullName>
    <label>Final Destination Detail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/FinalDestinationsDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>FinalDestinationsDetailInformation__c</fullName>
    <label>Final Destination&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HouseBookingNo__c.field-meta.xml
<CustomField>
    <fullName>HouseBookingNo__c</fullName>
    <label>House Booking No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HouseFreightCollectPrepaid__c.field-meta.xml
<CustomField>
    <fullName>HouseFreightCollectPrepaid__c</fullName>
    <label>House Freight Collect/Prepaid</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collected</fullName>
            </value>
            <value>
                <fullName>Prepaid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MeasurementTotalCBM__c.field-meta.xml
<CustomField>
    <fullName>MeasurementTotalCBM__c</fullName>
    <label>Measurement (Total CBM)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MotherVesselFlight__c.field-meta.xml
<CustomField>
    <fullName>MotherVesselFlight__c</fullName>
    <label>Mother Vessel/Flight</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/NotesforCustomer__c.field-meta.xml
<CustomField>
    <fullName>NotesforCustomer__c</fullName>
    <label>Notes for Customer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PlaceofDeliveryDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>PlaceofDeliveryDetailInformation__c</fullName>
    <label>Place of Delivery&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PlaceofReceiptDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>PlaceofReceiptDetailInformation__c</fullName>
    <label>Place of Receipt&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PlaceofStuffing__c.field-meta.xml
<CustomField>
    <fullName>PlaceofStuffing__c</fullName>
    <label>Place of Stuffing</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PODAOA__c.field-meta.xml
<CustomField>
    <fullName>PODAOA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.D(A.O.A)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PODAOAsDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>PODAOAsDetailInformation__c</fullName>
    <label>P.O.D(A.O.A)&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/POLAOD__c.field-meta.xml
<CustomField>
    <fullName>POLAOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.L(A.O.D)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/POLAODsDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>POLAODsDetailInformation__c</fullName>
    <label>P.O.L(A.O.D)&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PrepaidAt__c.field-meta.xml
<CustomField>
    <fullName>PrepaidAt__c</fullName>
    <label>Prepaid At</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Salesman__c.field-meta.xml
<CustomField>
    <fullName>Salesman__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesman</label>
    <referenceTo>User</referenceTo>
    <relationshipName>F_TMS_S_O1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Shipper__c.field-meta.xml
<CustomField>
    <fullName>Shipper__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipper</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>F_TMS_S_O1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ShipperDetailInformation_text__c.field-meta.xml
<CustomField>
    <fullName>ShipperDetailInformation_text__c</fullName>
    <label>Shipper&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/StuffingContact__c.field-meta.xml
<CustomField>
    <fullName>StuffingContact__c</fullName>
    <label>Stuffing Contact</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/TransitVoyageFlight__c.field-meta.xml
<CustomField>
    <fullName>TransitVoyageFlight__c</fullName>
    <label>Transit Voyage/Flight</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/VesselFlight__c.field-meta.xml
<CustomField>
    <fullName>VesselFlight__c</fullName>
    <label>Vessel/Flight</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Voyage__c.field-meta.xml
<CustomField>
    <fullName>Voyage__c</fullName>
    <label>Voyage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortCode__c/PortCode__c.object-meta.xml
<CustomObject>
    <label>Port Code</label>
    <nameField>
        <label>Port Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Port Code</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PortCode__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code (not used_</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AD</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AG</fullName>
            </value>
            <value>
                <fullName>AI</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AQ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>AX</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BJ</fullName>
            </value>
            <value>
                <fullName>BL</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BN</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>BQ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch (not used)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ha Noi</fullName>
            </value>
            <value>
                <fullName>Hai Phong</fullName>
            </value>
            <value>
                <fullName>Ho Chi Minh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/CargoUnit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B/PLT</fullName>
    </customValue>
    <customValue>
        <fullName>BAG</fullName>
    </customValue>
    <customValue>
        <fullName>BAL</fullName>
    </customValue>
    <customValue>
        <fullName>BALE</fullName>
    </customValue>
    <customValue>
        <fullName>BALE, COMPRESSED</fullName>
    </customValue>
    <customValue>
        <fullName>Bale,non-compressed</fullName>
        <label>BALE, NON-COMPRESSED</label>
    </customValue>
    <customValue>
        <fullName>Bar</fullName>
        <label>BAR</label>
    </customValue>
    <customValue>
        <fullName>BARE</fullName>
    </customValue>
    <customValue>
        <fullName>BARREL</fullName>
    </customValue>
    <customValue>
        <fullName>BILL</fullName>
    </customValue>
    <customValue>
        <fullName>BIN</fullName>
    </customValue>
    <customValue>
        <fullName>BOX</fullName>
    </customValue>
    <customValue>
        <fullName>BOX CARTON</fullName>
    </customValue>
    <customValue>
        <fullName>BOXE</fullName>
    </customValue>
    <customValue>
        <fullName>BOXPAL</fullName>
    </customValue>
    <customValue>
        <fullName>BUCKET</fullName>
    </customValue>
    <customValue>
        <fullName>BULK</fullName>
    </customValue>
    <customValue>
        <fullName>BUNDLE</fullName>
    </customValue>
    <customValue>
        <fullName>CAGE</fullName>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
    </customValue>
    <customValue>
        <fullName>Can,cylindrical</fullName>
        <label>CAN, CYLINDRICAL</label>
    </customValue>
    <customValue>
        <fullName>Can,rectangular</fullName>
        <label>CAN, RECTANGULAR</label>
    </customValue>
    <customValue>
        <fullName>CARBOY, NON-PROTECTED</fullName>
    </customValue>
    <customValue>
        <fullName>Carboy,protected</fullName>
        <label>CARBOY, PROTECTED</label>
    </customValue>
    <customValue>
        <fullName>CARDBOARD</fullName>
    </customValue>
    <customValue>
        <fullName>CARDBOXE</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON BOX</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON BOXE</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON PALLET</fullName>
    </customValue>
    <masterLabel>Cargo Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BookingNoteController.cls
public with sharing class BookingNoteController {
    public FTMSSO__c shipment {get;set;}
    public String shipmentId {get;set;}
    public String strQueryShipment {get;set;}
    private static Set<String> setFieldShipment = new Set<String>();

    public CompanyInformation__c companyInf {get;set;}
    public String strQueryCompany {get;set;}
    private static Set<String> setFieldCompany = new Set<String>();

    public List<CntrWrapper> lstCntr {get;set;}
    public String strQueryCntr {get;set;}
    private static Set<String> setFieldsCntr = new Set<String>();
    public List<String> lstContainer {get;set;}


    static {
        setFieldShipment.add('HouseBookingNo__c');
        setFieldShipment.add('ShipperDetailInformation_text__c');
        setFieldShipment.add('Shipper__r.Name');
        setFieldShipment.add('POLAOD__r.Name');
        setFieldShipment.add('POLAOD__r.Country_Code__c');
        setFieldShipment.add('POLAODsDetailInformation__c');
        setFieldShipment.add('PODAOAsDetailInformation__c');
        setFieldShipment.add('PlaceofStuffing__c');
        setFieldShipment.add('StuffingContact__c');
        setFieldShipment.add('PODAOA__r.Name');
        setFieldShipment.add('MotherVesselFlight__c');

        setFieldShipment.add('VesselFlight__c');
        setFieldShipment.add('Voyage__c');
        setFieldShipment.add('ETA__c');
        setFieldShipment.add('ETD__c');

        setFieldShipment.add('ETD__c');
        setFieldShipment.add('TransitVoyageFlight__c');
        setFieldShipment.add('NotesforCustomer__c');
        setFieldShipment.add('MeasurementTotalCBM__c');
        setFieldShipment.add('PlaceofDeliveryDetailInformation__c');
        setFieldShipment.add('PlaceofReceiptDetailInformation__c');
        setFieldShipment.add('FinalDestinationsDetailInformation__c');
        setFieldShipment.add('FinalDestinationDetail__c');
        setFieldShipment.add('CargoClosingTime__c');
        setFieldShipment.add('Date_of_issue__c');
        setFieldShipment.add('Salesman__r.Name');
        setFieldShipment.add('Salesman__r.Phone');
        setFieldShipment.add('PrepaidAt__c');
        setFieldShipment.add('CollectAt__c');
        setFieldShipment.add('HouseFreightCollectPrepaid__c');
        setFieldShipment.add('Branch__c');
        setFieldShipment.add('CargoQuantity__c');
        setFieldShipment.add('CargoUnit__c');
        setFieldShipment.add('Precarriagevoyage__c');
        setFieldShipment.add('Shipment_Type__c');


        setFieldCompany.add('Name');
        setFieldCompany.add('Address__c');
        setFieldCompany.add('Tel__c');
        setFieldCompany.add('Fax__c');

        setFieldsCntr.add('Container_Type__c');
    }

    public BookingNoteController() {
        shipment = new FTMSSO__c();
        companyInf = new CompanyInformation__c();
        lstCntr = new List<CntrWrapper>();
        lstContainer = new list<String>();
        strQueryShipment = '';
        strQueryCntr = '';
        shipmentId = '';

        shipmentId = ApexPages.currentPage().getParameters().get('Id');

        strQueryShipment = stringQueryShipment(shipmentId);
        shipment = getDataShipment(strQueryShipment);

        if(shipment.CargoQuantity__c > 1 && shipment.CargoUnit__c != null && shipment.CargoUnit__c != ''){
            shipment.CargoUnit__c = shipment.CargoUnit__c + 's';
        }
        
        strQueryCompany = stringQueryCompany(shipment.Branch__c);
        companyInf = getDataCompany(strQueryCompany);

        strQueryCntr = stringQueryCntr(shipmentId);
        List<CntrinTrans__c> lstCntr = new List<CntrinTrans__c>();
        lstCntr = Database.query(strQueryCntr);
        Map<String, Integer> mapNameToCount = new Map<String, Integer>();

        for(CntrinTrans__c objCon : lstCntr)
        {
            if(mapNameToCount.containsKey(objCon.Container_Type__c))
            {
                mapNameToCount.put(objCon.Container_Type__c, mapNameToCount.get(objCon.Container_Type__c));
            }
            else
            {
                mapNameToCount.put(objCon.Container_Type__c, 1);
            }
        }

        System.debug('1234:' + mapNameToCount);
        String stringCon = '';
        for (String name: mapNameToCount.keySet()) {
            Integer value = mapNameToCount.get(name);
            stringCon = value + 'X' + name + ' ';
            lstContainer.add(stringCon);
        }
        System.debug('1234:' + lstContainer);

    }

    private FTMSSO__c getDataShipment (String strQueryShipment){
        FTMSSO__c ship = new FTMSSO__c();
        ship = Database.query(strQueryShipment);
        return ship;
    }

    private CompanyInformation__c getDataCompany(String strQueryCompany){
        CompanyInformation__c com = new CompanyInformation__c();
        com = Database.query(strQueryCompany);
        return com;
    }

    private String stringQueryShipment (String shipmentId){
        String strSelect = 'SELECT ' + String.join(new List<String>(setFieldShipment),',');
        String strFrom = ' FROM FTMSSO__c ';
        String strWhere = ' WHERE Id = \'' + shipmentId + '\'';
        String strOrderBy = ' ORDER BY Name';
        return strSelect + strFrom + strWhere + strOrderBy;
    }

    private String stringQueryCompany (String branch){
        String strSelect = 'SELECT ' + String.join(new List<String>(setFieldCompany),',');
        String strFrom = ' FROM CompanyInformation__c ';
        String strWhere = ' WHERE Branch__c = \'' + branch + '\'';
        String strOrderBy = ' ORDER BY Name LIMIT 1';
        return strSelect + strFrom + strWhere + strOrderBy;
    }

    private String stringQueryCntr (String shipmentId){
        String strSelect = 'SELECT ' + String.join(new List<String>(setFieldsCntr),',');
        String strFrom = ' FROM CntrinTrans__c ';
        String strWhere = ' WHERE 	F_TMS_S_O__c = \'' + shipmentId + '\'';
        String strOrderBy = ' ORDER BY Name ';
        return strSelect + strFrom + strWhere + strOrderBy;
    }
    
    public class CntrWrapper{
        public String ContainerName {get;set;}
        public Decimal CountCon {get;set;}
        public CntrWrapper(){
            ContainerName = '';
            CountCon = 0;
        }
    }
}