force-app/main/default/objects/Account/fields/Salesman__c.field-meta.xml
<CustomField>
    <fullName>Salesman__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesman</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/CntrinTrans__c.object-meta.xml
<CustomObject>
    <label>CNTR in Trans</label>
    <nameField>
        <displayFormat>CNTR-{00000}</displayFormat>
        <label>CNTR in Trans</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CNTR in Trans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CntrinTrans__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <formula>F_TMS_S_O__r.Agent__r.Name</formula>
    <label>Agent</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/ETA__c.field-meta.xml
<CustomField>
    <fullName>ETA__c</fullName>
    <formula>F_TMS_S_O__r.ETA__c</formula>
    <label>ETA</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/Salesman__c.field-meta.xml
<CustomField>
    <fullName>Salesman__c</fullName>
    <formula>HYPERLINK( &quot;/&quot; &amp; CASESAFEID(F_TMS_S_O__r.Salesman__r.Id)
,F_TMS_S_O__r.Salesman__r.FirstName&amp;&quot; &quot;&amp;F_TMS_S_O__r.Salesman__r.LastName
, &quot;_self&quot; )</formula>
    <label>Salesman</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/CompanyInformation__c.object-meta.xml
<CustomObject>
    <label>Company Information</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CompanyInformation__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch (not used)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ha Noi</fullName>
            </value>
            <value>
                <fullName>Hai Phong</fullName>
            </value>
            <value>
                <fullName>Ho Chi Minh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSBill__c/FTMSBill__c.object-meta.xml
<CustomObject>
    <label>F/TMS Bill</label>
    <nameField>
        <displayFormat>FTB-{000000}</displayFormat>
        <label>F/TMS Bill ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>F/TMS Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSBill__c/fields/BillNameatPrintENG__c.field-meta.xml
<CustomField>
    <fullName>BillNameatPrintENG__c</fullName>
    <label>Bill Name at Print(ENG)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/ChargeQuantity__c.field-meta.xml
<CustomField>
    <fullName>ChargeQuantity__c</fullName>
    <label>Charge Quantity</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/FTMSSO__c.field-meta.xml
<CustomField>
    <fullName>FTMSSO__c</fullName>
    <label>F/TMS S/O</label>
    <referenceTo>FTMSSO__c</referenceTo>
    <relationshipLabel>F/TMS Bills</relationshipLabel>
    <relationshipName>F_TMS_Bills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/TotalAmountofSellingFCY__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountofSellingFCY__c</fullName>
    <formula>IF(TaxIncluded__c= FALSE, ChargeQuantity__c *  UnitPriceFCY__c, ChargeQuantity__c *  UnitPriceFCY__c - AmountTaxSellingFCY__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount of Selling (FCY)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/TotalAmountofSellingLocal__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountofSellingLocal__c</fullName>
    <formula>IF(TaxIncluded__c= FALSE, ChargeQuantity__c *  UnitPriceofSellingLocal__c, ChargeQuantity__c *  UnitPriceofSellingLocal__c - AmountTaxSellingLocal__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount of Selling (Local)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/UnitPriceFCY__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceFCY__c</fullName>
    <label>Unit Price of Selling (FCY)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/UnitPriceofSellingLocal__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceofSellingLocal__c</fullName>
    <label>Unit Price of Selling(Local)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/FTMSSO__c.object-meta.xml
<CustomObject>
    <label>Shipment.</label>
    <nameField>
        <displayFormat>FSO-{000000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments.</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSSO__c/fields/Agent2nd__c.field-meta.xml
<CustomField>
    <fullName>Agent2nd__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent (2nd)</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>F_TMS_S_OPK7V</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This Agent will be show on Bill</inlineHelpText>
    <label>Agent</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>F_TMS_S_O4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch (not used)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ha Noi</fullName>
                <default>true</default>
                <label>Ha Noi</label>
            </value>
            <value>
                <fullName>Hai Phong</fullName>
            </value>
            <value>
                <fullName>Ho Chi Minh</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoQuantity__c.field-meta.xml
<CustomField>
    <fullName>CargoQuantity__c</fullName>
    <label>Cargo Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Date_of_issue__c.field-meta.xml
<CustomField>
    <fullName>Date_of_issue__c</fullName>
    <label>Date of issue</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>Gross Weight</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HAWBNumber__c.field-meta.xml
<CustomField>
    <fullName>HAWBNumber__c</fullName>
    <label>H AWB Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HBLNumber__c.field-meta.xml
<CustomField>
    <fullName>HBLNumber__c</fullName>
    <label>H B/L Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/JobRequestID__c.field-meta.xml
<CustomField>
    <fullName>JobRequestID__c</fullName>
    <label>File No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MAWBNumber__c.field-meta.xml
<CustomField>
    <fullName>MAWBNumber__c</fullName>
    <label>MAWB Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MBLNumber__c.field-meta.xml
<CustomField>
    <fullName>MBLNumber__c</fullName>
    <label>M B/L Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MeasurementTotalCBM__c.field-meta.xml
<CustomField>
    <fullName>MeasurementTotalCBM__c</fullName>
    <label>Measurement (Total CBM)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PlaceofDelivery__c.field-meta.xml
<CustomField>
    <fullName>PlaceofDelivery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place of Delivery</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PlaceofReceipt__c.field-meta.xml
<CustomField>
    <fullName>PlaceofReceipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place of Receipt</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Plural_Cargo_Unit__c.field-meta.xml
<CustomField>
    <fullName>Plural_Cargo_Unit__c</fullName>
    <formula>IF( CargoQuantity__c = 1, TEXT(CargoUnit__c) ,
IF(Text(CargoUnit__c)= &quot;&quot;, &quot;&quot;,
IF(Text(CargoUnit__c)= &quot;BALE, COMPRESSED&quot;, &quot;BALES, COMPRESSED&quot;,
IF(Text(CargoUnit__c)= &quot;CARBOY, NON-PROTECTED&quot;, &quot;CARBOYS, NON-PROTECTED&quot;,
IF(
  OR(
    RIGHT(TEXT(CargoUnit__c), 1) = &quot;S&quot;,
    RIGHT(TEXT(CargoUnit__c), 1) = &quot;Z&quot;,
    RIGHT(TEXT(CargoUnit__c), 1) = &quot;O&quot;,
    RIGHT(TEXT(CargoUnit__c), 2) = &quot;SH&quot;,
    RIGHT(TEXT(CargoUnit__c), 2) = &quot;CH&quot;,
    RIGHT(TEXT(CargoUnit__c), 2) = &quot;SS&quot;,
    RIGHT(TEXT(CargoUnit__c), 1) = &quot;X&quot;,
    RIGHT(TEXT(CargoUnit__c), 2) = &quot;SS&quot;),
  	TEXT(CargoUnit__c) &amp; &quot;ES&quot;,
IF(
    OR(
RIGHT(TEXT(CargoUnit__c), 2) = &quot;AY&quot;,
RIGHT(TEXT(CargoUnit__c), 2) = &quot;OY&quot;,
RIGHT(TEXT(CargoUnit__c), 2) = &quot;EY&quot;,
RIGHT(TEXT(CargoUnit__c), 2) = &quot;IY&quot;,
RIGHT(TEXT(CargoUnit__c), 2) = &quot;UY&quot;
),
     TEXT(CargoUnit__c) &amp; &quot;S&quot;,
IF(
    RIGHT(TEXT(CargoUnit__c), 1) = &quot;Y&quot;,
     LEFT(TEXT(CargoUnit__c), LEN(TEXT(CargoUnit__c)) - 1) &amp; &quot;IES&quot;,
  IF(
      RIGHT(TEXT(CargoUnit__c), 2) = &quot;FE&quot;,
      IF(
        TEXT(CargoUnit__c) = &quot;wife&quot;,
        &quot;wives&quot;,
        IF(
          TEXT(CargoUnit__c) = &quot;wolf&quot;,
          &quot;wolves&quot;,
          LEFT(TEXT(CargoUnit__c), LEN(TEXT(CargoUnit__c)) - 2) &amp; &quot;VES&quot;
        )
      ),
      TEXT(CargoUnit__c) &amp; &quot;S&quot;
    )
  )
)
))))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plural Cargo Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PODAOAsDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>PODAOAsDetailInformation__c</fullName>
    <label>P.O.D(A.O.A)&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/POLAODsDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>POLAODsDetailInformation__c</fullName>
    <label>P.O.L(A.O.D)&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Salesman__c.field-meta.xml
<CustomField>
    <fullName>Salesman__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesman</label>
    <referenceTo>User</referenceTo>
    <relationshipName>F_TMS_S_O1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/TotalAmountofSellingLocal__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountofSellingLocal__c</fullName>
    <label>Total Amount of Selling (Local)</label>
    <summarizedField>FTMSBill__c.TotalAmountofSellingLocal__c</summarizedField>
    <summaryForeignKey>FTMSBill__c.FTMSSO__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/VesselFlight__c.field-meta.xml
<CustomField>
    <fullName>VesselFlight__c</fullName>
    <label>Vessel/Flight</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Voyage__c.field-meta.xml
<CustomField>
    <fullName>Voyage__c</fullName>
    <label>Voyage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch (not used)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ha Noi</fullName>
            </value>
            <value>
                <fullName>Hai Phong</fullName>
            </value>
            <value>
                <fullName>Ho Chi Minh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DebitNoteForCustomerController.cls
public with sharing class DebitNoteForCustomerController {
    public FTMSSO__c shipment {get; set;}

    public CntrinTrans__c Container {get;set;}

    public List<FTMSBill__c> lstBill {get; set;}

    public List<FTMSBill__c> lstBill2 {get; set;}
    
    public FTMSBill__c bill {get; set;}

    public FTMSBill__c billOut {get; set;}

    public Contact contact {get; set;}

    public CompanyInformation__c Company {get; set;}

    public String selectedCustomerId {get; set;}

    public String customerValue {get; set;}

    public String InvoiceValue {get; set;}

    private String shipId {get; set;}

    public String branchCompany {get; set;}

    public Decimal AmountSellingFCY {get; set;}
    
    public Decimal AmountSellinglocal {get; set;}

    public Decimal AmountSellingInclFCY {get; set;}

    public Decimal AmountSellingInclLocal {get; set;}

    public Decimal AmountTaxSellingFCY {get; set;}

    public Decimal AmountTaxSellingLocal {get; set;}

    public String readTotalAmountVND {get; set;}

    public String outboundVATInvNo {get;set;}

    public String UserName {get;set;}

    public Decimal GrandTotalFCY {get;set;}

    public Decimal GrandTotalLocal {get;set;}

    public Decimal TotalExVATlocal {get;set;}

    public Decimal TotalExVATfcy {get;set;}

    public Decimal VATlocal {get;set;}

    public Decimal VATfcy {get;set;}

    public Decimal TotalAmount {get;set;}

    public String ankenIds {get; set;}

    public Date today {get; set;}

    public static List<String> lstAnken = new List<String>();

    private static Set<String> fieldsShipQuery = new Set<String>();

    static{
        fieldsShipQuery.add('JobRequestID__c');
        fieldsShipQuery.add('Salesman__r.Name');
        fieldsShipQuery.add('Date_of_issue__c');
        fieldsShipQuery.add('ETD__c');
        fieldsShipQuery.add('HBLNumber__c');
        fieldsShipQuery.add('Branch__c');
        fieldsShipQuery.add('VesselFlight__c');
        fieldsShipQuery.add('Voyage__c');
        fieldsShipQuery.add('ETA__c');
        fieldsShipQuery.add('Placeofdelivery__r.Name');
        fieldsShipQuery.add('Placeofreceipt__r.Name');
        fieldsShipQuery.add('HBLNumber__c');
        fieldsShipQuery.add('HAWBNumber__c');
        fieldsShipQuery.add('MBLNumber__c');
        fieldsShipQuery.add('MAWBNumber__c');
        fieldsShipQuery.add('GrossWeight__c');
        fieldsShipQuery.add('MeasurementTotalCBM__c');
        fieldsShipQuery.add('CargoQuantity__c');
        fieldsShipQuery.add('Plural_Cargo_Unit__c');
        fieldsShipQuery.add('Branch__c');   
        fieldsShipQuery.add('RecordType.Name');
        fieldsShipQuery.add('Agent__c');
        fieldsShipQuery.add('Agent2nd__c');
        fieldsShipQuery.add('POLAODsDetailInformation__c'); 
        fieldsShipQuery.add('PODAOAsDetailInformation__c'); 
    }
    private static Set<String> fieldsBillQuery = new Set<String>();
    static{
        fieldsBillQuery.add('BillNameatPrintENG__c');
        fieldsBillQuery.add('ChargeQuantity__c	');
        fieldsBillQuery.add('UnitPriceFCY__c');
        fieldsBillQuery.add('UnitPriceofSellingLocal__c');
        fieldsBillQuery.add('TotalAmountofSellingFCY__c');
        fieldsBillQuery.add('TotalAmountofSellingLocal__c');
        fieldsBillQuery.add('TaxRateSelling__c');
        fieldsBillQuery.add('TotalSellingInclTaxFCY__c');
        fieldsBillQuery.add('TotalSellingInclTaxLocal__c');
        fieldsBillQuery.add('ExchangeRateSelling__c');
        fieldsBillQuery.add('AmountTaxSellingFCY__c');
        fieldsBillQuery.add('AmountTaxSellingLocal__c');
        fieldsBillQuery.add('InvoiceTo__r.Name');
        fieldsBillQuery.add('InvoiceTo__r.EnglishAddress__c');
        fieldsBillQuery.add('CurrencySelling__c');
        fieldsBillQuery.add('ChargeUnit__c');
        fieldsBillQuery.add('OutboundVATInvNo__c');
        fieldsBillQuery.add('CreditNofromAgent__c');
        fieldsBillQuery.add('InboundVATINVNo__c');
        fieldsBillQuery.add('InvNoonCreditfromCompany__c');
        fieldsBillQuery.add('ContainerType__c');
        fieldsBillQuery.add('MMYY_Debit__c');
        fieldsBillQuery.add('Debit_check__c');
    }
    private static Set<String> fieldsCompanyQuery = new Set<String>();
    static{
        fieldsCompanyQuery.add('Name');
        fieldsCompanyQuery.add('Address__c');
        fieldsCompanyQuery.add('Tel__c');
        fieldsCompanyQuery.add('Fax__c');
        fieldsCompanyQuery.add('CompanyLogo__c');
        fieldsCompanyQuery.add('Email__c');
        fieldsCompanyQuery.add('Website__c');
    }

    private static Set<String> fieldsContainerQuery = new Set<String>();
    static{
        fieldsContainerQuery.add('Container_Number__c');
        fieldsContainerQuery.add('Seal_Number__c');
        fieldsContainerQuery.add('Container_Type__c');
        // fieldsContainerQuery.add('Fax__c');
    }
    public DebitNoteForCustomerController() {
        shipId = ApexPages.currentPage().getParameters().get('Id');
        customerValue = ApexPages.currentPage().getParameters().get('customerValue');
        InvoiceValue = ApexPages.currentPage().getParameters().get('Invoice');
        ankenIds = ApexPages.currentPage().getParameters().get('BillId');
        String Draft = ApexPages.currentPage().getParameters().get('Draft');
        String Official = ApexPages.currentPage().getParameters().get('Official');
        System.debug('Official :'+Official);
        if(!String.isBlank(ankenIds)){
            lstAnken = ankenIds.split(',');
        }
        AmountSellingFCY = 0;
        AmountSellinglocal = 0;
        AmountSellingInclFCY = 0;
        AmountSellingInclLocal = 0;
        AmountTaxSellingFCY = 0;
        AmountTaxSellingLocal = 0;
        GrandTotalFCY = 0;
        GrandTotalLocal = 0;
        TotalExVATfcy = 0;
        TotalExVATlocal = 0;
        VATfcy = 0;
        VATlocal = 0;
        TotalAmount = 0;
        readTotalAmountVND = '';
        branchCompany = '';
        outboundVATInvNo = '';
        today = Date.today();
        System.debug('customerValue123 :'+customerValue);
        shipment = getShipment(shipId);
        System.debug('1423:'+shipment.RecordType.Name);
        Container = getContainer(shipId);
        lstBill = getListBill(shipId,customerValue,InvoiceValue);
        lstBill2 = getListBill2(shipId,customerValue);
        bill = getBill(shipId,customerValue);
        billOut = getBillOut(shipId,customerValue);
        contact = getContact(customerValue);
        branchCompany = shipment.Branch__c;
        Company = getListCompany(branchCompany);
        System.debug('lstCompany :'+Company);
        
        System.debug('lstBill :'+lstBill);

        for(FTMSBill__c bill : lstBill){
            TotalExVATfcy += bill.TotalAmountofSellingFCY__c;
            TotalExVATlocal += bill.TotalAmountofSellingLocal__c;
            VATfcy += bill.AmountTaxSellingFCY__c;
            VATlocal += bill.AmountTaxSellingLocal__c;
            // AmountSellingFCY += bill.TotalAmountofSellingFCY__c;
            // AmountSellinglocal += bill.TotalAmountofSellingLocal__c;
            // AmountSellingInclFCY += bill.TotalSellingInclTaxFCY__c;
            // AmountSellingInclLocal += bill.TotalSellingInclTaxLocal__c;
            // AmountTaxSellingFCY += bill.AmountTaxSellingFCY__c;
            // AmountTaxSellingLocal += bill.AmountTaxSellingLocal__c;
            if(InvoiceValue != null && InvoiceValue != ''){
                outboundVATInvNo = bill.OutboundVATInvNo__c;
            }
        }
        for(FTMSBill__c bill2 : lstBill2){
            AmountSellingInclLocal += bill2.TotalSellingInclTaxLocal__c;
        }

        GrandTotalFCY = TotalExVATfcy + VATfcy;
        GrandTotalLocal = TotalExVATlocal + VATlocal;
        TotalAmount = AmountSellingInclLocal + GrandTotalLocal;
        readTotalAmountVND = EnglishNumberToWords.convert(TotalAmount.setScale(2));
        UserName = UserInfo.getName();

        // if( Draft == 'true' || Official == 'true'){

            // String shipID = ApexPages.currentPage().getParameters().get('id');
            // String billIds = ApexPages.currentPage().getParameters().get('strAkens');
            // System.debug('111'+billIds);
            // // String customerValue = ApexPages.currentPage().getParameters().get('customerValue');
            // System.debug('customerValue :'+customerValue);
            // String official = ApexPages.currentPage().getParameters().get('checkOfficial');
            // System.debug('121: '+official);
            List<String> lstBillIds = new List<String>();
            if(!String.isBlank(ankenIds)){
                lstBillIds = ankenIds.split(',');         
            }
            String strSelect = 'SELECT ' + String.join(new List<String>(fieldsBillQuery), ',');
            String strFrom = ' FROM FTMSBill__c ';
            String strWhere = 'WHERE FTMSSO__c = \'' + shipId + '\'' +  ' AND Id IN : lstBillIds';
            String strOrderBy = ' ORDER BY Name';
            String query = strSelect + strFrom + strWhere +strOrderBy;  
    
            String strSelect1 = 'SELECT ' + String.join(new List<String>(fieldsBillQuery), ',');
            String strFrom1 = ' FROM FTMSBill__c ';
            // String strWhere = 'WHERE FTMSSO__c = \'' + shipmentId + '\'' +  ' AND Id IN : lstBillIds';
            String strOrderBy1 = ' ORDER BY Name';
            String query1 = strSelect1 + strFrom1 +strOrderBy1; 
    
            //List<FTMSBill__c> lstBill = Database.query(query);
            List<FTMSBill__c> lstBill1 = Database.query(query1);
            List<String> numberPoint = new List<String>();
            String months = String.valueOf(today.month());
            if(Integer.valueOf(today.month()) < 10){
                months = '0' + months;
            }
            String yearMonth = String.valueOf(today.year()).substring(2) + months;
            System.debug('26: ' + yearMonth);
            for(FTMSBill__c bill1 : lstBill1){
                System.debug('27: ' + bill1.MMYY_Debit__c);
                if(bill1.OutboundVATInvNo__c != null && bill1.MMYY_Debit__c == yearMonth){
                    String endPoint = bill1.Debit_check__c;
                    System.debug('333c :'+endPoint);
                    numberPoint.add(endPoint);
                }    
            }
            System.debug('444d :'+numberPoint); 
            Integer max = 0;
            for(Integer i = 0; i < numberPoint.size(); i++){
                // max = Integer.valueOf(numberPoint[0]);
                if(Integer.valueOf(numberPoint[i]) > max){
                    max = Integer.valueOf(numberPoint[i]);
                }
            }
            System.debug('555b :'+max);
            String First = '';
            System.debug('42:' + lstBill.size());
            for(FTMSBill__c bill : lstBill){
                System.debug('666b :'+max);
                if(bill.InvoiceTo__c == shipment.Agent__c || bill.InvoiceTo__c == shipment.Agent2nd__c){
                    First = '-DN-';
                }
                else{
                    First = '-LDN-';
                }
                if(Integer.valueOf(today.month()) < 10){
                    months = '0' + months;
                }
                if(bill.OutboundVATInvNo__c == null){
                    if(max <10){
                        outboundVATInvNo = 'ASAP' + First + yearMonth +'-'+ '00' +(max+1);
                        bill.OutboundInvDate__c = today;
                    }
                    else if(max >= 10 && max < 100){
                        outboundVATInvNo = 'ASAP' + First + yearMonth +'-'+ '0' +(max+1);
                        bill.OutboundInvDate__c = today;
                    }
                    else {
                        outboundVATInvNo = 'ASAP' + First + yearMonth + '-' +(max+1);
                        bill.OutboundInvDate__c = today;
                    }
                    // bill.OutboundVATInvNo__c = 'ASAP' + First + yearMonth +'-'+ + '0'+ (max+1);
                    // bill.OutboundInvDate__c = today;
                }
            }
            // outboundVATInvNo = billOut.OutboundVATInvNo__c;
        // }
        System.debug('outboundVATInvNo :' + outboundVATInvNo);
    }
    private FTMSSO__c getShipment(String shipId){
        String strSelect = String.join(new List<String>(fieldsShipQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM FTMSSO__c'
                    + ' WHERE Id = \'' + String.escapeSingleQuotes(shipId) + '\'';
        FTMSSO__c ship;
        try{
            ship = Database.query(strQuery);
        } catch(QueryException e){
            ship = new FTMSSO__c();
        }
        return ship;
    }

    private CntrinTrans__c getContainer(String shipId){
        String strSelect = String.join(new List<String>(fieldsContainerQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM CntrinTrans__c'
                    + ' WHERE F_TMS_S_O__c = \'' + String.escapeSingleQuotes(shipId) + '\'';
        CntrinTrans__c con;
        try{
            con = Database.query(strQuery);
        } catch(QueryException e){
            con = new CntrinTrans__c();
        }
        return con;
    }
    private List<FTMSBill__c> getListBill(String shipId, String cusId, String InvoiceValue){
        String strSelect = String.join(new List<String>(fieldsBillQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM FTMSBill__c'
                    + ' WHERE FTMSSO__c = \'' + String.escapeSingleQuotes(shipId) + '\' AND InvoiceTo__c = \''+ String.escapeSingleQuotes(cusId) + '\' AND AdvancePaymentonbehalfofCustomer__c = false';
        String strWhere = '';
        if(lstAnken.size() > 0){
            strWhere += ' AND Id IN : lstAnken';
         } 
         else{
            strWhere += ' AND OutboundVATInvNo__c = \'' + String.escapeSingleQuotes(InvoiceValue) + '\'';
         }
        strQuery += strWhere;
        strQuery += ' ORDER BY Name ASC';
        List<FTMSBill__c> lstBill;
        try{
            lstBill = Database.query(strQuery);
        } catch(QueryException e){
            lstBill = new List<FTMSBill__c>();
        }
        System.debug('1132:' + strQuery);
        return lstBill;
    }

    private List<FTMSBill__c> getListBill2(String shipId, String cusId){
        String strSelect = String.join(new List<String>(fieldsBillQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM FTMSBill__c'
                    + ' WHERE FTMSSO__c = \'' + String.escapeSingleQuotes(shipId) + '\' AND InvoiceTo__c = \''+ String.escapeSingleQuotes(cusId) + '\' AND AdvancePaymentonbehalfofCustomer__c = true';
        String strWhere = '';
        if(lstAnken.size() > 0){
            strWhere += ' AND Id IN : lstAnken';
         } 
         else{
            strWhere += ' AND OutboundVATInvNo__c = \'' + String.escapeSingleQuotes(InvoiceValue) + '\'';
         }
        strQuery += strWhere;
        strQuery += ' ORDER BY Name ASC';
        List<FTMSBill__c> lstBill2;
        try{
            lstBill2 = Database.query(strQuery);
        } catch(QueryException e){
            lstBill2 = new List<FTMSBill__c>();
        }
        // System.debug('1132:' + strQuery);
        return lstBill2;
    }
    private FTMSBill__c getBill(String shipId, String cusId){
        String strSelect = String.join(new List<String>(fieldsBillQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM FTMSBill__c'
                    + ' WHERE FTMSSO__c = \'' + String.escapeSingleQuotes(shipId) + '\' AND InvoiceTo__c = \''+ String.escapeSingleQuotes(cusId) + '\'';
        strQuery += ' ORDER BY Name LIMIT 1';
        FTMSBill__c Bill;
        try{
            Bill = Database.query(strQuery);
        } catch(QueryException e){
            Bill = new FTMSBill__c();
        }
        return Bill;
    }

    private Contact getContact(String customerValue){
        // String strSelect = String.join(new List<String>(fieldsBillQuery), ',');
        String strQuery = 'SELECT Name'
                    + ' FROM Contact'
                    + ' WHERE AccountId = \'' + String.escapeSingleQuotes(customerValue) + '\'';
        strQuery += ' ORDER BY Name LIMIT 1';
        Contact cont;
        try{
            cont = Database.query(strQuery);
        } catch(QueryException e){
            cont = new Contact();
        }
        return cont;
    }

    private CompanyInformation__c getListCompany(String branchCompany){
        String strSelect = String.join(new List<String>(fieldsCompanyQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM CompanyInformation__c'
                    + ' WHERE Branch__c = \'' + String.escapeSingleQuotes(branchCompany) + '\'';
        strQuery += ' ORDER BY Name LIMIT 1';
        CompanyInformation__c lstCompany;
        try{
            lstCompany = Database.query(strQuery);
        } catch(QueryException e){
            lstCompany = new CompanyInformation__c();
        }
        return lstCompany;
    }

    private FTMSBill__c getBillOut(String shipId, String cusId){
        String strSelect = String.join(new List<String>(fieldsBillQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM FTMSBill__c'
                    + ' WHERE FTMSSO__c = \'' + String.escapeSingleQuotes(shipId) + '\' AND InvoiceTo__c = \''+ String.escapeSingleQuotes(cusId) + '\'';
        strQuery += ' ORDER BY OutboundVATInvNo__c DESC LIMIT 1';
        FTMSBill__c Bill;
        try{
            Bill = Database.query(strQuery);
        } catch(QueryException e){
            Bill = new FTMSBill__c();
        }
        return Bill;
    }
}