force-app/main/default/objects/Account/fields/TaxCode__c.field-meta.xml
<CustomField>
    <fullName>TaxCode__c</fullName>
    <label>Tax Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/CompanyInformation__c.object-meta.xml
<CustomObject>
    <label>Company Information</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CompanyInformation__c/fields/Branch1__c.field-meta.xml
<CustomField>
    <fullName>Branch1__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Branch</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/fields/ShowAddressonHeader__c.field-meta.xml
<CustomField>
    <fullName>ShowAddressonHeader__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Address on Header</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/fields/TaxCode__c.field-meta.xml
<CustomField>
    <fullName>TaxCode__c</fullName>
    <label>Tax Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/fields/Tel__c.field-meta.xml
<CustomField>
    <fullName>Tel__c</fullName>
    <label>Tel</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/FTMSSO__c.object-meta.xml
<CustomObject>
    <label>Shipment.</label>
    <nameField>
        <displayFormat>FSO-{000000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments.</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSSO__c/fields/Branch1__c.field-meta.xml
<CustomField>
    <fullName>Branch1__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Branch</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoClosingTime__c.field-meta.xml
<CustomField>
    <fullName>CargoClosingTime__c</fullName>
    <label>Cargo Closing Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Consignee__c.field-meta.xml
<CustomField>
    <fullName>Consignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consignee</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>F_TMS_S_O2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/FinalDestination__c.field-meta.xml
<CustomField>
    <fullName>FinalDestination__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Final Destination</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/FlightDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>FlightDetailInformation__c</fullName>
    <formula>POLAOD__r.Standard_Port_Code__c &amp;&quot; - &quot;&amp; PODAOA__r.Standard_Port_Code__c &amp;&quot; / &quot;&amp; VesselFlight__c &amp;&quot; / &quot;&amp; text(ETD__c)
&amp;BR()&amp; 
PODAOA__r.Standard_Port_Code__c &amp;&quot; - &quot;&amp; PODAOA2nd__r.Standard_Port_Code__c &amp;&quot; / &quot;&amp; VesselFlight2nd__c &amp;&quot; / &quot;&amp;  text(ETD2nd__c)  
&amp;BR()&amp; 
PODAOA2nd__r.Standard_Port_Code__c &amp;&quot; - &quot;&amp; PODAOA3rd__r.Standard_Port_Code__c &amp;&quot; / &quot;&amp; VesselFlight3rd__c &amp;&quot; / &quot;&amp;  text(ETD3rd__c)</formula>
    <label>Flight Detail Information</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>Gross Weight</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MeasurementTotalCBM__c.field-meta.xml
<CustomField>
    <fullName>MeasurementTotalCBM__c</fullName>
    <label>Measurement (Total CBM)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PlaceofDelivery__c.field-meta.xml
<CustomField>
    <fullName>PlaceofDelivery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place of Delivery</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PlaceofReceipt__c.field-meta.xml
<CustomField>
    <fullName>PlaceofReceipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place of Receipt</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PlaceofStuffing__c.field-meta.xml
<CustomField>
    <fullName>PlaceofStuffing__c</fullName>
    <label>Place of Stuffing</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ShipperDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>ShipperDetailInformation__c</fullName>
    <label>Shipper’s Detail Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Terminal__c.field-meta.xml
<CustomField>
    <fullName>Terminal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Terminal</label>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PortCode__c/PortCode__c.object-meta.xml
<CustomObject>
    <label>Port Code</label>
    <nameField>
        <label>Port Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Port Code</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PortCode__c/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <formula>Country__r.CountryCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortCode__c/fields/Standard_Port_Code__c.field-meta.xml
<CustomField>
    <fullName>Standard_Port_Code__c</fullName>
    <label>Standard Port Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Branch.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cambodia</fullName>
    </customValue>
    <customValue>
        <fullName>Hải Phòng</fullName>
    </customValue>
    <customValue>
        <fullName>Hồ Chí Minh</fullName>
        <default>true</default>
        <label>Hồ Chí Minh</label>
    </customValue>
    <customValue>
        <fullName>Đà Nẵng</fullName>
    </customValue>
    <customValue>
        <fullName>Taiwan</fullName>
    </customValue>
    <masterLabel>Branch</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PrintBK.cls
public with sharing class PrintBK{
    public FTMSSO__c shipment {get;set;}
    public CompanyInformation__c companyInfor {get; set;}
    private String shipId {get; set;}
    public String bookingNo {get; set;}
    public Date currentDate  {get; set;}
   	public String formattedDate {get; set;}
    public Date dateToFormat {get; set;}
    public String formattedDateTable {get; set;}
    public String formattedTimeTable {get; set;}
    public Date originalDate  {get; set;}
    public Time originalTime  {get; set;}
    public String closingTime  {get; set;}
    public String terminal  {get; set;}
    public String html {get; set;}
    private static Set<String> fieldsComInfoQuery = new Set<String>();
    static{
        fieldsComInfoQuery.add('Name');
        fieldsComInfoQuery.add('Address__c');
        fieldsComInfoQuery.add('Branch1__c');
        fieldsComInfoQuery.add('Fax__c');
        fieldsComInfoQuery.add('Tel__c');
        fieldsComInfoQuery.add('TaxCode__c');
        fieldsComInfoQuery.add('Website__c');
        fieldsComInfoQuery.add('ShowAddressonHeader__c');
    }

    private static Set<String> fieldsFTMSQuery = new Set<String>();
    static{
      
        fieldsFTMSQuery.add('FlightDetailInformation__c');
        fieldsFTMSQuery.add('Consignee__r.name');
        fieldsFTMSQuery.add('ShipperDetailInformation__c');
        fieldsFTMSQuery.add('PlaceofReceipt__r.Name');
        fieldsFTMSQuery.add('PlaceofDelivery__r.Name');
        fieldsFTMSQuery.add('PlaceofStuffing__c');
        fieldsFTMSQuery.add('CargoClosingTime__c');
     
       
        fieldsFTMSQuery.add('MeasurementTotalCBM__c');
        fieldsFTMSQuery.add('PlaceofReceipt__r.Standard_Port_Code__c');
        fieldsFTMSQuery.add('FinalDestination__r.Standard_Port_Code__c');

       
       

        fieldsFTMSQuery.add('GrossWeight__c');
        fieldsFTMSQuery.add('MeasurementTotalCBM__c');

        fieldsFTMSQuery.add('Dimension__c');
        
        fieldsFTMSQuery.add('Terminal__r.Name');
        fieldsFTMSQuery.add('Terminal__r.CountryCode__c');
 
        
       
        
    }

    public PrintBK(){
        FormatDate formatDate = new FormatDate();
        companyInfor = new CompanyInformation__c();
        companyInfor = getComInfor();
        
        shipId = ApexPages.currentPage().getParameters().get('Id');
        shipment = getShipment(shipId);
        
        formattedDate = formatDate.FormatDate(Date.today());
        if (shipment.CargoClosingTime__c != null) {
            originalDate = shipment.CargoClosingTime__c.date();
            originalTime = shipment.CargoClosingTime__c.time();
            formattedDateTable = formatDate.FormatDate(originalDate);
            formattedTimeTable = formateTime(originalTime);
            closingTime = formattedDateTable +' - ' + formattedTimeTable;
        }
        if(shipment.Terminal__r.Name != null || shipment.Terminal__r.CountryCode__c != null)
            terminal = shipment.Terminal__r.Name + ' / ' + shipment.Terminal__r.CountryCode__c;
        html = getGeneratedHTMLPage();
        
    }
    private String formateTime(Time inputTime){
        Integer hours = inputTime.hour();
        Integer minutes = inputTime.minute();
        
        String formattedTime = hours.format() + ':' + minutes.format().leftPad(2, '0');
        
        return formattedTime;
    }
    
    
    
    private CompanyInformation__c getComInfor (){
        CompanyInformation__c infor = new CompanyInformation__c();
        String strSelect = String.join(new List<String>(fieldsComInfoQuery), ','); 
        String strQuery = 'SELECT ' + strSelect +
                  ' FROM CompanyInformation__c' +
                  ' WHERE Branch1__c = \'Hồ Chí Minh\'' ;
        try{
            infor = Database.query(strQuery);
        } catch(QueryException e){
            infor = new CompanyInformation__c();
        }
        return infor;
    }

    private FTMSSO__c getShipment(String shipId){
      
      
        String strSelect = String.join(new List<String>(fieldsFTMSQuery), ','); 
        String strQuery  =  'SELECT ' + strSelect 
                            + ' FROM FTMSSO__c '
                            + ' WHERE Id = \'' + String.escapeSingleQuotes(shipId) + '\'';
         System.debug('queryShip: '+strQuery);
         FTMSSO__c shipment;
        try{
            shipment = Database.query(strQuery); 
        } catch(QueryException e){
            shipment = new FTMSSO__c();
        }
   
        System.debug('bac: ' + shipment.FlightDetailInformation__c);
        return shipment;
    }
    private String getGeneratedHTMLPage() {
        String html = '<html>';
        html += '<head>';
        html += '<title>Trang HTML trong Apex Class</title>';
        html += '</head>';
        html += '<body>';
        html += '<div id="content-company">';
        html += '<div>';
        html += '<strong style="border-bottom:1px solid black">FROM:</strong>&nbsp;';
        html += '<strong>TIMES CARGO LOGISTIC CO., LTD</strong>';
        html += '</div>';
        html += '<div>';
        html += '<strong style="border-bottom:1px solid black">TO:</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
        html += '<strong>VUONG QUOC SO JSC (VN HUB)</strong>';
        html += '</div>';
        html += '<div>';
        html += '<strong style="border-bottom:1px solid black">ATTN:</strong>&nbsp;';
        html += '<strong> MS. PHUONG – 090.886.5470</strong>';
        html += '</div>';
        html += '<div style="margin-left: 400px;">';
        html += '<strong>Date: </strong>';
        html += '<strong>' + formattedDate + '</strong>';
        html += '</div>';
        html += '</div>';
        html += '</html>';

       
        return html;
    }
   
    
    

}