force-app/main/default/objects/Punch_In_Out__c/Punch_In_Out__c.object-meta.xml
<CustomObject>
    <label>Punch In/Out</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Punch In/Out ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Punch In/Out</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Punch_In_Out__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Raw data</fullName>
            </value>
            <value>
                <fullName>In</fullName>
            </value>
            <value>
                <fullName>Out</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GoogleMapPunchController.cls
public with sharing class GoogleMapPunchController {

    public Punch_In_Out__c event{get; set;}

    public String id {get;set;}

    private static Set<String> setFields = new Set<String>();

    static{
        setFields.add('Latitude__c');
        setFields.add('Longitude__c');
        setFields.add('Type__c');
    }

    public GoogleMapPunchController() {
        id = ApexPages.currentPage().getParameters().get('id');
        
        event = Database.query(queryEvent(id));
        System.debug('checkin: ');
    }

    private String queryEvent(String id){
        String strSelect = 'SELECT ' + String.join(new List<String>(setFields), ',');
        String strFrom = ' FROM Punch_In_Out__c ';
        String strWhere = ' WHERE Id = \'' + id+'\'';
        return strSelect + strFrom + strWhere;
    }

    @AuraEnabled
    public static void savePosition(String recordId, String latitude, String longitude){
        Punch_In_Out__c model = [SELECT Id, 
            Latitude__c, 
            Longitude__c,
            Type__c
            FROM Punch_In_Out__c WHERE Id = :recordId];
        model.Latitude__c = latitude;
        model.Longitude__c = longitude;
        
        update model;
    }
}