force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>QT-{00000}</displayFormat>
        <label>Quote ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/QuoteName__c.field-meta.xml
<CustomField>
    <fullName>QuoteName__c</fullName>
    <label>Quote Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/QuotePIC__c.field-meta.xml
<CustomField>
    <fullName>QuotePIC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote PIC</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/RequesterCompany__c.field-meta.xml
<CustomField>
    <fullName>RequesterCompany__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requester Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Validto__c.field-meta.xml
<CustomField>
    <fullName>Validto__c</fullName>
    <label>Valid to</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quoteline__c/Quoteline__c.object-meta.xml
<CustomObject>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000}</displayFormat>
        <label>Quoteline ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quoteline__c/fields/QuoteID__c.field-meta.xml
<CustomField>
    <fullName>QuoteID__c</fullName>
    <label>Quote ID</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote lines</relationshipLabel>
    <relationshipName>Quote_lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AddMultipleQuoteLineControllerTest.cls
@isTest
public class AddMultipleQuoteLineControllerTest {
  	@isTest
    public Static void TestCase1(){
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        
     	User usr = new User(LastName = 'LIVESTON',
                           FirstName='JASON',
                           Alias = 'jliv',
                           Email = 'jason.liveston@asdf.com',
                           Username = 'jas2on.liveston@asdf.com',
                           ProfileId = profileId.id,
                           TimeZoneSidKey = 'GMT',
                           LanguageLocaleKey = 'en_US',
                           EmailEncodingKey = 'UTF-8',
                           LocaleSidKey = 'en_US'
                           );
        insert usr;
        
        Account act= new Account(
                Name='account');
        insert act;
        
        Quote__c qt= new Quote__c(
            QuoteName__c = 'Qt1',
            Validto__c= Date.newInstance(2023, 11, 11),
            QuotePIC__c= usr.Id,
            RequesterCompany__c= act.Id
        );
        insert qt;
        
        Quote__c qt2= new Quote__c(
            QuoteName__c = 'Qt2',
            Validto__c= Date.newInstance(2023, 11, 11),
            QuotePIC__c= usr.Id,
            RequesterCompany__c= act.Id
        );
        insert qt2;
        
        list<Quoteline__c> lineList= new List<Quoteline__c>();
        Quoteline__c qtline= new Quoteline__c(
        QuoteID__c =qt.Id
        );
        lineList.add(qtline);
        
      //  insert lineList;
        Test.startTest();
        AddMultipleQuoteLineController AMQC = new AddMultipleQuoteLineController();
        String rs = AddMultipleQuoteLineController.saveQuoteLineList(lineList, qt2.Id);
        System.assertEquals(true, true);
        Test.stopTest();
        
    }
}