force-app/main/default/objects/FTMSSO__c/FTMSSO__c.object-meta.xml
<CustomObject>
    <label>Shipment.</label>
    <nameField>
        <displayFormat>FSO-{000000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments.</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSSO__c/fields/AgentDetailInformation_text__c.field-meta.xml
<CustomField>
    <fullName>AgentDetailInformation_text__c</fullName>
    <label>Agent&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoQuantity__c.field-meta.xml
<CustomField>
    <fullName>CargoQuantity__c</fullName>
    <label>Cargo Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ChargeableWeight__c.field-meta.xml
<CustomField>
    <fullName>ChargeableWeight__c</fullName>
    <label>Chargeable Weight</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Consignee__c.field-meta.xml
<CustomField>
    <fullName>Consignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consignee</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>F_TMS_S_O2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ConsigneeDetailInformation1__c.field-meta.xml
<CustomField>
    <fullName>ConsigneeDetailInformation1__c</fullName>
    <formula>IF(NOT(ISBLANK( Consignee__r.AccountNameENG__c )), Consignee__r.AccountNameENG__c , NULL) + &quot; &quot; + BR()&amp;
IF(NOT(ISBLANK(Consignee__r.BillingStreet)), Consignee__r.BillingStreet , NULL) + &quot; &quot; +
IF(NOT(ISBLANK(Consignee__r.BillingCity)), Consignee__r.BillingCity , NULL) + &quot; &quot; +
IF(NOT(ISBLANK(Consignee__r.BillingState)), Consignee__r.BillingState, NULL) + &quot; &quot; +
IF(NOT(ISBLANK(Consignee__r.BillingPostalCode)), &quot;, &quot; + Consignee__r.BillingPostalCode , NULL) + &quot; &quot; +
IF(NOT(ISBLANK(Consignee__r.BillingCountry)), Consignee__r.BillingCountry, NULL) + &quot; &quot; + BR()&amp;
IF(NOT(ISBLANK(Consignee__r.Phone)), &quot; &quot; + &quot;TEL:&quot; +&quot; &quot;+ Consignee__r.Phone, NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Consignee&apos;s Detail Information1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ConsigneeDetailInformation_text__c.field-meta.xml
<CustomField>
    <fullName>ConsigneeDetailInformation_text__c</fullName>
    <label>Consignee&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CWDimension__c.field-meta.xml
<CustomField>
    <fullName>CWDimension__c</fullName>
    <label>C.W(Dimension)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/DateofHouseBLIssued__c.field-meta.xml
<CustomField>
    <fullName>DateofHouseBLIssued__c</fullName>
    <label>Date of House B/L Issued</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/DeliveryAgentInfoonBL__c.field-meta.xml
<CustomField>
    <fullName>DeliveryAgentInfoonBL__c</fullName>
    <label>Delivery Agent Info on BL</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/DimensionDetail__c.field-meta.xml
<CustomField>
    <fullName>DimensionDetail__c</fullName>
    <label>Dimension Detail</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ETAAtTransitPort__c.field-meta.xml
<CustomField>
    <fullName>ETAAtTransitPort__c</fullName>
    <label>ETA At Transit Port</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ETD2nd__c.field-meta.xml
<CustomField>
    <fullName>ETD2nd__c</fullName>
    <label>ETD (2nd)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ETD3rd__c.field-meta.xml
<CustomField>
    <fullName>ETD3rd__c</fullName>
    <label>ETD (3rd)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/FinalDestinationsDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>FinalDestinationsDetailInformation__c</fullName>
    <label>Final Destination&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/FlightNumber__c.field-meta.xml
<CustomField>
    <fullName>FlightNumber__c</fullName>
    <label>Flight Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/GoodsAttachment__c.field-meta.xml
<CustomField>
    <fullName>GoodsAttachment__c</fullName>
    <label>Goods Attachment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>Gross Weight</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HAWBNumber__c.field-meta.xml
<CustomField>
    <fullName>HAWBNumber__c</fullName>
    <label>H AWB Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HBLNumber__c.field-meta.xml
<CustomField>
    <fullName>HBLNumber__c</fullName>
    <label>H B/L Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HouseFreightCollectPrepaid__c.field-meta.xml
<CustomField>
    <fullName>HouseFreightCollectPrepaid__c</fullName>
    <label>House Freight Collect/Prepaid</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collected</fullName>
            </value>
            <value>
                <fullName>Prepaid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HouseNotifyDetailInformation_text__c.field-meta.xml
<CustomField>
    <fullName>HouseNotifyDetailInformation_text__c</fullName>
    <label>House Notify&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HouseNotifyParty__c.field-meta.xml
<CustomField>
    <fullName>HouseNotifyParty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>House Notify Party</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>F_TMS_S_O3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNumber__c</fullName>
    <label>Invoice Number on Air Manifest</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MarksAndNumbers__c.field-meta.xml
<CustomField>
    <fullName>MarksAndNumbers__c</fullName>
    <label>Marks And Numbers</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MasterCarrierConsolidator__c.field-meta.xml
<CustomField>
    <fullName>MasterCarrierConsolidator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Carrier/Consolidator</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>F_TMS_S_O7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MAWBNumber__c.field-meta.xml
<CustomField>
    <fullName>MAWBNumber__c</fullName>
    <label>MAWB Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MAWBNumberonAWB__c.field-meta.xml
<CustomField>
    <fullName>MAWBNumberonAWB__c</fullName>
    <formula>IF( LEN( MAWBNumber__c) = 9,LEFT( MAWBNumber__c , 3) +&quot; &quot; + POLAOD__r.Port_Code_Short__c +&quot; &quot;+ RIGHT( MAWBNumber__c , 6),
IF( LEN( MAWBNumber__c) = 10,LEFT( MAWBNumber__c , 3) +&quot; &quot; + POLAOD__r.Port_Code_Short__c +&quot; &quot;+ RIGHT( MAWBNumber__c , 7),
IF( AND(LEN( MAWBNumber__c)= 12, CONTAINS(MAWBNumber__c,&apos;-&apos; )) ,LEFT( MAWBNumber__c , 3) +&quot; &quot; + POLAOD__r.Port_Code_Short__c +&quot; &quot;+ RIGHT( MAWBNumber__c , 8),
LEFT( MAWBNumber__c , 3) +&quot; &quot; + POLAOD__r.Port_Code_Short__c +&quot; &quot;+ RIGHT( MAWBNumber__c , 9))))</formula>
    <label>MAWB Number on AWB</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <label>Measurement</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MeasurementTotalCBM__c.field-meta.xml
<CustomField>
    <fullName>MeasurementTotalCBM__c</fullName>
    <label>Measurement (Total CBM)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PODAOA2nd__c.field-meta.xml
<CustomField>
    <fullName>PODAOA2nd__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.D(A.O.A) (2nd)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PODAOA3rd__c.field-meta.xml
<CustomField>
    <fullName>PODAOA3rd__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.D(A.O.A) (3rd)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PODAOA__c.field-meta.xml
<CustomField>
    <fullName>PODAOA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.D(A.O.A)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PODAOAsDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>PODAOAsDetailInformation__c</fullName>
    <label>P.O.D(A.O.A)&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/POLAODsDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>POLAODsDetailInformation__c</fullName>
    <label>P.O.L(A.O.D)&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PortofDischargeDetailPrint__c.field-meta.xml
<CustomField>
    <fullName>PortofDischargeDetailPrint__c</fullName>
    <formula>&quot;Port&quot;</formula>
    <label>Port of Discharge Detail-Print</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PortofLoadingDetail__c.field-meta.xml
<CustomField>
    <fullName>PortofLoadingDetail__c</fullName>
    <label>Port of Loading Detail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ShipperDetailInformation_text__c.field-meta.xml
<CustomField>
    <fullName>ShipperDetailInformation_text__c</fullName>
    <label>Shipper&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ShippersAddressonBL__c.field-meta.xml
<CustomField>
    <fullName>ShippersAddressonBL__c</fullName>
    <label>Shipper&apos;s Address on BL</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/TransitPort__c.field-meta.xml
<CustomField>
    <fullName>TransitPort__c</fullName>
    <label>Transit Port</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/VesselFlight2nd__c.field-meta.xml
<CustomField>
    <fullName>VesselFlight2nd__c</fullName>
    <label>Vessel/Flight (2nd)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/VesselFlight3rd__c.field-meta.xml
<CustomField>
    <fullName>VesselFlight3rd__c</fullName>
    <label>Vessel/Flight (3rd)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/VesselFlight__c.field-meta.xml
<CustomField>
    <fullName>VesselFlight__c</fullName>
    <label>Vessel/Flight</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortCode__c/PortCode__c.object-meta.xml
<CustomObject>
    <label>Port Code</label>
    <nameField>
        <label>Port Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Port Code</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PortCode__c/fields/Port_Code_Short__c.field-meta.xml
<CustomField>
    <fullName>Port_Code_Short__c</fullName>
    <label>Port Code (Short)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortCode__c/fields/PortCode__c.field-meta.xml
<CustomField>
    <fullName>PortCode__c</fullName>
    <label>Port Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transit__c/Transit__c.object-meta.xml
<CustomObject>
    <label>Transit</label>
    <nameField>
        <displayFormat>TRS-{00000}</displayFormat>
        <label>Transit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transit__c/fields/ETAatTransitPort__c.field-meta.xml
<CustomField>
    <fullName>ETAatTransitPort__c</fullName>
    <label>ETA at Transit Port</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transit__c/fields/TransitVesselFlight__c.field-meta.xml
<CustomField>
    <fullName>TransitVesselFlight__c</fullName>
    <label>Transit Vessel/Flight</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PrintHBLControllerNew.cls
public with sharing class PrintHBLControllerNew {
    public String id {get; set;}
    public String billing {get; set;}
    public String customer {get; set;}
    public String customer1 {get; set;}
    public Boolean isCreateAttachment {get; set;}
    public Boolean isCreateNumber {get;set;}
    public FTMSSO__c shipment {get; set;}
    public FTMSSO__c shipmentnew {get; set;}
    public String notiFy {get; set;}


    public PrintHBLControllerNew() {
        id = ApexPages.currentPage().getParameters().get('id');
        billing = 'hawb';
        customer = ApexPages.currentPage().getParameters().get('customer');
        // isCreateAttachment = ApexPages.currentPage().getParameters().get('isCreateAttachment') == 'true';
        // isCreateNumber = ApexPages.currentPage().getParameters().get('isNumber') == 'true';
        System.debug('id: ' + id + ' isCreateAttachment: ' + isCreateAttachment + ' customer: ' + customer);
        shipment = getData(id);

        if(customer == 'FOR SHIPPER'){
            customer1 = 'ORIGINAL 3' + ' ' + '(' + customer + ')';
        }
        else{

            customer1 = 'ORIGINAL 5' + ' ' + '(' + customer + ')';
        }
        
        if(shipment.MeasurementTotalCBM__c != null){
            shipment.MeasurementTotalCBM__c = shipment.MeasurementTotalCBM__c.setScale(3, RoundingMode.HALF_UP);
        }else {
            shipment.MeasurementTotalCBM__c = 0;
        }
        if(shipment.CWDimension__c != null){
            shipment.CWDimension__c = shipment.CWDimension__c.setScale(3, RoundingMode.HALF_UP);
        }else {
            shipment.CWDimension__c = 0;
        }
        System.debug('shipment: ' + shipment);
        
        Apexpages.currentPage().getHeaders().put('content-disposition', billing == 'hbl' ? 'inline;filename=HBL.pdf' : 'inline; filename=HAWB.pdf');
        notiFy=SetNotify();
    }

    public FTMSSO__c getData(String id){
        List<FTMSSO__c> shipments = [SELECT Id, 
        ShippersAddressonBL__c, 
        ConsigneeDetailInformation1__c,
         DeliveryAgentInfoonBL__c,
         PortofLoadingDetail__c,
         PortofDischargeDetailPrint__c,
         MarksAndNumbers__c,
         DescriptionofGoods__c,
         GrossWeight__c,
         MeasurementTotalCBM__c,
         Measurement__c,
         HouseFreightCollectPrepaid__c,
         GoodsAttachment__c,
         HAWBNumber__c,
         MAWBNumberonAWB__c,
         FlightNumber__c,
         ChargeableWeight__c,
         ETD__c,
         CWDimension__c,
         CargoQuantity__c,
         MasterCarrierConsolidator__c,
         PODAOA__c,
         PODAOA__r.Port_Code_Short__c,
         DimensionDetail__c,
         ShipperDetailInformation_text__c,
         ConsigneeDetailInformation_text__c,
         HouseNotifyDetailInformation_text__c,
         POLAODsDetailInformation__c,
         MAWBNumber__c,
         PODAOA__r.PortCode__c,
         VesselFlight__c,
         PODAOAsDetailInformation__c,
         AgentDetailInformation_text__c,
         InvoiceNumber__c,
         Dimension__c,
         DateofHouseBLIssued__c,
         HBLNumber__c,
         FinalDestinationsDetailInformation__c,
         HouseNotifyParty__c,
         Consignee__c,
         PODAOA2nd__r.PortCode__c,
         PODAOA3rd__r.PortCode__c,
         VesselFlight2nd__c,
         ETD2nd__c,
         ETD3rd__c,
         VesselFlight3rd__c,


         (SELECT TransitVesselFlight__c, ETAatTransitPort__c,
         TransitPort__r.Port_Code_Short__c FROM Transits__r
         WHERE InOrderofTransit__c = 1 LIMIT 1) 
         FROM FTMSSO__c WHERE Id = :id];

        return shipments.size() > 0 ? shipments.get(0) : null;
    }

    @AuraEnabled
    public static Boolean isAutoCheckedCreateAttachment(String id){
        try {
            FTMSSO__c shipment = [SELECT GoodsAttachment__c, TransitPort__c FROM FTMSSO__c WHERE Id = :id];
            return (shipment.GoodsAttachment__c != null || shipment.TransitPort__c != null) ? true : false;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public String SetNotify(){
        if(shipment.HouseNotifyParty__c == shipment.Consignee__c){
            return 'SAME AS CONSIGNEE';
        }else return shipment.HouseNotifyDetailInformation_text__c;
    }
    // public void generateAttachmentFile(){
    //     PageReference pageTo = Page.PrintHBL;
    //     // if(fileType == 'pdf'){
    //     //    pageTo = Page.page_InvoicePrint_V1; 
    //     // }else{ 
    //     //     pageTo = Page.page_InvoicePrintExcel_V1; 
    //     // }
    //     // pageTo.getParameters().put('shipmentId', shipmentId);
    //     // pageTo.getParameters().put('customerId', customerId);
    //     // pageTo.getParameters().put('curr', currencyType);
    //     // pageTo.getParameters().put('companyTo', companyTo);
    //     // pageTo.getParameters().put('bankType', bankType);
    //     // pageTo.getParameters().put('showContainer', 'false');
    //     // pageTo.getParameters().put('templateType', templateType);
        
    //     pageTo.setRedirect(true);
    //     attachName = 'DebitNote v';
    //     String attachNameSearch = attachName + '%';
    //     // get exist file Name
    //     List<Attachment> attachments = [SELECT Id, Name, ParentId 
    //                                     FROM Attachment 
    //                                     WHERE ParentId =: id 
    //                                     AND Name LIKE : attachNameSearch 
    //                                     ORDER BY CreatedDate DESC LIMIT 1];
    //     if(attachments.isEmpty()){
    //         attachName += '1';
    //     }else{
    //         String attachNameExist = attachments[0].Name;
    //         attachNameExist = attachNameExist.substringAfter(attachName);
    //         attachNameExist = attachNameExist.substringBefore('.pdf');
    //         attachNameExist = attachNameExist.substringBefore('.xls');
    //         Decimal versionNumber = Decimal.valueOf(attachNameExist);
    //         versionNumber += 1;
    //         attachName += String.valueOf(versionNumber);
    //     }
    //     if(fileType != 'pdf'){
    //         pageTo.getParameters().put('contentType', 'application/vnd.ms-excel#' + attachName + '.xls'); 
    //     }
    //     System.debug('12345:'+ pageTo);
    //     if(requiredAttachmentCreation ){
 
    //         Attachment attach = new Attachment();
    //         Blob body;
    //         attach.Name = fileType == 'pdf'? attachName + '.pdf' : attachName + '.xls'; 
    //         attach.IsPrivate = false;
    //         attach.ParentId = shipmentId;
    //          if(!Test.isRunningTest()){
    //             System.debug('12345:'+ pageTo);
    //             body = fileType == 'pdf'? pageTo.getContentAsPDF() : pageTo.getContent();
    //             System.debug('12345:'+ body);
    //             attach.Body = body;
    //             FlsService.doInsert(attach);
    //          }
    //     }

    // }
}