force-app/main/default/objects/FTMSSO__c/FTMSSO__c.object-meta.xml
<CustomObject>
    <label>Shipment.</label>
    <nameField>
        <displayFormat>FSO-{000000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments.</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSSO__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch (not used)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ha Noi</fullName>
                <default>true</default>
                <label>Ha Noi</label>
            </value>
            <value>
                <fullName>Hai Phong</fullName>
            </value>
            <value>
                <fullName>Ho Chi Minh</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DebitNoteForCustomerControllerTest.cls
@isTest
public class DebitNoteForCustomerControllerTest {
    public static testMethod void DebitNoteCustomerTest(){
        Test.startTest();
        Date eta = Date.newInstance(2023, 02, 20);
        Date etd = Date.newInstance(2023, 02, 15);
        FTMSSO__c shipment = new FTMSSO__c(Branch__c = 'Ho Chi Minh', ETA__c = eta, ETD__c = etd);
        insert shipment;
        PageReference pageRef = Page.page_DebitNoteForCustomer; // Add your VF page Name here
        pageRef.getParameters().put('shipId', shipment.Id);
        //pageRef.getParameters().put('showInfo', 'true');
        //pageRef.getParameters().put('attachment', 'true');
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('shipId', shipment.Id);
        	DebitNoteForCustomerController DebitNote = new DebitNoteForCustomerController();
        Test.stopTest();
    }
}