force-app/main/default/objects/BankAcc__c/BankAcc__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Bank  Acc ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BankAcc__c/fields/BankAccountNameLocal__c.field-meta.xml
<CustomField>
    <fullName>BankAccountNameLocal__c</fullName>
    <label>Bank Account Name (Local)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BankAcc__c/fields/BankAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>BankAccountNumber__c</fullName>
    <label>Bank Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BankAcc__c/fields/BankAddress__c.field-meta.xml
<CustomField>
    <fullName>BankAddress__c</fullName>
    <label>Bank Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/BankAcc__c/fields/BankBranchName__c.field-meta.xml
<CustomField>
    <fullName>BankBranchName__c</fullName>
    <label>Bank Branch Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BankAcc__c/fields/BankOfficialName__c.field-meta.xml
<CustomField>
    <fullName>BankOfficialName__c</fullName>
    <label>Bank Official Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BankAcc__c/fields/BankShortName__c.field-meta.xml
<CustomField>
    <fullName>BankShortName__c</fullName>
    <label>Bank Short Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BankAcc__c/fields/InternationalBank__c.field-meta.xml
<CustomField>
    <fullName>InternationalBank__c</fullName>
    <defaultValue>false</defaultValue>
    <label>International Bank?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BankAcc__c/fields/SWIFTCode__c.field-meta.xml
<CustomField>
    <fullName>SWIFTCode__c</fullName>
    <label>SWIFT Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/CompanyInformation__c.object-meta.xml
<CustomObject>
    <label>Company Information</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CompanyInformation__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <defaultValue>&apos;TIMES CARGO LOGISTIC CO.,LTD&apos;</defaultValue>
    <label>Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/fields/TaxCode__c.field-meta.xml
<CustomField>
    <fullName>TaxCode__c</fullName>
    <label>Tax Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/fields/Tel__c.field-meta.xml
<CustomField>
    <fullName>Tel__c</fullName>
    <label>Tel</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Ref No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <label>Account Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/BankAccount__c.field-meta.xml
<CustomField>
    <fullName>BankAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account</label>
    <referenceTo>BankAcc__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/CBM__c.field-meta.xml
<CustomField>
    <fullName>CBM__c</fullName>
    <formula>IF(ISBLANK(FTMSSO__c) = FALSE, FTMSSO__r.MeasurementTotalCBM__c,  AdvancedShipment__r.MeasurementCBM__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CBM</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/ContSeal__c.field-meta.xml
<CustomField>
    <fullName>ContSeal__c</fullName>
    <formula>ContainerNoSealNo__c</formula>
    <label>Cont/Seal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Dest__c.field-meta.xml
<CustomField>
    <fullName>Dest__c</fullName>
    <formula>IF(ISBLANK(FTMSSO__c) = FALSE, FTMSSO__r.FinalDestinationsDetailInformation__c,  AdvancedShipment__r.FinalDestination__r.Name )</formula>
    <label>Dest.</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/DocumentsDetails__c.field-meta.xml
<CustomField>
    <fullName>DocumentsDetails__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Documents Details</label>
    <referenceTo>Documentsdetails__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/ETA__c.field-meta.xml
<CustomField>
    <fullName>ETA__c</fullName>
    <formula>FTMSSO__r.ETA__c</formula>
    <label>ETA</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/ETD__c.field-meta.xml
<CustomField>
    <fullName>ETD__c</fullName>
    <formula>FTMSSO__r.ETD__c</formula>
    <label>ETD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/FTMSSO__c.field-meta.xml
<CustomField>
    <fullName>FTMSSO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>F/TMS S/O</label>
    <referenceTo>FTMSSO__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/GW__c.field-meta.xml
<CustomField>
    <fullName>GW__c</fullName>
    <formula>IF(ISBLANK(FTMSSO__c) = FALSE, FTMSSO__r.GrossWeight__c, AdvancedShipment__r.GrossWeight__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>G.W</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/HBLNo__c.field-meta.xml
<CustomField>
    <fullName>HBLNo__c</fullName>
    <formula>if(ISNULL(FTMSSO__r.HBLNumber__c)=true,  FTMSSO__r.HAWBNumber__c, FTMSSO__r.HBLNumber__c)</formula>
    <label>H-B/L No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/JobreferenceNo__c.field-meta.xml
<CustomField>
    <fullName>JobreferenceNo__c</fullName>
    <formula>FTMSSO__r.JobRequestID__c</formula>
    <label>Job reference No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/MBLNo__c.field-meta.xml
<CustomField>
    <fullName>MBLNo__c</fullName>
    <formula>FTMSSO__r.MBLNumber__c</formula>
    <label>M-B/L No.</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <formula>IF(ISBLANK(FTMSSO__c) = FALSE, FTMSSO__r.PlaceofReceiptDetailInformation__c,  AdvancedShipment__r.PlaceofReceipt__r.Name )</formula>
    <label>Origin</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/QtyCTNS__c.field-meta.xml
<CustomField>
    <fullName>QtyCTNS__c</fullName>
    <formula>IF(FTMSSO__r.ContainerQuantity1__c&lt;10,&quot;0&quot;&amp;TEXT(FTMSSO__r.ContainerQuantity1__c)&amp;&quot;X&quot;&amp;TEXT(FTMSSO__r.ContainerType1__c),
    TEXT(FTMSSO__r.ContainerQuantity1__c)&amp;&quot;X&quot;&amp;TEXT(FTMSSO__r.ContainerType1__c))
&amp;&quot;(&quot;
&amp; TEXT(FTMSSO__r.CargoQuantity__c)
&amp;&quot; &quot;
&amp; IF(FTMSSO__r.CargoQuantity__c=1,TEXT(FTMSSO__r.CargoUnit__c),FTMSSO__r.Plural_Cargo_Unit__c)
&amp;&quot;)&quot;</formula>
    <label>Qty/CTNS</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/TaxCode__c.field-meta.xml
<CustomField>
    <fullName>TaxCode__c</fullName>
    <label>Tax Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Tel__c.field-meta.xml
<CustomField>
    <fullName>Tel__c</fullName>
    <label>Tel</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/VesselVoy__c.field-meta.xml
<CustomField>
    <fullName>VesselVoy__c</fullName>
    <formula>FTMSSO__r.VesselFlight__c &amp;&quot; &quot;&amp;FTMSSO__r.Voyage__c</formula>
    <label>Vessel/Voy</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/Documentsdetails__c.object-meta.xml
<CustomObject>
    <label>Documents details</label>
    <nameField>
        <displayFormat>DD-{0000000}</displayFormat>
        <label>Documents details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Documentsdetails__c/fields/ChargeUnit__c.field-meta.xml
<CustomField>
    <fullName>ChargeUnit__c</fullName>
    <formula>text( ConsolBill__r.ChargeUnit__c )</formula>
    <label>Charge Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <referenceTo>Document__c</referenceTo>
    <relationshipLabel>Documents details</relationshipLabel>
    <relationshipName>Documents_details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/FTMSSO__c.field-meta.xml
<CustomField>
    <fullName>FTMSSO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>F/TMS S/O</label>
    <referenceTo>FTMSSO__c</referenceTo>
    <relationshipLabel>Documents details</relationshipLabel>
    <relationshipName>Documents_details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/PricingName__c.field-meta.xml
<CustomField>
    <fullName>PricingName__c</fullName>
    <formula>ConsolBill__r.PricingName__r.Name</formula>
    <label>Pricing Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/PricingNamePrinted__c.field-meta.xml
<CustomField>
    <fullName>PricingNamePrinted__c</fullName>
    <label>Pricing Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <formula>ConsolBill__r.Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/TotalBuyingInclTaxActual__c.field-meta.xml
<CustomField>
    <fullName>TotalBuyingInclTaxActual__c</fullName>
    <label>Total Buying Incl Tax (Actual)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/TotalSellingInclTaxActual__c.field-meta.xml
<CustomField>
    <fullName>TotalSellingInclTaxActual__c</fullName>
    <label>Total Selling Incl Tax (Actual)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/UnitPriceofBuyingActual__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceofBuyingActual__c</fullName>
    <label>Unit Price of Buying (Actual)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/UnitPriceofBuyingFCY__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceofBuyingFCY__c</fullName>
    <formula>ConsolBill__r.UnitPriceofBuyingFCY__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Price of Buying (USD)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/UnitPriceofBuyingLocal__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceofBuyingLocal__c</fullName>
    <formula>ConsolBill__r.UnitPriceofBuyingLocal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Price of Buying (VND)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/UnitPriceofSellingActual__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceofSellingActual__c</fullName>
    <label>Unit Price of Selling (Actual)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Documentsdetails__c/fields/UnitPriceofSellingFCY__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceofSellingFCY__c</fullName>
    <formula>ConsolBill__r.UnitPriceofSellingFCY__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Price of Selling (USD)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/FTMSSO__c.object-meta.xml
<CustomObject>
    <label>Shipment.</label>
    <nameField>
        <displayFormat>FSO-{000000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments.</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSSO__c/fields/Consignee__c.field-meta.xml
<CustomField>
    <fullName>Consignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consignee</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>F_TMS_S_O2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ContSeal__c.field-meta.xml
<CustomField>
    <fullName>ContSeal__c</fullName>
    <label>Cont/Seal</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Shipper__c.field-meta.xml
<CustomField>
    <fullName>Shipper__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipper</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>F_TMS_S_O1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/documentControler.cls
public with sharing class documentControler {
    private static Set<String> SoQuery = new Set<String>();
    private static Set<String> docDetal = new Set<String>();

    private static Set<String> CNTRQuery = new Set<String>();
    public CompanyInformation__c adr1 {get;set;}
    public CompanyInformation__c adr2 {get;set;}
    public CompanyInformation__c adr3 {get;set;}
    public String textTotal { get; set; }
    public String textTotalVN { get; set; }

    public String formName { get; set; }
    

    public Document__c Doc {get;set;}
    public String formattedDateTime { get; set; }
    public String cur { get; set; }

    public Decimal Total { get; set; }
    public Integer TotalVN { get; set; }


    public List<Documentsdetails__c> DocDT {get;set;}


    
    static{
        SoQuery.add('RecordType.name');

        
        SoQuery.add('AccountName__c');
        SoQuery.add('Address__c');
        SoQuery.add('Tel__c');
        SoQuery.add('Fax__c');
        SoQuery.add('TaxCode__c');
        SoQuery.add('Name');
        SoQuery.add('JobreferenceNo__c');
        SoQuery.add('Origin__c');
        SoQuery.add('MBLNo__c');
        SoQuery.add('FTMSSO__r.Shipper__r.Name');
        SoQuery.add('FTMSSO__r.Shipper__r.Company_Address__c');
        SoQuery.add('VesselVoy__c');
        SoQuery.add('QtyCTNS__c');
        SoQuery.add('ETD__c');
        SoQuery.add('ETA__c');
        SoQuery.add('Dest__c');
        SoQuery.add('HBLNo__c');
        SoQuery.add('FTMSSO__r.Consignee__r.Name');
        SoQuery.add('FTMSSO__r.Consignee__r.Company_Address__c');
        SoQuery.add('GW__c');
        SoQuery.add('CBM__c');
        SoQuery.add('ContSeal__c');

        SoQuery.add('BankAccount__r.BankAccountNameLocal__c');
        
        SoQuery.add('BankAccount__r.InternationalBank__c');

        SoQuery.add('BankAccount__r.BankOfficialName__c');
        SoQuery.add('BankAccount__r.BankBranchName__c');
        SoQuery.add('BankAccount__r.BankShortName__c');
        SoQuery.add('BankAccount__r.BankAddress__c');
        SoQuery.add('BankAccount__r.SWIFTCode__c');
        SoQuery.add('BankAccount__r.BankAccountNumber__c');



        docDetal.add('PricingName__c');
        docDetal.add('PricingNamePrinted__c');

        docDetal.add('Quantity__c');


        docDetal.add('TotalBuyingInclTaxActual__c');


        docDetal.add('TotalSellingInclTaxActual__c');

        docDetal.add('UnitPriceofBuyingActual__c');

        docDetal.add('UnitPriceofSellingActual__c');





        docDetal.add('ChargeUnit__c');
        docDetal.add('UnitPriceofBuyingFCY__c');
        docDetal.add('UnitPriceofBuyingLocal__c');
        docDetal.add('UnitPriceofSellingFCY__c');
        docDetal.add('UnitPriceofSellingLocal__c');
        docDetal.add('TaxRatioBuying__c');
        docDetal.add('TaxRatioSelling__c');
        docDetal.add('CurrencyBuying__c');
        docDetal.add('CurrencySelling__c');
        docDetal.add('Total_Selling_Incl_Tax_Local__c');
        docDetal.add('Total_Selling_Incl_Tax_FCY__c');
        docDetal.add('TotalBuyingInclTaxLocal__c');
        docDetal.add('TotalBuyingInclTaxFCY__c');



       
    }


    public documentControler() {
        String DocID = ApexPages.currentPage().getParameters().get('id');
        cur = ApexPages.currentPage().getParameters().get('cur');
        
        //  cur= 'usd';
         Total=0;
         TotalVN=0;
       adr1= getCpn('Hồ Chí Minh');
       adr2= getCpn('Đà Nẵng');
       adr3= getCpn('Hải Phòng');



        Doc = getDoc(DocID);
        DocDT= getDocDT(DocID);

        Datetime currentDateTime = Datetime.now();
        formattedDateTime = formatDatetime(currentDateTime);
        formName=Doc.RecordType.name;
        if(formName== 'Invoice' && DocDT.size()>0 ){
            if( DocDT[0].TotalBuyingInclTaxLocal__c !=null && DocDT[0].TotalBuyingInclTaxFCY__c != null) {
                Doc.RecordType.name='Credit Note';
            }else if(DocDT[0].Total_Selling_Incl_Tax_Local__c !=null && DocDT[0].Total_Selling_Incl_Tax_FCY__c != null){
                Doc.RecordType.name='Debit Note';
            }
        }

        if(cur=='vnd' && Doc.RecordType.name == 'Credit Note' && DocDT.size()>0 ){
            for(Documentsdetails__c item : DocDT){
                if(item.TotalBuyingInclTaxLocal__c != null)
                TotalVN += Integer.valueOf(item.TotalBuyingInclTaxLocal__c);
            }
        }
        else if(cur=='usd' && Doc.RecordType.name == 'Credit Note'  && DocDT.size()>0){
            for(Documentsdetails__c item : DocDT){
                if(item.TotalBuyingInclTaxFCY__c != null)
                
                Total += item.TotalBuyingInclTaxFCY__c;
            }
        }
        else if(cur=='vnd' && Doc.RecordType.name == 'Debit Note'  && DocDT.size()>0){
            for(Documentsdetails__c item : DocDT){
                if(item.Total_Selling_Incl_Tax_Local__c != null)
                
                TotalVN += Integer.valueOf(item.Total_Selling_Incl_Tax_Local__c);
            }
        } 
        else if(cur=='usd' && Doc.RecordType.name == 'Debit Note'  && DocDT.size()>0){
            for(Documentsdetails__c item : DocDT){
                if(item.Total_Selling_Incl_Tax_FCY__c != null)
                
                Total += item.Total_Selling_Incl_Tax_FCY__c;
            }
        }
        
       if(cur=='vnd'){
        Total= TotalVN + 0.00;
       }
       textTotal= ReadNumberToWords.convert(Total);
    //    textTotalVN='12xx';
       textTotalVN=ReaReadNumberToWordsVN.convertToVietnamese( TotalVN);
    }

    public String formatDatetime(Datetime dt) {
        // Format the datetime in the desired format
        return dt.format('dd MMM, yyyy  h:mm:ssa');
     }
   
     public void generateAttachmentFile(){
          
        String recordID = String.valueOf(ApexPages.currentPage().getParameters().get('id'));

        // checkPackage = Boolean.valueOf(ApexPages.currentPage().getParameters().get('checkPack'));
        // System.debug('1234:'+ requiredAttachment);
        PageReference pageRef = new PageReference('/apex/page_TT_HT_NoiBo');
        pageRef.getParameters().put('Id', recordID);
        // pageRef.getParameters().put('checkPackage', String.valueOf(checkPackage));
        System.debug('1234:xxxxx' + pageRef);
        String namefile = 'Contract' + '_v';

        String attachNameSearch = namefile + '%';
        // get exist file Name
        List<Attachment> attachments = [SELECT Id, Name, ParentId 
                                        FROM Attachment 
                                        WHERE ParentId =: recordID 
                                        AND Name LIKE : attachNameSearch 
                                        ORDER BY CreatedDate DESC LIMIT 1];
                                        
        if(attachments.isEmpty()){
            namefile += '1.1';
        }else{
            String attachNameExist = attachments[0].Name;
            attachNameExist = attachNameExist.substringAfter(namefile);
            attachNameExist = attachNameExist.substringBefore('.pdf');
            Decimal versionNumber = Decimal.valueOf(attachNameExist);
            versionNumber += 0.1;
            namefile += String.valueOf(versionNumber);
        }
        if(true){
            Attachment attach = new Attachment();
            Blob body;
            attach.Name = namefile + '.pdf'; 
            attach.IsPrivate = false;
            attach.ParentId = recordID;
            if(!Test.isRunningTest()){
            body = pageRef.getContentAsPDF();
            System.debug('1234:'+body);
            attach.Body = body;
            FlsService.doInsert(attach);
        }
        }
        
        
    }
    private CompanyInformation__c getCpn(String branch){
        CompanyInformation__c  Company= [SELECT Name,Name__c,
        Id,CompanyLogo__c,
        TaxCode__c,Tel__c,Website__c
        ,Email__c ,Address__c,Fax__c
        FROM CompanyInformation__c  WHERE Branch1__c =:branch limit 1];
        if(Company == null){
            return new CompanyInformation__c();
        }
        return Company;
    }

    private Document__c getDoc(String scheduleID){
        String strSelect = String.join(new List<String>(SoQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM Document__c'
                    + ' WHERE Id = \'' + scheduleID + '\'';
                    Document__c donhang;
        try{
            donhang = Database.query(strQuery);
        } catch(QueryException e){
            donhang = new Document__c();
        }
        return donhang;
    }

    private List<Documentsdetails__c> getDocDT(String scheduleID){
        String strSelect = String.join(new List<String>(docDetal), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM Documentsdetails__c'
                    + ' WHERE Document__c = \'' + scheduleID + '\'';
                    List<Documentsdetails__c> donhang;
        try{
            donhang = Database.query(strQuery);
        } catch(QueryException e){
            donhang = new List<Documentsdetails__c>();
        }
        return donhang;
    }

    

}