force-app/main/default/objects/FTMSBill__c/FTMSBill__c.object-meta.xml
<CustomObject>
    <label>F/TMS Bill</label>
    <nameField>
        <displayFormat>FTB-{000000}</displayFormat>
        <label>F/TMS Bill ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>F/TMS Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSBill__c/fields/AmountPaidforCustomerFCY__c.field-meta.xml
<CustomField>
    <fullName>AmountPaidforCustomerFCY__c</fullName>
    <label>Amount Paid-Buying (FCY)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/AmountPaidforCustomerLocal__c.field-meta.xml
<CustomField>
    <fullName>AmountPaidforCustomerLocal__c</fullName>
    <label>Amount Paid-Buying (Local)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/AmountReceivedfromCustomer__c.field-meta.xml
<CustomField>
    <fullName>AmountReceivedfromCustomer__c</fullName>
    <label>Amount Received from Customer (FCY)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/AmountReceivedfromCustomerLocal__c.field-meta.xml
<CustomField>
    <fullName>AmountReceivedfromCustomerLocal__c</fullName>
    <label>Amount Received from Customer(Local)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/PaymentConfirmedBuying__c.field-meta.xml
<CustomField>
    <fullName>PaymentConfirmedBuying__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment Confirmed-Buying</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/PaymentConfirmedSelling__c.field-meta.xml
<CustomField>
    <fullName>PaymentConfirmedSelling__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment Confirmed-Selling</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/TotalBuyingInclTaxFCY__c.field-meta.xml
<CustomField>
    <fullName>TotalBuyingInclTaxFCY__c</fullName>
    <formula>AmountTaxBuyingFCY__c+ TotalAmountofBuyingFCY__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Buying Incl Tax (FCY)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/TotalBuyingInclTaxLocal__c.field-meta.xml
<CustomField>
    <fullName>TotalBuyingInclTaxLocal__c</fullName>
    <formula>AmountTaxBuyingLocal__c +  TotalAmountofBuyingLocal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Buying Incl Tax (Local)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/TotalSellingInclTaxFCY__c.field-meta.xml
<CustomField>
    <fullName>TotalSellingInclTaxFCY__c</fullName>
    <formula>AmountTaxSellingFCY__c +  TotalAmountofSellingFCY__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Selling Incl Tax (FCY)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/TotalSellingInclTaxLocal__c.field-meta.xml
<CustomField>
    <fullName>TotalSellingInclTaxLocal__c</fullName>
    <formula>AmountTaxSellingLocal__c +  TotalAmountofSellingLocal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Selling Incl Tax (Local)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/FTMSBillClass.cls
public class FTMSBillClass {
	public static void isBeforeInsert(List<FTMSBill__c> lstBillNew){
        for (FTMSBill__c bill : lstBillNew){
             if (bill.PaymentConfirmedSelling__c == true) {
                if (bill.AmountReceivedfromCustomerLocal__c == null || bill.AmountReceivedfromCustomerLocal__c == 0) {
                    bill.AmountReceivedfromCustomerLocal__c = bill.TotalSellingInclTaxLocal__c;
                }
    
                if (bill.AmountReceivedfromCustomer__c == null || bill.AmountReceivedfromCustomer__c == 0) {
                    bill.AmountReceivedfromCustomer__c = bill.TotalSellingInclTaxFCY__c ;
                }
            }
            
            if (bill.PaymentConfirmedBuying__c == true) {
                if (bill.AmountPaidforCustomerLocal__c == null || bill.AmountPaidforCustomerLocal__c == 0) {
                    bill.AmountPaidforCustomerLocal__c = bill.TotalBuyingInclTaxLocal__c;
                }
    
                if (bill.AmountPaidforCustomerFCY__c == null || bill.AmountPaidforCustomerFCY__c == 0) {
                    bill.AmountPaidforCustomerFCY__c = bill.TotalBuyingInclTaxFCY__c;
                }
            }
        }
    }
    public static void isBeforeUpdate(List<FTMSBill__c> lstBillNew, List<FTMSBill__c> lstBillOld){
        for (FTMSBill__c bill : lstBillNew){
            if (bill.PaymentConfirmedSelling__c == true) {
                if (bill.AmountReceivedfromCustomerLocal__c == null || bill.AmountReceivedfromCustomerLocal__c == 0) {
                    bill.AmountReceivedfromCustomerLocal__c = bill.TotalSellingInclTaxLocal__c;
                }
    
                if (bill.AmountReceivedfromCustomer__c == null || bill.AmountReceivedfromCustomer__c == 0) {
                    bill.AmountReceivedfromCustomer__c = bill.TotalSellingInclTaxFCY__c ;
                }
            }
            
            if (bill.PaymentConfirmedBuying__c == true) {
                if (bill.AmountPaidforCustomerLocal__c == null || bill.AmountPaidforCustomerLocal__c == 0) {
                    bill.AmountPaidforCustomerLocal__c = bill.TotalBuyingInclTaxLocal__c;
                }
    
                if (bill.AmountPaidforCustomerFCY__c == null || bill.AmountPaidforCustomerFCY__c == 0) {
                    bill.AmountPaidforCustomerFCY__c = bill.TotalBuyingInclTaxFCY__c;
                }
            }
        }
    }
}