force-app/main/default/objects/FTMSBill__c/FTMSBill__c.object-meta.xml
<CustomObject>
    <label>F/TMS Bill</label>
    <nameField>
        <displayFormat>FTB-{000000}</displayFormat>
        <label>F/TMS Bill ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>F/TMS Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSBill__c/fields/AmountPaidforCustomerFCY__c.field-meta.xml
<CustomField>
    <fullName>AmountPaidforCustomerFCY__c</fullName>
    <label>Amount Paid-Buying (FCY)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/AmountPaidforCustomerLocal__c.field-meta.xml
<CustomField>
    <fullName>AmountPaidforCustomerLocal__c</fullName>
    <label>Amount Paid-Buying (Local)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/AmountReceivedfromCustomer__c.field-meta.xml
<CustomField>
    <fullName>AmountReceivedfromCustomer__c</fullName>
    <label>Amount Received from Customer (FCY)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/AmountReceivedfromCustomerLocal__c.field-meta.xml
<CustomField>
    <fullName>AmountReceivedfromCustomerLocal__c</fullName>
    <label>Amount Received from Customer(Local)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/ApplicantSelling__c.field-meta.xml
<CustomField>
    <fullName>ApplicantSelling__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant-Selling</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS Bills (Applicant-Selling)</relationshipLabel>
    <relationshipName>F_TMS_Bills2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/BankAccountforPayment__c.field-meta.xml
<CustomField>
    <fullName>BankAccountforPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account for Payment</label>
    <referenceTo>BankAcc__c</referenceTo>
    <relationshipLabel>F/TMS Bills</relationshipLabel>
    <relationshipName>F_TMS_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/BankAccountforReceipt__c.field-meta.xml
<CustomField>
    <fullName>BankAccountforReceipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account for Receipt</label>
    <referenceTo>BankAcc__c</referenceTo>
    <relationshipLabel>F/TMS Bills (Bank Account for Receipt)</relationshipLabel>
    <relationshipName>F_TMS_Bills1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/BeneficiaryBuying__c.field-meta.xml
<CustomField>
    <fullName>BeneficiaryBuying__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beneficiary-Buying</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS Bills (Benificiary-Buying)</relationshipLabel>
    <relationshipName>F_TMS_Bills3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/PaymentConfirmedBuying__c.field-meta.xml
<CustomField>
    <fullName>PaymentConfirmedBuying__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment Confirmed-Buying</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/PaymentConfirmedSelling__c.field-meta.xml
<CustomField>
    <fullName>PaymentConfirmedSelling__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment Confirmed-Selling</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/PaymentNotesBuying__c.field-meta.xml
<CustomField>
    <fullName>PaymentNotesBuying__c</fullName>
    <label>Payment Notes-Buying</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/PaymentNotesSelling__c.field-meta.xml
<CustomField>
    <fullName>PaymentNotesSelling__c</fullName>
    <label>Payment Notes - Selling</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/PaymentSettledDateBuying__c.field-meta.xml
<CustomField>
    <fullName>PaymentSettledDateBuying__c</fullName>
    <label>Payment Settled Date - Buying</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/PaymentSettledDateSelling__c.field-meta.xml
<CustomField>
    <fullName>PaymentSettledDateSelling__c</fullName>
    <label>Payment Settled Date - Selling</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/PaymentTypeBuying__c.field-meta.xml
<CustomField>
    <fullName>PaymentTypeBuying__c</fullName>
    <label>Payment Type - Buying</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Cheque (Received but not Claimed)</fullName>
            </value>
            <value>
                <fullName>Cheque (Received and Claimed)</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Payment Offset</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
            <value>
                <fullName>Deposit Offset</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/PaymentTypeSelling__c.field-meta.xml
<CustomField>
    <fullName>PaymentTypeSelling__c</fullName>
    <label>Payment Type - Selling</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Cheque (Received but not Claimed)</fullName>
            </value>
            <value>
                <fullName>Cheque (Received and Claimed)</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Payment Offset</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
            <value>
                <fullName>Deposit Offset</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/TotalBuyingInclTaxFCY__c.field-meta.xml
<CustomField>
    <fullName>TotalBuyingInclTaxFCY__c</fullName>
    <formula>AmountTaxBuyingFCY__c+ TotalAmountofBuyingFCY__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Buying Incl Tax (FCY)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/TotalBuyingInclTaxLocal__c.field-meta.xml
<CustomField>
    <fullName>TotalBuyingInclTaxLocal__c</fullName>
    <formula>AmountTaxBuyingLocal__c +  TotalAmountofBuyingLocal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Buying Incl Tax (Local)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/TotalSellingInclTaxFCY__c.field-meta.xml
<CustomField>
    <fullName>TotalSellingInclTaxFCY__c</fullName>
    <formula>AmountTaxSellingFCY__c +  TotalAmountofSellingFCY__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Selling Incl Tax (FCY)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/TotalSellingInclTaxLocal__c.field-meta.xml
<CustomField>
    <fullName>TotalSellingInclTaxLocal__c</fullName>
    <formula>AmountTaxSellingLocal__c +  TotalAmountofSellingLocal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Selling Incl Tax (Local)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ShowReceivablePayableBatch.cls
global with sharing class ShowReceivablePayableBatch implements Database.Batchable<sObject>, Database.Stateful {
    private List<String> ankenMeisaiIdUpdateList {get; set;}
    private FTMSBill__c objAnkenMeisaiInput {get; set;}
    private Boolean isShowReceivable {get; set;}

    global ShowReceivablePayableBatch(List<String> ankenMeisaiIdList, FTMSBill__c objAnkenMeisai, Boolean isShowReceivable) {
        this.ankenMeisaiIdUpdateList = ankenMeisaiIdList;
        this.objAnkenMeisaiInput = objAnkenMeisai;
        this.isShowReceivable = isShowReceivable;
    }

    global List<FTMSBill__c> start(Database.BatchableContext bc) {
        List<FTMSBill__c> ankenMeisaiUpdateList = new List<FTMSBill__c>();
        if (!ankenMeisaiIdUpdateList.isEmpty()) {
            for(String meisaiIdUpdate : this.ankenMeisaiIdUpdateList) {
                ankenMeisaiUpdateList.add(this.createanKenMeisaiUpdate(meisaiIdUpdate, this.objAnkenMeisaiInput, this.isShowReceivable));					
            }
        }
        return ankenMeisaiUpdateList;
	}

    global void execute(Database.BatchableContext bc, List<FTMSBill__c> ankenMeisaiUpdateList) {
        Savepoint sp;
        try {
			if (!ankenMeisaiUpdateList.isEmpty()) {
				sp = Database.setSavepoint();
				FlsService.doupdate(ankenMeisaiUpdateList);
			}
		} catch (Exception ex) {
            if (sp != null) {
				Database.rollback(sp);
			}

		}    
    }

    global void finish(Database.BatchableContext bc) {
        try {
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            string[] to = new string[] { UserInfo.getUserEmail() };
           
            email.setToAddresses(to);
            email.setSubject('ShowReceivablePayablBatch');
            String msg = 'Process done. <br/><br/>';
            email.setHtmlBody(msg);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { email });      
        } catch (Exception ex) {

        }
    }

    private FTMSBill__c createanKenMeisaiUpdate(String meisaiIdUpdate
                                                                    ,FTMSBill__c objAnkenMeisai
                                                                    ,Boolean isReceivable) {
        FTMSBill__c objAnkenMeisaiUpdate = new FTMSBill__c();
        objAnkenMeisaiUpdate.Id = meisaiIdUpdate;
        FTMSBill__c getBill = [SELECT Id, TotalSellingInclTaxLocal__c, TotalSellingInclTaxFCY__c, TotalBuyingInclTaxLocal__c,TotalBuyingInclTaxFCY__c FROM FTMSBill__c WHERE Id =: meisaiIdUpdate];

        if (isReceivable) {
            objAnkenMeisaiUpdate.PaymentConfirmedSelling__c = objAnkenMeisai.PaymentConfirmedSelling__c;
            objAnkenMeisaiUpdate.ApplicantSelling__c = objAnkenMeisai.ApplicantSelling__c;
            objAnkenMeisaiUpdate.PaymentTypeSelling__c = objAnkenMeisai.PaymentTypeSelling__c;
            objAnkenMeisaiUpdate.PaymentSettledDateSelling__c = objAnkenMeisai.PaymentSettledDateSelling__c;
            objAnkenMeisaiUpdate.BankAccountforReceipt__c = objAnkenMeisai.BankAccountforReceipt__c;
            objAnkenMeisaiUpdate.PaymentNotesSelling__c = objAnkenMeisai.PaymentNotesSelling__c;

            // if (objAnkenMeisai.PaymentConfirmedSelling__c == true) {
            //     if (objAnkenMeisai.AmountReceivedfromCustomerLocal__c == null || objAnkenMeisai.AmountReceivedfromCustomerLocal__c == 0) {
            //         objAnkenMeisaiUpdate.AmountReceivedfromCustomerLocal__c = objAnkenMeisai.TotalSellingInclTaxLocal__c;
            //     }
    
            //     if (objAnkenMeisai.AmountReceivedfromCustomer__c == null || objAnkenMeisai.AmountReceivedfromCustomer__c == 0) {
            //         objAnkenMeisaiUpdate.AmountReceivedfromCustomer__c = objAnkenMeisai.TotalSellingInclTaxFCY__c ;
            //     }
            // }
        } else {
            objAnkenMeisaiUpdate.PaymentConfirmedBuying__c = objAnkenMeisai.PaymentConfirmedBuying__c;
            objAnkenMeisaiUpdate.BeneficiaryBuying__c = objAnkenMeisai.BeneficiaryBuying__c;
            objAnkenMeisaiUpdate.PaymentTypeBuying__c = objAnkenMeisai.PaymentTypeBuying__c;
            objAnkenMeisaiUpdate.PaymentSettledDateBuying__c = objAnkenMeisai.PaymentSettledDateBuying__c;
            objAnkenMeisaiUpdate.BankAccountforPayment__c = objAnkenMeisai.BankAccountforPayment__c;
            objAnkenMeisaiUpdate.PaymentNotesBuying__c = objAnkenMeisai.PaymentNotesBuying__c;

            // if (objAnkenMeisai.PaymentConfirmedBuying__c == true) {
            //     if (objAnkenMeisai.AmountPaidforCustomerLocal__c == null || objAnkenMeisai.AmountPaidforCustomerLocal__c == 0) {
            //         objAnkenMeisaiUpdate.AmountPaidforCustomerLocal__c = objAnkenMeisai.TotalBuyingInclTaxLocal__c;
            //     }
    
            //     if (objAnkenMeisai.AmountPaidforCustomerFCY__c == null || objAnkenMeisai.AmountPaidforCustomerFCY__c == 0) {
            //         objAnkenMeisaiUpdate.AmountPaidforCustomerFCY__c = objAnkenMeisai.TotalBuyingInclTaxFCY__c;
            //     }
            // }
        }
        
        return objAnkenMeisaiUpdate;
    }
}