force-app/main/default/objects/FTMSBill__c/FTMSBill__c.object-meta.xml
<CustomObject>
    <label>F/TMS Bill</label>
    <nameField>
        <displayFormat>FTB-{000000}</displayFormat>
        <label>F/TMS Bill ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>F/TMS Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSBill__c/fields/FTMSSO__c.field-meta.xml
<CustomField>
    <fullName>FTMSSO__c</fullName>
    <label>F/TMS S/O</label>
    <referenceTo>FTMSSO__c</referenceTo>
    <relationshipLabel>F/TMS Bills</relationshipLabel>
    <relationshipName>F_TMS_Bills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/InvoiceTo__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS Bills</relationshipLabel>
    <relationshipName>F_TMS_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/PaymentTo__c.field-meta.xml
<CustomField>
    <fullName>PaymentTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS Bills (Payment To)</relationshipLabel>
    <relationshipName>F_TMS_Bills1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/FTMSSO__c.object-meta.xml
<CustomObject>
    <label>Shipment.</label>
    <nameField>
        <displayFormat>FSO-{000000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments.</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSSO__c/fields/AccountedDate__c.field-meta.xml
<CustomField>
    <fullName>AccountedDate__c</fullName>
    <label>Accounted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This Agent will be show on Bill</inlineHelpText>
    <label>Agent</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>F_TMS_S_O4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch (not used)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ha Noi</fullName>
                <default>true</default>
                <label>Ha Noi</label>
            </value>
            <value>
                <fullName>Hai Phong</fullName>
            </value>
            <value>
                <fullName>Ho Chi Minh</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoQuantity__c.field-meta.xml
<CustomField>
    <fullName>CargoQuantity__c</fullName>
    <label>Cargo Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CarrierAirlinerVendor__c.field-meta.xml
<CustomField>
    <fullName>CarrierAirlinerVendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Carrier/Airliner/Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>F_TMS_S_O5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/POLAOD__c.field-meta.xml
<CustomField>
    <fullName>POLAOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.L(A.O.D)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/VesselFlight__c.field-meta.xml
<CustomField>
    <fullName>VesselFlight__c</fullName>
    <label>Vessel/Flight</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortCode__c/PortCode__c.object-meta.xml
<CustomObject>
    <label>Port Code</label>
    <nameField>
        <label>Port Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Port Code</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PortCode__c/fields/PortCode__c.field-meta.xml
<CustomField>
    <fullName>PortCode__c</fullName>
    <label>Port Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateKhoanThuControllerTest.cls
@isTest
public class UpdateKhoanThuControllerTest {
    @istest public static void case1() {
          PortCode__c pc2= new PortCode__c(Name= 'VP of Services',Active__c = true);
        insert pc2;
        Date acDate=  Date.newInstance(2023, 02, 12);
      
        List<Account> listAc= new List<Account>();
        
       Account act= new Account(
                Name='account');
        listAc.add(act);
         Account act2= new Account(
                Name='account2');
        listAc.add(act2);
        insert listAc;
        
        FTMSSO__c item = new FTMSSO__c( 
           
            POLAOD__c= pc2.Id,
            VesselFlight__c= 'AC',
            CargoQuantity__c=100,
            Branch__c='Ho Chi Minh',
            Agent__c=act.Id,
            CarrierAirlinerVendor__c= act.Id,
            AccountedDate__c = acDate);
        
     	List<FTMSSO__c> jsonvl= new List<FTMSSO__c>();
        jsonvl.add(item);
        insert jsonvl;
        
        
        List<FTMSBill__c> billlist= new List<FTMSBill__c>();
        FTMSBill__c bill = new FTMSBill__c(
        FTMSSO__c=item.Id,
            InvoiceTo__c= act.Id,
            PaymentTo__c= act2.Id
            
        );
        billlist.add(bill);
        insert billlist;
        String JsonSO= JSON.serialize(billlist);
        Test.startTest();
       // UpdateKhoanThuController.getRecordTypeId();
        UpdateKhoanThuController.getDescribeSobjectResult();
       UpdateKhoanThuController.getAllBillingsInvoice(item.Id,true);
        UpdateKhoanThuController.getAllBillingsInvoice(item.Id,false);
        UpdateKhoanThuController.getAllBillingsPayment(item.Id,true);
       UpdateKhoanThuController.getAllBillingsPayment(item.Id,false);
        UpdateKhoanThuController.updateBillings(JsonSO, true, true, true, true, true, true, true, true, true, true);
UpdateKhoanThuController.deleteBilling(bill.Id);
        System.assertEquals(true, true);
        Test.stopTest();
    }
}