force-app/main/default/objects/FTMSBill__c/FTMSBill__c.object-meta.xml
<CustomObject>
    <label>F/TMS Bill</label>
    <nameField>
        <displayFormat>FTB-{000000}</displayFormat>
        <label>F/TMS Bill ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>F/TMS Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSBill__c/fields/CurrencyBuying__c.field-meta.xml
<CustomField>
    <fullName>CurrencyBuying__c</fullName>
    <label>Currency-Buying</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VND</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>KHR</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>KRW</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/CurrencySelling__c.field-meta.xml
<CustomField>
    <fullName>CurrencySelling__c</fullName>
    <label>Currency-Selling</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VND</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>KHR</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>KRW</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/FTMSSO__c.field-meta.xml
<CustomField>
    <fullName>FTMSSO__c</fullName>
    <label>F/TMS S/O</label>
    <referenceTo>FTMSSO__c</referenceTo>
    <relationshipLabel>F/TMS Bills</relationshipLabel>
    <relationshipName>F_TMS_Bills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/TaxRateBuying__c.field-meta.xml
<CustomField>
    <fullName>TaxRateBuying__c</fullName>
    <label>Tax Rate-Buying(%)</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/TaxRateSelling__c.field-meta.xml
<CustomField>
    <fullName>TaxRateSelling__c</fullName>
    <label>Tax Rate-Selling(%)</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/UnitPriceFCY__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceFCY__c</fullName>
    <label>Unit Price of Selling (FCY)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/UnitPriceofBuyingFCY__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceofBuyingFCY__c</fullName>
    <label>Unit Price of Buying (FCY)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/UnitPriceofBuyingLocal__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceofBuyingLocal__c</fullName>
    <label>Unit Price of Buying(Local)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/UnitPriceofSelling3rdCurrency__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceofSelling3rdCurrency__c</fullName>
    <label>Unit Price of Selling(3rd Currency)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/UnitPriceofSellingLocal__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceofSellingLocal__c</fullName>
    <label>Unit Price of Selling(Local)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/FTMSSO__c.object-meta.xml
<CustomObject>
    <label>Shipment.</label>
    <nameField>
        <displayFormat>FSO-{000000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments.</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SiteCustomSettings__c/fields/FCYCurrency__c.field-meta.xml
<CustomField>
    <fullName>FCYCurrency__c</fullName>
    <label>FCY Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SiteCustomSettings__c/fields/LocalCurrency__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrency__c</fullName>
    <label>Local Currency</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AddMultipleBillController.cls
public with sharing class AddMultipleBillController {
    @AuraEnabled
    public static String saveBillList(List<FTMSBill__c> billList,Id shipmentId) 
	{   
        SiteCustomSettings__c custom = [SELECT FCYCurrency__c,LocalCurrency__c FROM SiteCustomSettings__c ];
        for(FTMSBill__c bill: billList){
            bill.FTMSSO__c = shipmentId;
            if(bill.CurrencySelling__c == custom.FCYCurrency__c){
                bill.UnitPriceFCY__c = bill.UnitPriceFCY__c;
                bill.UnitPriceofSellingLocal__c = null;
                // bill.clofor_com_cfs__AmountSellingUSDAdjustment__c = bill.clofor_com_cfs__AmountSellingLocalAdjustment__c;
                // bill.clofor_com_cfs__AmountSellingLocalAdjustment__c = null;
            }else if(bill.CurrencySelling__c == custom.LocalCurrency__c){
                bill.UnitPriceofSellingLocal__c = bill.UnitPriceFCY__c;
                System.debug('123: ' + bill.UnitPriceofSellingLocal__c);
                System.debug('456: ' + bill.UnitPriceFCY__c);
                // bill.clofor_com_cfs__AmountSellingLocalAdjustment__c = bill.clofor_com_cfs__AmountSellingLocalAdjustment__c;
            }else {
                // bill.clofor_com_cfs__UnitPriceofSelling3rdCurrency__c = bill.UnitPriceofSellingLocal__c; =======================
                bill.UnitPriceofSellingLocal__c = null;
                // bill.clofor_com_cfs__AmountSellingInclTax3rdCurrencyAdjust__c = bill.clofor_com_cfs__AmountSellingLocalAdjustment__c;
                // bill.clofor_com_cfs__AmountSellingLocalAdjustment__c = null;
            }

            if(bill.CurrencyBuying__c == custom.FCYCurrency__c){
                bill.UnitPriceofBuyingFCY__c = bill.UnitPriceofBuyingFCY__c;
                bill.UnitPriceofBuyingLocal__c = null;
                // bill.clofor_com_cfs__AmountBuyingUSDAdjustment__c = bill.clofor_com_cfs__AmountBuyingLocalAdjustment__c;
                // bill.clofor_com_cfs__AmountBuyingLocalAdjustment__c = null;
            }else if(bill.CurrencyBuying__c == custom.LocalCurrency__c){
                bill.UnitPriceofBuyingLocal__c = bill.UnitPriceofBuyingFCY__c;
                // bill.clofor_com_cfs__AmountBuyingLocalAdjustment__c = bill.clofor_com_cfs__AmountBuyingLocalAdjustment__c;
            }else {
                // bill.UnitPriceofSelling3rdCurrency__c = bill.UnitPriceofSellingLocal__c;
                bill.UnitPriceofBuyingLocal__c = null;
                // bill.clofor_com_cfs__AmountBuyingInclTax3rdCurrencyAdjust__c = bill.clofor_com_cfs__AmountBuyingLocalAdjustment__c;
                // bill.clofor_com_cfs__AmountBuyingLocalAdjustment__c = null;

            }    
            // if(bill.TaxRateSelling__c != null){
            //     bill.Included_in_tax_invoice_selling__c = true; 
            // }
            // if(bill.TaxRateBuying__c != null){
            //     bill.Included_in_tax_invoice_buying__c = true; 

            // }       
        }
        
        System.debug('accList1:' + billList);     
        try{
            insert billList;
        }
        catch (Exception e) {
            return e.getMessage();
        }
        return null;
        // System.debug('accList2:' + accList);
    }
    
}