force-app/main/default/objects/FTMSBill__c/FTMSBill__c.object-meta.xml
<CustomObject>
    <label>F/TMS Bill</label>
    <nameField>
        <displayFormat>FTB-{000000}</displayFormat>
        <label>F/TMS Bill ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>F/TMS Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSBill__c/fields/AdvancePaymentonbehalfofCustomer__c.field-meta.xml
<CustomField>
    <fullName>AdvancePaymentonbehalfofCustomer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Advance Payment on-behalf-of Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/BillNameatPrintENG__c.field-meta.xml
<CustomField>
    <fullName>BillNameatPrintENG__c</fullName>
    <label>Bill Name at Print(ENG)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/ChargeQuantity__c.field-meta.xml
<CustomField>
    <fullName>ChargeQuantity__c</fullName>
    <label>Charge Quantity</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/ChargeUnit__c.field-meta.xml
<CustomField>
    <fullName>ChargeUnit__c</fullName>
    <label>Charge Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20&apos;DC-Flexi</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>B/L</fullName>
            </value>
            <value>
                <fullName>Bill</fullName>
            </value>
            <value>
                <fullName>Box</fullName>
            </value>
            <value>
                <fullName>Carton</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>CBM</fullName>
            </value>
            <value>
                <fullName>Container</fullName>
            </value>
            <value>
                <fullName>Day</fullName>
            </value>
            <value>
                <fullName>Drum</fullName>
            </value>
            <value>
                <fullName>Keg</fullName>
            </value>
            <value>
                <fullName>Kg</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Package</fullName>
            </value>
            <value>
                <fullName>Pallet</fullName>
            </value>
            <value>
                <fullName>Roll</fullName>
            </value>
            <value>
                <fullName>RTON</fullName>
            </value>
            <value>
                <fullName>Set</fullName>
            </value>
            <value>
                <fullName>Sheet</fullName>
            </value>
            <value>
                <fullName>Shipment</fullName>
            </value>
            <value>
                <fullName>Skid</fullName>
            </value>
            <value>
                <fullName>Unit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/ChargeUnitinPrint__c.field-meta.xml
<CustomField>
    <fullName>ChargeUnitinPrint__c</fullName>
    <label>Charge Unit in Print</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/ContainerType__c.field-meta.xml
<CustomField>
    <fullName>ContainerType__c</fullName>
    <label>Container Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ChargeUnit__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20&apos;DC</fullName>
            </value>
            <value>
                <fullName>40&apos;DC</fullName>
            </value>
            <value>
                <fullName>45&apos;DC</fullName>
            </value>
            <value>
                <fullName>40&apos;HC</fullName>
            </value>
            <value>
                <fullName>45&apos;HC</fullName>
            </value>
            <value>
                <fullName>20&apos;RF</fullName>
            </value>
            <value>
                <fullName>40&apos;RF</fullName>
            </value>
            <value>
                <fullName>45&apos;RF</fullName>
            </value>
            <value>
                <fullName>20&apos;OT</fullName>
            </value>
            <value>
                <fullName>40&apos;OT</fullName>
            </value>
            <value>
                <fullName>45&apos;OT</fullName>
            </value>
            <value>
                <fullName>20&apos;FR</fullName>
            </value>
            <value>
                <fullName>40&apos;FR</fullName>
            </value>
            <value>
                <fullName>Bulk</fullName>
            </value>
            <value>
                <fullName>ISO</fullName>
            </value>
            <value>
                <fullName>20&apos;IMO</fullName>
            </value>
            <value>
                <fullName>40&apos;IMO</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>20&apos;DC-Flexi</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>CBM</fullName>
            </value>
            <value>
                <fullName>RTON</fullName>
            </value>
            <value>
                <fullName>2*20&apos;DC</fullName>
                <isActive>false</isActive>
                <label>2*20&apos;DC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/CurrencyBuying__c.field-meta.xml
<CustomField>
    <fullName>CurrencyBuying__c</fullName>
    <label>Currency-Buying</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VND</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>KHR</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>KRW</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/CurrencyConversionforSelling__c.field-meta.xml
<CustomField>
    <fullName>CurrencyConversionforSelling__c</fullName>
    <label>Currency Conversion for Selling</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>From FCY to Local Currency</fullName>
            </value>
            <value>
                <fullName>From Local Currency to FCY</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/CurrencySelling__c.field-meta.xml
<CustomField>
    <fullName>CurrencySelling__c</fullName>
    <label>Currency-Selling</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VND</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>KHR</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>KRW</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/ExchangeRateSelling__c.field-meta.xml
<CustomField>
    <fullName>ExchangeRateSelling__c</fullName>
    <label>Exchange Rate - Selling</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/FTMSSO__c.field-meta.xml
<CustomField>
    <fullName>FTMSSO__c</fullName>
    <label>F/TMS S/O</label>
    <referenceTo>FTMSSO__c</referenceTo>
    <relationshipLabel>F/TMS Bills</relationshipLabel>
    <relationshipName>F_TMS_Bills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/FxRateID__c.field-meta.xml
<CustomField>
    <fullName>FxRateID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FxRate ID</label>
    <referenceTo>FxRate__c</referenceTo>
    <relationshipLabel>F/TMS Bills</relationshipLabel>
    <relationshipName>F_TMS_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/InvoiceSBDisplayNo__c.field-meta.xml
<CustomField>
    <fullName>InvoiceSBDisplayNo__c</fullName>
    <label>Invoice S/B Display No</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/InvoiceTo__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS Bills</relationshipLabel>
    <relationshipName>F_TMS_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/PaymentTo__c.field-meta.xml
<CustomField>
    <fullName>PaymentTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS Bills (Payment To)</relationshipLabel>
    <relationshipName>F_TMS_Bills1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/Print__c.field-meta.xml
<CustomField>
    <fullName>Print__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Print</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Service__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>F/TMS Bills</relationshipLabel>
    <relationshipName>F_TMS_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/TaxRateSelling__c.field-meta.xml
<CustomField>
    <fullName>TaxRateSelling__c</fullName>
    <label>Tax Rate-Selling(%)</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/UnitPriceFCY__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceFCY__c</fullName>
    <label>Unit Price of Selling (FCY)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/UnitPriceofBuying3rdCurrency__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceofBuying3rdCurrency__c</fullName>
    <label>Unit Price of Buying(3rd Currency)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/UnitPriceofBuyingFCY__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceofBuyingFCY__c</fullName>
    <label>Unit Price of Buying (FCY)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/UnitPriceofBuyingLocal__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceofBuyingLocal__c</fullName>
    <label>Unit Price of Buying(Local)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/UnitPriceofSelling3rdCurrency__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceofSelling3rdCurrency__c</fullName>
    <label>Unit Price of Selling(3rd Currency)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/UnitPriceofSellingLocal__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceofSellingLocal__c</fullName>
    <label>Unit Price of Selling(Local)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/VATrateselling__c.field-meta.xml
<CustomField>
    <fullName>VATrateselling__c</fullName>
    <label>VAT rate-selling</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Value1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MassUpdateBillingController.cls
public class MassUpdateBillingController {
    @AuraEnabled
    public static String getRecordTypeId(){
        //TODO: Need to clarify which spefic developer name record here
        return [SELECT Id,SobjectType FROM RecordType WHERE SobjectType = 'FTMSBill__c' AND DeveloperName = 'Selling_Buyging_Standard'].Id;
    }
    
	@AuraEnabled
    public static String getDescribeSobjectResult(){
		DescribeSobjectResult objResult = Schema.SObjectType.FTMSBill__c;
        return objResult.isCreateable() + '_' + objResult.isUpdateable() + '_' + objResult.isAccessible() + '_' + objResult.isDeletable();
    }
	@AuraEnabled
    public static List<FTMSBill__c> getAllBillings(String shipmentId, Boolean isSelling){        
        List<FTMSBill__c> getBilling = new List<FTMSBill__c>();
        if(isSelling){
            getBilling =  [Select id FROM FTMSBill__c 
            WHERE FTMSSO__c = :shipmentId 
            // AND ((UnitPriceFCY__c != 0 AND UnitPriceFCY__c != null)
            // OR (UnitPriceofSellingLocal__c != 0 AND UnitPriceofSellingLocal__c != null))
            ORDER BY Name];
        } else {
            getBilling =  [Select id FROM FTMSBill__c 
                WHERE FTMSSO__c = :shipmentId 
                // AND ((UnitPriceofBuyingFCY__c != 0 AND UnitPriceofBuyingFCY__c != null)
                // OR (UnitPriceofBuyingLocal__c != 0 AND UnitPriceofBuyingLocal__c != null))
                ORDER BY Name];
        }
        // List<FTMSBill__c> getBilling1 = new List<FTMSBill__c>();
        // if(isSelling){
        //     getBilling1 =  [Select id FROM FTMSBill__c 
        //     WHERE FTMSSO__c = :shipmentId 
        //     AND ((UnitPriceFCY__c = 0)
        //     AND (UnitPriceofSellingLocal__c = 0))
        //     ORDER BY Name];
        // } else{
        //     getBilling1 =  [Select id FROM FTMSBill__c 
        //     WHERE FTMSSO__c = :shipmentId 
        //     AND ((UnitPriceofBuyingFCY__c = 0)
        //     AND (UnitPriceofBuyingLocal__c = 0))
        //     ORDER BY Name];
        // }
        // List<FTMSBill__c> getBilling2 = new List<FTMSBill__c>();
        // if(isSelling){
        //     getBilling2 =  [Select id FROM FTMSBill__c 
        //     WHERE FTMSSO__c = :shipmentId 
        //     AND ((UnitPriceFCY__c = 0)
        //     AND (UnitPriceofSellingLocal__c = null))
        //     ORDER BY Name];
        // } else{
        //     getBilling2 =  [Select id FROM FTMSBill__c 
        //     WHERE FTMSSO__c = :shipmentId 
        //     AND ((UnitPriceofBuyingFCY__c = 0)
        //     AND (UnitPriceofBuyingLocal__c = null))
        //     ORDER BY Name];
        // }
        // List<FTMSBill__c> getBilling3 = new List<FTMSBill__c>();
        // if(isSelling){
        //     getBilling3 =  [Select id FROM FTMSBill__c 
        //     WHERE FTMSSO__c = :shipmentId 
        //     AND ((UnitPriceFCY__c = null)
        //     AND (UnitPriceofSellingLocal__c = 0))
        //     ORDER BY Name];
        // } else{
        //     getBilling3 =  [Select id FROM FTMSBill__c 
        //     WHERE FTMSSO__c = :shipmentId 
        //     AND ((UnitPriceofBuyingFCY__c = null)
        //     AND (UnitPriceofBuyingLocal__c = 0))
        //     ORDER BY Name];
        // }
        // List<FTMSBill__c> getBilling4 = new List<FTMSBill__c>();
        // if(isSelling){
        //     getBilling4 =  [Select id FROM FTMSBill__c 
        //     WHERE FTMSSO__c = :shipmentId 
        //     AND ((UnitPriceFCY__c = null)
        //     AND (UnitPriceofSellingLocal__c = null))
        //     ORDER BY Name];
        // } else{
        //     getBilling4 =  [Select id FROM FTMSBill__c 
        //     WHERE FTMSSO__c = :shipmentId 
        //     AND ((UnitPriceofBuyingFCY__c = null)
        //     AND (UnitPriceofBuyingLocal__c = null))
        //     ORDER BY Name];
        // }
        // System.debug('123:' +shipmentId );
        // getBilling.addAll(getBilling1);
        // getBilling.addAll(getBilling2);
        // getBilling.addAll(getBilling3);
        // getBilling.addAll(getBilling4);
        return getBilling;
    }

	@AuraEnabled
    public static Boolean deleteBilling(String id){
        try {
            List<FTMSBill__c> billings = [Select Id FROM FTMSBill__c WHERE Id = :id];
            if(billings.size() == 0)
                return false;
            delete billings;
            return true;
        } catch (DmlException e) {
            throw e;
        }
    }

	@AuraEnabled
    public static String updateBillings(String jsonRecords, Boolean isSelling, Boolean isBuying, Boolean isVATRateSelling, Boolean isExchangeRateIDDebitCredit, Boolean isCurrencyConversionForSelling, Boolean isExchangeRateSellingDebit, Boolean isVATRateBuying, Boolean isExchangeRateBuyingCredit, Boolean isCurrencyConversionForBuying, Boolean isAdvancePaymentonbehalfofOurCompany ){
		List<FTMSBill__c> records = (List<FTMSBill__c>) JSON.deserialize(jsonRecords, List<FTMSBill__c>.class);
        System.debug('debug1 :'+records);
        Set<Id> ids = (new Map<Id,SObject>(records)).keySet();
        System.debug('Idd :'+ids);
        List<FTMSBill__c>  billings = [SELECT Id,Name,InvoiceSBDisplayNo__c,Service__c,InvoiceTo__c,PaymentTo__c,
        ChargeQuantity__c,ChargeUnitinPrint__c,ChargeUnit__c,Print__c,CurrencySelling__c,AdvancePaymentonbehalfofCustomer__c,
        UnitPriceofSellingLocal__c,UnitPriceFCY__c,UnitPriceofSelling3rdCurrency__c,TaxRateSelling__c,VATrateselling__c,
        FxRateID__c,ExchangeRateSelling__c,CurrencyConversionforSelling__c,CurrencyBuying__c,ContainerType__c,
        BillNameatPrintENG__c,UnitPriceofBuyingLocal__c,UnitPriceofBuyingFCY__c,UnitPriceofBuying3rdCurrency__c,TaxRateBuying__c,VATratebuying__c,AdvancePaymentonbehalfofOurCompany__c,
        ExchangeRateBuying__c,CurrencyConversionforBuying__c
        FROM FTMSBill__c 
        WHERE Id in :ids
        ORDER BY Name];
        System.debug('debug2 :'+billings);

        
        List<FTMSBill__c> itemsIdsToRemove = new List<FTMSBill__c>();
        
        for(Integer i  = 0; i < records.size(); i++){
            FTMSBill__c r = records[i];
            
    
                if(billings[i].Id == r.Id){
                    if(billings[i].InvoiceSBDisplayNo__c != r.InvoiceSBDisplayNo__c ||
                    billings[i].Service__c != r.Service__c ||
                    billings[i].BillNameatPrintENG__c != r.BillNameatPrintENG__c ||
                    billings[i].InvoiceTo__c != r.InvoiceTo__c ||
                    billings[i].PaymentTo__c != r.PaymentTo__c ||
                    billings[i].ChargeQuantity__c != r.ChargeQuantity__c ||
                    billings[i].ChargeUnitinPrint__c != r.ChargeUnitinPrint__c ||
                    billings[i].ChargeUnit__c != r.ChargeUnit__c ||
                    billings[i].ContainerType__c != r.ContainerType__c ||
                    billings[i].Print__c != r.Print__c ||
                    billings[i].CurrencySelling__c != r.CurrencySelling__c ||
                    billings[i].AdvancePaymentonbehalfofCustomer__c != r.AdvancePaymentonbehalfofCustomer__c ||
                    billings[i].UnitPriceofSellingLocal__c != r.UnitPriceofSellingLocal__c ||
                    billings[i].UnitPriceFCY__c != r.UnitPriceFCY__c ||
                    billings[i].UnitPriceofBuying3rdCurrency__c != r.UnitPriceofBuying3rdCurrency__c ||
                    billings[i].TaxRateSelling__c != r.TaxRateSelling__c ||
                    billings[i].FxRateID__c != r.FxRateID__c ||
                    billings[i].ExchangeRateSelling__c != r.ExchangeRateSelling__c ||
                    billings[i].CurrencyConversionforSelling__c != r.CurrencyConversionforSelling__c ||
                    billings[i].VATrateselling__c != r.VATrateselling__c ||
                    billings[i].CurrencyBuying__c != r.CurrencyBuying__c ||
                        billings[i].AdvancePaymentonbehalfofOurCompany__c != r.AdvancePaymentonbehalfofOurCompany__c ||
                        billings[i].UnitPriceofBuyingLocal__c != r.UnitPriceofBuyingLocal__c ||
                        billings[i].UnitPriceofBuyingFCY__c != r.UnitPriceofBuyingFCY__c ||
                        billings[i].UnitPriceofBuying3rdCurrency__c != r.UnitPriceofBuying3rdCurrency__c ||
                        billings[i].TaxRateBuying__c != r.TaxRateBuying__c ||
                        billings[i].ExchangeRateBuying__c != r.ExchangeRateBuying__c ||
                        billings[i].CurrencyConversionforBuying__c != r.CurrencyConversionforBuying__c ||
                        billings[i].VATratebuying__c != r.VATratebuying__c
                    ){
                        itemsIdsToRemove.add(r);
                    }
                    
                
            }
           
           
        }
        
        System.debug('debug3  :'+itemsIdsToRemove.size());
        try {
        	update itemsIdsToRemove;
        	return JSON.serialize(itemsIdsToRemove);
        }
        catch (Exception e) {
            throw new DmlException(e.getMessage());
        }
    }
}