force-app/main/default/objects/CompanyInformation__c/CompanyInformation__c.object-meta.xml
<CustomObject>
    <label>Company Information</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CompanyInformation__c/fields/Branch1__c.field-meta.xml
<CustomField>
    <fullName>Branch1__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Branch</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/fields/CompanyLogo__c.field-meta.xml
<CustomField>
    <fullName>CompanyLogo__c</fullName>
    <label>Company Logo</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/fields/TaxCode__c.field-meta.xml
<CustomField>
    <fullName>TaxCode__c</fullName>
    <label>Tax Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/fields/Tel__c.field-meta.xml
<CustomField>
    <fullName>Tel__c</fullName>
    <label>Tel</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/FTMSSO__c.object-meta.xml
<CustomObject>
    <label>Shipment.</label>
    <nameField>
        <displayFormat>FSO-{000000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments.</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSSO__c/fields/AgentDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>AgentDetailInformation__c</fullName>
    <label>Agent’s Detail Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoQuantity__c.field-meta.xml
<CustomField>
    <fullName>CargoQuantity__c</fullName>
    <label>Cargo Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoUnit__c.field-meta.xml
<CustomField>
    <fullName>CargoUnit__c</fullName>
    <label>Cargo Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargoUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ConsigneeDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>ConsigneeDetailInformation__c</fullName>
    <label>Consignee’s Detail Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Date_of_issue__c.field-meta.xml
<CustomField>
    <fullName>Date_of_issue__c</fullName>
    <label>Date of issue</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/FinalDestination__c.field-meta.xml
<CustomField>
    <fullName>FinalDestination__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Final Destination</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>Gross Weight</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HouseFreightCollectPrepaid__c.field-meta.xml
<CustomField>
    <fullName>HouseFreightCollectPrepaid__c</fullName>
    <label>House Freight Collect/Prepaid</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collected</fullName>
            </value>
            <value>
                <fullName>Prepaid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HouseNotifyPartyDetail_Information__c.field-meta.xml
<CustomField>
    <fullName>HouseNotifyPartyDetail_Information__c</fullName>
    <label>House Notify Party’s Detail Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MarksNumbersAttachment__c.field-meta.xml
<CustomField>
    <fullName>MarksNumbersAttachment__c</fullName>
    <label>Marks &amp; Numbers Attachment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MeasurementTotalCBM__c.field-meta.xml
<CustomField>
    <fullName>MeasurementTotalCBM__c</fullName>
    <label>Measurement (Total CBM)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/NumberofOriginalHBLIssued__c.field-meta.xml
<CustomField>
    <fullName>NumberofOriginalHBLIssued__c</fullName>
    <label>Number of Original H B/L Issued</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZERO(0)</fullName>
            </value>
            <value>
                <fullName>ONE(1)</fullName>
            </value>
            <value>
                <fullName>TWO(2)</fullName>
            </value>
            <value>
                <fullName>THREE(3)</fullName>
                <default>true</default>
                <label>THREE(3)</label>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Payable_At_HBL__c.field-meta.xml
<CustomField>
    <fullName>Payable_At_HBL__c</fullName>
    <formula>IF(TEXT(HouseFreightCollectPrepaid__c)=&quot;Prepaid&quot;, POLAODsDetailInformation__c, PODAOAsDetailInformation__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payable At (HBL)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Place_of_issue__c.field-meta.xml
<CustomField>
    <fullName>Place_of_issue__c</fullName>
    <label>Place of issue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PlaceofDelivery__c.field-meta.xml
<CustomField>
    <fullName>PlaceofDelivery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place of Delivery</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PlaceofReceipt__c.field-meta.xml
<CustomField>
    <fullName>PlaceofReceipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place of Receipt</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Plural_Cargo_Unit__c.field-meta.xml
<CustomField>
    <fullName>Plural_Cargo_Unit__c</fullName>
    <formula>IF( CargoQuantity__c = 1, TEXT(CargoUnit__c) ,
IF(Text(CargoUnit__c)= &quot;&quot;, &quot;&quot;,
IF(Text(CargoUnit__c)= &quot;BALE, COMPRESSED&quot;, &quot;BALES, COMPRESSED&quot;,
IF(Text(CargoUnit__c)= &quot;CARBOY, NON-PROTECTED&quot;, &quot;CARBOYS, NON-PROTECTED&quot;,
IF(
  OR(
    RIGHT(TEXT(CargoUnit__c), 1) = &quot;S&quot;,
    RIGHT(TEXT(CargoUnit__c), 1) = &quot;Z&quot;,
    RIGHT(TEXT(CargoUnit__c), 1) = &quot;O&quot;,
    RIGHT(TEXT(CargoUnit__c), 2) = &quot;SH&quot;,
    RIGHT(TEXT(CargoUnit__c), 2) = &quot;CH&quot;,
    RIGHT(TEXT(CargoUnit__c), 2) = &quot;SS&quot;,
    RIGHT(TEXT(CargoUnit__c), 1) = &quot;X&quot;,
    RIGHT(TEXT(CargoUnit__c), 2) = &quot;SS&quot;),
  	TEXT(CargoUnit__c) &amp; &quot;ES&quot;,
IF(
    OR(
RIGHT(TEXT(CargoUnit__c), 2) = &quot;AY&quot;,
RIGHT(TEXT(CargoUnit__c), 2) = &quot;OY&quot;,
RIGHT(TEXT(CargoUnit__c), 2) = &quot;EY&quot;,
RIGHT(TEXT(CargoUnit__c), 2) = &quot;IY&quot;,
RIGHT(TEXT(CargoUnit__c), 2) = &quot;UY&quot;
),
     TEXT(CargoUnit__c) &amp; &quot;S&quot;,
IF(
    RIGHT(TEXT(CargoUnit__c), 1) = &quot;Y&quot;,
     LEFT(TEXT(CargoUnit__c), LEN(TEXT(CargoUnit__c)) - 1) &amp; &quot;IES&quot;,
  IF(
      RIGHT(TEXT(CargoUnit__c), 2) = &quot;FE&quot;,
      IF(
        TEXT(CargoUnit__c) = &quot;wife&quot;,
        &quot;wives&quot;,
        IF(
          TEXT(CargoUnit__c) = &quot;wolf&quot;,
          &quot;wolves&quot;,
          LEFT(TEXT(CargoUnit__c), LEN(TEXT(CargoUnit__c)) - 2) &amp; &quot;VES&quot;
        )
      ),
      TEXT(CargoUnit__c) &amp; &quot;S&quot;
    )
  )
)
))))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plural Cargo Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PODAOA__c.field-meta.xml
<CustomField>
    <fullName>PODAOA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.D(A.O.A)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/POLAOD__c.field-meta.xml
<CustomField>
    <fullName>POLAOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.L(A.O.D)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PrepaidAt__c.field-meta.xml
<CustomField>
    <fullName>PrepaidAt__c</fullName>
    <label>Prepaid At</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ShipperDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>ShipperDetailInformation__c</fullName>
    <label>Shipper’s Detail Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PortCode__c/PortCode__c.object-meta.xml
<CustomObject>
    <label>Port Code</label>
    <nameField>
        <label>Port Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Port Code</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PortCode__c/fields/City_Name__c.field-meta.xml
<CustomField>
    <fullName>City_Name__c</fullName>
    <label>City Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortCode__c/fields/CountryName__c.field-meta.xml
<CustomField>
    <fullName>CountryName__c</fullName>
    <formula>Country__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transportation__c/Transportation__c.object-meta.xml
<CustomObject>
    <label>Trucking</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Transportation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Truckings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transportation__c/fields/Cargo_Delivery_Remarks__c.field-meta.xml
<CustomField>
    <fullName>Cargo_Delivery_Remarks__c</fullName>
    <label>Cargo Delivery Remarks</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transportation__c/fields/ETD__c.field-meta.xml
<CustomField>
    <fullName>ETD__c</fullName>
    <label>ETD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transportation__c/fields/FinalDestination__c.field-meta.xml
<CustomField>
    <fullName>FinalDestination__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Final Destination</label>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipLabel>Truckings (Final Destination)</relationshipLabel>
    <relationshipName>Truckings2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transportation__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>Gross Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transportation__c/fields/PlaceofDelivery__c.field-meta.xml
<CustomField>
    <fullName>PlaceofDelivery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place of Delivery</label>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipLabel>Truckings (Place of Delivery)</relationshipLabel>
    <relationshipName>Truckings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transportation__c/fields/PlaceofReceipt__c.field-meta.xml
<CustomField>
    <fullName>PlaceofReceipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place of Receipt</label>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipLabel>Truckings (Place of Receipt)</relationshipLabel>
    <relationshipName>Truckings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transportation__c/fields/TruckingBillNo__c.field-meta.xml
<CustomField>
    <fullName>TruckingBillNo__c</fullName>
    <label>Trucking Bill No</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Branch.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cambodia</fullName>
    </customValue>
    <customValue>
        <fullName>Hải Phòng</fullName>
    </customValue>
    <customValue>
        <fullName>Hồ Chí Minh</fullName>
        <default>true</default>
        <label>Hồ Chí Minh</label>
    </customValue>
    <customValue>
        <fullName>Đà Nẵng</fullName>
    </customValue>
    <customValue>
        <fullName>Taiwan</fullName>
    </customValue>
    <masterLabel>Branch</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/CargoUnit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B/PLT</fullName>
    </customValue>
    <customValue>
        <fullName>BAG</fullName>
    </customValue>
    <customValue>
        <fullName>BAL</fullName>
    </customValue>
    <customValue>
        <fullName>BALE</fullName>
    </customValue>
    <customValue>
        <fullName>BALE, COMPRESSED</fullName>
    </customValue>
    <customValue>
        <fullName>Bale,non-compressed</fullName>
        <label>BALE, NON-COMPRESSED</label>
    </customValue>
    <customValue>
        <fullName>Bar</fullName>
        <label>BAR</label>
    </customValue>
    <customValue>
        <fullName>BARE</fullName>
    </customValue>
    <customValue>
        <fullName>BARREL</fullName>
    </customValue>
    <customValue>
        <fullName>BILL</fullName>
    </customValue>
    <customValue>
        <fullName>BIN</fullName>
    </customValue>
    <customValue>
        <fullName>BOX</fullName>
    </customValue>
    <customValue>
        <fullName>BOX CARTON</fullName>
    </customValue>
    <customValue>
        <fullName>BOXE</fullName>
    </customValue>
    <customValue>
        <fullName>BOXPAL</fullName>
    </customValue>
    <customValue>
        <fullName>BUCKET</fullName>
    </customValue>
    <customValue>
        <fullName>BULK</fullName>
    </customValue>
    <customValue>
        <fullName>BUNDLE</fullName>
    </customValue>
    <customValue>
        <fullName>CAGE</fullName>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
    </customValue>
    <customValue>
        <fullName>Can,cylindrical</fullName>
        <label>CAN, CYLINDRICAL</label>
    </customValue>
    <customValue>
        <fullName>Can,rectangular</fullName>
        <label>CAN, RECTANGULAR</label>
    </customValue>
    <customValue>
        <fullName>CARBOY, NON-PROTECTED</fullName>
    </customValue>
    <customValue>
        <fullName>Carboy,protected</fullName>
        <label>CARBOY, PROTECTED</label>
    </customValue>
    <customValue>
        <fullName>CARDBOARD</fullName>
    </customValue>
    <customValue>
        <fullName>CARDBOXE</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON BOX</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON BOXE</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON PALLET</fullName>
    </customValue>
    <masterLabel>Cargo Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/truckingBillController.cls
public with sharing class truckingBillController {
    public CompanyInformation__c Company {get;set;}
    public Transportation__c trains {get;set;}
    public FTMSSO__c So {get;set;}


    private static Set<String> SoQuery = new Set<String>();
    private static Set<String> trainQuery = new Set<String>();

    static{
        SoQuery.add('ShipperDetailInformation__c');
        SoQuery.add('ConsigneeDetailInformation__c');
        SoQuery.add('HouseNotifyPartyDetail_Information__c');
        SoQuery.add('PlaceofReceipt__r.City_Name__c');
        SoQuery.add('PlaceofReceipt__r.CountryName__c');
        SoQuery.add('POLAOD__r.City_Name__c');
        SoQuery.add('POLAOD__r.CountryName__c');
        SoQuery.add('PODAOA__r.City_Name__c');
        SoQuery.add('PODAOA__r.CountryName__c');
        SoQuery.add('PlaceofDelivery__r.City_Name__c');
        SoQuery.add('PlaceofDelivery__r.CountryName__c');
        SoQuery.add('FinalDestination__r.City_Name__c');
        SoQuery.add('FinalDestination__r.CountryName__c');
        SoQuery.add('MarksNumbersAttachment__c');
        SoQuery.add('CargoQuantity__c');
        SoQuery.add('CargoUnit__c');
        SoQuery.add('DescriptionofGoods__c');
        SoQuery.add('GrossWeight__c');
        SoQuery.add('MeasurementTotalCBM__c');
        SoQuery.add('ETD__c');
        SoQuery.add('HouseFreightCollectPrepaid__c');
        SoQuery.add('AgentDetailInformation__c');
        SoQuery.add('PrepaidAt__c');
        SoQuery.add('Payable_At_HBL__c');
        SoQuery.add('NumberofOriginalHBLIssued__c');
        SoQuery.add('Place_of_issue__c');
        SoQuery.add('Date_of_issue__c');
        SoQuery.add('PODAOA__r.City_Name__c');
        SoQuery.add('Plural_Cargo_Unit__c');

        
        
        
        trainQuery.add('Cargo_Delivery_Remarks__c');
        trainQuery.add('TruckingBillNo__c');



    }
    public truckingBillController() {
        String scheduleID = ApexPages.currentPage().getParameters().get('id');
        String OderID = ApexPages.currentPage().getParameters().get('orderId');
     
        trains = getDonHang(scheduleID);
        So = getSo(OderID);
        Company= [SELECT Name, Id,CompanyLogo__c,Address__c,TaxCode__c,Tel__c,Website__c,Email__c  FROM CompanyInformation__c  WHERE Branch1__c = 'Hồ Chí Minh' limit 1];

    }

    private Transportation__c getDonHang(String scheduleID){
        String strSelect = String.join(new List<String>(trainQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM Transportation__c'
                    + ' WHERE Id = \'' + scheduleID + '\'';
        Transportation__c donhang;
        try{
            donhang = Database.query(strQuery);
        } catch(QueryException e){
            donhang = new Transportation__c();
        }
        return donhang;
    }

    private FTMSSO__c getSo(String scheduleID){
        String strSelect = String.join(new List<String>(SoQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM FTMSSO__c'
                    + ' WHERE Id = \'' + scheduleID + '\'';
                    FTMSSO__c donhang;
        try{
            donhang = Database.query(strQuery);
        } catch(QueryException e){
            donhang = new FTMSSO__c();
        }
        return donhang;
    }

  
}