force-app/main/default/objects/CompanyInformation__c/CompanyInformation__c.object-meta.xml
<CustomObject>
    <label>Company Information</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CompanyInformation__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch (not used)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ha Noi</fullName>
            </value>
            <value>
                <fullName>Hai Phong</fullName>
            </value>
            <value>
                <fullName>Ho Chi Minh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSBill__c/FTMSBill__c.object-meta.xml
<CustomObject>
    <label>F/TMS Bill</label>
    <nameField>
        <displayFormat>FTB-{000000}</displayFormat>
        <label>F/TMS Bill ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>F/TMS Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSBill__c/fields/BillNameatPrintENG__c.field-meta.xml
<CustomField>
    <fullName>BillNameatPrintENG__c</fullName>
    <label>Bill Name at Print(ENG)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/BillNameatPrintLocal__c.field-meta.xml
<CustomField>
    <fullName>BillNameatPrintLocal__c</fullName>
    <label>Bill Name at Print(Local)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/FTMSSO__c.field-meta.xml
<CustomField>
    <fullName>FTMSSO__c</fullName>
    <label>F/TMS S/O</label>
    <referenceTo>FTMSSO__c</referenceTo>
    <relationshipLabel>F/TMS Bills</relationshipLabel>
    <relationshipName>F_TMS_Bills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/TaxRateSelling__c.field-meta.xml
<CustomField>
    <fullName>TaxRateSelling__c</fullName>
    <label>Tax Rate-Selling(%)</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/TotalSellingInclTaxFCY__c.field-meta.xml
<CustomField>
    <fullName>TotalSellingInclTaxFCY__c</fullName>
    <formula>AmountTaxSellingFCY__c +  TotalAmountofSellingFCY__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Selling Incl Tax (FCY)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/TotalSellingInclTaxLocal__c.field-meta.xml
<CustomField>
    <fullName>TotalSellingInclTaxLocal__c</fullName>
    <formula>AmountTaxSellingLocal__c +  TotalAmountofSellingLocal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Selling Incl Tax (Local)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/FTMSSO__c.object-meta.xml
<CustomObject>
    <label>Shipment.</label>
    <nameField>
        <displayFormat>FSO-{000000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments.</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSSO__c/fields/agentnamefor__c.field-meta.xml
<CustomField>
    <fullName>agentnamefor__c</fullName>
    <formula>IF (NOT(ISBLANK( Agent__r.AccountNameENG__c )), Agent__r.AccountNameENG__c , NULL)</formula>
    <label>agent name - for</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch (not used)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ha Noi</fullName>
                <default>true</default>
                <label>Ha Noi</label>
            </value>
            <value>
                <fullName>Hai Phong</fullName>
            </value>
            <value>
                <fullName>Ho Chi Minh</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/BranchpickupDO__c.field-meta.xml
<CustomField>
    <fullName>BranchpickupDO__c</fullName>
    <label>Branch pick up DO</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ha Noi</fullName>
            </value>
            <value>
                <fullName>Hai Phong</fullName>
            </value>
            <value>
                <fullName>Ho Chi Minh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoQuantity__c.field-meta.xml
<CustomField>
    <fullName>CargoQuantity__c</fullName>
    <label>Cargo Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoUnit__c.field-meta.xml
<CustomField>
    <fullName>CargoUnit__c</fullName>
    <label>Cargo Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargoUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ChargeableWeight__c.field-meta.xml
<CustomField>
    <fullName>ChargeableWeight__c</fullName>
    <label>Chargeable Weight</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Consignee__c.field-meta.xml
<CustomField>
    <fullName>Consignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consignee</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>F_TMS_S_O2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ConsigneeDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>ConsigneeDetailInformation__c</fullName>
    <label>Consignee’s Detail Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ConsigneeDetailInformation_text__c.field-meta.xml
<CustomField>
    <fullName>ConsigneeDetailInformation_text__c</fullName>
    <label>Consignee&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>Gross Weight</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HAWBNumber__c.field-meta.xml
<CustomField>
    <fullName>HAWBNumber__c</fullName>
    <label>H AWB Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HouseNotifyParty__c.field-meta.xml
<CustomField>
    <fullName>HouseNotifyParty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>House Notify Party</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>F_TMS_S_O3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/JobRequestID__c.field-meta.xml
<CustomField>
    <fullName>JobRequestID__c</fullName>
    <label>File No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MAWBNumber__c.field-meta.xml
<CustomField>
    <fullName>MAWBNumber__c</fullName>
    <label>MAWB Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PackageUnitCode__c.field-meta.xml
<CustomField>
    <fullName>PackageUnitCode__c</fullName>
    <label>Package Unit Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BK</fullName>
            </value>
            <value>
                <fullName>BL</fullName>
            </value>
            <value>
                <fullName>BN</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>BX</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CG</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CK</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CP</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>CS</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>CX</fullName>
            </value>
            <value>
                <fullName>CY</fullName>
            </value>
            <value>
                <fullName>DJ</fullName>
            </value>
            <value>
                <fullName>DP</fullName>
            </value>
            <value>
                <fullName>DR</fullName>
            </value>
            <value>
                <fullName>FB</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>FT</fullName>
            </value>
            <value>
                <fullName>HD</fullName>
            </value>
            <value>
                <fullName>HG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Plural_Cargo_Unit__c.field-meta.xml
<CustomField>
    <fullName>Plural_Cargo_Unit__c</fullName>
    <formula>IF( CargoQuantity__c = 1, TEXT(CargoUnit__c) ,
IF(Text(CargoUnit__c)= &quot;&quot;, &quot;&quot;,
IF(Text(CargoUnit__c)= &quot;BALE, COMPRESSED&quot;, &quot;BALES, COMPRESSED&quot;,
IF(Text(CargoUnit__c)= &quot;CARBOY, NON-PROTECTED&quot;, &quot;CARBOYS, NON-PROTECTED&quot;,
IF(
  OR(
    RIGHT(TEXT(CargoUnit__c), 1) = &quot;S&quot;,
    RIGHT(TEXT(CargoUnit__c), 1) = &quot;Z&quot;,
    RIGHT(TEXT(CargoUnit__c), 1) = &quot;O&quot;,
    RIGHT(TEXT(CargoUnit__c), 2) = &quot;SH&quot;,
    RIGHT(TEXT(CargoUnit__c), 2) = &quot;CH&quot;,
    RIGHT(TEXT(CargoUnit__c), 2) = &quot;SS&quot;,
    RIGHT(TEXT(CargoUnit__c), 1) = &quot;X&quot;,
    RIGHT(TEXT(CargoUnit__c), 2) = &quot;SS&quot;),
  	TEXT(CargoUnit__c) &amp; &quot;ES&quot;,
IF(
    OR(
RIGHT(TEXT(CargoUnit__c), 2) = &quot;AY&quot;,
RIGHT(TEXT(CargoUnit__c), 2) = &quot;OY&quot;,
RIGHT(TEXT(CargoUnit__c), 2) = &quot;EY&quot;,
RIGHT(TEXT(CargoUnit__c), 2) = &quot;IY&quot;,
RIGHT(TEXT(CargoUnit__c), 2) = &quot;UY&quot;
),
     TEXT(CargoUnit__c) &amp; &quot;S&quot;,
IF(
    RIGHT(TEXT(CargoUnit__c), 1) = &quot;Y&quot;,
     LEFT(TEXT(CargoUnit__c), LEN(TEXT(CargoUnit__c)) - 1) &amp; &quot;IES&quot;,
  IF(
      RIGHT(TEXT(CargoUnit__c), 2) = &quot;FE&quot;,
      IF(
        TEXT(CargoUnit__c) = &quot;wife&quot;,
        &quot;wives&quot;,
        IF(
          TEXT(CargoUnit__c) = &quot;wolf&quot;,
          &quot;wolves&quot;,
          LEFT(TEXT(CargoUnit__c), LEN(TEXT(CargoUnit__c)) - 2) &amp; &quot;VES&quot;
        )
      ),
      TEXT(CargoUnit__c) &amp; &quot;S&quot;
    )
  )
)
))))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plural Cargo Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Shippernamefor__c.field-meta.xml
<CustomField>
    <fullName>Shippernamefor__c</fullName>
    <formula>IF(NOT(ISBLANK( Shipper__r.AccountNameENG__c )), Shipper__r.AccountNameENG__c , NULL)</formula>
    <label>Shipper name - for</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/TotalSellingInclTaxFCY__c.field-meta.xml
<CustomField>
    <fullName>TotalSellingInclTaxFCY__c</fullName>
    <label>Total Selling Incl Tax (USD)</label>
    <summarizedField>FTMSBill__c.TotalSellingInclTaxFCY__c</summarizedField>
    <summaryFilterItems>
        <field>FTMSBill__c.CurrencySelling__c</field>
        <operation>equals</operation>
        <value>USD</value>
    </summaryFilterItems>
    <summaryForeignKey>FTMSBill__c.FTMSSO__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/TotalSellingInclTaxLocal__c.field-meta.xml
<CustomField>
    <fullName>TotalSellingInclTaxLocal__c</fullName>
    <label>Total Selling Incl Tax (Local)</label>
    <summarizedField>FTMSBill__c.TotalSellingInclTaxLocal__c</summarizedField>
    <summaryForeignKey>FTMSBill__c.FTMSSO__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/VesselFlight__c.field-meta.xml
<CustomField>
    <fullName>VesselFlight__c</fullName>
    <label>Vessel/Flight</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/CargoUnit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B/PLT</fullName>
    </customValue>
    <customValue>
        <fullName>BAG</fullName>
    </customValue>
    <customValue>
        <fullName>BAL</fullName>
    </customValue>
    <customValue>
        <fullName>BALE</fullName>
    </customValue>
    <customValue>
        <fullName>BALE, COMPRESSED</fullName>
    </customValue>
    <customValue>
        <fullName>Bale,non-compressed</fullName>
        <label>BALE, NON-COMPRESSED</label>
    </customValue>
    <customValue>
        <fullName>Bar</fullName>
        <label>BAR</label>
    </customValue>
    <customValue>
        <fullName>BARE</fullName>
    </customValue>
    <customValue>
        <fullName>BARREL</fullName>
    </customValue>
    <customValue>
        <fullName>BILL</fullName>
    </customValue>
    <customValue>
        <fullName>BIN</fullName>
    </customValue>
    <customValue>
        <fullName>BOX</fullName>
    </customValue>
    <customValue>
        <fullName>BOX CARTON</fullName>
    </customValue>
    <customValue>
        <fullName>BOXE</fullName>
    </customValue>
    <customValue>
        <fullName>BOXPAL</fullName>
    </customValue>
    <customValue>
        <fullName>BUCKET</fullName>
    </customValue>
    <customValue>
        <fullName>BULK</fullName>
    </customValue>
    <customValue>
        <fullName>BUNDLE</fullName>
    </customValue>
    <customValue>
        <fullName>CAGE</fullName>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
    </customValue>
    <customValue>
        <fullName>Can,cylindrical</fullName>
        <label>CAN, CYLINDRICAL</label>
    </customValue>
    <customValue>
        <fullName>Can,rectangular</fullName>
        <label>CAN, RECTANGULAR</label>
    </customValue>
    <customValue>
        <fullName>CARBOY, NON-PROTECTED</fullName>
    </customValue>
    <customValue>
        <fullName>Carboy,protected</fullName>
        <label>CARBOY, PROTECTED</label>
    </customValue>
    <customValue>
        <fullName>CARDBOARD</fullName>
    </customValue>
    <customValue>
        <fullName>CARDBOXE</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON BOX</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON BOXE</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON PALLET</fullName>
    </customValue>
    <masterLabel>Cargo Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ArrivalNoticeController.cls
public with sharing class ArrivalNoticeController {
    public FTMSSO__c shipment {get; set;}
    public List<FTMSBill__c> lstBill {get; set;}
    private String shipId {get; set;}
    public CompanyInformation__c ComInf {get; set;}
    public CompanyInformation__c DOinfo {get; set;}
    public Decimal totalVND {get; set;}
    public Decimal totalUSD {get; set;}
    public Boolean requiredPackage {get;set;}

    private static Set<String> fieldsShipQuery = new Set<String>();
    private static Set<String> fieldsBillQuery = new Set<String>();
    private static Set<String> fieldsComInQuery = new Set<String>();
    private static Set<String> fieldsDOinfoQuery = new Set<String>();
    static{
        fieldsShipQuery.add('Id');
        fieldsShipQuery.add('Name');
        fieldsShipQuery.add('JobRequestID__c');
        fieldsShipQuery.add('ETA__c');
        fieldsShipQuery.add('ConsigneeDetailInformation__c');
        fieldsShipQuery.add('agentnamefor__c');
        fieldsShipQuery.add('VesselFlight__c');
        fieldsShipQuery.add('Warehouse__c');
        fieldsShipQuery.add('HAWBNumber__c');
        fieldsShipQuery.add('MAWBNumber__c');
        fieldsShipQuery.add('CargoQuantity__c');
        fieldsShipQuery.add('CargoUnit__c');
        fieldsShipQuery.add('GrossWeight__c');
        fieldsShipQuery.add('Shippernamefor__c');
        fieldsShipQuery.add('DescriptionofGoods__c');
        fieldsShipQuery.add('Branch__c');
        fieldsShipQuery.add('ChargeableWeight__c');
        fieldsShipQuery.add('ConsigneeDetailInformation_text__c');
        fieldsShipQuery.add('Consignee__c');
        fieldsShipQuery.add('HouseNotifyParty__c');
        fieldsShipQuery.add('HouseNotifyParty__r.Name');
        fieldsShipQuery.add('PackageUnitCode__c');
        fieldsShipQuery.add('BranchpickupDO__c');
        fieldsShipQuery.add('Plural_Cargo_Unit__c');
    }

    static{
        fieldsBillQuery.add('Id');
        fieldsBillQuery.add('Name');
        fieldsBillQuery.add('BillNameatPrintLocal__c');
        fieldsBillQuery.add('BillNameatPrintENG__c');
        fieldsBillQuery.add('TaxRateSelling__c');
        fieldsBillQuery.add('TotalSellingInclTaxFCY__c');
        fieldsBillQuery.add('TotalSellingInclTaxLocal__c');
        fieldsBillQuery.add('CurrencySelling__c');
        fieldsBillQuery.add('InvoiceTo__c');
    }

    static {
        fieldsComInQuery.add('Id');
        fieldsComInQuery.add('Name');
        fieldsComInQuery.add('Address__c');
        fieldsComInQuery.add('Tel__c');
        fieldsComInQuery.add('Fax__c');
        fieldsComInQuery.add('Taxcode__c');
        fieldsComInQuery.add('Branch__c');
        fieldsComInQuery.add('CompanyLogo__c');
        fieldsComInQuery.add('Email__c');
        fieldsComInQuery.add('Website__c');
    }

    static {
        fieldsDOinfoQuery.add('Name');
        fieldsDOinfoQuery.add('Address__c');
        fieldsDOinfoQuery.add('Tel__c');
        fieldsDOinfoQuery.add('Fax__c');
    }
    public ArrivalNoticeController() {
        totalVND = 0;
        totalUSD = 0;
        DOinfo = new CompanyInformation__c();
        shipId = ApexPages.currentPage().getParameters().get('Id');
        requiredPackage = Boolean.valueOf(ApexPages.currentPage().getParameters().get('checkPackage'));
        shipment = getShipment(shipId);
        
        if(shipment.CargoQuantity__c > 1){
            shipment.CargoUnit__c = shipment.CargoUnit__c + 's';
        }

        // String consignee = (shipment.HouseNotifyParty__c == null || shipment.HouseNotifyParty__r.Name == 'SAME AS CONSIGNEE')?shipment.Consignee__c: shipment.HouseNotifyParty__c;
        // lstBill = getListBill(shipId,consignee);
        lstBill = getListBill(shipId,shipment.Consignee__c,shipment.HouseNotifyParty__c);
        ComInf = getComIn(shipment.Branch__c);
        if(shipment.BranchpickupDO__c != null){
            DOinfo = getDOin(shipment.BranchpickupDO__c);
            System.debug('1133: ' + DOinfo);
        }
        
        for (FTMSBill__c bill : lstBill) {
            if (bill.CurrencySelling__c == 'USD'){
                if (bill.TotalSellingInclTaxFCY__c != null) {
                    totalUSD += bill.TotalSellingInclTaxFCY__c;
                }
            }
            
            if (bill.CurrencySelling__c == 'VND'){
                if (bill.TotalSellingInclTaxLocal__c != null) {
                    totalVND += bill.TotalSellingInclTaxLocal__c;
                }
            }
        }

    }

    
    private FTMSSO__c getShipment(String shipId){
        String strSelect = String.join(new List<String>(fieldsShipQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM FTMSSO__c'
                    + ' WHERE Id = \'' + String.escapeSingleQuotes(shipId) + '\'';
        FTMSSO__c ship;
        try{
            ship = Database.query(strQuery);
        } catch(QueryException e){
            ship = new FTMSSO__c();
        }
        return ship;
    }
    private List<FTMSBill__c> getListBill(String shipId, String consignee, String notifyparty){
        system.debug('123: ' + consignee);
        List<FTMSBill__c> listBill;
        String strSelect = String.join(new List<String>(fieldsBillQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM FTMSBill__c'
                    + ' WHERE FTMSSO__c = \'' + String.escapeSingleQuotes(shipId) + '\' AND Print__c = true';
        if (consignee != null && notifyparty == null){
            strQuery += ' AND InvoiceTo__c = \'' + String.escapeSingleQuotes(consignee)+'\'';
        } else if (consignee == null && notifyparty != null) {
            strQuery += ' AND InvoiceTo__c = \'' + String.escapeSingleQuotes(notifyparty)+'\'';
        } else if (consignee != null && notifyparty != null) {
            strQuery += ' AND (InvoiceTo__c = \'' + String.escapeSingleQuotes(consignee)+'\' OR InvoiceTo__c = \'' + String.escapeSingleQuotes(notifyparty) +'\')';
        } else {
            listBill = new List<FTMSBill__c>();
            return listBill;
        }
        strQuery += ' ORDER BY Name ASC';
        try{
            listBill = Database.query(strQuery);         
        } catch(QueryException e){
            listBill = new List<FTMSBill__c>();
        }
        return listBill;
    }
    private CompanyInformation__c getComIn(String branch){
        String strSelect = String.join(new List<String>(fieldsComInQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM CompanyInformation__c'
                    + ' WHERE Branch__c = \'' + String.escapeSingleQuotes(branch) + '\'';
        strQuery += ' ORDER BY Name ASC Limit 1';        
        CompanyInformation__c ComIn;
        try{
            ComIn = Database.query(strQuery);
        } catch(QueryException e){
            ComIn = new CompanyInformation__c();
        }
        return ComIn;
    }

    private CompanyInformation__c getDOin(String branch){
        String strSelect = String.join(new List<String>(fieldsDOinfoQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM CompanyInformation__c'
                    + ' WHERE Branch__c = \'' + String.escapeSingleQuotes(branch) + '\'';
        strQuery += ' ORDER BY Name ASC Limit 1';        
        CompanyInformation__c DOIn;
        try{
            DOIn = Database.query(strQuery);
        } catch(QueryException e){
            DOIn = new CompanyInformation__c();
        }
        return DOIn;
    }
}