force-app/main/default/objects/CompanyInformation__c/CompanyInformation__c.object-meta.xml
<CustomObject>
    <label>Company Information</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CompanyInformation__c/fields/CompanyLogo__c.field-meta.xml
<CustomField>
    <fullName>CompanyLogo__c</fullName>
    <label>Company Logo</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/FTMSSO__c.object-meta.xml
<CustomObject>
    <label>Shipment.</label>
    <nameField>
        <displayFormat>FSO-{000000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments.</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSSO__c/fields/AgentDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>AgentDetailInformation__c</fullName>
    <label>Agent’s Detail Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoDeliveryRemark__c.field-meta.xml
<CustomField>
    <fullName>CargoDeliveryRemark__c</fullName>
    <label>Cargo Delivery Remark</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoQuantity__c.field-meta.xml
<CustomField>
    <fullName>CargoQuantity__c</fullName>
    <label>Cargo Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoUnit__c.field-meta.xml
<CustomField>
    <fullName>CargoUnit__c</fullName>
    <label>Cargo Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargoUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ChargeableWeight__c.field-meta.xml
<CustomField>
    <fullName>ChargeableWeight__c</fullName>
    <label>Chargeable Weight</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ConsigneeDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>ConsigneeDetailInformation__c</fullName>
    <label>Consignee’s Detail Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Date_of_issue__c.field-meta.xml
<CustomField>
    <fullName>Date_of_issue__c</fullName>
    <label>Date of issue</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/DimensionDetail__c.field-meta.xml
<CustomField>
    <fullName>DimensionDetail__c</fullName>
    <label>Dimension Detail</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/File_No1__c.field-meta.xml
<CustomField>
    <fullName>File_No1__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;+Id ,  JobRequestID__c  , &quot;_blank&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>File No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/FinalDestination__c.field-meta.xml
<CustomField>
    <fullName>FinalDestination__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Final Destination</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>Gross Weight</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HAWBNumber__c.field-meta.xml
<CustomField>
    <fullName>HAWBNumber__c</fullName>
    <label>H AWB Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HouseFreightCollectPrepaid__c.field-meta.xml
<CustomField>
    <fullName>HouseFreightCollectPrepaid__c</fullName>
    <label>House Freight Collect/Prepaid</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collected</fullName>
            </value>
            <value>
                <fullName>Prepaid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/JobRequestID__c.field-meta.xml
<CustomField>
    <fullName>JobRequestID__c</fullName>
    <label>File No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MAWBNumber__c.field-meta.xml
<CustomField>
    <fullName>MAWBNumber__c</fullName>
    <label>MAWB Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Place_of_issue__c.field-meta.xml
<CustomField>
    <fullName>Place_of_issue__c</fullName>
    <label>Place of issue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PODAOA2nd__c.field-meta.xml
<CustomField>
    <fullName>PODAOA2nd__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.D(A.O.A) (2nd)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PODAOA3rd__c.field-meta.xml
<CustomField>
    <fullName>PODAOA3rd__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.D(A.O.A) (3rd)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PODAOA__c.field-meta.xml
<CustomField>
    <fullName>PODAOA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.D(A.O.A)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/POLAOD__c.field-meta.xml
<CustomField>
    <fullName>POLAOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.L(A.O.D)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/RateCharge__c.field-meta.xml
<CustomField>
    <fullName>RateCharge__c</fullName>
    <label>Rate/Charge</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ShipperDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>ShipperDetailInformation__c</fullName>
    <label>Shipper’s Detail Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/VesselFlight2nd__c.field-meta.xml
<CustomField>
    <fullName>VesselFlight2nd__c</fullName>
    <label>Vessel/Flight (2nd)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/VesselFlight3rd__c.field-meta.xml
<CustomField>
    <fullName>VesselFlight3rd__c</fullName>
    <label>Vessel/Flight (3rd)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/VesselFlight__c.field-meta.xml
<CustomField>
    <fullName>VesselFlight__c</fullName>
    <label>Vessel/Flight</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortCode__c/PortCode__c.object-meta.xml
<CustomObject>
    <label>Port Code</label>
    <nameField>
        <label>Port Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Port Code</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PortCode__c/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <formula>Country__r.CountryCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortCode__c/fields/CountryName__c.field-meta.xml
<CustomField>
    <fullName>CountryName__c</fullName>
    <formula>Country__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortCode__c/fields/PortCode__c.field-meta.xml
<CustomField>
    <fullName>PortCode__c</fullName>
    <label>Port Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/CargoUnit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B/PLT</fullName>
    </customValue>
    <customValue>
        <fullName>BAG</fullName>
    </customValue>
    <customValue>
        <fullName>BAL</fullName>
    </customValue>
    <customValue>
        <fullName>BALE</fullName>
    </customValue>
    <customValue>
        <fullName>BALE, COMPRESSED</fullName>
    </customValue>
    <customValue>
        <fullName>Bale,non-compressed</fullName>
        <label>BALE, NON-COMPRESSED</label>
    </customValue>
    <customValue>
        <fullName>Bar</fullName>
        <label>BAR</label>
    </customValue>
    <customValue>
        <fullName>BARE</fullName>
    </customValue>
    <customValue>
        <fullName>BARREL</fullName>
    </customValue>
    <customValue>
        <fullName>BILL</fullName>
    </customValue>
    <customValue>
        <fullName>BIN</fullName>
    </customValue>
    <customValue>
        <fullName>BOX</fullName>
    </customValue>
    <customValue>
        <fullName>BOX CARTON</fullName>
    </customValue>
    <customValue>
        <fullName>BOXE</fullName>
    </customValue>
    <customValue>
        <fullName>BOXPAL</fullName>
    </customValue>
    <customValue>
        <fullName>BUCKET</fullName>
    </customValue>
    <customValue>
        <fullName>BULK</fullName>
    </customValue>
    <customValue>
        <fullName>BUNDLE</fullName>
    </customValue>
    <customValue>
        <fullName>CAGE</fullName>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
    </customValue>
    <customValue>
        <fullName>Can,cylindrical</fullName>
        <label>CAN, CYLINDRICAL</label>
    </customValue>
    <customValue>
        <fullName>Can,rectangular</fullName>
        <label>CAN, RECTANGULAR</label>
    </customValue>
    <customValue>
        <fullName>CARBOY, NON-PROTECTED</fullName>
    </customValue>
    <customValue>
        <fullName>Carboy,protected</fullName>
        <label>CARBOY, PROTECTED</label>
    </customValue>
    <customValue>
        <fullName>CARDBOARD</fullName>
    </customValue>
    <customValue>
        <fullName>CARDBOXE</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON BOX</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON BOXE</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON PALLET</fullName>
    </customValue>
    <masterLabel>Cargo Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PrintHAWBController.cls
public with sharing class PrintHAWBController {
    public String id {get; set;}
    public FTMSSO__c shipment {get; set;}
    public FTMSSO__c shipmentnew {get; set;}
    public CompanyInformation__c ComInfo {get; set;}
    public Integer count {get; set;}
    private static Set<String> fieldsQuery = new Set<String>();
    static {
        fieldsQuery.add('Id');
        fieldsQuery.add('MAWBNumber__c');
        fieldsQuery.add('ShipperDetailInformation__c');
        fieldsQuery.add('HAWBNumber__c');
        fieldsQuery.add('ConsigneeDetailInformation__c');
        fieldsQuery.add('CargoQuantity__c');
        fieldsQuery.add('CargoUnit__c');
        fieldsQuery.add('GrossWeight__c');
        fieldsQuery.add('ChargeableWeight__c');
        fieldsQuery.add('AgentDetailInformation__c');
        fieldsQuery.add('RateCharge__c');
        fieldsQuery.add('DescriptionofGoods__c');
        fieldsQuery.add('DimensionDetail__c');
        fieldsQuery.add('POLAOD__r.Name');
        fieldsQuery.add('Date_of_issue__c');
		fieldsQuery.add('Place_of_issue__c');

        fieldsQuery.add('POLAOD__r.CountryName__c');
        fieldsQuery.add('PODAOA__r.PortCode__c');
        fieldsQuery.add('PODAOA2nd__r.PortCode__c');
        fieldsQuery.add('PODAOA3rd__r.PortCode__c');

        fieldsQuery.add('FinalDestination__r.PortCode__c');
        fieldsQuery.add('Currency__c');
        fieldsQuery.add('PODAOA2nd__r.CountryCode__c');

        fieldsQuery.add('PODAOA3rd__r.CountryCode__c');
        fieldsQuery.add('VesselFlight__c');
        fieldsQuery.add('ETD__c');
        fieldsQuery.add('VesselFlight2nd__c');
        fieldsQuery.add('VesselFlight3rd__c');
        fieldsQuery.add('CargoDeliveryRemark__c');
        fieldsQuery.add('HouseFreightCollectPrepaid__c');
    }
    public PrintHAWBController() {
        id = ApexPages.currentPage().getParameters().get('id');
        System.debug('id: ' + id);
        shipment = getShipment(id);
        System.debug('shipment: ' + shipment);
        ComInfo = [SELECT CompanyLogo__c FROM CompanyInformation__c LIMIT 1];
        
        count = 0;
        //  list = new List<String>();
        if(shipment.DescriptionofGoods__c != null){
            List<String> list1 = shipment.DescriptionofGoods__c.split('\n');
            for(String str : list1){
                count++;
            }
            
        }
        if(shipment.DimensionDetail__c != null){
            List<String> list2 = shipment.DimensionDetail__c.split('\n');
           for(String str : list2){
               count++;
           }
            
        }
        System.debug('i: ' + count);
    }

    @AuraEnabled
    public static void createAttatchment(String recordId, String backGround){
        System.debug('recordId: '+recordId);
        FTMSSO__c SO = [SELECT Id, Name, JobRequestID__c, File_No1__c FROM FTMSSO__c WHERE Id =: recordId];
        PageReference pdf_file = backGround ==  'true' ? Page.page_HAWB3 : Page.page_HAWB2;
        pdf_file.getParameters().put('id', recordId);
        String namefile = 'TCL_HAWB_' + SO.JobRequestID__c;
        // for(PicklistEntry value: User.LanguageLocalekey.getDescribe().getPicklistValues()) {
        //     if(value.getValue().contains(language)) {
        //         languaName = value.getLabel();
        //         break;
        //     }
        // }
        String attachName = namefile + '_v';
        String attachNameSearch = attachName + '%';
        // get exist file Name
        List<Attachment> attachments = [SELECT Id, Name, ParentId 
                                        FROM Attachment 
                                        WHERE ParentId =: recordId 
                                        AND Name LIKE : attachNameSearch 
                                        ORDER BY CreatedDate DESC LIMIT 1];
        if(attachments.isEmpty()){
            attachName += '1.1';
        }else{
            String attachNameExist = attachments[0].Name;
            attachNameExist = attachNameExist.substringAfter(attachName);
            attachNameExist = attachNameExist.substringBefore('.pdf');
            Decimal versionNumber = Decimal.valueOf(attachNameExist);
            versionNumber += 0.1;
            attachName += String.valueOf(versionNumber);
        }
        // Attachment attach = new Attachment();
        // Blob body;
        // attach.Name = attachName + '.pdf'; 
        // attach.IsPrivate = false;
        // attach.ParentId = recordId;
        // if(!Test.isRunningTest()){
        //     body = pdf_file.getContentAsPDF();
        //     attach.Body = body;
        //     insert(attach);
        // }
        ContentVersion cv = new ContentVersion();
        // Blob body;
        cv.PathOnClient = attachName + '.pdf';
        cv.Title = attachName + '.pdf';
        cv.Description = attachName + '.pdf';
        cv.FirstPublishLocationId = recordId;
        if(!Test.isRunningTest()){
            // body = pdf_file.getContentAsPDF();
            cv.VersionData = pdf_file.getContentAsPDF();
            // attach.Body = body;
            insert cv;
        }

    }

    private FTMSSO__c getShipment(String shipId){
        String strSelect = String.join(new List<String>(fieldsQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM FTMSSO__c'
                    + ' WHERE Id = \'' + String.escapeSingleQuotes(shipId) + '\'';
        
        FTMSSO__c ship;
        try{
            ship = Database.query(strQuery);
            System.debug('get');
        } catch(QueryException e){
            ship = new FTMSSO__c();
        }
        return ship;
    }
}