force-app/main/default/objects/CompanyInformation__c/CompanyInformation__c.object-meta.xml
<CustomObject>
    <label>Company Information</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CompanyInformation__c/fields/Branch1__c.field-meta.xml
<CustomField>
    <fullName>Branch1__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Branch</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/fields/ShowAddressonHeader__c.field-meta.xml
<CustomField>
    <fullName>ShowAddressonHeader__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Address on Header</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/fields/Tel__c.field-meta.xml
<CustomField>
    <fullName>Tel__c</fullName>
    <label>Tel</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/FTMSSO__c.object-meta.xml
<CustomObject>
    <label>Shipment.</label>
    <nameField>
        <displayFormat>FSO-{000000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments.</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSSO__c/fields/AgentDetailInformation_text__c.field-meta.xml
<CustomField>
    <fullName>AgentDetailInformation_text__c</fullName>
    <label>Agent&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Branch1__c.field-meta.xml
<CustomField>
    <fullName>Branch1__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Branch</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoQuantity__c.field-meta.xml
<CustomField>
    <fullName>CargoQuantity__c</fullName>
    <label>Cargo Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoUnit__c.field-meta.xml
<CustomField>
    <fullName>CargoUnit__c</fullName>
    <label>Cargo Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargoUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Consignee__c.field-meta.xml
<CustomField>
    <fullName>Consignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consignee</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>F_TMS_S_O2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ConsigneeDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>ConsigneeDetailInformation__c</fullName>
    <label>Consignee’s Detail Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ConsigneeDetailInformation_text__c.field-meta.xml
<CustomField>
    <fullName>ConsigneeDetailInformation_text__c</fullName>
    <label>Consignee&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Date_of_issue__c.field-meta.xml
<CustomField>
    <fullName>Date_of_issue__c</fullName>
    <label>Date of issue</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/FinalDestinationsDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>FinalDestinationsDetailInformation__c</fullName>
    <label>Final Destination&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>Gross Weight</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HBLNumber__c.field-meta.xml
<CustomField>
    <fullName>HBLNumber__c</fullName>
    <label>H B/L Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HouseFreightCollectPrepaid__c.field-meta.xml
<CustomField>
    <fullName>HouseFreightCollectPrepaid__c</fullName>
    <label>House Freight Collect/Prepaid</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collected</fullName>
            </value>
            <value>
                <fullName>Prepaid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HouseNotifyDetailInformation_text__c.field-meta.xml
<CustomField>
    <fullName>HouseNotifyDetailInformation_text__c</fullName>
    <label>House Notify&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MarksNumbersAttachment__c.field-meta.xml
<CustomField>
    <fullName>MarksNumbersAttachment__c</fullName>
    <label>Marks &amp; Numbers Attachment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MBLNumber__c.field-meta.xml
<CustomField>
    <fullName>MBLNumber__c</fullName>
    <label>M B/L Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MeasurementTotalCBM__c.field-meta.xml
<CustomField>
    <fullName>MeasurementTotalCBM__c</fullName>
    <label>Measurement (Total CBM)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/NetWeightKg__c.field-meta.xml
<CustomField>
    <fullName>NetWeightKg__c</fullName>
    <label>Net Weight(Kg)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/NumberofOriginalHBLIssued__c.field-meta.xml
<CustomField>
    <fullName>NumberofOriginalHBLIssued__c</fullName>
    <label>Number of Original H B/L Issued</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZERO(0)</fullName>
            </value>
            <value>
                <fullName>ONE(1)</fullName>
            </value>
            <value>
                <fullName>TWO(2)</fullName>
            </value>
            <value>
                <fullName>THREE(3)</fullName>
                <default>true</default>
                <label>THREE(3)</label>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PlaceofDeliveryDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>PlaceofDeliveryDetailInformation__c</fullName>
    <label>Place of Delivery&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PlaceofReceiptDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>PlaceofReceiptDetailInformation__c</fullName>
    <label>Place of Receipt&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Plural_Cargo_Unit__c.field-meta.xml
<CustomField>
    <fullName>Plural_Cargo_Unit__c</fullName>
    <formula>IF( CargoQuantity__c = 1, TEXT(CargoUnit__c) ,
IF(Text(CargoUnit__c)= &quot;&quot;, &quot;&quot;,
IF(Text(CargoUnit__c)= &quot;BALE, COMPRESSED&quot;, &quot;BALES, COMPRESSED&quot;,
IF(Text(CargoUnit__c)= &quot;CARBOY, NON-PROTECTED&quot;, &quot;CARBOYS, NON-PROTECTED&quot;,
IF(
  OR(
    RIGHT(TEXT(CargoUnit__c), 1) = &quot;S&quot;,
    RIGHT(TEXT(CargoUnit__c), 1) = &quot;Z&quot;,
    RIGHT(TEXT(CargoUnit__c), 1) = &quot;O&quot;,
    RIGHT(TEXT(CargoUnit__c), 2) = &quot;SH&quot;,
    RIGHT(TEXT(CargoUnit__c), 2) = &quot;CH&quot;,
    RIGHT(TEXT(CargoUnit__c), 2) = &quot;SS&quot;,
    RIGHT(TEXT(CargoUnit__c), 1) = &quot;X&quot;,
    RIGHT(TEXT(CargoUnit__c), 2) = &quot;SS&quot;),
  	TEXT(CargoUnit__c) &amp; &quot;ES&quot;,
IF(
    OR(
RIGHT(TEXT(CargoUnit__c), 2) = &quot;AY&quot;,
RIGHT(TEXT(CargoUnit__c), 2) = &quot;OY&quot;,
RIGHT(TEXT(CargoUnit__c), 2) = &quot;EY&quot;,
RIGHT(TEXT(CargoUnit__c), 2) = &quot;IY&quot;,
RIGHT(TEXT(CargoUnit__c), 2) = &quot;UY&quot;
),
     TEXT(CargoUnit__c) &amp; &quot;S&quot;,
IF(
    RIGHT(TEXT(CargoUnit__c), 1) = &quot;Y&quot;,
     LEFT(TEXT(CargoUnit__c), LEN(TEXT(CargoUnit__c)) - 1) &amp; &quot;IES&quot;,
  IF(
      RIGHT(TEXT(CargoUnit__c), 2) = &quot;FE&quot;,
      IF(
        TEXT(CargoUnit__c) = &quot;wife&quot;,
        &quot;wives&quot;,
        IF(
          TEXT(CargoUnit__c) = &quot;wolf&quot;,
          &quot;wolves&quot;,
          LEFT(TEXT(CargoUnit__c), LEN(TEXT(CargoUnit__c)) - 2) &amp; &quot;VES&quot;
        )
      ),
      TEXT(CargoUnit__c) &amp; &quot;S&quot;
    )
  )
)
))))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plural Cargo Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PODAOAsDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>PODAOAsDetailInformation__c</fullName>
    <label>P.O.D(A.O.A)&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/POLAODsDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>POLAODsDetailInformation__c</fullName>
    <label>P.O.L(A.O.D)&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Shipper__c.field-meta.xml
<CustomField>
    <fullName>Shipper__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipper</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>F_TMS_S_O1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ShipperDetailInformation_text__c.field-meta.xml
<CustomField>
    <fullName>ShipperDetailInformation_text__c</fullName>
    <label>Shipper&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/VesselFlight__c.field-meta.xml
<CustomField>
    <fullName>VesselFlight__c</fullName>
    <label>Vessel/Flight</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Voyage__c.field-meta.xml
<CustomField>
    <fullName>Voyage__c</fullName>
    <label>Voyage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Branch.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cambodia</fullName>
    </customValue>
    <customValue>
        <fullName>Hải Phòng</fullName>
    </customValue>
    <customValue>
        <fullName>Hồ Chí Minh</fullName>
        <default>true</default>
        <label>Hồ Chí Minh</label>
    </customValue>
    <customValue>
        <fullName>Đà Nẵng</fullName>
    </customValue>
    <customValue>
        <fullName>Taiwan</fullName>
    </customValue>
    <masterLabel>Branch</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/CargoUnit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B/PLT</fullName>
    </customValue>
    <customValue>
        <fullName>BAG</fullName>
    </customValue>
    <customValue>
        <fullName>BAL</fullName>
    </customValue>
    <customValue>
        <fullName>BALE</fullName>
    </customValue>
    <customValue>
        <fullName>BALE, COMPRESSED</fullName>
    </customValue>
    <customValue>
        <fullName>Bale,non-compressed</fullName>
        <label>BALE, NON-COMPRESSED</label>
    </customValue>
    <customValue>
        <fullName>Bar</fullName>
        <label>BAR</label>
    </customValue>
    <customValue>
        <fullName>BARE</fullName>
    </customValue>
    <customValue>
        <fullName>BARREL</fullName>
    </customValue>
    <customValue>
        <fullName>BILL</fullName>
    </customValue>
    <customValue>
        <fullName>BIN</fullName>
    </customValue>
    <customValue>
        <fullName>BOX</fullName>
    </customValue>
    <customValue>
        <fullName>BOX CARTON</fullName>
    </customValue>
    <customValue>
        <fullName>BOXE</fullName>
    </customValue>
    <customValue>
        <fullName>BOXPAL</fullName>
    </customValue>
    <customValue>
        <fullName>BUCKET</fullName>
    </customValue>
    <customValue>
        <fullName>BULK</fullName>
    </customValue>
    <customValue>
        <fullName>BUNDLE</fullName>
    </customValue>
    <customValue>
        <fullName>CAGE</fullName>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
    </customValue>
    <customValue>
        <fullName>Can,cylindrical</fullName>
        <label>CAN, CYLINDRICAL</label>
    </customValue>
    <customValue>
        <fullName>Can,rectangular</fullName>
        <label>CAN, RECTANGULAR</label>
    </customValue>
    <customValue>
        <fullName>CARBOY, NON-PROTECTED</fullName>
    </customValue>
    <customValue>
        <fullName>Carboy,protected</fullName>
        <label>CARBOY, PROTECTED</label>
    </customValue>
    <customValue>
        <fullName>CARDBOARD</fullName>
    </customValue>
    <customValue>
        <fullName>CARDBOXE</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON BOX</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON BOXE</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON PALLET</fullName>
    </customValue>
    <masterLabel>Cargo Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DeliveryRecordController_V2.cls
public class DeliveryRecordController_V2 {
	public FTMSSO__c shipment {get;set;}
    public Date today {get; set;}
    public String myDateString {get; set;}
    public String accountName {get; set;}
    public List <CompanyInformation__c> companyInfor {get; set;}
    public CompanyInformation__c companyInforHCM {get; set;}
    public CompanyInformation__c companyInforDN {get; set;}
    public CompanyInformation__c companyInforHPH {get; set;}
   
    private String shipId {get; set;}

    private static Set<String> fieldsComInfoQuery = new Set<String>();
    static{
        fieldsComInfoQuery.add('Name');
        fieldsComInfoQuery.add('Address__c');
        fieldsComInfoQuery.add('Branch1__c');
        fieldsComInfoQuery.add('Fax__c');
        fieldsComInfoQuery.add('Tel__c');
        fieldsComInfoQuery.add('Website__c');
        fieldsComInfoQuery.add('ShowAddressonHeader__c');
    }

    private static Set<String> fieldsFTMSQuery = new Set<String>();
    static{
        fieldsFTMSQuery.add('ConsigneeDetailInformation__c');
        fieldsFTMSQuery.add('Consignee__r.name');
        fieldsFTMSQuery.add('Shipper__r.Name');
        fieldsFTMSQuery.add('MBLNumber__c');
        fieldsFTMSQuery.add('HBLNumber__c');
    	fieldsFTMSQuery.add('PlaceofDeliveryDetailInformation__c');
        fieldsFTMSQuery.add('CargoQuantity__c');    
        fieldsFTMSQuery.add('CargoUnit__c');    
        fieldsFTMSQuery.add('Plural_Cargo_Unit__c');
        fieldsFTMSQuery.add('GrossWeight__c');    
        fieldsFTMSQuery.add('NetWeightKg__c');
        fieldsFTMSQuery.add('FinalDestinationsDetailInformation__c');
        
            
    }

    public DeliveryRecordController_V2(){
        companyInfor = new List<CompanyInformation__c>();
        companyInfor = getComInfor();
        companyInforHCM = new CompanyInformation__c();
        companyInforDN = new CompanyInformation__c();
        companyInforHPH = new CompanyInformation__c();
        
        companyInforHCM = getComInforHCM();
        companyInforDN = getComInforDN();
        companyInforHPH = getComInforHPH();
            
        
		today = Date.today();
        myDateString = Datetime.now().format('dd MMM, yyyy h:mm:ssa');
        accountName = UserInfo.getName();
        shipId = ApexPages.currentPage().getParameters().get('Id');
        shipment = getShipment(shipId); 
    }

    private List<CompanyInformation__c> getComInfor (){
        List<CompanyInformation__c> infor = new List<CompanyInformation__c>();
        String strSelect = String.join(new List<String>(fieldsComInfoQuery), ','); 
        String strQuery  =  'SELECT ' + strSelect 
                            + ' FROM CompanyInformation__c'
                            + ' WHERE ShowAddressonHeader__c = true';
        try{
            infor = Database.query(strQuery); 
            for(CompanyInformation__c com : infor){
                if(com.Name != null){
                    com.Name = com.Name.replace('TIMES CARGO LOGISTIC CO.,LTD - ', '');
                }
            }
        } catch(QueryException e){
            infor = new List<CompanyInformation__c>();
        }
        return infor;
    }
    private CompanyInformation__c getComInforHCM(){
		CompanyInformation__c infor = new CompanyInformation__c();
        String strSelect = String.join(new List<String>(fieldsComInfoQuery), ','); 
        String strQuery = 'SELECT ' + strSelect +
                  ' FROM CompanyInformation__c' +
                  ' WHERE Branch1__c = \'Hồ Chí Minh\'';
        try{
            infor = Database.query(strQuery); 
           
                if(infor.Name != null){
                    infor.Name = infor.Name.replace('TIMES CARGO LOGISTIC CO.,LTD - ', '');
                }
            
        } catch(QueryException e){
            infor = new CompanyInformation__c();
        }
        return infor;
       
    }
    private CompanyInformation__c getComInforDN(){
		CompanyInformation__c infor = new CompanyInformation__c();
        String strSelect = String.join(new List<String>(fieldsComInfoQuery), ','); 
        String strQuery = 'SELECT ' + strSelect +
                  ' FROM CompanyInformation__c' +
                  ' WHERE Branch1__c = \'Đà Nẵng\'';
        try{
            infor = Database.query(strQuery); 
           
                if(infor.Name != null){
                    infor.Name = infor.Name.replace('TIMES CARGO LOGISTIC CO.,LTD - ', '');
                }
            
        } catch(QueryException e){
            infor = new CompanyInformation__c();
        }
        return infor;
    }
    private CompanyInformation__c getComInforHPH(){
		CompanyInformation__c infor = new CompanyInformation__c();
        String strSelect = String.join(new List<String>(fieldsComInfoQuery), ','); 
        String strQuery = 'SELECT ' + strSelect +
                  ' FROM CompanyInformation__c' +
                  ' WHERE Branch1__c = \'Hải Phòng\'';
        try{
            infor = Database.query(strQuery); 
           
                if(infor.Name != null){
                    infor.Name = infor.Name.replace('TIMES CARGO LOGISTIC CO.,LTD - ', '');
                }
            
        } catch(QueryException e){
            infor = new CompanyInformation__c();
        }
        return infor;
    }
    
    
    
    private FTMSSO__c getShipment(String shipId){
        FTMSSO__c shipment = new FTMSSO__c();
        String strSelect = String.join(new List<String>(fieldsFTMSQuery), ','); 
        String strQuery  =  'SELECT ' + strSelect 
                            + ' FROM FTMSSO__c'
                            + ' WHERE Id = \'' + String.escapeSingleQuotes(shipId) + '\'';
        try{
            shipment = Database.query(strQuery); 
        } catch(QueryException e){
            shipment = new FTMSSO__c();
        }
        return shipment;
    }
    @AuraEnabled
    public static void generateAttachmentFile(String recordId,Boolean requiredAttachmentCreation,Boolean isBackground){
        PageReference pdf_file ;
        pdf_file = Page.page_DeliveryRecord_V2;
       
        System.debug('recordId :'+recordId);

        pdf_file.getParameters().put('Id', recordId);
        pdf_file.getParameters().put('requiredAttachmentCreation', 'false');
        pdf_file.getParameters().put('isBackground', 'false');
        
        FTMSSO__c item = new FTMSSO__c();
        String strSelect ='SELECT Id,ShipperDetailInformation_text__c,HBLNumber__c,ConsigneeDetailInformation_text__c,HouseNotifyDetailInformation_text__c,PlaceofReceiptDetailInformation__c,POLAODsDetailInformation__c,PODAOAsDetailInformation__c,VesselFlight__c ,Voyage__c,PlaceofDeliveryDetailInformation__c,NumberofOriginalHBLIssued__c,CargoQuantity__c,DescriptionofGoods__c,GrossWeight__c,MeasurementTotalCBM__c,MarksNumbersAttachment__c,CargoUnit__c,HouseFreightCollectPrepaid__c,AgentDetailInformation_text__c,Date_of_issue__c';
        String strFrom = ' FROM FTMSSO__c ';
        String strWhere = 'WHERE Id = \'' + recordId + '\'' ;
        String strOrderBy = ' ORDER BY Name LIMIT 1';
        String data = strSelect + strFrom + strWhere + strOrderBy;
        System.debug('data :'+data);
        item = Database.query(data);
        String namefile ='ProofOfDelivery_v' ;

       
        String attachName = namefile ;
        String attachNameSearch = attachName + '%';
        // get exist file Name
        List<Attachment> attachments = [SELECT Id, Name, ParentId 
                                        FROM Attachment 
                                        WHERE ParentId =: recordId 
                                        AND Name LIKE : attachNameSearch 
                                        ORDER BY CreatedDate DESC LIMIT 1];
                                        
        if(attachments.isEmpty()){
            attachName += '1.1';
        }else{
            String attachNameExist = attachments[0].Name;
            attachNameExist = attachNameExist.substringAfter(attachName);
            attachNameExist = attachNameExist.substringBefore('.pdf');
            Decimal versionNumber = Decimal.valueOf(attachNameExist);
            versionNumber += 0.1;
            attachName += String.valueOf(versionNumber);
        }
        if(requiredAttachmentCreation != false){
            Attachment attach = new Attachment();
            Blob body;
            attach.Name = attachName + '.pdf'; 
            attach.IsPrivate = false;
            attach.ParentId = recordId;
            if(!Test.isRunningTest()){
                System.debug('checkk');
                body = pdf_file.getContentAsPDF();
            
                attach.Body = body;
                FlsService.doInsert(attach);
            }
        }   
    }

}