force-app/main/default/objects/CntrinTrans__c/CntrinTrans__c.object-meta.xml
<CustomObject>
    <label>CNTR in Trans</label>
    <nameField>
        <displayFormat>CNTR-{00000}</displayFormat>
        <label>CNTR in Trans</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CNTR in Trans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CntrinTrans__c/fields/Cargo_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Cargo_Quantity__c</fullName>
    <label>Cargo Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/Cargo_Unit__c.field-meta.xml
<CustomField>
    <fullName>Cargo_Unit__c</fullName>
    <label>Cargo Unit</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>B/PLT</fullName>
            </value>
            <value>
                <fullName>BAG</fullName>
            </value>
            <value>
                <fullName>BAL</fullName>
            </value>
            <value>
                <fullName>BALE</fullName>
            </value>
            <value>
                <fullName>BALE, COMPRESSED</fullName>
            </value>
            <value>
                <fullName>BALE, NON-COMPRESSED</fullName>
            </value>
            <value>
                <fullName>BAR</fullName>
            </value>
            <value>
                <fullName>BARE</fullName>
            </value>
            <value>
                <fullName>BARREL</fullName>
            </value>
            <value>
                <fullName>BILL</fullName>
            </value>
            <value>
                <fullName>BIN</fullName>
            </value>
            <value>
                <fullName>BOX</fullName>
            </value>
            <value>
                <fullName>BOX CARTON</fullName>
            </value>
            <value>
                <fullName>BOXE</fullName>
            </value>
            <value>
                <fullName>BOXPAL</fullName>
            </value>
            <value>
                <fullName>BUCKET</fullName>
            </value>
            <value>
                <fullName>BULK</fullName>
            </value>
            <value>
                <fullName>BUNDLE</fullName>
            </value>
            <value>
                <fullName>CAGE</fullName>
            </value>
            <value>
                <fullName>CAN</fullName>
            </value>
            <value>
                <fullName>CAN, CYLINDRICAL</fullName>
            </value>
            <value>
                <fullName>CAN, RECTANGULAR</fullName>
            </value>
            <value>
                <fullName>CARBOY, NON-PROTECTED</fullName>
            </value>
            <value>
                <fullName>CARBOY, PROTECTED</fullName>
            </value>
            <value>
                <fullName>CARDBOARD</fullName>
            </value>
            <value>
                <fullName>CARDBOXE</fullName>
            </value>
            <value>
                <fullName>CARTON</fullName>
            </value>
            <value>
                <fullName>CARTON BOX</fullName>
            </value>
            <value>
                <fullName>CARTON BOXE</fullName>
            </value>
            <value>
                <fullName>CARTON PALLET</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/CargoUnit__c.field-meta.xml
<CustomField>
    <fullName>CargoUnit__c</fullName>
    <label>Cargo Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargoUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/Container_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Container_Quantity__c</fullName>
    <formula>1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Container Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/Container_Type__c.field-meta.xml
<CustomField>
    <fullName>Container_Type__c</fullName>
    <label>Container Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20&apos;DC</fullName>
            </value>
            <value>
                <fullName>20&apos;HC</fullName>
            </value>
            <value>
                <fullName>40&apos;DC</fullName>
            </value>
            <value>
                <fullName>45&apos;DC</fullName>
            </value>
            <value>
                <fullName>40&apos;HC</fullName>
            </value>
            <value>
                <fullName>45&apos;HC</fullName>
            </value>
            <value>
                <fullName>20&apos;RF</fullName>
            </value>
            <value>
                <fullName>40&apos;RF</fullName>
            </value>
            <value>
                <fullName>45&apos;RF</fullName>
            </value>
            <value>
                <fullName>20&apos;OT</fullName>
            </value>
            <value>
                <fullName>40&apos;OT</fullName>
            </value>
            <value>
                <fullName>45&apos;OT</fullName>
            </value>
            <value>
                <fullName>20&apos;FR</fullName>
            </value>
            <value>
                <fullName>40&apos;FR</fullName>
            </value>
            <value>
                <fullName>Bulk</fullName>
            </value>
            <value>
                <fullName>ISO</fullName>
            </value>
            <value>
                <fullName>20&apos;IMO</fullName>
            </value>
            <value>
                <fullName>40&apos;IMO</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>20&apos;DC-Flexi</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>CBM</fullName>
            </value>
            <value>
                <fullName>RTON</fullName>
            </value>
            <value>
                <fullName>2*20&apos;DC</fullName>
                <isActive>false</isActive>
                <label>2*20&apos;DC</label>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/F_TMS_S_O__c.field-meta.xml
<CustomField>
    <fullName>F_TMS_S_O__c</fullName>
    <label>F/TMS S/O</label>
    <referenceTo>FTMSSO__c</referenceTo>
    <relationshipLabel>CNTR in Trans</relationshipLabel>
    <relationshipName>CNTR_in_Trans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/Gross_Weight_Kg__c.field-meta.xml
<CustomField>
    <fullName>Gross_Weight_Kg__c</fullName>
    <label>Gross Weight(Kg)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/Measurement_CBM__c.field-meta.xml
<CustomField>
    <fullName>Measurement_CBM__c</fullName>
    <label>Measurement(CBM)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/FTMSSO__c.object-meta.xml
<CustomObject>
    <label>Shipment.</label>
    <nameField>
        <displayFormat>FSO-{000000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments.</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSSO__c/fields/CargoQuantity__c.field-meta.xml
<CustomField>
    <fullName>CargoQuantity__c</fullName>
    <label>Cargo Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoType__c.field-meta.xml
<CustomField>
    <fullName>CargoType__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargoType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoUnit__c.field-meta.xml
<CustomField>
    <fullName>CargoUnit__c</fullName>
    <label>Cargo Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargoUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HBLType__c.field-meta.xml
<CustomField>
    <fullName>HBLType__c</fullName>
    <label>House bill Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ORIGINAL</fullName>
            </value>
            <value>
                <fullName>SURRENDERED</fullName>
            </value>
            <value>
                <fullName>TELEX</fullName>
                <isActive>false</isActive>
                <label>TELEX</label>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ParentFTMSSO__c.field-meta.xml
<CustomField>
    <fullName>ParentFTMSSO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent F/TMS S/O</label>
    <referenceTo>FTMSSO__c</referenceTo>
    <relationshipName>F_TMS_S_O</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ReadCargoes__c.field-meta.xml
<CustomField>
    <fullName>ReadCargoes__c</fullName>
    <label>Read Cargoes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ReadContainers__c.field-meta.xml
<CustomField>
    <fullName>ReadContainers__c</fullName>
    <label>Read Containers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Shipment_Type__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Type__c</fullName>
    <label>Shipment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consol</fullName>
            </value>
            <value>
                <fullName>FCL</fullName>
            </value>
            <value>
                <fullName>LCL</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
                <isActive>false</isActive>
                <label>Logistics</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/CargoType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CFS/CFS</fullName>
    </customValue>
    <customValue>
        <fullName>CFS/CY</fullName>
    </customValue>
    <customValue>
        <fullName>CFS/DOOR</fullName>
    </customValue>
    <customValue>
        <fullName>CY/CFS</fullName>
    </customValue>
    <customValue>
        <fullName>CY/CY</fullName>
    </customValue>
    <customValue>
        <fullName>DOOR/DOOR</fullName>
    </customValue>
    <customValue>
        <fullName>FCL/FCL</fullName>
    </customValue>
    <customValue>
        <fullName>LCL/LCL</fullName>
    </customValue>
    <masterLabel>Cargo Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/CargoUnit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B/PLT</fullName>
    </customValue>
    <customValue>
        <fullName>BAG</fullName>
    </customValue>
    <customValue>
        <fullName>BAL</fullName>
    </customValue>
    <customValue>
        <fullName>BALE</fullName>
    </customValue>
    <customValue>
        <fullName>BALE, COMPRESSED</fullName>
    </customValue>
    <customValue>
        <fullName>Bale,non-compressed</fullName>
        <label>BALE, NON-COMPRESSED</label>
    </customValue>
    <customValue>
        <fullName>Bar</fullName>
        <label>BAR</label>
    </customValue>
    <customValue>
        <fullName>BARE</fullName>
    </customValue>
    <customValue>
        <fullName>BARREL</fullName>
    </customValue>
    <customValue>
        <fullName>BILL</fullName>
    </customValue>
    <customValue>
        <fullName>BIN</fullName>
    </customValue>
    <customValue>
        <fullName>BOX</fullName>
    </customValue>
    <customValue>
        <fullName>BOX CARTON</fullName>
    </customValue>
    <customValue>
        <fullName>BOXE</fullName>
    </customValue>
    <customValue>
        <fullName>BOXPAL</fullName>
    </customValue>
    <customValue>
        <fullName>BUCKET</fullName>
    </customValue>
    <customValue>
        <fullName>BULK</fullName>
    </customValue>
    <customValue>
        <fullName>BUNDLE</fullName>
    </customValue>
    <customValue>
        <fullName>CAGE</fullName>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
    </customValue>
    <customValue>
        <fullName>Can,cylindrical</fullName>
        <label>CAN, CYLINDRICAL</label>
    </customValue>
    <customValue>
        <fullName>Can,rectangular</fullName>
        <label>CAN, RECTANGULAR</label>
    </customValue>
    <customValue>
        <fullName>CARBOY, NON-PROTECTED</fullName>
    </customValue>
    <customValue>
        <fullName>Carboy,protected</fullName>
        <label>CARBOY, PROTECTED</label>
    </customValue>
    <customValue>
        <fullName>CARDBOARD</fullName>
    </customValue>
    <customValue>
        <fullName>CARDBOXE</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON BOX</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON BOXE</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON PALLET</fullName>
    </customValue>
    <masterLabel>Cargo Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CNTRClass.cls
public class CNTRClass {
    
    public static String convertToPlural(String input) {
        List<String> pluralWords = new List<String>();
        String[] words = input.split(';');
        for (String word : words) {
            if( word.contains(',')){
                List<String> tmpList = new List<String>();
                String[] wordsItems = word.split(','); 
                for (String wordItem : wordsItems) {
                    String tmp = convertWordToPlural(wordItem.trim());
                    tmpList.add(tmp);
                }
                 String resultTmp = '';

                for (Integer i = 0; i < tmpList.size(); i++) {
                    resultTmp += tmpList[i].trim();
                    if( i< tmpList.size()-1){

                        resultTmp +=  ', ';
                    }
                   
            
                }
                pluralWords.add(resultTmp);

            }
            else{
                String pluralWord = convertWordToPlural(word.trim());
                pluralWords.add(pluralWord);
            }
        }
        
        String result = '';
        for (Integer i = 0; i < pluralWords.size(); i++) {
            if (i > 0) {
                result += '; ';
            }
            result += pluralWords[i];
        }
        
        return result;
    }
    
    private static boolean checkChar(String c) {
        System.debug('debuggg List value :'+ c);
 
        return c == 'A' || c == 'E' || c == 'I' || c == 'O' || c == 'U';
    }

    public static String convertWordToPlural(String word) {
        if (word == null || word.length() == 0 ||word.endsWith('ED')){
            return word;
        }
        
        if (word.endsWith('Y') && !checkChar(word.substring(word.length()-1))) {
            return word.substring(0, word.length() - 1) + 'IES';
        } else if (word.endsWith('S') || word.endsWith('CH') || word.endsWith('SH') || word.endsWith('X') || word.endsWith('Z')) {
            return word + 'ES';
        } 
        else {
            return word + 'S';
        } 
    }

    public static void readContainerandCargoesInsertandUpdate(List<CntrinTrans__c> listCNTRNew) {
        Set<Id> lstIdSO = new Set<Id>();
        for (CntrinTrans__c cont : listCNTRNew) {
            if (!lstIdSO.contains(cont.F_TMS_S_O__c)){
                lstIdSO.add(cont.F_TMS_S_O__c);
            }
        }
        if (lstIdSO.size()>0) {
            Map<String,String> mapSOReadContainer = new Map<String,String>();
            // Map<String,String> mapSOReadCargoes = new Map<String,String>();
            // List<FTMSSO__c> lstSO= [SELECT Id, Name, HBLType__c, ReadContainers__c, ReadCargoes__c FROM FTMSSO__c WHERE Id in: lstIdSO];
            // for (FTMSSO__c so : lstSO) {
            //     mapSOReadContainer.put(so,new List<CntrinTrans__c>());
            // }
            List<CntrinTrans__c> lstCNTR = [SELECT Id, Name, F_TMS_S_O__c, F_TMS_S_O__r.Shipment_Type__c, Container_Number__c, Container_Type__c, Seal_Number__c, Container_Quantity__c, Cargo_Quantity__c, Gross_Weight_Kg__c, Measurement_CBM__c, Cargo_Unit__c FROM CntrinTrans__c WHERE F_TMS_S_O__c IN: lstIdSO];
            // for (CntrinTrans__c cont : lstCNTR) {
            //     Decimal contQuantity = cont.Container_Quantity__c != null? cont.Container_Quantity__c : 0;
            //     if (!mapSOReadContainer.containsKey(cont.F_TMS_S_O__c)) {
            //         String readCont = '';
            //         if (contQuantity > 0 && contQuantity <10) {
            //             readCont = ReadNumberToWords.convert(contQuantity.setScale(2, System.RoundingMode.HALF_UP)) + ' ('+'0'  + contQuantity + ')X' + cont.Container_Type__c;
            //         } else {
            //             readCont = ReadNumberToWords.convert(contQuantity.setScale(2, System.RoundingMode.HALF_UP)) + ' (' + contQuantity + ')X' + cont.Container_Type__c;
            //         }
            //         mapSOReadContainer.put(cont.F_TMS_S_O__c,readCont);
            //     } else {
            //         String readCont = mapSOReadContainer.get(cont.F_TMS_S_O__c);
            //         if (contQuantity > 0 && contQuantity <10) {
            //             readCont += ' AND ' + ReadNumberToWords.convert(contQuantity.setScale(2, System.RoundingMode.HALF_UP)) + ' ('+'0'  + contQuantity + ')X' + cont.Container_Type__c;
            //         } else {
            //             readCont += ' AND ' + ReadNumberToWords.convert(contQuantity.setScale(2, System.RoundingMode.HALF_UP)) + ' (' + contQuantity + ')X' + cont.Container_Type__c;
            //         }
            //         mapSOReadContainer.put(cont.F_TMS_S_O__c,readCont);
            //     }
            // }
            
            Map<String,Decimal> mapConType = new Map<String,Decimal>();
            Map<String,List<Decimal>> mapIdSoContQuantity = new Map<String,List<Decimal>>();
            Map<String,List<String>> mapIdSoContType = new Map<String,List<String>>();
            List<WrapperCon> lstWrapper = new List<WrapperCon>();
            Set<String> setIdSoContype = new Set<String>();

            for (CntrinTrans__c cont : lstCNTR) {
                WrapperCon item = new WrapperCon();
                item.idSO = cont.F_TMS_S_O__c;
                item.contype = cont.Container_Type__c;
                Decimal quantityCont = cont.Container_Quantity__c != null? cont.Container_Quantity__c : 0;
                if (!mapConType.containsKey(item.idSO+'-'+item.contype)) {
                    mapConType.put(item.idSO+'-'+item.contype,quantityCont);
                    lstWrapper.add(item);
                } else {
                    Decimal quantity = mapConType.get(item.idSO+'-'+item.contype) + quantityCont;
                    mapConType.put(item.idSO+'-'+item.contype,quantity);
                }
            }
            for (WrapperCon item : lstWrapper) {
                List<Decimal> lstQuantity = mapIdSoContQuantity.get(item.idSO);
                List<String> lstContType = mapIdSoContType.get(item.idSO);
                if (!mapIdSoContQuantity.containsKey(item.idSO)){
                    lstQuantity = new List<Decimal>();
                    lstQuantity.add(mapConType.get(item.idSO+'-'+item.contype));
                    mapIdSoContQuantity.put(item.idSO,lstQuantity);
                    lstContType = new List<String>();
                    lstContType.add(item.contype);
                    mapIdSoContType.put(item.idSO,lstContType);
                } else {
                    lstQuantity.add(mapConType.get(item.idSO+'-'+item.contype));
                    lstContType.add(item.contype);
                    mapIdSoContQuantity.put(item.idSO,lstQuantity);
                    mapIdSoContType.put(item.idSO,lstContType);
                }
            }
            System.debug('mapConType: '+ mapConType);
            System.debug('mapIdSoContQuantity: '+ mapIdSoContQuantity);
            System.debug('mapIdSoContType: '+ mapIdSoContType);


            // Update Shipment
            List<FTMSSO__c> lstSO= [SELECT Id, Name, HBLType__c, ReadContainers__c, ReadCargoes__c, Shipment_Type__c, CargoType__c, CargoQuantity__c,CargoUnit__c FROM FTMSSO__c WHERE Id in: lstIdSO];
            for (FTMSSO__c ship : lstSO){
                String readContainer = '';
                Integer count = 0;
                for (Decimal value : mapIdSoContQuantity.get(ship.Id)) {
                    if (count != 0) {
                        if (value > 0 && value <10) {
                            readContainer += ' AND ' + ReadNumberToWords.convert(value.setScale(2, System.RoundingMode.HALF_UP)) + ' ('+'0'  + value + ')X' + mapIdSoContType.get(ship.Id).get(count);
                        } else {
                            readContainer += ' AND ' + ReadNumberToWords.convert(value.setScale(2, System.RoundingMode.HALF_UP)) + ' (' + value + ')X' + mapIdSoContType.get(ship.Id).get(count);
                        }
                    } else {
                        if (value > 0 && value <10) {
                            readContainer += ReadNumberToWords.convert(value.setScale(2, System.RoundingMode.HALF_UP)) + ' ('+'0'  + value + ')X' + mapIdSoContType.get(ship.Id).get(count);
                        } else {
                            readContainer += ReadNumberToWords.convert(value.setScale(2, System.RoundingMode.HALF_UP)) + ' (' + value + ')X' + mapIdSoContType.get(ship.Id).get(count);
                        }
                    }
                    count ++;
                }
                if (ship.Shipment_Type__c == 'FCL') {
                    ship.ReadContainers__c = readContainer + ' CONTAINER(S)'; 
                    ship.ReadCargoes__c = readContainer + ' CONTAINER(S) ONLY';
                } else {
                    Decimal shipQuantity = ship.CargoQuantity__c != null? ship.CargoQuantity__c : 0;
                    ship.ReadContainers__c = 'A PART OF ' + readContainer + ' CONTAINER(S)';
                    ship.ReadCargoes__c = ReadNumberToWords.convert(shipQuantity.setScale(2, System.RoundingMode.HALF_UP)) + ' (' + shipQuantity + ') ' + ship.CargoUnit__c + '(S) ONLY';
                }
            }

            // // Update Shipment
            // List<FTMSSO__c> lstSO= [SELECT Id, Name, HBLType__c, ReadContainers__c, ReadCargoes__c, Shipment_Type__c, CargoType__c, CargoQuantity__c,CargoUnit__c FROM FTMSSO__c WHERE Id in: lstIdSO];
            // for (FTMSSO__c ship : lstSO){
            //     Decimal shipQuantity = ship.CargoQuantity__c != null? ship.CargoQuantity__c : 0;
            //     if (ship.Shipment_Type__c == 'FCL') {
            //         ship.ReadContainers__c = mapSOReadContainer.get(ship.Id); 
            //         ship.ReadCargoes__c = 'SAY '+ mapSOReadContainer.get(ship.Id) + ' ONLY';
            //     } else {
            //         ship.ReadContainers__c = 'A PART OF ' + mapSOReadContainer.get(ship.Id);
            //         ship.ReadCargoes__c = 'SAY '+ ReadNumberToWords.convert(shipQuantity.setScale(2, System.RoundingMode.HALF_UP)) + ' (' + shipQuantity + ')X' + ship.CargoUnit__c + ' ONLY';
            //     }
            // }
            update lstSO;
        }
    }

    public static void readContainerandCargoesDelete(List<CntrinTrans__c> listCNTROld) {
        Set<Id> lstIdSO = new Set<Id>();
        Set<Id> lstIdCNTROld = new Set<Id>();
        for (CntrinTrans__c cont : listCNTROld) {
            if (!lstIdSO.contains(cont.F_TMS_S_O__c)){
                lstIdSO.add(cont.F_TMS_S_O__c);
            }
            lstIdCNTROld.add(cont.Id);
        }
        if (lstIdSO.size()>0) {
            Map<String,String> mapSOReadContainer = new Map<String,String>();
            // Map<String,String> mapSOReadCargoes = new Map<String,String>();
            // List<FTMSSO__c> lstSO= [SELECT Id, Name, HBLType__c, ReadContainers__c, ReadCargoes__c FROM FTMSSO__c WHERE Id in: lstIdSO];
            // for (FTMSSO__c so : lstSO) {
            //     mapSOReadContainer.put(so,new List<CntrinTrans__c>());
            // }
            List<CntrinTrans__c> lstCNTR = [SELECT Id, Name, F_TMS_S_O__c, F_TMS_S_O__r.Shipment_Type__c, Container_Number__c, Container_Type__c, Seal_Number__c, Container_Quantity__c, Cargo_Quantity__c, Gross_Weight_Kg__c, Measurement_CBM__c, Cargo_Unit__c FROM CntrinTrans__c WHERE F_TMS_S_O__c IN: lstIdSO AND Id NOT IN: lstIdCNTROld];
            // for (CntrinTrans__c cont : lstCNTR) {
            //     Decimal contQuantity = cont.Container_Quantity__c != null? cont.Container_Quantity__c : 0;
            //     if (!mapSOReadContainer.containsKey(cont.F_TMS_S_O__c)) {
            //         String readCont = '';
            //         if (contQuantity > 0 && contQuantity <10) {
            //             readCont = ReadNumberToWords.convert(contQuantity.setScale(2, System.RoundingMode.HALF_UP)) + ' ('+'0'  + contQuantity + ')X' + cont.Container_Type__c;
            //         } else {
            //             readCont = ReadNumberToWords.convert(contQuantity.setScale(2, System.RoundingMode.HALF_UP)) + ' (' + contQuantity + ')X' + cont.Container_Type__c;
            //         }
            //         mapSOReadContainer.put(cont.F_TMS_S_O__c,readCont);
            //     } else {
            //         String readCont = mapSOReadContainer.get(cont.F_TMS_S_O__c);
            //         if (contQuantity > 0 && contQuantity <10) {
            //             readCont += ' AND ' + ReadNumberToWords.convert(contQuantity.setScale(2, System.RoundingMode.HALF_UP)) + ' ('+'0'  + contQuantity + ')X' + cont.Container_Type__c;
            //         } else {
            //             readCont += ' AND ' + ReadNumberToWords.convert(contQuantity.setScale(2, System.RoundingMode.HALF_UP)) + ' (' + contQuantity + ')X' + cont.Container_Type__c;
            //         }
            //         mapSOReadContainer.put(cont.F_TMS_S_O__c,readCont);
            //     }
            // }

            // // Update Shipment
            // List<FTMSSO__c> lstSO= [SELECT Id, Name, HBLType__c, ReadContainers__c, ReadCargoes__c, Shipment_Type__c, CargoType__c, CargoQuantity__c FROM FTMSSO__c WHERE Id in: lstIdSO];
            // for (FTMSSO__c ship : lstSO){
            //     Decimal shipQuantity = ship.CargoQuantity__c != null? ship.CargoQuantity__c : 0;
            //     if (ship.Shipment_Type__c == 'FCL') {
            //         ship.ReadContainers__c = mapSOReadContainer.get(ship.Id); 
            //         ship.ReadCargoes__c = 'SAY '+ mapSOReadContainer.get(ship.Id) + ' ONLY';
            //     } else {
            //         ship.ReadContainers__c = 'A PART OF' + mapSOReadContainer.get(ship.Id);
            //         ship.ReadCargoes__c = 'SAY '+ ReadNumberToWords.convert(shipQuantity.setScale(2, System.RoundingMode.HALF_UP)) + ' (' + shipQuantity + ')X' + ship.CargoType__c + ' ONLY';
            //     }
            // }

            Map<String,Decimal> mapConType = new Map<String,Decimal>();
            Map<String,List<Decimal>> mapIdSoContQuantity = new Map<String,List<Decimal>>();
            Map<String,List<String>> mapIdSoContType = new Map<String,List<String>>();
            List<WrapperCon> lstWrapper = new List<WrapperCon>();
            Set<String> setIdSoContype = new Set<String>();
            
            for (CntrinTrans__c cont : lstCNTR) {
                WrapperCon item = new WrapperCon();
                item.idSO = cont.F_TMS_S_O__c;
                item.contype = cont.Container_Type__c;
                Decimal quantityCont = cont.Container_Quantity__c != null? cont.Container_Quantity__c : 0;

                if (!mapConType.containsKey(item.idSO+'-'+item.contype)) {
                    mapConType.put(item.idSO+'-'+item.contype,quantityCont);
                    lstWrapper.add(item);
                } else {
                    Decimal quantity = mapConType.get(item.idSO+'-'+item.contype) + quantityCont;
                    mapConType.put(item.idSO+'-'+item.contype,quantity);
                }
            }
            for (WrapperCon item : lstWrapper) {
                List<Decimal> lstQuantity = mapIdSoContQuantity.get(item.idSO);
                List<String> lstContType = mapIdSoContType.get(item.idSO);
                if (!mapIdSoContQuantity.containsKey(item.idSO)){
                    lstQuantity = new List<Decimal>();
                    lstQuantity.add(mapConType.get(item.idSO+'-'+item.contype));
                    mapIdSoContQuantity.put(item.idSO,lstQuantity);
                    lstContType = new List<String>();
                    lstContType.add(item.contype);
                    mapIdSoContType.put(item.idSO,lstContType);
                } else {
                    lstQuantity.add(mapConType.get(item.idSO+'-'+item.contype));
                    lstContType.add(item.contype);
                    mapIdSoContQuantity.put(item.idSO,lstQuantity);
                    mapIdSoContType.put(item.idSO,lstContType);
                }
            }
            System.debug('mapConType: '+ mapConType);
            System.debug('mapIdSoContQuantity: '+ mapIdSoContQuantity);
            System.debug('mapIdSoContType: '+ mapIdSoContType);

            // Update Shipment
            List<FTMSSO__c> lstSO= [SELECT Id, Name, HBLType__c, ReadContainers__c, ReadCargoes__c, Shipment_Type__c, CargoType__c, CargoQuantity__c,CargoUnit__c FROM FTMSSO__c WHERE Id in: lstIdSO];
            for (FTMSSO__c ship : lstSO){
                String readContainer = '';
                Integer count = 0;
                for (Decimal value : mapIdSoContQuantity.get(ship.Id)) {
                    if (count != 0) {
                        if (value > 0 && value <10) {
                            readContainer += ' AND ' + ReadNumberToWords.convert(value.setScale(2, System.RoundingMode.HALF_UP)) + ' ('+'0'  + value + ')X' + mapIdSoContType.get(ship.Id).get(count);
                        } else {
                            readContainer += ' AND ' + ReadNumberToWords.convert(value.setScale(2, System.RoundingMode.HALF_UP)) + ' (' + value + ')X' + mapIdSoContType.get(ship.Id).get(count);
                        }
                    } else {
                        if (value > 0 && value <10) {
                            readContainer += ReadNumberToWords.convert(value.setScale(2, System.RoundingMode.HALF_UP)) + ' ('+'0'  + value + ')X' + mapIdSoContType.get(ship.Id).get(count);
                        } else {
                            readContainer += ReadNumberToWords.convert(value.setScale(2, System.RoundingMode.HALF_UP)) + ' (' + value + ')X' + mapIdSoContType.get(ship.Id).get(count);
                        }
                    }
                }
                if (ship.Shipment_Type__c == 'FCL') {
                    ship.ReadContainers__c = readContainer; 
                    ship.ReadCargoes__c = 'SAY '+ readContainer + ' ONLY';
                } else {
                    Decimal shipQuantity = ship.CargoQuantity__c != null? ship.CargoQuantity__c : 0;
                    ship.ReadContainers__c = 'A PART OF ' + readContainer;
                    ship.ReadCargoes__c = 'SAY '+ ReadNumberToWords.convert(shipQuantity.setScale(2, System.RoundingMode.HALF_UP)) + ' (' + shipQuantity + ')X' + ship.CargoUnit__c + ' ONLY';
                }
            }
            update lstSO;
        }
    }
    public class WrapperCon {
        public String contype {get; set;}
        public String idSO {get; set;}
        public WrapperCon() {
            contype = '';
            idSO = '';
        } 
    }
}