force-app/main/default/objects/CntrinTrans__c/CntrinTrans__c.object-meta.xml
<CustomObject>
    <label>CNTR in Trans</label>
    <nameField>
        <displayFormat>CNTR-{00000}</displayFormat>
        <label>CNTR in Trans</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CNTR in Trans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CntrinTrans__c/fields/Cargo_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Cargo_Quantity__c</fullName>
    <label>Cargo Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/Cargo_Unit__c.field-meta.xml
<CustomField>
    <fullName>Cargo_Unit__c</fullName>
    <label>Cargo Unit</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>B/PLT</fullName>
            </value>
            <value>
                <fullName>BAG</fullName>
            </value>
            <value>
                <fullName>BAL</fullName>
            </value>
            <value>
                <fullName>BALE</fullName>
            </value>
            <value>
                <fullName>BALE, COMPRESSED</fullName>
            </value>
            <value>
                <fullName>BALE, NON-COMPRESSED</fullName>
            </value>
            <value>
                <fullName>BAR</fullName>
            </value>
            <value>
                <fullName>BARE</fullName>
            </value>
            <value>
                <fullName>BARREL</fullName>
            </value>
            <value>
                <fullName>BILL</fullName>
            </value>
            <value>
                <fullName>BIN</fullName>
            </value>
            <value>
                <fullName>BOX</fullName>
            </value>
            <value>
                <fullName>BOX CARTON</fullName>
            </value>
            <value>
                <fullName>BOXE</fullName>
            </value>
            <value>
                <fullName>BOXPAL</fullName>
            </value>
            <value>
                <fullName>BUCKET</fullName>
            </value>
            <value>
                <fullName>BULK</fullName>
            </value>
            <value>
                <fullName>BUNDLE</fullName>
            </value>
            <value>
                <fullName>CAGE</fullName>
            </value>
            <value>
                <fullName>CAN</fullName>
            </value>
            <value>
                <fullName>CAN, CYLINDRICAL</fullName>
            </value>
            <value>
                <fullName>CAN, RECTANGULAR</fullName>
            </value>
            <value>
                <fullName>CARBOY, NON-PROTECTED</fullName>
            </value>
            <value>
                <fullName>CARBOY, PROTECTED</fullName>
            </value>
            <value>
                <fullName>CARDBOARD</fullName>
            </value>
            <value>
                <fullName>CARDBOXE</fullName>
            </value>
            <value>
                <fullName>CARTON</fullName>
            </value>
            <value>
                <fullName>CARTON BOX</fullName>
            </value>
            <value>
                <fullName>CARTON BOXE</fullName>
            </value>
            <value>
                <fullName>CARTON PALLET</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/CargoUnit__c.field-meta.xml
<CustomField>
    <fullName>CargoUnit__c</fullName>
    <label>Cargo Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargoUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/Container_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Container_Quantity__c</fullName>
    <formula>1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Container Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/Container_Type__c.field-meta.xml
<CustomField>
    <fullName>Container_Type__c</fullName>
    <label>Container Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20&apos;DC</fullName>
            </value>
            <value>
                <fullName>20&apos;HC</fullName>
            </value>
            <value>
                <fullName>40&apos;DC</fullName>
            </value>
            <value>
                <fullName>45&apos;DC</fullName>
            </value>
            <value>
                <fullName>40&apos;HC</fullName>
            </value>
            <value>
                <fullName>45&apos;HC</fullName>
            </value>
            <value>
                <fullName>20&apos;RF</fullName>
            </value>
            <value>
                <fullName>40&apos;RF</fullName>
            </value>
            <value>
                <fullName>45&apos;RF</fullName>
            </value>
            <value>
                <fullName>20&apos;OT</fullName>
            </value>
            <value>
                <fullName>40&apos;OT</fullName>
            </value>
            <value>
                <fullName>45&apos;OT</fullName>
            </value>
            <value>
                <fullName>20&apos;FR</fullName>
            </value>
            <value>
                <fullName>40&apos;FR</fullName>
            </value>
            <value>
                <fullName>Bulk</fullName>
            </value>
            <value>
                <fullName>ISO</fullName>
            </value>
            <value>
                <fullName>20&apos;IMO</fullName>
            </value>
            <value>
                <fullName>40&apos;IMO</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>20&apos;DC-Flexi</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>CBM</fullName>
            </value>
            <value>
                <fullName>RTON</fullName>
            </value>
            <value>
                <fullName>2*20&apos;DC</fullName>
                <isActive>false</isActive>
                <label>2*20&apos;DC</label>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/Gross_Weight_Kg__c.field-meta.xml
<CustomField>
    <fullName>Gross_Weight_Kg__c</fullName>
    <label>Gross Weight(Kg)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/Measurement_CBM__c.field-meta.xml
<CustomField>
    <fullName>Measurement_CBM__c</fullName>
    <label>Measurement(CBM)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/FTMSSO__c.object-meta.xml
<CustomObject>
    <label>Shipment.</label>
    <nameField>
        <displayFormat>FSO-{000000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments.</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSSO__c/fields/AgentDetailInformation_text__c.field-meta.xml
<CustomField>
    <fullName>AgentDetailInformation_text__c</fullName>
    <label>Agent&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoQuantity__c.field-meta.xml
<CustomField>
    <fullName>CargoQuantity__c</fullName>
    <label>Cargo Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoType__c.field-meta.xml
<CustomField>
    <fullName>CargoType__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargoType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoUnit__c.field-meta.xml
<CustomField>
    <fullName>CargoUnit__c</fullName>
    <label>Cargo Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargoUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ConsigneeDetailInformation_text__c.field-meta.xml
<CustomField>
    <fullName>ConsigneeDetailInformation_text__c</fullName>
    <label>Consignee&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Date_of_issue__c.field-meta.xml
<CustomField>
    <fullName>Date_of_issue__c</fullName>
    <label>Date of issue</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/DateofHouseBLIssued__c.field-meta.xml
<CustomField>
    <fullName>DateofHouseBLIssued__c</fullName>
    <label>Date of House B/L Issued</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/DeliveryPartysDetails_text__c.field-meta.xml
<CustomField>
    <fullName>DeliveryPartysDetails_text__c</fullName>
    <label>Delivery Party&apos;s Details</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>Gross Weight</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HBLNumber__c.field-meta.xml
<CustomField>
    <fullName>HBLNumber__c</fullName>
    <label>H B/L Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HouseFreightCollectPrepaid__c.field-meta.xml
<CustomField>
    <fullName>HouseFreightCollectPrepaid__c</fullName>
    <label>House Freight Collect/Prepaid</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collected</fullName>
            </value>
            <value>
                <fullName>Prepaid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HouseNotifyDetailInformation_text__c.field-meta.xml
<CustomField>
    <fullName>HouseNotifyDetailInformation_text__c</fullName>
    <label>House Notify&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MarksNumbersAttachment__c.field-meta.xml
<CustomField>
    <fullName>MarksNumbersAttachment__c</fullName>
    <label>Marks &amp; Numbers Attachment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <label>Measurement</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MeasurementTotalCBM__c.field-meta.xml
<CustomField>
    <fullName>MeasurementTotalCBM__c</fullName>
    <label>Measurement (Total CBM)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/NumberofOriginalHBLIssued__c.field-meta.xml
<CustomField>
    <fullName>NumberofOriginalHBLIssued__c</fullName>
    <label>Number of Original H B/L Issued</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZERO(0)</fullName>
            </value>
            <value>
                <fullName>ONE(1)</fullName>
            </value>
            <value>
                <fullName>TWO(2)</fullName>
            </value>
            <value>
                <fullName>THREE(3)</fullName>
                <default>true</default>
                <label>THREE(3)</label>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PlaceofDeliveryDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>PlaceofDeliveryDetailInformation__c</fullName>
    <label>Place of Delivery&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PlaceofHouseBLIssued__c.field-meta.xml
<CustomField>
    <fullName>PlaceofHouseBLIssued__c</fullName>
    <label>Place of House B/L Issued</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PlaceofReceiptDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>PlaceofReceiptDetailInformation__c</fullName>
    <label>Place of Receipt&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PODAOAsDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>PODAOAsDetailInformation__c</fullName>
    <label>P.O.D(A.O.A)&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/POLAODsDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>POLAODsDetailInformation__c</fullName>
    <label>P.O.L(A.O.D)&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ShipperDetailInformation_text__c.field-meta.xml
<CustomField>
    <fullName>ShipperDetailInformation_text__c</fullName>
    <label>Shipper&apos;s Detail Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/VesselFlight__c.field-meta.xml
<CustomField>
    <fullName>VesselFlight__c</fullName>
    <label>Vessel/Flight</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Voyage__c.field-meta.xml
<CustomField>
    <fullName>Voyage__c</fullName>
    <label>Voyage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/CargoType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CFS/CFS</fullName>
    </customValue>
    <customValue>
        <fullName>CFS/CY</fullName>
    </customValue>
    <customValue>
        <fullName>CFS/DOOR</fullName>
    </customValue>
    <customValue>
        <fullName>CY/CFS</fullName>
    </customValue>
    <customValue>
        <fullName>CY/CY</fullName>
    </customValue>
    <customValue>
        <fullName>DOOR/DOOR</fullName>
    </customValue>
    <customValue>
        <fullName>FCL/FCL</fullName>
    </customValue>
    <customValue>
        <fullName>LCL/LCL</fullName>
    </customValue>
    <masterLabel>Cargo Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/CargoUnit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B/PLT</fullName>
    </customValue>
    <customValue>
        <fullName>BAG</fullName>
    </customValue>
    <customValue>
        <fullName>BAL</fullName>
    </customValue>
    <customValue>
        <fullName>BALE</fullName>
    </customValue>
    <customValue>
        <fullName>BALE, COMPRESSED</fullName>
    </customValue>
    <customValue>
        <fullName>Bale,non-compressed</fullName>
        <label>BALE, NON-COMPRESSED</label>
    </customValue>
    <customValue>
        <fullName>Bar</fullName>
        <label>BAR</label>
    </customValue>
    <customValue>
        <fullName>BARE</fullName>
    </customValue>
    <customValue>
        <fullName>BARREL</fullName>
    </customValue>
    <customValue>
        <fullName>BILL</fullName>
    </customValue>
    <customValue>
        <fullName>BIN</fullName>
    </customValue>
    <customValue>
        <fullName>BOX</fullName>
    </customValue>
    <customValue>
        <fullName>BOX CARTON</fullName>
    </customValue>
    <customValue>
        <fullName>BOXE</fullName>
    </customValue>
    <customValue>
        <fullName>BOXPAL</fullName>
    </customValue>
    <customValue>
        <fullName>BUCKET</fullName>
    </customValue>
    <customValue>
        <fullName>BULK</fullName>
    </customValue>
    <customValue>
        <fullName>BUNDLE</fullName>
    </customValue>
    <customValue>
        <fullName>CAGE</fullName>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
    </customValue>
    <customValue>
        <fullName>Can,cylindrical</fullName>
        <label>CAN, CYLINDRICAL</label>
    </customValue>
    <customValue>
        <fullName>Can,rectangular</fullName>
        <label>CAN, RECTANGULAR</label>
    </customValue>
    <customValue>
        <fullName>CARBOY, NON-PROTECTED</fullName>
    </customValue>
    <customValue>
        <fullName>Carboy,protected</fullName>
        <label>CARBOY, PROTECTED</label>
    </customValue>
    <customValue>
        <fullName>CARDBOARD</fullName>
    </customValue>
    <customValue>
        <fullName>CARDBOXE</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON BOX</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON BOXE</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON PALLET</fullName>
    </customValue>
    <masterLabel>Cargo Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PrintSIController.cls
public with sharing class PrintSIController {
    public String id {get; set;}
    public FTMSSO__c shipment {get; set;}
    public FTMSSO__c shipmentnew {get; set;}
    public String readUnit {get; set;}
    public List<CntrinTrans__c> lstCon {get; set;}
    public List<WrapperCon> lstConOutput {get; set;}
    public String typeMarks {get; set;}
    public String typeDescrip {get; set;}
    public String typeMarksBlank {get; set;}
    public String typeDescripBlank {get; set;}
    public String readCon{get; set;}
    public String readConFull{get; set;}
    public Decimal totalQuantity{get; set;}
    public Decimal totalGrossWeight{get; set;}
    public Decimal totalMeasurement{get; set;}
    public Integer finalTop {get;set;}
    public Integer finalTopBlank {get;set;}
    public String type {get; set;}
    public Boolean isCreateAttachment {get; set;}
    public Boolean isShowCont {get; set;}
    public String backGround {get;set;}
    public String cargoUnit {get; set;}


    public PrintSIController() {
        id = ApexPages.currentPage().getParameters().get('id');
        type = ApexPages.currentPage().getParameters().get('type');
        System.debug('type :'+type);
        backGround = ApexPages.currentPage().getParameters().get('backGround');
        isCreateAttachment = ApexPages.currentPage().getParameters().get('isCreateAttachment') == 'true';
        isShowCont = ApexPages.currentPage().getParameters().get('isShowCont') == 'true';
        System.debug('isCreateAttachment :'+isCreateAttachment);
        System.debug('backGround :'+backGround);
        cargoUnit = '';
        shipment = getData(id);
        String descrip = shipment.DescriptionofGoods__c;
        System.debug('111 :'+descrip);
        Decimal quantityCargo = 0;
        if (shipment.CargoQuantity__c != null){
            quantityCargo = shipment.CargoQuantity__c;
        }
        String quantity =  ReadNumberToWords.convert(quantityCargo.setScale(2, System.RoundingMode.HALF_UP));
        String addS =  shipment.CargoQuantity__c==1?''+ ' ONLY':'(S)' + ' ONLY';
        readUnit = quantity + ' (' + String.valueOf(quantityCargo) + ') ' + shipment.CargoUnit__c + addS;
        lstCon = getDataCon(id);
        lstConOutput = new List<WrapperCon>();
        Integer top = 107;
        Integer topDes = 103;
        Integer topBlank = 116;
        Integer topDesBlank = 112;
        String read = '';
        totalQuantity = 0;
        totalMeasurement =0;
        totalGrossWeight = 0;
        finalTop = 0;
        finalTopBlank = 0;
        Integer count = 0;
        for (CntrinTrans__c con : lstCon) {
            WrapperCon conOutput = new WrapperCon(); 
            String output = 'position:absolute; left: 11mm; top:' + top + 'mm; width:50mm; text-align: left';
            String outputBlank = 'position:absolute; left: 15mm; top:' + topBlank + 'mm; width:50mm; text-align: left';
            conOutput.conNo = con.Container_Number__c;
            conOutput.conType = con.Container_Type__c;
            conOutput.sealNo = con.Seal_Number__c;
            if(con.Cargo_Unit__c != null && con.Cargo_Quantity__c == 1){
                conOutput.unit = con.Cargo_Unit__c;
            }
            if(con.Cargo_Unit__c != null && con.Cargo_Quantity__c > 1){
                conOutput.unit = con.Cargo_Unit__c +'S';
            }
            if(con.Cargo_Unit__c == null){
                conOutput.unit = '';
            }
            
            conOutput.type = output;
            conOutput.typeBlank = outputBlank;
            conOutput.typeReadCon = 'position:absolute; left: 81mm; top:' + topDes + 'mm; width:60mm; text-align: left;';
            conOutput.typeReadConBlank = 'position:absolute; left: 67mm; top:' + topDesBlank + 'mm; width:60mm; text-align: left;';
            conOutput.readCon = 'A PART OF '+ReadNumberToWords.convert(con.Container_Quantity__c.setScale(2, System.RoundingMode.HALF_UP)) + ' ('  + con.Container_Quantity__c + ')X' + con.Container_Type__c + ' CONTAINER(S)' ; 
            if (count > 0) {
                read += ' AND ' + ReadNumberToWords.convert(con.Container_Quantity__c.setScale(2, System.RoundingMode.HALF_UP)) + ' ('  + con.Container_Quantity__c + ')X' + con.Container_Type__c;
            } else {
                read += ReadNumberToWords.convert(con.Container_Quantity__c.setScale(2, System.RoundingMode.HALF_UP)) + ' ('  + con.Container_Quantity__c + ')X' + con.Container_Type__c;
            }
            conOutput.top = top;
            conOutput.topBlank = topBlank;
            conOutput.quantity = con.Cargo_Quantity__c != null?con.Cargo_Quantity__c:0;
            conOutput.grossWeight = con.Gross_Weight_Kg__c != null?con.Gross_Weight_Kg__c:0;
            conOutput.measurement = con.Measurement_CBM__c != null?con.Measurement_CBM__c:0;
            totalQuantity += conOutput.quantity;
            totalGrossWeight += conOutput.grossWeight;
            totalMeasurement += conOutput.measurement;
            count ++;
            topDes += 4;
            top += 4;
            topDesBlank += 4;
            topBlank += 4;
            lstConOutput.add(conOutput);
        }
        if (lstCon.size() == 0){
            topDes += 4;
            topDesBlank += 4;
        }
        finalTop = top;
        finalTopBlank = topBlank;
        readCon = 'A PART OF '+ read + ' CONTAINER(S)';
        readConFull = read + ' CONTAINER(S)';
        typeMarks = 'position:absolute; left: 11mm; top:' + (top+4) + 'mm; width:65mm; text-align: left';
        typeDescrip = 'position:absolute; left: 81mm; top:' + topDes + 'mm; width:60mm; text-align: left;';
        typeMarksBlank = 'position:absolute; left: 15mm; top:' + (topBlank+4) + 'mm; width:65mm; text-align: left';
        typeDescripBlank = 'position:absolute; left: 67mm; top:' + topDesBlank + 'mm; width:60mm; text-align: left;';

        if(shipment.CargoUnit__c != null && totalQuantity == 1){
            cargoUnit = shipment.CargoUnit__c;
        }
        if(shipment.CargoUnit__c != null && totalQuantity > 1){
            cargoUnit = shipment.CargoUnit__c + 'S';
        }
        if(shipment.CargoUnit__c == null){
            cargoUnit = '';
        }
        
    }

    public FTMSSO__c getData(String id){
        List<FTMSSO__c> shipments = [SELECT 
        Id,
        ShipperDetailInformation_text__c,
        HBLNumber__c,
        ConsigneeDetailInformation_text__c,
        HouseNotifyDetailInformation_text__c,
        PlaceofReceiptDetailInformation__c,
        POLAODsDetailInformation__c,
        PODAOAsDetailInformation__c,
        VesselFlight__c ,
        Voyage__c,
        PlaceofDeliveryDetailInformation__c,
        NumberofOriginalHBLIssued__c,
        CargoType__c,
        CargoQuantity__c,
        DescriptionofGoods__c,
        GrossWeight__c,
        Measurement__c,
        MarksNumbersAttachment__c,
        CargoUnit__c,
        PlaceofHouseBLIssued__c,
        DateofHouseBLIssued__c,
        MeasurementTotalCBM__c,
        HouseFreightCollectPrepaid__c,
        AgentDetailInformation_text__c,
        Date_of_issue__c,
        DeliveryPartysDetails_text__c,
        HBLType__c,
        Precarriagevoyage__c,
        MasterShippersDetailInformation__c,
        MasterNotifyPartysDetailInformation__c,
        MasterConsigneesDetailInformation__c
         FROM FTMSSO__c WHERE Id = :id];

        shipments.get(0).CargoQuantity__c = shipments.get(0).CargoQuantity__c == null?0:shipments.get(0).CargoQuantity__c;

        return shipments.size() > 0 ? shipments.get(0) : null;
    }

    public List<CntrinTrans__c> getDataCon(String shipId){
        List<CntrinTrans__c> cntrs = [SELECT 
        Id,
        Container_Number__c,
        Container_Type__c,
        Seal_Number__c,
        Container_Quantity__c,
        Cargo_Quantity__c,
        Gross_Weight_Kg__c,
        Measurement_CBM__c,
        Cargo_Unit__c
        FROM CntrinTrans__c WHERE F_TMS_S_O__c = :shipId];

        return cntrs.size() > 0 ? cntrs : new List<CntrinTrans__c>();
    }
    @AuraEnabled
    public static String checkTypeHBL(String recordId){       
        FTMSSO__c item = new FTMSSO__c();
        String strSelect ='SELECT Id,Shipment_Type__c';
        String strFrom = ' FROM FTMSSO__c ';
        String strWhere = 'WHERE Id = \'' + recordId + '\'' ;
        String strOrderBy = ' ORDER BY Name LIMIT 1';
        String data = strSelect + strFrom + strWhere + strOrderBy;
        item = Database.query(data);
        if (item.Shipment_Type__c == 'FCL'){
            return 'FCL';
        } else {
            return 'LCL';
        }   
    }
    @AuraEnabled
    public static void generateAttachmentFile(String recordId,Boolean requiredAttachmentCreation, String type, String backGround){
        PageReference pdf_file =Page.page_PrintHBLFull;
        if(type == 'fcl' && backGround == 'true'){
             pdf_file =Page.page_PrintHBLFull;
        }
        if(type == 'fcl' && backGround == 'false'){
             pdf_file =Page.page_PrintHBLFullBlank;
        }
        if(type == 'lcl' && backGround == 'true'){
             pdf_file =Page.page_PrintHBL;
        }
        if(type == 'lcl' && backGround == 'false'){
             pdf_file =Page.page_PrintHBLBlank;
        }
        
        pdf_file.getParameters().put('Id', recordId);
        pdf_file.getParameters().put('requiredAttachmentCreation', 'false');
        
        FTMSSO__c item = new FTMSSO__c();
        String strSelect ='SELECT Id,ShipperDetailInformation_text__c,HBLNumber__c,ConsigneeDetailInformation_text__c,HouseNotifyDetailInformation_text__c,PlaceofReceiptDetailInformation__c,POLAODsDetailInformation__c,PODAOAsDetailInformation__c,VesselFlight__c ,Voyage__c,PlaceofDeliveryDetailInformation__c,NumberofOriginalHBLIssued__c,CargoType__c,CargoQuantity__c,DescriptionofGoods__c,GrossWeight__c,Measurement__c,MarksNumbersAttachment__c,CargoUnit__c,PlaceofHouseBLIssued__c,DateofHouseBLIssued__c,MeasurementTotalCBM__c,HouseFreightCollectPrepaid__c,AgentDetailInformation_text__c,Date_of_issue__c,DeliveryPartysDetails_text__c,HBLType__c';
        String strFrom = ' FROM FTMSSO__c ';
        String strWhere = 'WHERE Id = \'' + recordId + '\'' ;
        String strOrderBy = ' ORDER BY Name LIMIT 1';
        String data = strSelect + strFrom + strWhere + strOrderBy;
        item = Database.query(data);
        String namefile ='HBL_v' ;

       
        String attachName = namefile ;
        String attachNameSearch = attachName + '%';
        // get exist file Name
        List<Attachment> attachments = [SELECT Id, Name, ParentId 
                                        FROM Attachment 
                                        WHERE ParentId =: recordId 
                                        AND Name LIKE : attachNameSearch 
                                        ORDER BY CreatedDate DESC LIMIT 1];
                                        
        if(attachments.isEmpty()){
            attachName += '1.1';
        }else{
            String attachNameExist = attachments[0].Name;
            attachNameExist = attachNameExist.substringAfter(attachName);
            attachNameExist = attachNameExist.substringBefore('.pdf');
            Decimal versionNumber = Decimal.valueOf(attachNameExist);
            versionNumber += 0.1;
            attachName += String.valueOf(versionNumber);
        }
        if(requiredAttachmentCreation != false){
            Attachment attach = new Attachment();
            Blob body;
            attach.Name = attachName + '.pdf'; 
            attach.IsPrivate = false;
            attach.ParentId = recordId;
            if(!Test.isRunningTest()){
                body = pdf_file.getContentAsPDF();
                System.debug('debuggg Thong :'+body);
                attach.Body = body;
                FlsService.doInsert(attach);
            }
        }   
    }

    public class WrapperCon {
        public String conNo {get; set;}
        public String conType {get; set;}
        public String sealNo {get; set;}
        public String type {get; set;}
        public String typeBlank {get; set;}
        public String typeReadCon {get; set;}
        public String typeReadConBlank {get; set;}
        public Decimal quantity {get; set;}
        public Decimal grossWeight {get; set;}
        public Decimal measurement {get; set;}
        public String readCon {get; set;}
        public String unit {get; set;}
        public Integer top {get; set;}
        public Integer topBlank {get; set;}
        public WrapperCon() {
            conNo = '';
            conType = '';
            sealNo = '';
            type = '';
            typeBlank = '';
            typeReadCon = '';
            typeReadConBlank = '';
            readCon = '';
            unit = '';
            quantity = 0;
            grossWeight = 0;
            measurement = 0;
        } 
    }
}