force-app/main/default/objects/CntrinTrans__c/CntrinTrans__c.object-meta.xml
<CustomObject>
    <label>CNTR in Trans</label>
    <nameField>
        <displayFormat>CNTR-{00000}</displayFormat>
        <label>CNTR in Trans</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CNTR in Trans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CntrinTrans__c/fields/CargoUnit__c.field-meta.xml
<CustomField>
    <fullName>CargoUnit__c</fullName>
    <label>Cargo Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargoUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/Transportation__c.field-meta.xml
<CustomField>
    <fullName>Transportation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transportation</label>
    <referenceTo>Transportation__c</referenceTo>
    <relationshipLabel>CNTR in Trans</relationshipLabel>
    <relationshipName>CNTR_in_Trans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CompanyInformation__c/CompanyInformation__c.object-meta.xml
<CustomObject>
    <label>Company Information</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CompanyInformation__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <defaultValue>&apos;TIMES CARGO LOGISTIC CO.,LTD&apos;</defaultValue>
    <label>Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/FTMSSO__c.object-meta.xml
<CustomObject>
    <label>Shipment.</label>
    <nameField>
        <displayFormat>FSO-{000000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments.</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSSO__c/fields/AgentDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>AgentDetailInformation__c</fullName>
    <label>Agent’s Detail Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoQuantity__c.field-meta.xml
<CustomField>
    <fullName>CargoQuantity__c</fullName>
    <label>Cargo Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoUnit__c.field-meta.xml
<CustomField>
    <fullName>CargoUnit__c</fullName>
    <label>Cargo Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CargoUnit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ConsigneeDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>ConsigneeDetailInformation__c</fullName>
    <label>Consignee’s Detail Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ContainerNo__c.field-meta.xml
<CustomField>
    <fullName>ContainerNo__c</fullName>
    <label>Container No</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ContainerNoSealNo__c.field-meta.xml
<CustomField>
    <fullName>ContainerNoSealNo__c</fullName>
    <label>Container No/Seal No</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CWDimension__c.field-meta.xml
<CustomField>
    <fullName>CWDimension__c</fullName>
    <label>C.W(Dimension)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Date_of_issue__c.field-meta.xml
<CustomField>
    <fullName>Date_of_issue__c</fullName>
    <label>Date of issue</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/FinalDestination__c.field-meta.xml
<CustomField>
    <fullName>FinalDestination__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Final Destination</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>Gross Weight</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HouseFreightCollectPrepaid__c.field-meta.xml
<CustomField>
    <fullName>HouseFreightCollectPrepaid__c</fullName>
    <label>House Freight Collect/Prepaid</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collected</fullName>
            </value>
            <value>
                <fullName>Prepaid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/HouseNotifyPartyDetail_Information__c.field-meta.xml
<CustomField>
    <fullName>HouseNotifyPartyDetail_Information__c</fullName>
    <label>House Notify Party’s Detail Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MarksNumbersAttachment__c.field-meta.xml
<CustomField>
    <fullName>MarksNumbersAttachment__c</fullName>
    <label>Marks &amp; Numbers Attachment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/MeasurementTotalCBM__c.field-meta.xml
<CustomField>
    <fullName>MeasurementTotalCBM__c</fullName>
    <label>Measurement (Total CBM)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/NumberofOriginalHBLIssued__c.field-meta.xml
<CustomField>
    <fullName>NumberofOriginalHBLIssued__c</fullName>
    <label>Number of Original H B/L Issued</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZERO(0)</fullName>
            </value>
            <value>
                <fullName>ONE(1)</fullName>
            </value>
            <value>
                <fullName>TWO(2)</fullName>
            </value>
            <value>
                <fullName>THREE(3)</fullName>
                <default>true</default>
                <label>THREE(3)</label>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Payable_At_HBL__c.field-meta.xml
<CustomField>
    <fullName>Payable_At_HBL__c</fullName>
    <formula>IF(TEXT(HouseFreightCollectPrepaid__c)=&quot;Prepaid&quot;, POLAODsDetailInformation__c, PODAOAsDetailInformation__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payable At (HBL)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Place_of_issue__c.field-meta.xml
<CustomField>
    <fullName>Place_of_issue__c</fullName>
    <label>Place of issue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PlaceofDelivery__c.field-meta.xml
<CustomField>
    <fullName>PlaceofDelivery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place of Delivery</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PlaceofReceipt__c.field-meta.xml
<CustomField>
    <fullName>PlaceofReceipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place of Receipt</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PODAOA__c.field-meta.xml
<CustomField>
    <fullName>PODAOA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.D(A.O.A)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/POLAOD__c.field-meta.xml
<CustomField>
    <fullName>POLAOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.L(A.O.D)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/PrepaidAt__c.field-meta.xml
<CustomField>
    <fullName>PrepaidAt__c</fullName>
    <label>Prepaid At</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/SecondNotifyParty__c.field-meta.xml
<CustomField>
    <fullName>SecondNotifyParty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>2nd Notify Party</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>FTMSSO7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/ShipperDetailInformation__c.field-meta.xml
<CustomField>
    <fullName>ShipperDetailInformation__c</fullName>
    <label>Shipper’s Detail Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PortCode__c/PortCode__c.object-meta.xml
<CustomObject>
    <label>Port Code</label>
    <nameField>
        <label>Port Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Port Code</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PortCode__c/fields/City_Name__c.field-meta.xml
<CustomField>
    <fullName>City_Name__c</fullName>
    <label>City Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortCode__c/fields/CountryName__c.field-meta.xml
<CustomField>
    <fullName>CountryName__c</fullName>
    <formula>Country__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transportation__c/Transportation__c.object-meta.xml
<CustomObject>
    <label>Trucking</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Transportation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Truckings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transportation__c/fields/CNTRinTrans__c.field-meta.xml
<CustomField>
    <fullName>CNTRinTrans__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CNTR in Trans</label>
    <referenceTo>CntrinTrans__c</referenceTo>
    <relationshipLabel>Truckings</relationshipLabel>
    <relationshipName>Truckings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transportation__c/fields/ContainerNo__c.field-meta.xml
<CustomField>
    <fullName>ContainerNo__c</fullName>
    <formula>If(   JobContainer__c  &lt;&gt; null,    JobContainer__r.Container_Number__c   ,  CNTRinTrans__r.Container_Number__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Container No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transportation__c/fields/ETD__c.field-meta.xml
<CustomField>
    <fullName>ETD__c</fullName>
    <label>ETD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transportation__c/fields/FinalDestination__c.field-meta.xml
<CustomField>
    <fullName>FinalDestination__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Final Destination</label>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipLabel>Truckings (Final Destination)</relationshipLabel>
    <relationshipName>Truckings2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transportation__c/fields/GrossWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossWeight__c</fullName>
    <label>Gross Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transportation__c/fields/PlaceofDelivery__c.field-meta.xml
<CustomField>
    <fullName>PlaceofDelivery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place of Delivery</label>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipLabel>Truckings (Place of Delivery)</relationshipLabel>
    <relationshipName>Truckings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transportation__c/fields/PlaceofReceipt__c.field-meta.xml
<CustomField>
    <fullName>PlaceofReceipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Place of Receipt</label>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipLabel>Truckings (Place of Receipt)</relationshipLabel>
    <relationshipName>Truckings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/CargoUnit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B/PLT</fullName>
    </customValue>
    <customValue>
        <fullName>BAG</fullName>
    </customValue>
    <customValue>
        <fullName>BAL</fullName>
    </customValue>
    <customValue>
        <fullName>BALE</fullName>
    </customValue>
    <customValue>
        <fullName>BALE, COMPRESSED</fullName>
    </customValue>
    <customValue>
        <fullName>Bale,non-compressed</fullName>
        <label>BALE, NON-COMPRESSED</label>
    </customValue>
    <customValue>
        <fullName>Bar</fullName>
        <label>BAR</label>
    </customValue>
    <customValue>
        <fullName>BARE</fullName>
    </customValue>
    <customValue>
        <fullName>BARREL</fullName>
    </customValue>
    <customValue>
        <fullName>BILL</fullName>
    </customValue>
    <customValue>
        <fullName>BIN</fullName>
    </customValue>
    <customValue>
        <fullName>BOX</fullName>
    </customValue>
    <customValue>
        <fullName>BOX CARTON</fullName>
    </customValue>
    <customValue>
        <fullName>BOXE</fullName>
    </customValue>
    <customValue>
        <fullName>BOXPAL</fullName>
    </customValue>
    <customValue>
        <fullName>BUCKET</fullName>
    </customValue>
    <customValue>
        <fullName>BULK</fullName>
    </customValue>
    <customValue>
        <fullName>BUNDLE</fullName>
    </customValue>
    <customValue>
        <fullName>CAGE</fullName>
    </customValue>
    <customValue>
        <fullName>CAN</fullName>
    </customValue>
    <customValue>
        <fullName>Can,cylindrical</fullName>
        <label>CAN, CYLINDRICAL</label>
    </customValue>
    <customValue>
        <fullName>Can,rectangular</fullName>
        <label>CAN, RECTANGULAR</label>
    </customValue>
    <customValue>
        <fullName>CARBOY, NON-PROTECTED</fullName>
    </customValue>
    <customValue>
        <fullName>Carboy,protected</fullName>
        <label>CARBOY, PROTECTED</label>
    </customValue>
    <customValue>
        <fullName>CARDBOARD</fullName>
    </customValue>
    <customValue>
        <fullName>CARDBOXE</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON BOX</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON BOXE</fullName>
    </customValue>
    <customValue>
        <fullName>CARTON PALLET</fullName>
    </customValue>
    <masterLabel>Cargo Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/printSeaManifestController.cls
public with sharing class printSeaManifestController {
    private static Set<String> SoQuery = new Set<String>();
    private static Set<String> CNTRQuery = new Set<String>();

    public Transportation__c trains {get;set;}
    public CompanyInformation__c Company {get;set;}
    public String formattedDateTime { get; set; }
    public List<CntrinTrans__c> CNTRList {get;set;}
    public FTMSSO__c So {get;set;}

    static{
        SoQuery.add('ShipperDetailInformation__c');
        SoQuery.add('ConsigneeDetailInformation__c');
        SoQuery.add('HouseNotifyPartyDetail_Information__c');
        SoQuery.add('PlaceofReceipt__r.City_Name__c');
        SoQuery.add('PlaceofReceipt__r.CountryName__c');
        SoQuery.add('POLAOD__r.City_Name__c');
        SoQuery.add('POLAOD__r.CountryName__c');
        SoQuery.add('PODAOA__r.City_Name__c');
        SoQuery.add('PODAOA__r.CountryName__c');
        SoQuery.add('PlaceofDelivery__r.City_Name__c');
        SoQuery.add('PlaceofDelivery__r.CountryName__c');
        SoQuery.add('FinalDestination__r.City_Name__c');
        SoQuery.add('FinalDestination__r.CountryName__c');
        SoQuery.add('MarksNumbersAttachment__c');
        SoQuery.add('CargoQuantity__c');
        SoQuery.add('CargoUnit__c');
        SoQuery.add('DescriptionofGoods__c');
        SoQuery.add('GrossWeight__c');
        SoQuery.add('MeasurementTotalCBM__c');
        SoQuery.add('ETD__c');
        SoQuery.add('HouseFreightCollectPrepaid__c');
        SoQuery.add('AgentDetailInformation__c');
        SoQuery.add('PrepaidAt__c');
        SoQuery.add('Payable_At_HBL__c');
        SoQuery.add('NumberofOriginalHBLIssued__c');
        SoQuery.add('Place_of_issue__c');
        SoQuery.add('Date_of_issue__c');
        SoQuery.add('PODAOA__r.City_Name__c');
        SoQuery.add('CWDimension__c');
        SoQuery.add('ContainerNo__c');
        SoQuery.add('ContainerNoSealNo__c');
        SoQuery.add('SecondNotifyParty__c');
        SoQuery.add('TransitPortCode__c');
        SoQuery.add('FinalDestination__r.PortCode__c');
        SoQuery.add('POLAOD__r.PortCode__c');
        SoQuery.add('PODAOA__r.PortCode__c');
        SoQuery.add('PlaceofDelivery__r.Name');
        SoQuery.add('CargoType__c');
        SoQuery.add('HBLNumber__c');
        SoQuery.add('DateofHouseBLIssued__c');
        SoQuery.add('MBLNumber__c');
        SoQuery.add('DateofMasterBLIssued__c');
        SoQuery.add('PackageUnitCode__c');
        SoQuery.add('GrossWeightUnit__c');
        SoQuery.add('RemarkonManifest__c');
        SoQuery.add('MAWBNumber__c');
        SoQuery.add('POLAOD__r.Name');
        SoQuery.add('FlightNumber__c');
        SoQuery.add('HAWBNumber__c');
        SoQuery.add('NumberofContainersPackages__c');
        SoQuery.add('Plural_Cargo_Unit__c');
        SoQuery.add('FinalDestination__r.Standard_Port_Code__c');
        SoQuery.add('VesselFlight__c');
        SoQuery.add('HSCode__c');
        SoQuery.add('HouseNotifyPartyDetail_Information__c');
        SoQuery.add('SecondNotifyPartyDetailInformation__c');
        SoQuery.add('FinalDestination__r.Standard_Port_Code__c');
        SoQuery.add('POLAOD__r.Standard_Port_Code__c');
        SoQuery.add('PODAOA__r.Standard_Port_Code__c');
        

        CNTRQuery.add('Gross_Weight_Kg__c');
         CNTRQuery.add('Description_of_Goods__c');
         CNTRQuery.add('Measurement_CBM__c');
         CNTRQuery.add('Container_Number__c');
         CNTRQuery.add('Seal_Number__c');

        
    }
    public printSeaManifestController() {
        String OderID = ApexPages.currentPage().getParameters().get('id');
        So = getSo(OderID);
        CNTRList = getCNTR(OderID);

        Company= [SELECT Name,Name__c,
         Id,CompanyLogo__c,
         TaxCode__c,Tel__c,Website__c
         ,Email__c ,Address__c,Fax__c
          FROM CompanyInformation__c  WHERE Branch1__c = 'Hồ Chí Minh' limit 1];
          Datetime currentDateTime = Datetime.now();
          formattedDateTime = formatDatetime(currentDateTime);

    }
    public String formatDatetime(Datetime dt) {
        // Format the datetime in the desired format
        return dt.format('dd MMM, yyyy  h:mm:ssa');
     }
    private FTMSSO__c getSo(String scheduleID){
        String strSelect = String.join(new List<String>(SoQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM FTMSSO__c'
                    + ' WHERE Id = \'' + scheduleID + '\'';
                    FTMSSO__c donhang;
        try{
            donhang = Database.query(strQuery);
        } catch(QueryException e){
            donhang = new FTMSSO__c();
        }
        return donhang;
    }

    private List<CntrinTrans__c> getCNTR(String scheduleID){
        String strSelect = String.join(new List<String>(CNTRQuery), ',');
        String strQuery = 'SELECT ' + strSelect 
                    + ' FROM CntrinTrans__c'
                    + ' WHERE F_TMS_S_O__c = \'' + scheduleID + '\'';
                    List<CntrinTrans__c> donhang;
        try{
            donhang = Database.query(strQuery);
        } catch(QueryException e){
            donhang = new List<CntrinTrans__c>();
        }
        return donhang;
    }

}