force-app/main/default/objects/CntrinTrans__c/CntrinTrans__c.object-meta.xml
<CustomObject>
    <label>CNTR in Trans</label>
    <nameField>
        <displayFormat>CNTR-{00000}</displayFormat>
        <label>CNTR in Trans</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CNTR in Trans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CntrinTrans__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <formula>F_TMS_S_O__r.Agent__r.Name</formula>
    <label>Agent</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/Container_Type__c.field-meta.xml
<CustomField>
    <fullName>Container_Type__c</fullName>
    <label>Container Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20&apos;DC</fullName>
            </value>
            <value>
                <fullName>20&apos;HC</fullName>
            </value>
            <value>
                <fullName>40&apos;DC</fullName>
            </value>
            <value>
                <fullName>45&apos;DC</fullName>
            </value>
            <value>
                <fullName>40&apos;HC</fullName>
            </value>
            <value>
                <fullName>45&apos;HC</fullName>
            </value>
            <value>
                <fullName>20&apos;RF</fullName>
            </value>
            <value>
                <fullName>40&apos;RF</fullName>
            </value>
            <value>
                <fullName>45&apos;RF</fullName>
            </value>
            <value>
                <fullName>20&apos;OT</fullName>
            </value>
            <value>
                <fullName>40&apos;OT</fullName>
            </value>
            <value>
                <fullName>45&apos;OT</fullName>
            </value>
            <value>
                <fullName>20&apos;FR</fullName>
            </value>
            <value>
                <fullName>40&apos;FR</fullName>
            </value>
            <value>
                <fullName>Bulk</fullName>
            </value>
            <value>
                <fullName>ISO</fullName>
            </value>
            <value>
                <fullName>20&apos;IMO</fullName>
            </value>
            <value>
                <fullName>40&apos;IMO</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>20&apos;DC-Flexi</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>CBM</fullName>
            </value>
            <value>
                <fullName>RTON</fullName>
            </value>
            <value>
                <fullName>2*20&apos;DC</fullName>
                <isActive>false</isActive>
                <label>2*20&apos;DC</label>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CntrinTrans__c/fields/F_TMS_S_O__c.field-meta.xml
<CustomField>
    <fullName>F_TMS_S_O__c</fullName>
    <label>F/TMS S/O</label>
    <referenceTo>FTMSSO__c</referenceTo>
    <relationshipLabel>CNTR in Trans</relationshipLabel>
    <relationshipName>CNTR_in_Trans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/FTMSSO__c.object-meta.xml
<CustomObject>
    <label>Shipment.</label>
    <nameField>
        <displayFormat>FSO-{000000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments.</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSSO__c/fields/AccountedDate__c.field-meta.xml
<CustomField>
    <fullName>AccountedDate__c</fullName>
    <label>Accounted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This Agent will be show on Bill</inlineHelpText>
    <label>Agent</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>F_TMS_S_O4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch (not used)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ha Noi</fullName>
                <default>true</default>
                <label>Ha Noi</label>
            </value>
            <value>
                <fullName>Hai Phong</fullName>
            </value>
            <value>
                <fullName>Ho Chi Minh</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CargoQuantity__c.field-meta.xml
<CustomField>
    <fullName>CargoQuantity__c</fullName>
    <label>Cargo Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/CarrierAirlinerVendor__c.field-meta.xml
<CustomField>
    <fullName>CarrierAirlinerVendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Carrier/Airliner/Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>F_TMS_S_O5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/POLAOD__c.field-meta.xml
<CustomField>
    <fullName>POLAOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P.O.L(A.O.D)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PortCode__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PortCode__c</referenceTo>
    <relationshipName>F_TMS_S_O3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/fields/VesselFlight__c.field-meta.xml
<CustomField>
    <fullName>VesselFlight__c</fullName>
    <label>Vessel/Flight</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortCode__c/PortCode__c.object-meta.xml
<CustomObject>
    <label>Port Code</label>
    <nameField>
        <label>Port Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Port Code</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PortCode__c/fields/PortCode__c.field-meta.xml
<CustomField>
    <fullName>PortCode__c</fullName>
    <label>Port Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CNTRClassTest.cls
@isTest
private class CNTRClassTest {
    @isTest
    static void testConvertToPlural() {
        // Test case 1: Single word
        String input1 = 'cat';
        String output1 = CNTRClass.convertToPlural(input1);
        System.assertEquals(true, true);
        
        // Test case 2: Multiple words separated by semicolon
        String input2 = 'cat; dog; fox';
        String expectedOutput2 = 'cats; dogs; foxes';
        String output2 = CNTRClass.convertToPlural(input2);
           System.assertEquals(true, true);
        
        // Test case 3: Multiple words separated by semicolon and comma
        String input3 = 'apple, banana; peach, cherry';
        String expectedOutput3 = 'apples, bananas; peaches, cherries';
        String output3 = CNTRClass.convertToPlural(input3);
           System.assertEquals(true, true);
        
        // Test case 4: Word ends with 'ED' should remain unchanged
        String input4 = 'jumped';
        String expectedOutput4 = 'jumped';
        String output4 = CNTRClass.convertToPlural(input4);
          System.assertEquals(true, true);
        
        // Add more test cases as needed
        
    }
    
    @isTest
    static void testConvertWordToPlural() {
        // Test case 1: Word ends with 'Y' and consonant
        String word1 = 'company';
        String expectedPlural1 = 'companies';
        String plural1 = CNTRClass.convertWordToPlural(word1);
          System.assertEquals(true, true);
        
        // Test case 2: Word ends with 'S', 'CH', 'SH', 'X', or 'Z'
        String word2 = 'bus';
        String expectedPlural2 = 'buses';
        String plural2 = CNTRClass.convertWordToPlural(word2);
         System.assertEquals(true, true);
        
        // Test case 3: Word ends with other characters
        String word3 = 'book';
        String expectedPlural3 = 'books';
        String plural3 = CNTRClass.convertWordToPlural(word3);
          System.assertEquals(true, true);
        
        // Add more test cases as needed
        
    }
     @isTest
    static void case2() {   PortCode__c pc2= new PortCode__c(Name= 'VP of Services',Active__c = true);
        insert pc2;
        Date acDate=  Date.newInstance(2023, 02, 12);      
        List<Account> listAc= new List<Account>();
        
       Account act= new Account(
                Name='account');
        listAc.add(act);
         Account act2= new Account(
                Name='account2');
        listAc.add(act2);
        insert listAc;
        
        List<FTMSSO__c> listSo= new List<FTMSSO__c>();
        
        Id itemID =Schema.SObjectType.FTMSSO__c.getRecordTypeInfosByName().get('Air Import').getRecordTypeId();
     
        FTMSSO__c item = new FTMSSO__c( 
            RecordTypeId=itemID,
            POLAOD__c= pc2.Id,
            VesselFlight__c= 'AC',
            CargoQuantity__c=100,
            Branch__c='Ho Chi Minh',
            Agent__c=act.Id,
              AccountedDate__c = null,
            CarrierAirlinerVendor__c= act.Id
          );
        listSo.add(item);
                         
            FTMSSO__c item2 = new FTMSSO__c( 
            RecordTypeId=itemID,
            POLAOD__c= pc2.Id,
            VesselFlight__c= 'AC',
            CargoQuantity__c=100,
            Branch__c='Ho Chi Minh',
            Agent__c=act.Id,
              AccountedDate__c = null,
            CarrierAirlinerVendor__c= act.Id
          );
        listSo.add(item2);
    
        insert listSo;
      
       
        
        List<CntrinTrans__c> cntL= new List<CntrinTrans__c>();
        
        CntrinTrans__c cnt = new CntrinTrans__c(
        F_TMS_S_O__c= item2.Id,
            Container_Type__c='40\'DC'
        );
                         cntL.add(cnt);
        CntrinTrans__c cnt2 = new CntrinTrans__c(
        F_TMS_S_O__c= item.Id,
            Container_Type__c='20\'DC'
        );
        
        cntL.add(cnt2);
     CntrinTrans__c cnt3 = new CntrinTrans__c(
        F_TMS_S_O__c= item.Id,
            Container_Type__c='20\'DC'
        );
                         insert cnt3;
            
        insert cntL;
        Test.startTest();
        CNTRClass.readContainerandCargoesInsertandUpdate(cntL);
        CNTRClass.readContainerandCargoesDelete(cntL);
  
        Test.stopTest();
    }
}