force-app/main/default/objects/ConsolBill__c/ConsolBill__c.object-meta.xml
<CustomObject>
    <label>Billing</label>
    <nameField>
        <displayFormat>MC-{000000}</displayFormat>
        <label>Billing ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ConsolBill__c/fields/ChargeUnit__c.field-meta.xml
<CustomField>
    <fullName>ChargeUnit__c</fullName>
    <label>Charge Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>20&apos;DC-Flexi</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>B/L</fullName>
            </value>
            <value>
                <fullName>Bill</fullName>
            </value>
            <value>
                <fullName>Box</fullName>
            </value>
            <value>
                <fullName>Carton</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>CBM</fullName>
            </value>
            <value>
                <fullName>Container</fullName>
            </value>
            <value>
                <fullName>Day</fullName>
            </value>
            <value>
                <fullName>Drum</fullName>
            </value>
            <value>
                <fullName>Keg</fullName>
            </value>
            <value>
                <fullName>Kg</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Package</fullName>
            </value>
            <value>
                <fullName>Pallet</fullName>
            </value>
            <value>
                <fullName>Roll</fullName>
            </value>
            <value>
                <fullName>RTON</fullName>
            </value>
            <value>
                <fullName>Set</fullName>
            </value>
            <value>
                <fullName>Sheet</fullName>
            </value>
            <value>
                <fullName>Shipment</fullName>
            </value>
            <value>
                <fullName>Skid</fullName>
            </value>
            <value>
                <fullName>Truck</fullName>
            </value>
            <value>
                <fullName>Unit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/ConsolidationShipmentName__c.field-meta.xml
<CustomField>
    <fullName>ConsolidationShipmentName__c</fullName>
    <label>Consolidation Shipment Name</label>
    <referenceTo>AdvancedShipment__c</referenceTo>
    <relationshipName>Consol_Bills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/Container_Type__c.field-meta.xml
<CustomField>
    <fullName>Container_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ChargeUnit__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20&apos;DC</fullName>
            </value>
            <value>
                <fullName>20&apos;HC</fullName>
            </value>
            <value>
                <fullName>40&apos;DC</fullName>
            </value>
            <value>
                <fullName>45&apos;DC</fullName>
            </value>
            <value>
                <fullName>40&apos;HC</fullName>
            </value>
            <value>
                <fullName>45&apos;HC</fullName>
            </value>
            <value>
                <fullName>20&apos;RF</fullName>
            </value>
            <value>
                <fullName>40&apos;RF</fullName>
            </value>
            <value>
                <fullName>45&apos;RF</fullName>
            </value>
            <value>
                <fullName>20&apos;OT</fullName>
            </value>
            <value>
                <fullName>40&apos;OT</fullName>
            </value>
            <value>
                <fullName>45&apos;OT</fullName>
            </value>
            <value>
                <fullName>20&apos;FR</fullName>
            </value>
            <value>
                <fullName>40&apos;FR</fullName>
            </value>
            <value>
                <fullName>Bulk</fullName>
            </value>
            <value>
                <fullName>ISO</fullName>
            </value>
            <value>
                <fullName>20&apos;IMO</fullName>
            </value>
            <value>
                <fullName>40&apos;IMO</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>20&apos;DC-Flexi</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>CBM</fullName>
            </value>
            <value>
                <fullName>RTON</fullName>
            </value>
            <value>
                <fullName>-1000KGS</fullName>
            </value>
            <value>
                <fullName>+1000KGS</fullName>
            </value>
            <value>
                <fullName>+2000KGS</fullName>
            </value>
            <value>
                <fullName>+3000KGS</fullName>
            </value>
            <value>
                <fullName>+4000KGS</fullName>
            </value>
            <value>
                <fullName>+5000KGS</fullName>
            </value>
            <value>
                <fullName>+6000KGS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/CurrencySelling__c.field-meta.xml
<CustomField>
    <fullName>CurrencySelling__c</fullName>
    <label>Currency-Selling</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/FTMSSO__c.field-meta.xml
<CustomField>
    <fullName>FTMSSO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FTMSSO__c.ConsolidationID__c</field>
            <operation>equals</operation>
            <valueField>$Source.ConsolidationShipmentName__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FTMSSO__c</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Consol_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/Invoiceto__c.field-meta.xml
<CustomField>
    <fullName>Invoiceto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice to</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Consol_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/MasterBilling__c.field-meta.xml
<CustomField>
    <fullName>MasterBilling__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Billing</label>
    <referenceTo>ConsolBill__c</referenceTo>
    <relationshipName>Consol_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/PaymentTo__c.field-meta.xml
<CustomField>
    <fullName>PaymentTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment To</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Consol_Bills1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/PricingName__c.field-meta.xml
<CustomField>
    <fullName>PricingName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pricing Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Service__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service__c</referenceTo>
    <relationshipName>Consol_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/Tax_Included_Selling__c.field-meta.xml
<CustomField>
    <fullName>Tax_Included_Selling__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tax Included-Selling</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/TaxRatioSelling__c.field-meta.xml
<CustomField>
    <fullName>TaxRatioSelling__c</fullName>
    <label>Tax Ratio-Selling</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/UnitPriceofSellingActual__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceofSellingActual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Price of Selling (Actual)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/FTMSBill__c.object-meta.xml
<CustomObject>
    <label>F/TMS Bill</label>
    <nameField>
        <displayFormat>FTB-{000000}</displayFormat>
        <label>F/TMS Bill ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>F/TMS Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSBill__c/fields/ChargeUnit__c.field-meta.xml
<CustomField>
    <fullName>ChargeUnit__c</fullName>
    <label>Charge Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20&apos;DC-Flexi</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>B/L</fullName>
            </value>
            <value>
                <fullName>Bill</fullName>
            </value>
            <value>
                <fullName>Box</fullName>
            </value>
            <value>
                <fullName>Carton</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>CBM</fullName>
            </value>
            <value>
                <fullName>Container</fullName>
            </value>
            <value>
                <fullName>Day</fullName>
            </value>
            <value>
                <fullName>Drum</fullName>
            </value>
            <value>
                <fullName>Keg</fullName>
            </value>
            <value>
                <fullName>Kg</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Package</fullName>
            </value>
            <value>
                <fullName>Pallet</fullName>
            </value>
            <value>
                <fullName>Roll</fullName>
            </value>
            <value>
                <fullName>RTON</fullName>
            </value>
            <value>
                <fullName>Set</fullName>
            </value>
            <value>
                <fullName>Sheet</fullName>
            </value>
            <value>
                <fullName>Shipment</fullName>
            </value>
            <value>
                <fullName>Skid</fullName>
            </value>
            <value>
                <fullName>Unit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/ConsolBill__c.field-meta.xml
<CustomField>
    <fullName>ConsolBill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consol Bill</label>
    <referenceTo>ConsolBill__c</referenceTo>
    <relationshipLabel>F/TMS Bills (Consol Bill)</relationshipLabel>
    <relationshipName>F_TMS_Bills1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/CurrencySelling__c.field-meta.xml
<CustomField>
    <fullName>CurrencySelling__c</fullName>
    <label>Currency-Selling</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VND</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>KHR</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>KRW</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/FTMSSO__c.field-meta.xml
<CustomField>
    <fullName>FTMSSO__c</fullName>
    <label>F/TMS S/O</label>
    <referenceTo>FTMSSO__c</referenceTo>
    <relationshipLabel>F/TMS Bills</relationshipLabel>
    <relationshipName>F_TMS_Bills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/InvoiceTo__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS Bills</relationshipLabel>
    <relationshipName>F_TMS_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>VND</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>KHR</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <customValue>
        <fullName>KRW</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>Value1</fullName>
        <isActive>false</isActive>
        <label>Value1</label>
    </customValue>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MassUpdateConsolBillControllerV5.cls
public with sharing class MassUpdateConsolBillControllerV5 {
  @AuraEnabled
  public static String getRecordTypeId() {
    //TODO: Need to clarify which spefic developer name record here
    return [
      SELECT Id, SobjectType
      FROM RecordType
      WHERE
        SobjectType = 'FTMSBill__c'
        AND DeveloperName = 'Selling_Buyging_Standard'
    ]
    .Id;
  }

  @AuraEnabled
  public static String getDescribeSobjectResult() {
    DescribeSobjectResult objResult = Schema.SObjectType.FTMSBill__c;
    return objResult.isCreateable() +
      '_' +
      objResult.isUpdateable() +
      '_' +
      objResult.isAccessible() +
      '_' +
      objResult.isDeletable();
  }
  @AuraEnabled
  public static List<ConsolBill__c> getAllBillings(String shipmentId) {
    List<ConsolBill__c> getBilling = new List<ConsolBill__c>();
    getBilling = [
      SELECT (SELECT id FROM Consol_Bills__r),Id,
      Name,
      MasterBilling__c,
      PricingName__c,
      FTMSSO__c,
      ChargeUnit__c,
      Quantity__c,
      Container_Type__c,
      Invoiceto__c,
      CurrencySelling__c,
      UnitPriceofSellingActual__c,
      TaxRatioSelling__c,
      Tax_Included_Selling__c,
      PaymentTo__c,
      UnitPriceofBuyingActual__c,
      TaxRatioBuying__c,
      Tax_Included__c
      FROM ConsolBill__c
      WHERE ConsolidationShipmentName__c = :shipmentId AND MasterBilling__c = null
      ORDER BY Name
    ];

    return getBilling;
  }

  @AuraEnabled
  public static List<ConsolBill__c> getNewBillings(
    String shipmentId,
    Boolean isSelling,
    List<String> ids
  ) {
    List<ConsolBill__c> getBilling = new List<ConsolBill__c>();
    // if(isSelling){
    getBilling = [
      SELECT Id
      FROM ConsolBill__c
      WHERE ConsolidationShipmentName__c = :shipmentId AND Id NOT IN :ids
      ORDER BY Name
    ];
    System.debug('Thong debug :' + getBilling);
    // } else {
    //     getBilling =  [Select Id FROM ConsolBill__c
    //         WHERE ConsolidationShipmentName__c = :shipmentId
    //         AND Id NOT IN :ids

    //         ORDER BY Name];
    // }

    return getBilling;
  }
  @AuraEnabled
  public static List<ConsolBill__c> getSubBillings(String shipmentId) {
    List<ConsolBill__c> getBilling = new List<ConsolBill__c>();
    System.debug('shipmentId :' + shipmentId);
    getBilling = [
      SELECT Id,
      Name,
      MasterBilling__c,
      PricingName__c,
      FTMSSO__c,
      ChargeUnit__c,
      Quantity__c,
      Container_Type__c,
      Invoiceto__c,
      CurrencySelling__c,
      UnitPriceofSellingActual__c,
      TaxRatioSelling__c,
      Tax_Included_Selling__c,
      PaymentTo__c,
      UnitPriceofBuyingActual__c,
      TaxRatioBuying__c,
      Tax_Included__c
      FROM ConsolBill__c
      WHERE MasterBilling__c = :shipmentId
      ORDER BY Name
    ];
    System.debug('Thong debug 2 :' + getBilling);

    return getBilling;
  }
  @AuraEnabled
  public static Map<String, Object> getListWapper(String ShipID) {
    Map<String, Object> result = new Map<String, Object>();
    List<ConsolBill__c> lisdt = new List<ConsolBill__c>();
    List<ConsolBill__c> lisdoc = [
      SELECT id, (SELECT id FROM Consol_Bills__r)
      FROM ConsolBill__c
      WHERE ConsolidationShipmentName__c = :ShipID
      ORDER BY Name
    ];

    List<Id> unique = new List<Id>();
    for (ConsolBill__c lisdocItem : lisdoc) {
      if (lisdocItem.Id != null && !unique.contains(lisdocItem.Id)) {
        unique.add(lisdocItem.Id);
      }
    }

    system.debug('Fu doc list:' + lisdoc);
    if (lisdoc.size() > 0) {
      lisdt = [SELECT Id FROM ConsolBill__c WHERE MasterBilling__c IN :unique];
    }
    system.debug('Fu docdt list :' + lisdoc);
    result.put('DocList', lisdoc);
    result.put('DocListDT', lisdt);
    return result;
  }

  @AuraEnabled
  public static Boolean deleteBilling(String id) {
    try {
      List<ConsolBill__c> billings = [
        SELECT Id
        FROM ConsolBill__c
        WHERE Id = :id
      ];
      if (billings.size() == 0)
        return false;
      delete billings;
      return true;
    } catch (DmlException e) {
      throw e;
    }
  }

  @AuraEnabled
  public static String updateBillings(List<ConsolBill__c> jsonRecords, String billString) {
    System.debug('checkdebug1 :'+billString);
    // String u = '[{"Id":"a058d00000AhkaaAAB","Name":"MC-000007","MasterBilling__c":"a058d00000AhkauAAB","PricingName__c":"a0J8d000004TaQgEAK","ChargeUnit__c":"Container","Quantity__c":"7","Container_Type__c":"20\'DC","CurrencySelling__c":"USD","UnitPriceofSellingActual__c":0,"TaxRatioSelling__c":10,"Tax_Included_Selling__c":false,"PaymentTo__c":"0018d00000lU4oUAAS","UnitPriceofBuyingActual__c":1,"Tax_Included__c":false,"Consol_Bills__r":[{"MasterBilling__c":"a058d00000AhkaaAAB","Id":"a058d000009ad21AAA","Quantity__c":"8"},{"MasterBilling__c":"a058d00000AhkaaAAB","Id":"a058d00000AhkakAAB"}]';
    // List<ConsolBill__c> records = (List<ConsolBill__c>) System.JSON.deserialize(
    //   u,
    //   List<ConsolBill__c>.class
    // );
    // map<string,Object> resultMap = (map<string,Object>)JSON.deserializeUntyped(billString);
    // System.debug('debug1 :' + resultMap);
    List<ConsolBill__c> lstIdChild = new List<ConsolBill__c>();
    System.debug('Thong Debug :'+jsonRecords);
    Set<Id> ids = (new Map<Id, SObject>(jsonRecords)).keySet();
    System.debug('Idd :' + ids);
    List<ConsolBill__c> billings = [SELECT Id,
        
        Name,
        MasterBilling__c,
        PricingName__c,
        FTMSSO__c,
        ChargeUnit__c,
        Quantity__c,
        Container_Type__c,
        Invoiceto__c,
        CurrencySelling__c,
        UnitPriceofSellingActual__c,
        TaxRatioSelling__c,
        Tax_Included_Selling__c,
        PaymentTo__c,
        UnitPriceofBuyingActual__c,
        TaxRatioBuying__c,
        Tax_Included__c
      FROM ConsolBill__c
      WHERE Id IN :ids
      ORDER BY Name
    ];
    System.debug('debug2 :' + billings);

    for (ConsolBill__c childId : billings) {
      lstIdChild.addAll(childId.Consol_Bills__r);
    }
    System.debug('lstIdChild :'+lstIdChild);
    List<ConsolBill__c> itemsIdsToRemove = new List<ConsolBill__c>();

    for (Integer i = 0; i < jsonRecords.size(); i++) {
      ConsolBill__c r = jsonRecords[i];

      if (billings[i].Id == r.Id) {
        System.debug('checkdebug1');
        if (
          billings[i].PricingName__c != r.PricingName__c ||
          billings[i].MasterBilling__c != r.MasterBilling__c ||
          billings[i].FTMSSO__c != r.FTMSSO__c ||
          billings[i].ChargeUnit__c != r.ChargeUnit__c ||
          billings[i].Quantity__c != r.Quantity__c ||
          billings[i].Container_Type__c != r.Container_Type__c ||
          billings[i].Invoiceto__c != r.Invoiceto__c ||
          billings[i].CurrencySelling__c != r.CurrencySelling__c ||
          billings[i].UnitPriceofSellingActual__c !=
          r.UnitPriceofSellingActual__c ||
          billings[i].TaxRatioSelling__c != r.TaxRatioSelling__c ||
          billings[i].Tax_Included_Selling__c != r.Tax_Included_Selling__c ||
          billings[i].PaymentTo__c != r.PaymentTo__c ||
          billings[i].UnitPriceofBuyingActual__c !=
          r.UnitPriceofBuyingActual__c ||
          billings[i].TaxRatioBuying__c != r.TaxRatioBuying__c ||
          billings[i].Tax_Included__c != r.Tax_Included__c 
        ) {
        System.debug('checkdebug2');

          itemsIdsToRemove.add(r);
        }
      }
      System.debug('ThongCheck :'+itemsIdsToRemove);
    
    }
    // for (ConsolBill__c bill : itemsIdsToRemove) {
    //   System.debug('debug 4 :' + bill.ExchangeRateSelling__c);
    // }
    System.debug('debug3  :' + itemsIdsToRemove.size());
    try {
      update itemsIdsToRemove;
      return JSON.serialize(itemsIdsToRemove);
    } catch (Exception e) {
      throw new DmlException(e.getMessage());
    }
  }
}