force-app/main/default/objects/ConsolBill__c/ConsolBill__c.object-meta.xml
<CustomObject>
    <label>Billing</label>
    <nameField>
        <displayFormat>MC-{000000}</displayFormat>
        <label>Billing ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ConsolBill__c/fields/ChargeUnit__c.field-meta.xml
<CustomField>
    <fullName>ChargeUnit__c</fullName>
    <label>Charge Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>20&apos;DC-Flexi</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>B/L</fullName>
            </value>
            <value>
                <fullName>Bill</fullName>
            </value>
            <value>
                <fullName>Box</fullName>
            </value>
            <value>
                <fullName>Carton</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>CBM</fullName>
            </value>
            <value>
                <fullName>Container</fullName>
            </value>
            <value>
                <fullName>Day</fullName>
            </value>
            <value>
                <fullName>Drum</fullName>
            </value>
            <value>
                <fullName>Keg</fullName>
            </value>
            <value>
                <fullName>Kg</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Package</fullName>
            </value>
            <value>
                <fullName>Pallet</fullName>
            </value>
            <value>
                <fullName>Roll</fullName>
            </value>
            <value>
                <fullName>RTON</fullName>
            </value>
            <value>
                <fullName>Set</fullName>
            </value>
            <value>
                <fullName>Sheet</fullName>
            </value>
            <value>
                <fullName>Shipment</fullName>
            </value>
            <value>
                <fullName>Skid</fullName>
            </value>
            <value>
                <fullName>Truck</fullName>
            </value>
            <value>
                <fullName>Unit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/Container_Type__c.field-meta.xml
<CustomField>
    <fullName>Container_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ChargeUnit__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20&apos;DC</fullName>
            </value>
            <value>
                <fullName>20&apos;HC</fullName>
            </value>
            <value>
                <fullName>40&apos;DC</fullName>
            </value>
            <value>
                <fullName>45&apos;DC</fullName>
            </value>
            <value>
                <fullName>40&apos;HC</fullName>
            </value>
            <value>
                <fullName>45&apos;HC</fullName>
            </value>
            <value>
                <fullName>20&apos;RF</fullName>
            </value>
            <value>
                <fullName>40&apos;RF</fullName>
            </value>
            <value>
                <fullName>45&apos;RF</fullName>
            </value>
            <value>
                <fullName>20&apos;OT</fullName>
            </value>
            <value>
                <fullName>40&apos;OT</fullName>
            </value>
            <value>
                <fullName>45&apos;OT</fullName>
            </value>
            <value>
                <fullName>20&apos;FR</fullName>
            </value>
            <value>
                <fullName>40&apos;FR</fullName>
            </value>
            <value>
                <fullName>Bulk</fullName>
            </value>
            <value>
                <fullName>ISO</fullName>
            </value>
            <value>
                <fullName>20&apos;IMO</fullName>
            </value>
            <value>
                <fullName>40&apos;IMO</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>20&apos;DC-Flexi</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>CBM</fullName>
            </value>
            <value>
                <fullName>RTON</fullName>
            </value>
            <value>
                <fullName>-1000KGS</fullName>
            </value>
            <value>
                <fullName>+1000KGS</fullName>
            </value>
            <value>
                <fullName>+2000KGS</fullName>
            </value>
            <value>
                <fullName>+3000KGS</fullName>
            </value>
            <value>
                <fullName>+4000KGS</fullName>
            </value>
            <value>
                <fullName>+5000KGS</fullName>
            </value>
            <value>
                <fullName>+6000KGS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/CurrencySelling__c.field-meta.xml
<CustomField>
    <fullName>CurrencySelling__c</fullName>
    <label>Currency-Selling</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/FTMSSO__c.field-meta.xml
<CustomField>
    <fullName>FTMSSO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FTMSSO__c.ConsolidationID__c</field>
            <operation>equals</operation>
            <valueField>$Source.ConsolidationShipmentName__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FTMSSO__c</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Consol_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/Invoiceto__c.field-meta.xml
<CustomField>
    <fullName>Invoiceto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice to</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Consol_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/MasterBilling__c.field-meta.xml
<CustomField>
    <fullName>MasterBilling__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Billing</label>
    <referenceTo>ConsolBill__c</referenceTo>
    <relationshipName>Consol_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/PaymentTo__c.field-meta.xml
<CustomField>
    <fullName>PaymentTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment To</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Consol_Bills1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/PricingName__c.field-meta.xml
<CustomField>
    <fullName>PricingName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pricing Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Service__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service__c</referenceTo>
    <relationshipName>Consol_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/Tax_Included_Selling__c.field-meta.xml
<CustomField>
    <fullName>Tax_Included_Selling__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tax Included-Selling</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/TaxRatioSelling__c.field-meta.xml
<CustomField>
    <fullName>TaxRatioSelling__c</fullName>
    <label>Tax Ratio-Selling</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/UnitPriceofSellingActual__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceofSellingActual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Price of Selling (Actual)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/FTMSBill__c.object-meta.xml
<CustomObject>
    <label>F/TMS Bill</label>
    <nameField>
        <displayFormat>FTB-{000000}</displayFormat>
        <label>F/TMS Bill ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>F/TMS Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FTMSBill__c/fields/ChargeUnit__c.field-meta.xml
<CustomField>
    <fullName>ChargeUnit__c</fullName>
    <label>Charge Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20&apos;DC-Flexi</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>B/L</fullName>
            </value>
            <value>
                <fullName>Bill</fullName>
            </value>
            <value>
                <fullName>Box</fullName>
            </value>
            <value>
                <fullName>Carton</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>CBM</fullName>
            </value>
            <value>
                <fullName>Container</fullName>
            </value>
            <value>
                <fullName>Day</fullName>
            </value>
            <value>
                <fullName>Drum</fullName>
            </value>
            <value>
                <fullName>Keg</fullName>
            </value>
            <value>
                <fullName>Kg</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Package</fullName>
            </value>
            <value>
                <fullName>Pallet</fullName>
            </value>
            <value>
                <fullName>Roll</fullName>
            </value>
            <value>
                <fullName>RTON</fullName>
            </value>
            <value>
                <fullName>Set</fullName>
            </value>
            <value>
                <fullName>Sheet</fullName>
            </value>
            <value>
                <fullName>Shipment</fullName>
            </value>
            <value>
                <fullName>Skid</fullName>
            </value>
            <value>
                <fullName>Unit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/ConsolBill__c.field-meta.xml
<CustomField>
    <fullName>ConsolBill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consol Bill</label>
    <referenceTo>ConsolBill__c</referenceTo>
    <relationshipLabel>F/TMS Bills (Consol Bill)</relationshipLabel>
    <relationshipName>F_TMS_Bills1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/CurrencySelling__c.field-meta.xml
<CustomField>
    <fullName>CurrencySelling__c</fullName>
    <label>Currency-Selling</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VND</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>KHR</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>KRW</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/FTMSSO__c.field-meta.xml
<CustomField>
    <fullName>FTMSSO__c</fullName>
    <label>F/TMS S/O</label>
    <referenceTo>FTMSSO__c</referenceTo>
    <relationshipLabel>F/TMS Bills</relationshipLabel>
    <relationshipName>F_TMS_Bills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/InvoiceTo__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS Bills</relationshipLabel>
    <relationshipName>F_TMS_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FTMSBill__c/fields/PaymentTo__c.field-meta.xml
<CustomField>
    <fullName>PaymentTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>F/TMS Bills (Payment To)</relationshipLabel>
    <relationshipName>F_TMS_Bills1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>VND</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>KHR</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <customValue>
        <fullName>KRW</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>Value1</fullName>
        <isActive>false</isActive>
        <label>Value1</label>
    </customValue>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MassUpdateConsolBillControllerV4.cls
public with sharing class MassUpdateConsolBillControllerV4 {
  @AuraEnabled
  public static String getRecordTypeId() {
    //TODO: Need to clarify which spefic developer name record here
    return [
      SELECT Id, SobjectType
      FROM RecordType
      WHERE
        SobjectType = 'FTMSBill__c'
        AND DeveloperName = 'Selling_Buyging_Standard'
    ]
    .Id;
  }

  @AuraEnabled
  public static String getDescribeSobjectResult() {
    DescribeSobjectResult objResult = Schema.SObjectType.FTMSBill__c;
    return objResult.isCreateable() +
      '_' +
      objResult.isUpdateable() +
      '_' +
      objResult.isAccessible() +
      '_' +
      objResult.isDeletable();
  }
  @AuraEnabled
  public static List<ConsolBill__c> getAllBillings(String shipmentId) {
    List<ConsolBill__c> getBilling = new List<ConsolBill__c>();
    getBilling = [
      SELECT (SELECT Id,
      Name,
      MasterBilling__c,
      PricingName__c,
      FTMSSO__c,
      ChargeUnit__c,
      Quantity__c,
      Container_Type__c,
      Invoiceto__c,
      CurrencySelling__c,
      UnitPriceofSellingActual__c,
      TaxRatioSelling__c,
      Tax_Included_Selling__c,
      PaymentTo__c,
      UnitPriceofBuyingActual__c,
      TaxRatioBuying__c,
      Tax_Included__c FROM Consol_Bills__r),Id,
      Name,
      MasterBilling__c,
      PricingName__c,
      FTMSSO__c,
      ChargeUnit__c,
      Quantity__c,
      Container_Type__c,
      Invoiceto__c,
      CurrencySelling__c,
      UnitPriceofSellingActual__c,
      TaxRatioSelling__c,
      Tax_Included_Selling__c,
      PaymentTo__c,
      UnitPriceofBuyingActual__c,
      TaxRatioBuying__c,
      Tax_Included__c
      FROM ConsolBill__c
      WHERE ConsolidationShipmentName__c = :shipmentId AND MasterBilling__c = null
      ORDER BY Name
    ];

    return getBilling;
  }

  @AuraEnabled
  public static List<ConsolBill__c> getNewBillings(
    String shipmentId,
    Boolean isSelling,
    List<String> ids
  ) {
    List<ConsolBill__c> getBilling = new List<ConsolBill__c>();
    // if(isSelling){
    getBilling = [
      SELECT Id
      FROM ConsolBill__c
      WHERE ConsolidationShipmentName__c = :shipmentId AND Id NOT IN :ids
      ORDER BY Name
    ];
    System.debug('Thong debug :' + getBilling);
    // } else {
    //     getBilling =  [Select Id FROM ConsolBill__c
    //         WHERE ConsolidationShipmentName__c = :shipmentId
    //         AND Id NOT IN :ids

    //         ORDER BY Name];
    // }

    return getBilling;
  }
  @AuraEnabled
  public static List<ConsolBill__c> getSubBillings(String shipmentId) {
    List<ConsolBill__c> getBilling = new List<ConsolBill__c>();
    System.debug('shipmentId :' + shipmentId);
    getBilling = [
      SELECT Id, Name
      FROM ConsolBill__c
      WHERE MasterBilling__c = :shipmentId
      ORDER BY Name
    ];
    System.debug('Thong debug 2 :' + getBilling);

    return getBilling;
  }
  @AuraEnabled
  public static Map<String, Object> getListWapper(String ShipID) {
    Map<String, Object> result = new Map<String, Object>();
    List<ConsolBill__c> lisdt = new List<ConsolBill__c>();
    List<ConsolBill__c> lisdoc = [
      SELECT id, (SELECT id FROM Consol_Bills__r)
      FROM ConsolBill__c
      WHERE ConsolidationShipmentName__c = :ShipID
      ORDER BY Name
    ];

    List<Id> unique = new List<Id>();
    for (ConsolBill__c lisdocItem : lisdoc) {
      if (lisdocItem.Id != null && !unique.contains(lisdocItem.Id)) {
        unique.add(lisdocItem.Id);
      }
    }

    system.debug('Fu doc list:' + lisdoc);
    if (lisdoc.size() > 0) {
      lisdt = [SELECT Id FROM ConsolBill__c WHERE MasterBilling__c IN :unique];
    }
    system.debug('Fu docdt list :' + lisdoc);
    result.put('DocList', lisdoc);
    result.put('DocListDT', lisdt);
    return result;
  }

  @AuraEnabled
  public static Boolean deleteBilling(String id) {
    try {
      List<ConsolBill__c> billings = [
        SELECT Id
        FROM ConsolBill__c
        WHERE Id = :id
      ];
      if (billings.size() == 0)
        return false;
      delete billings;
      return true;
    } catch (DmlException e) {
      throw e;
    }
  }

  @AuraEnabled
  public static String updateBillings(List<ConsolBill__c> jsonRecords, String billString) {
    System.debug('checkdebug1 :'+billString);
    // String u = '[{"Id":"a058d00000AhkaaAAB","Name":"MC-000007","MasterBilling__c":"a058d00000AhkauAAB","PricingName__c":"a0J8d000004TaQgEAK","ChargeUnit__c":"Container","Quantity__c":"7","Container_Type__c":"20\'DC","CurrencySelling__c":"USD","UnitPriceofSellingActual__c":0,"TaxRatioSelling__c":10,"Tax_Included_Selling__c":false,"PaymentTo__c":"0018d00000lU4oUAAS","UnitPriceofBuyingActual__c":1,"Tax_Included__c":false,"Consol_Bills__r":[{"MasterBilling__c":"a058d00000AhkaaAAB","Id":"a058d000009ad21AAA","Quantity__c":"8"},{"MasterBilling__c":"a058d00000AhkaaAAB","Id":"a058d00000AhkakAAB"}]';
    List<Object> input = (List<Object>)JSON.deserializeUntyped(billString);
    System.debug('checkdebug2 :'+input);
    Map<String, Object> results = new Map<String, Object>();
    Map<String, Object> resultsRelationship = new Map<String, Object>();
    List<List<Object>> lstCustomers = new List<List<Object>>();
    List<Object> lstCustomerstest = new List<Object>();
    List<ConsolBill__c> lstBillDetails = new List<ConsolBill__c>();
    List<ConsolBill__c> lstBillRelationship = new List<ConsolBill__c>();
    Set<String> setId = new Set<String>();
    for (Integer i=0;i < input.size();i++) {
      results = (Map<String, Object>)input[i];  
      System.debug('recordsMap :'+results);
      ConsolBill__c consolidatedRecord = new ConsolBill__c();

      if(results.get('Consol_Bills__r') != null){
        lstCustomers.add((List<Object>)results.get('Consol_Bills__r'));
      }
      System.debug('lstCustomerssss :'+lstCustomers.size());
    }
    System.debug('lstBillDetails :'+lstBillDetails);
    System.debug('lstCustomersSize :'+lstCustomers.size());
    // Map<String, Object> results = (Map<String, Object>)JSON.deserializeUntyped(billString);
    System.debug('results :'+results);
    
    System.debug('lstCustomers :'+lstCustomers);
    // for (Integer i=0;i < lstCustomers.size();i++) {
    //   for (Integer j=0;j < lstCustomers[i].size();j++) {
    //     ConsolBill__c billRecord = new ConsolBill__c();
    //     billRecord.ChargeUnit__c = (String)lstCustomers[i][j].get('ChargeUnit__c');
    //     lstBillRelationship.add(billRecord);
    //   }

    // }
    for (List<Object> lstOb : lstCustomers) {
        for (Object ob : lstOb) {
          // ConsolBill__c billRecord = new ConsolBill__c();
          // billRecord.ChargeUnit__c = (String)ob.get('ChargeUnit__c');
          lstCustomerstest.add(ob);
        }
    }
    System.debug('lstCustomerstest :'+lstCustomerstest);

    for(Integer i=0; i<lstCustomerstest.size(); i++){
      resultsRelationship = (Map<String, Object>)lstCustomerstest[i];
      System.debug('resultsRelationship :'+resultsRelationship);
      ConsolBill__c billRecord = new ConsolBill__c();
      billRecord.ChargeUnit__c = (String)resultsRelationship.get('ChargeUnit__c');
      billRecord.Container_Type__c = (String)resultsRelationship.get('Container_Type__c');
      billRecord.FTMSSO__c = (String)resultsRelationship.get('FTMSSO__c');
      billRecord.Id = (String)resultsRelationship.get('Id');
      billRecord.PaymentTo__c = (String)resultsRelationship.get('PaymentTo__c');
      billRecord.Invoiceto__c = (String)resultsRelationship.get('Invoiceto__c');
      billRecord.PricingName__c = (String)resultsRelationship.get('PricingName__c');
      billRecord.CurrencySelling__c = (String)resultsRelationship.get('CurrencySelling__c');
      billRecord.CurrencyBuying__c = (String)resultsRelationship.get('CurrencyBuying__c');
      // billRecord.UnitPriceofSellingActual__c = (Decimal)resultsRelationship.get('UnitPriceofSellingActual__c');
      billRecord.UnitPriceofSellingActual__c = Integer.valueOf(String.valueOf(resultsRelationship.get('UnitPriceofSellingActual__c')));
      System.debug('checktype :'+resultsRelationship.get('Quantity__c'));
      billRecord.Quantity__c = Integer.valueOf(String.valueOf(resultsRelationship.get('Quantity__c')));
      // billRecord.TaxRatioBuying__c = (Decimal)resultsRelationship.get('TaxRatioBuying__c');
      billRecord.TaxRatioBuying__c = Integer.valueOf(String.valueOf(resultsRelationship.get('TaxRatioBuying__c')));
      // billRecord.TaxRatioSelling__c = (Decimal)resultsRelationship.get('TaxRatioSelling__c');
      billRecord.TaxRatioSelling__c = Integer.valueOf(String.valueOf(resultsRelationship.get('TaxRatioSelling__c')));
      billRecord.Tax_Included_Selling__c = Boolean.valueOf(String.valueOf(resultsRelationship.get('Tax_Included_Selling__c')));
      // billRecord.UnitPriceofBuyingActual__c = (Decimal)resultsRelationship.get('UnitPriceofBuyingActual__c');
      billRecord.UnitPriceofBuyingActual__c = Integer.valueOf(String.valueOf(resultsRelationship.get('UnitPriceofBuyingActual__c')));
      // billRecord.Tax_Included__c = (Boolean)resultsRelationship.get('Tax_Included__c');
      billRecord.Tax_Included__c = Boolean.valueOf(String.valueOf(resultsRelationship.get('Tax_Included__c')));
      lstBillRelationship.add(billRecord);
    }
    System.debug('lstBillRelationship :'+lstBillRelationship);
    
    // for (Object customer : lstCustomers) {
    //   // now get attributes for this customer.
    //   Map<String, Object> customerAttributes = (Map<String, Object>)customer;
    //   // now loop through our customer attributes.
    //   for (String attributeName : customerAttributes.keyset()) {
    //       System.debug('========> ' + attributeName + ' = ' + 
    //           customerAttributes.get(attributeName));
    //   }
    // }
    
    // List<ConsolBill__c> recordsUpdate = new List<ConsolBill__c>();
    // List<ConsolBill__c> recordsReUpdate = new List<ConsolBill__c>();
    // Set<String> setId = new Set<String>();

    // for (Object ob : input) {
    //     if(!setId.contains(ob.get('Id'))){
    //       recordsReUpdate.add((ConsolBill__c)ob);
    //     }
    // }
    // System.debug('recordsReUpdate :'+recordsReUpdate);



    System.debug('Thong Debug 2 :'+input);
    
    List<ConsolBill__c> lstIdChild = new List<ConsolBill__c>();
    System.debug('Thong Debug :'+jsonRecords);
    Set<Id> ids = (new Map<Id, SObject>(jsonRecords)).keySet();
    Set<Id> idsRelationship = (new Map<Id, SObject>(lstBillRelationship)).keySet();
    System.debug('Idd :' + ids);
    System.debug('idsRelationship :' + idsRelationship);
    List<ConsolBill__c> billings = [SELECT Id,
        
        Name,
        MasterBilling__c,
        PricingName__c,
        FTMSSO__c,
        ChargeUnit__c,
        Quantity__c,
        Container_Type__c,
        Invoiceto__c,
        CurrencySelling__c,
        UnitPriceofSellingActual__c,
        TaxRatioSelling__c,
        Tax_Included_Selling__c,
        PaymentTo__c,
        UnitPriceofBuyingActual__c,
        TaxRatioBuying__c,
        Tax_Included__c
      FROM ConsolBill__c
      WHERE Id IN :ids
      ORDER BY Name
    ];
    System.debug('debug2 :' + billings);
    /////Query bill relationship
    List<ConsolBill__c> billingRelationship = [SELECT Id,
        
        Name,
        MasterBilling__c,
        PricingName__c,
        FTMSSO__c,
        ChargeUnit__c,
        Quantity__c,
        Container_Type__c,
        Invoiceto__c,
        CurrencySelling__c,
        UnitPriceofSellingActual__c,
        TaxRatioSelling__c,
        Tax_Included_Selling__c,
        PaymentTo__c,
        UnitPriceofBuyingActual__c,
        TaxRatioBuying__c,
        Tax_Included__c
      FROM ConsolBill__c
      WHERE Id IN :idsRelationship
      ORDER BY Name
    ];
    System.debug('debug3 :' + billingRelationship);

    for (ConsolBill__c childId : billings) {
      lstIdChild.addAll(childId.Consol_Bills__r);
    }
    System.debug('lstIdChild :'+lstIdChild);
    List<ConsolBill__c> itemsIdsToRemove = new List<ConsolBill__c>();
    List<ConsolBill__c> itemsIdsToRemoveRelationShip = new List<ConsolBill__c>();

    for (Integer i = 0; i < jsonRecords.size(); i++) {
      ConsolBill__c r = jsonRecords[i];

      if (billings[i].Id == r.Id) {
        System.debug('checkdebug1');
        if (
          billings[i].PricingName__c != r.PricingName__c ||
          billings[i].MasterBilling__c != r.MasterBilling__c ||
          billings[i].FTMSSO__c != r.FTMSSO__c ||
          billings[i].ChargeUnit__c != r.ChargeUnit__c ||
          billings[i].Quantity__c != r.Quantity__c ||
          billings[i].Container_Type__c != r.Container_Type__c ||
          billings[i].Invoiceto__c != r.Invoiceto__c ||
          billings[i].CurrencySelling__c != r.CurrencySelling__c ||
          billings[i].UnitPriceofSellingActual__c !=
          r.UnitPriceofSellingActual__c ||
          billings[i].TaxRatioSelling__c != r.TaxRatioSelling__c ||
          billings[i].Tax_Included_Selling__c != r.Tax_Included_Selling__c ||
          billings[i].PaymentTo__c != r.PaymentTo__c ||
          billings[i].UnitPriceofBuyingActual__c !=
          r.UnitPriceofBuyingActual__c ||
          billings[i].TaxRatioBuying__c != r.TaxRatioBuying__c ||
          billings[i].Tax_Included__c != r.Tax_Included__c 
        ) {
        System.debug('checkdebug2');

          itemsIdsToRemove.add(r);
        }
      }
      System.debug('ThongCheck :'+itemsIdsToRemove);
    
    }
    //// gán giá trị vào Relationship
    for (Integer i = 0; i < lstBillRelationship.size(); i++) {
      ConsolBill__c r = lstBillRelationship[i];

      if (billingRelationship[i].Id == r.Id) {
        System.debug('checkdebug1');
        if (
          billingRelationship[i].PricingName__c != r.PricingName__c ||
          billingRelationship[i].MasterBilling__c != r.MasterBilling__c ||
          billingRelationship[i].FTMSSO__c != r.FTMSSO__c ||
          billingRelationship[i].ChargeUnit__c != r.ChargeUnit__c ||
          billingRelationship[i].Quantity__c != r.Quantity__c ||
          billingRelationship[i].Container_Type__c != r.Container_Type__c ||
          billingRelationship[i].Invoiceto__c != r.Invoiceto__c ||
          billingRelationship[i].CurrencySelling__c != r.CurrencySelling__c ||
          billingRelationship[i].UnitPriceofSellingActual__c !=
          r.UnitPriceofSellingActual__c ||
          billingRelationship[i].TaxRatioSelling__c != r.TaxRatioSelling__c ||
          billingRelationship[i].Tax_Included_Selling__c != r.Tax_Included_Selling__c ||
          billingRelationship[i].PaymentTo__c != r.PaymentTo__c ||
          billingRelationship[i].UnitPriceofBuyingActual__c !=
          r.UnitPriceofBuyingActual__c ||
          billingRelationship[i].TaxRatioBuying__c != r.TaxRatioBuying__c ||
          billingRelationship[i].Tax_Included__c != r.Tax_Included__c 
        ) {
        System.debug('checkdebug223');

          itemsIdsToRemoveRelationShip.add(r);
        }
      }
      System.debug('ThongCheck112 :'+itemsIdsToRemoveRelationShip);
    
    }
    // for (ConsolBill__c bill : itemsIdsToRemove) {
    //   System.debug('debug 4 :' + bill.ExchangeRateSelling__c);
    // }
    System.debug('debug33  :' + itemsIdsToRemove.size());
    System.debug('debug3344  :' + itemsIdsToRemoveRelationShip.size());
    try {
      update itemsIdsToRemove;
      update itemsIdsToRemoveRelationShip;
      System.debug('checkupdate');
      return JSON.serialize(itemsIdsToRemove);
    } catch (Exception e) {
      throw new DmlException(e.getMessage());
    }
  }
}