force-app/main/default/objects/ConsolBill__c/ConsolBill__c.object-meta.xml
<CustomObject>
    <label>Billing</label>
    <nameField>
        <displayFormat>MC-{000000}</displayFormat>
        <label>Billing ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ConsolBill__c/fields/Billing_status__c.field-meta.xml
<CustomField>
    <fullName>Billing_status__c</fullName>
    <label>Billing status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Required approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <default>true</default>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/ChargeUnit__c.field-meta.xml
<CustomField>
    <fullName>ChargeUnit__c</fullName>
    <label>Charge Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>20&apos;DC-Flexi</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>B/L</fullName>
            </value>
            <value>
                <fullName>Bill</fullName>
            </value>
            <value>
                <fullName>Box</fullName>
            </value>
            <value>
                <fullName>Carton</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>CBM</fullName>
            </value>
            <value>
                <fullName>Container</fullName>
            </value>
            <value>
                <fullName>Day</fullName>
            </value>
            <value>
                <fullName>Drum</fullName>
            </value>
            <value>
                <fullName>Keg</fullName>
            </value>
            <value>
                <fullName>Kg</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Package</fullName>
            </value>
            <value>
                <fullName>Pallet</fullName>
            </value>
            <value>
                <fullName>Roll</fullName>
            </value>
            <value>
                <fullName>RTON</fullName>
            </value>
            <value>
                <fullName>Set</fullName>
            </value>
            <value>
                <fullName>Sheet</fullName>
            </value>
            <value>
                <fullName>Shipment</fullName>
            </value>
            <value>
                <fullName>Skid</fullName>
            </value>
            <value>
                <fullName>Truck</fullName>
            </value>
            <value>
                <fullName>Unit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/ConsolidationShipmentName__c.field-meta.xml
<CustomField>
    <fullName>ConsolidationShipmentName__c</fullName>
    <label>Consolidation Shipment Name</label>
    <referenceTo>AdvancedShipment__c</referenceTo>
    <relationshipName>Consol_Bills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/Container_Type__c.field-meta.xml
<CustomField>
    <fullName>Container_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ChargeUnit__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20&apos;DC</fullName>
            </value>
            <value>
                <fullName>20&apos;HC</fullName>
            </value>
            <value>
                <fullName>40&apos;DC</fullName>
            </value>
            <value>
                <fullName>45&apos;DC</fullName>
            </value>
            <value>
                <fullName>40&apos;HC</fullName>
            </value>
            <value>
                <fullName>45&apos;HC</fullName>
            </value>
            <value>
                <fullName>20&apos;RF</fullName>
            </value>
            <value>
                <fullName>40&apos;RF</fullName>
            </value>
            <value>
                <fullName>45&apos;RF</fullName>
            </value>
            <value>
                <fullName>20&apos;OT</fullName>
            </value>
            <value>
                <fullName>40&apos;OT</fullName>
            </value>
            <value>
                <fullName>45&apos;OT</fullName>
            </value>
            <value>
                <fullName>20&apos;FR</fullName>
            </value>
            <value>
                <fullName>40&apos;FR</fullName>
            </value>
            <value>
                <fullName>Bulk</fullName>
            </value>
            <value>
                <fullName>ISO</fullName>
            </value>
            <value>
                <fullName>20&apos;IMO</fullName>
            </value>
            <value>
                <fullName>40&apos;IMO</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>20&apos;DC-Flexi</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>CBM</fullName>
            </value>
            <value>
                <fullName>RTON</fullName>
            </value>
            <value>
                <fullName>-1000KGS</fullName>
            </value>
            <value>
                <fullName>+1000KGS</fullName>
            </value>
            <value>
                <fullName>+2000KGS</fullName>
            </value>
            <value>
                <fullName>+3000KGS</fullName>
            </value>
            <value>
                <fullName>+4000KGS</fullName>
            </value>
            <value>
                <fullName>+5000KGS</fullName>
            </value>
            <value>
                <fullName>+6000KGS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/CurrencyBuying__c.field-meta.xml
<CustomField>
    <fullName>CurrencyBuying__c</fullName>
    <label>Currency-Buying</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/CurrencySelling__c.field-meta.xml
<CustomField>
    <fullName>CurrencySelling__c</fullName>
    <label>Currency-Selling</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/Extra_cost__c.field-meta.xml
<CustomField>
    <fullName>Extra_cost__c</fullName>
    <formula>IF(PricingName__r.Extra_cost__c =TRUE, TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Extra cost</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/FTMSSO__c.field-meta.xml
<CustomField>
    <fullName>FTMSSO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FTMSSO__c.ConsolidationID__c</field>
            <operation>equals</operation>
            <valueField>$Source.ConsolidationShipmentName__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FTMSSO__c</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Consol_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/Invoiceto__c.field-meta.xml
<CustomField>
    <fullName>Invoiceto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice to</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Consol_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/PaymentTo__c.field-meta.xml
<CustomField>
    <fullName>PaymentTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment To</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Consol_Bills1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/PricingName__c.field-meta.xml
<CustomField>
    <fullName>PricingName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pricing Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Service__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service__c</referenceTo>
    <relationshipName>Consol_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipName>Consol_Bills1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/Tax_Included__c.field-meta.xml
<CustomField>
    <fullName>Tax_Included__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tax Included-Buying</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/Tax_Included_Selling__c.field-meta.xml
<CustomField>
    <fullName>Tax_Included_Selling__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tax Included-Selling</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/TaxRatioBuying__c.field-meta.xml
<CustomField>
    <fullName>TaxRatioBuying__c</fullName>
    <label>Tax Ratio-Buying</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/TaxRatioSelling__c.field-meta.xml
<CustomField>
    <fullName>TaxRatioSelling__c</fullName>
    <label>Tax Ratio-Selling</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/UnitPriceofBuyingActual__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceofBuyingActual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Price of Buying (Actual)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConsolBill__c/fields/UnitPriceofSellingActual__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceofSellingActual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Price of Selling (Actual)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FTMSSO__c/FTMSSO__c.object-meta.xml
<CustomObject>
    <label>Shipment.</label>
    <nameField>
        <displayFormat>FSO-{000000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments.</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Extra_cost__c.field-meta.xml
<CustomField>
    <fullName>Extra_cost__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Extra cost</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SiteCustomSettings__c/fields/FCYCurrency__c.field-meta.xml
<CustomField>
    <fullName>FCYCurrency__c</fullName>
    <label>FCY Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SiteCustomSettings__c/fields/LocalCurrency__c.field-meta.xml
<CustomField>
    <fullName>LocalCurrency__c</fullName>
    <label>Local Currency</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>VND</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>KHR</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <customValue>
        <fullName>KRW</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>Value1</fullName>
        <isActive>false</isActive>
        <label>Value1</label>
    </customValue>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AddMultipleConsolBillController.cls
public with sharing class AddMultipleConsolBillController {
    @AuraEnabled
    public static String saveBillList(List<ConsolBill__c> billList,Id shipmentId) 
	{   
        SiteCustomSettings__c custom = [SELECT FCYCurrency__c,LocalCurrency__c FROM SiteCustomSettings__c ];
        for(ConsolBill__c bill: billList){
            bill.ConsolidationShipmentName__c = shipmentId;
            bill.PricingName__c = bill.PricingName__c != null? bill.PricingName__c : '';
            System.debug('123 :'+bill.PricingName__r.Extra_cost__c);
            System.debug('1234:'+bill.PricingName__c);
            Service__c ser = [SELECT Extra_cost__c FROM Service__c WHERE Id =: bill.PricingName__c LIMIT 1];
            System.debug(' 555 :'+ser.Extra_cost__c);
            bill.Billing_status__c = ser.Extra_cost__c == true? 'Required approval':'Approved';
            // if(bill.PricingName__r.Extra_cost__c == true){
            //     bill.Billing_status__c = 'Required approval';
            // }
            // else {
            //     bill.Billing_status__c = 'Approved';
            // }
            bill.FTMSSO__c = bill.FTMSSO__c != null? bill.FTMSSO__c : '';
            System.debug('Thong debug :'+bill.FTMSSO__c);
            bill.ChargeUnit__c = bill.ChargeUnit__c != null? bill.ChargeUnit__c : '';
            bill.Quantity__c = bill.Quantity__c != null? bill.Quantity__c : 0;
            bill.Container_Type__c = bill.Container_Type__c != null? bill.Container_Type__c : '';
            bill.Invoiceto__c = bill.Invoiceto__c != null? bill.Invoiceto__c : '';	
            bill.CurrencySelling__c = bill.CurrencySelling__c != null? bill.CurrencySelling__c : '';
            bill.CurrencyBuying__c = bill.CurrencyBuying__c != null? bill.CurrencyBuying__c : '';
            bill.UnitPriceofSellingActual__c = bill.UnitPriceofSellingActual__c != null? bill.UnitPriceofSellingActual__c : 0;
            bill.TaxRatioSelling__c = bill.TaxRatioSelling__c != null? bill.TaxRatioSelling__c : 0;
            bill.Tax_Included_Selling__c = bill.Tax_Included_Selling__c != null? bill.Tax_Included_Selling__c : false;
            bill.PaymentTo__c = bill.PaymentTo__c != null? bill.PaymentTo__c : '';
            bill.UnitPriceofBuyingActual__c = bill.UnitPriceofBuyingActual__c != null? bill.UnitPriceofBuyingActual__c : 0;
            bill.TaxRatioBuying__c = bill.TaxRatioBuying__c != null? bill.TaxRatioBuying__c : 0;
            bill.Tax_Included__c = bill.Tax_Included__c != null? bill.Tax_Included__c : false;
        }
        try{
            insert billList;
        }
        catch (Exception e) {
            return e.getMessage();
        }
        return null;
        
        
    } 
}