force-app/main/default/objects/Quoteline__c/Quoteline__c.object-meta.xml
<CustomObject>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000}</displayFormat>
        <label>Quoteline ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quoteline__c/fields/ChargeUnit__c.field-meta.xml
<CustomField>
    <fullName>ChargeUnit__c</fullName>
    <label>Charge Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>20&apos;DC-Flexi</fullName>
            </value>
            <value>
                <fullName>45&apos;IMO</fullName>
            </value>
            <value>
                <fullName>AIR</fullName>
            </value>
            <value>
                <fullName>B/L</fullName>
            </value>
            <value>
                <fullName>Bill</fullName>
            </value>
            <value>
                <fullName>Box</fullName>
            </value>
            <value>
                <fullName>Carton</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>CBM</fullName>
            </value>
            <value>
                <fullName>Container</fullName>
            </value>
            <value>
                <fullName>Day</fullName>
            </value>
            <value>
                <fullName>Drum</fullName>
            </value>
            <value>
                <fullName>Keg</fullName>
            </value>
            <value>
                <fullName>Kg</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Package</fullName>
            </value>
            <value>
                <fullName>Pallet</fullName>
            </value>
            <value>
                <fullName>Roll</fullName>
            </value>
            <value>
                <fullName>RTON</fullName>
            </value>
            <value>
                <fullName>Set</fullName>
            </value>
            <value>
                <fullName>Sheet</fullName>
            </value>
            <value>
                <fullName>Shipment</fullName>
            </value>
            <value>
                <fullName>Skid</fullName>
            </value>
            <value>
                <fullName>Truck</fullName>
            </value>
            <value>
                <fullName>Unit</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quoteline__c/fields/PrintingSection__c.field-meta.xml
<CustomField>
    <fullName>PrintingSection__c</fullName>
    <label>Printing Section</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1st Section</fullName>
                <default>true</default>
                <label>1st Section</label>
            </value>
            <value>
                <fullName>2nd Section</fullName>
            </value>
            <value>
                <fullName>3rd Section</fullName>
            </value>
            <value>
                <fullName>4th Section</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quoteline__c/fields/QuoteID__c.field-meta.xml
<CustomField>
    <fullName>QuoteID__c</fullName>
    <label>Quote ID</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote lines</relationshipLabel>
    <relationshipName>Quote_lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quoteline__c/fields/QuoteLineNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineNumber__c</fullName>
    <label>Quote Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AddMultipleQuoteLineController.cls
public with sharing class AddMultipleQuoteLineController {
    @AuraEnabled
    public static String saveQuoteLineList(List<Quoteline__c> quoteLineList,Id quoteId) 
	{  
        AggregateResult numberQuote = [SELECT MAX(QuoteLineNumber__c) FROM Quoteline__c where QuoteID__c =:quoteId];
        Integer numMax = Integer.valueOf(numberQuote.get('expr0'));
        System.debug('1234:' + numMax);
        if(String.isBlank(String.valueOf(numMax))){
            numMax = 0;
        }
        for(Quoteline__c quoLine: quoteLineList){
            System.debug('1234:'+numberQuote);
            quoLine.QuoteID__c = quoteId;
            if(quoLine.ChargeUnit__c != null){
                quoLine.ChargeUnit__c = quoLine.ChargeUnit__c;
                System.debug('1234:' + quoLine.ChargeUnit__c);
            }
            System.debug('1234:'+numMax);
            quoLine.QuoteLineNumber__c = Integer.valueOf(Integer.valueOf(numMax)+1);
            quoLine.PrintingSection__c = '2nd Section';
            numMax++;
        }
        
        System.debug('1234:' + quoteLineList);
        try{
            Insert quoteLineList;
        }
        catch (Exception e) {
            return e.getMessage();
        }
        return null;
    }
}